### ISSUE TITLE
Grass turns into purple and black error blocks when a world is opened in Amulet

### ISSUE THREAD

**Issue by TheBMGPlayzYT** [Amulet-Team/Amulet-Map-Editor#1006]
## Bug Report
Grass turns into purple and black error blocks when a world is opened in Amulet.
### Current Behaviour:
Grass turns into this purple and black error blocks when a world is opened in Amulet.

### Expected Behaviour:
Grass should NOT turn into purple and black error blocks when opened in Amulet and it should have its normal texture back.

### Steps To Reproduce:
1. Open Amulet.
2. Open any world that you have.
3. You should see that the grass textures (not the grass block but the actual grass) were replaced by the purple and black error block.

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.17.41 and above including the latest 1.20.50
- Amulet Version: 0.10.25

### Screenshots
![Screenshot 2023-12-06 232327](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75167042/e7d72b6a-70f1-47e2-a96e-7aad5653d1b0)
![Screenshot 2023-12-06 232328](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75167042/76be0967-8219-43b1-bdc6-9790bab8860b)
![Capture](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75167042/cf29312a-25d1-4232-b663-11ce769ad417)

**Comment by gentlegiantJGC** [comment]
Looks like they removed the model for some reason.
I will add an override. It should still function normally.

**Comment by wildwitchwest** [comment]
this happened recently because Bedrock changed the model/name for tallgrass and grass so we need an update to reflect that. usually when gearing up for a new version of the game they change stuff around that messes with established blockdata
