### ISSUE TITLE
[Bug Report] Lighting problems after importing schematics

### ISSUE THREAD

**Issue by Rabbit0w0** [Amulet-Team/Amulet-Map-Editor#1008]
## Bug Report
The lighting of the map glitches after importing schematics
### Current Behaviour:
Glitching lighting
### Expected behavior:
Normal lighting
### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.27

**Comment by wildwitchwest** [comment]
this happens to me with bedrock as well. i've looked all over the internet and it's a common problem across minecraft when they changed their lighting system

**Comment by gentlegiantJGC** [comment]
Duplicate of #44
