### ISSUE TITLE
ERROR - Chiseled Bookshelves

### ISSUE THREAD

**Issue by theoldworld** [Amulet-Team/Amulet-Map-Editor#1021]
![Untitled-1](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/103148264/dbcd8961-af14-44d2-8d9f-99ce96798dcb)

Received this issue with Chiseled Bookshelves when copying between worlds. The ones I saw in game appeared to be normal.

**Comment by jamaa** [comment]
I am also getting this error message when opening a Java 1.20.6 world in Amulet v0.10.28. It doesn't seem to cause any issues though, can edit and save the world in Amulet and everything seems fine in game.

**Comment by gentlegiantJGC** [comment]
This should be fixed in the next release.
It was an issue in the translator and an issue in the resource pack library.
