### ISSUE TITLE
[Bug Report] Error free conversion of a particular PMC world doesn't create chunks in target

### ISSUE THREAD

**Issue by abrightmoore** [Amulet-Team/Amulet-Map-Editor#1026]
## Bug Report
World conversion Java --> Bedrock completes without error, only some chunks convert into the target world. Trimming the region folder to just a few regions and testing shows this behaviour.

### Current Behaviour:
Blocks in chunks present in the source world are not present in the target world.

### Expected behavior:
Blocks in chunks present in the source world will be present in the target world.

### Steps To Reproduce:
1. Steps to reproduce on discord thread: https://discord.com/channels/324647192583340043/1207803542681686017
2. Minimal source world to convert from is attached here: https://discord.com/channels/324647192583340043/1207803542681686017/1207956398013685800

### Environment:

- OS: Windows 11
- Minecraft Platform: Java 1.20.4 | Bedrock 1.20.4
- Minecraft Version: Java 1.20.4 | Bedrock 1.20.4. I think the source world may be a mix of chunk versions
- Amulet Version: v0.10.27

## Attachments
Sample source world: https://discord.com/channels/324647192583340043/1207803542681686017/1207956398013685800

### Screenshots
Worked example screenshots on thread: https://discord.com/channels/324647192583340043/1207803542681686017

### Worlds
Sample source world: https://discord.com/channels/324647192583340043/1207803542681686017/1207956398013685800

**Comment by gentlegiantJGC** [comment]
The status of all of these chunks is "liquid_carvers" which is not fully generated so Amulet will skip them.
