### ISSUE TITLE
[Feature Request] The version of PIL in Amulet Editor currently doesn't support ImageDraw

### ISSUE THREAD

**Issue by abrightmoore** [Amulet-Team/Amulet-Map-Editor#1031]
### The Problem
Trying to use PIL.ImageDraw within an Operation and the error is returned:
module 'PIL' has no attribute 'ImageDraw'

### Feature Description
Update PIL / pillow to contemporary versions.

### Alternatives
n/a

### Additional context
This is probably a pretty niche use case, however sometimes it's handy to work in image space with image tools then convert to voxels.

**Comment by gentlegiantJGC** [comment]
This is probably because we don't use it so PyInstaller doesn't include it. I will have to include it manually.
