### ISSUE TITLE
[Bug Report] bedrock .mcstructure export problem

### ISSUE THREAD

**Issue by jojojo805** [Amulet-Team/Amulet-Map-Editor#1033]
```
def main():
    world = amulet.load_level("C:/Users/jo1/AppData/Roaming/MinecraftPE_Netease/minecraftWorlds/java2")
    world_dimesion = "minecraft:overworld"
    version = (1, 18, 30)
    path = "C:/Users/jo1/AppData/Roaming/MinecraftPE_Netease/exported_structures/test.mcstructure"
    selection = SelectionGroup(SelectionBox((0, 50, 0), (500, 100, 500)))
    wrapper = MCStructureFormatWrapper(path)
    wrapper.create_and_open("bedrock", version, selection, True)

    wrapper.translation_manager = world.translation_manager
    wrapper_dimension = wrapper.dimensions[0]



    for (cx, cz) in selection.chunk_locations():
        try:
            chunk = world.level_wrapper.load_chunk(cx, cz, world_dimesion)
            wrapper.commit_chunk(chunk, wrapper_dimension)
        except ChunkLoadError:
            print("ChunkLoadError")

    wrapper.save()
    wrapper.close()


if __name__ == '__main__':
    main()
```

When I run this code, I get the.mcstructure file in the wrong format, When you open it with NBT Studio, you find "minecraft:andesite" in the block_palette, but the palette should actually be "name:minecraft:stone state:stone_type:andesite" Similar to this sentence, so I lost andesite when I converted, is there something wrong with the code I wrote? Can someone help me

![5446BCC8-2555-479b-9CB9-59DDFE0C6229](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75937179/05c57d59-9f2d-41ee-b3f9-da9b25682f44)
![44241B63-3FB3-4865-894A-06B2DBB2DB80](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75937179/f0816ab9-e2fd-487e-ad14-ff963e1732dd)

**Comment by gentlegiantJGC** [comment]
I have found the issue.

**Comment by jojojo805** [comment]
It was solved.Thank you.
