### ISSUE TITLE
[Bug Report] Can't install Amulet Map Editor from source on Mac

### ISSUE THREAD

**Issue by cherryswiftie13** [Amulet-Team/Amulet-Map-Editor#1034]
I'm trying to install Amulet Map Editor via source on my Mac. I already have all the proper prerequisites set up, including a virtual environment, all environments and interpreters are working correctly.

However, when I use `pip install amulet_map_editor`, I always get errors towards the end. For the first bit, the process looks to be working perfectly fine. But towards the end I get a bunch of errors. At the end it seems like it successfully installed, just with a couple missing wheels and stuff.

But when I try to run Amulet using `python -m amulet_map_editor` or `amulet_map_editor`, it says that the module doesn't exist. I have made sure that the right virtual environment is activated in terminal.

Here's a txt document with the full output of the installation process, if anyone can help me:
[amulet install error output.txt](https://github.com/Amulet-Team/Amulet-Map-Editor/files/14808435/amulet.install.error.output.txt)

**EDIT:** The issue seems to be that for some reason it can't build wheels for `pyopengl-accelerate`. I have tried every solution I could find online, and still getting the same error.

**UPDATE:** Found solution https://github.com/Amulet-Team/Amulet-Map-Editor/issues/1034#issuecomment-2057453252.

**Comment by gentlegiantJGC** [comment]
This is related to Amulet-Team/Amulet-Map-Editor#597
pyopengl-accelerate is disabled on arm macs because there were issues installing it.
What is the output from the following on your computer
```py
import platform
print(platform.machine())
```

**Comment by cherryswiftie13** [comment]
> This is related to #597 pyopengl-accelerate is disabled on arm macs because there were issues installing it. What is the output from the following on your computer
> 
> ```python
> import platform
> print(platform.machine())
> ```

I don't have an ARM Mac. It's a MacBook Air 2020 (Intel Core i3)

This is the output I get when I run that in the Terminal on my Mac.
`zsh: parse error near `)'`

I'm just running this on the default clean profile of Terminal. Is there somewhere specific I'm supposed to run this command?

**Comment by gentlegiantJGC** [comment]
Into the python interpreter

**Comment by cherryswiftie13** [comment]
> Into the python interpreter

okay, so I just open Terminal and run the command? my Mac has a global Python interpreter so it should work right? does zsh have something to do with it?

**Comment by cherryswiftie13** [comment]
**UDPATE:** After looking more into similar issues and scouring the internet, I found somewhere that some users reported Amulet failing to work on Python 3.10+. So I used `pyenv-virtualenv` to create a new virtual environment running 3.9.13. Once I did so and activated the environment, I tried running `pip install amulet_map_editor again`, and this time the wheels were successfully built, it looks like.
