### ISSUE TITLE
Crashing while trying to open 3D editor

### ISSUE THREAD

**Issue by axolotlagatsuma** [Amulet-Team/Amulet-Map-Editor#1037]
### Steps To Reproduce:
1. Install the latest from source in Ubuntu
2. Open a world and click on 3D Editor
3. See error

### Environment:
- OS: Linux
- Minecraft Platform: Java
- Minecraft Version: 1.20.4
- Amulet Version: 0.10.27

### Worlds
I tried this with 2 worlds both crashed. Here is the world that I want to reset chunks

**Comment by gentlegiantJGC** [comment]
I need more information to debug this.
`3. See error` Care to share the error message?
`Here is the world that I want to reset chunks` You haven't uploaded a world.

**Comment by axolotlagatsuma** [comment]
Oh right sorry for that. I am outside right now but I remember the last message in the terminal. It was ```çekirdek döküldü``` (i use Turkish)

**Comment by axolotlagatsuma** [comment]
I'll send the full log later today.

**Comment by axolotlagatsuma** [comment]
Btw I think it's Python's error not amulet's
