### ISSUE TITLE
[Bug Report] Doesnt work

### ISSUE THREAD

**Issue by Lauchwarm** [Amulet-Team/Amulet-Map-Editor#1040]
## Bug Report
My issue is that only red dots pop up when i want to edit world so the map is not downloading I sent screenshots for you to see
### Expected behavior:
I want to edit world

### Steps To Reproduce:
just went to 3d editor

### Env->
- OS: Windows
- Minecraft Platform: Java
- Minecraft Version:  1.20.5
- Amulet Version: 

### Additional context
I never used this app because its my first world where i want to reset chunks
### Screenshots
All I se is this 
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/168229926/5c3a5b55-9524-4f1c-b1d2-635ad8ba0d81)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/168229926/84ecf4ec-6c98-48d5-84f7-a82decaea184)

**Comment by gentlegiantJGC** [comment]
It takes me a little while to support new versions. I should have a new release out in a bit.
