### ISSUE TITLE
[Bug Report] Minecraft Bedrock crashes

### ISSUE THREAD

**Issue by Andrew-Sor** [Amulet-Team/Amulet-Map-Editor#1046]
## Bug Report
Minecraft Bedrock 1.21 crashes when loading a converted world from Minecraft Java 1.20.4.

### Current Behaviour:
Not a working world from Minecraft Java 1.20.4 to Minecraft Bedrock 1.21

### Expected behavior:
Working world from Minecraft Java 1.20.4 to Minecraft Bedrock 1.21

### Steps To Reproduce:

1. Go to "Amulet"
2. Click on "Open world"
3. Chose world from Minecraft Java 1.20.4
4. Go to "Convert"
5. Chose world from Minecraft Bedrock 1.21
6. Click on "Convert"
7. Open converted world
8. Get crash

### Environment:

- OS: Windows 11
- Minecraft Platform: Java and Bedrock
- Minecraft Version: 1.20.4 and 1.21
- Amulet Version: 0.10.29

### Additional context
Could this have something to do with the mods and resource packs used in the Java version of Minecraft or the world settings of the Bedrock version? I use Forge, Optifine and shaders with a texture pack. In the Bedrock version world, I enabled beta features and Education Edition.

### Worlds
Java: https://drive.google.com/file/d/1dk6Xj7wmoEFnOzrKWF5PizngH4Vy2vIL/view?usp=sharing
Bedrock: [heU5Zl+jAAA=.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/15234695/heU5Zl%2BjAAA.zip)

**Comment by gentlegiantJGC** [comment]
Looks like a corrupted lectern block entity.

**Comment by gentlegiantJGC** [comment]
The crash is coming from "hasBook" being set to 1 but there is no "book" tag.

I have added a bug report on the Bedrock bug tracker because the game should handle this gracefully.
https://bugs.mojang.com/browse/MCPE-183007

I will also look into fixing this in our codebase so it doesn't generate an invalid block entity.

**Comment by Andrew-Sor** [comment]
Okay, thank you!
