### ISSUE TITLE
[Bug Report] Unable to open world from Bedrock v 1.20.80.05

### ISSUE THREAD

**Issue by JpzJr** [Amulet-Team/Amulet-Map-Editor#1048]
## Bug Report
Bedrock.
It was time to copy a building from an old world to a new one. I am able to export out of the old world, v 1.20.72.1. I cannot open the new world, v 1.20.80.05.01.
Neither world has experimental features activated. Both created with bedrock vanilla server.

### Current Behaviour:
Attempting to open Bedrock world v 1.20.80.05.01 throws error:

unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 157, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 71, in __init__
  File "amulet\level\load.py", line 30, in load_level
  File "amulet\level\load.py", line 59, in load_format
  File "amulet\level\formats\leveldb_world\format.py", line 175, in __init__
  File "amulet\level\formats\leveldb_world\format.py", line 89, in from_file
  File "amulet\level\formats\leveldb_world\format.py", line 99, in _read_from
struct.error: unpack requires a buffer of 4 bytes

### Expected behavior:
To enjoy the simplicity of the process and continue playing.

### Steps To Reproduce:
1. Click Open World.
2. Choose world.
3. Error appears.

### Environment:
- OS: Windows 11 Home
- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.80.05
- Amulet Version: 0.10.29

### Additional context
Both worlds generated using vanilla server running on Ubuntu server.

I am unable to recreate the error on a new world created with Minecraft Bedrock edition on PC.
Minecraft on PC was able to open the world. Once opened by Minecraft, Amulet was able to open the world.

**Comment by gentlegiantJGC** [comment]
Did you close the server before trying to open in Amulet?
Please can you share a world that I can reproduce the issue with.
It looks like the level.dat file is empty. The game may recover it from the old level.dat.

**Comment by JpzJr** [comment]
I apologize, I thought notifications on GitHub would alert me, but I did not get an alert. Future attempts did not recreate the problem so as of now I do not have further information.
