### ISSUE TITLE
[Bug Report] amulet corrupts block_ticks field

### ISSUE THREAD

**Issue by ccJerrycc** [Amulet-Team/Amulet-Map-Editor#1052]
### Steps To Reproduce:
1. Place a repeat command block and set to active (like spam hi
2. Do some operation in the same chunk where it is in (like Fill
3. Rejoin the world

### Environment:
- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.20.6
- Amulet Version: V0.10.29

### Screenshots
before
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/112236293/50e7fa1d-e469-4b93-b621-4f5e96243d98)
after (see z is different
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/112236293/2965c4d5-5364-4f40-9446-4fcc7b92a956)

**Comment by gentlegiantJGC** [comment]
This was fixed in Amulet-Team/Amulet-Core#303
