### ISSUE TITLE
[Bug Report] Saving world after using 3D Editor corrupts.

### ISSUE THREAD

**Issue by jordanbruhh** [Amulet-Team/Amulet-Map-Editor#1058]
## Bug Report
After saving world in Amulet, attempting to load the world will give error "There was a problem loading this world."
-->
### Current Behaviour:
After saving world in Amulet, attempting to load the world will give error "There was a problem loading this world." Even if nothing has changed in the world. Tested with brand new worlds and backups from a Realm.

### Expected behavior:
Amulet saves any changes made and allows the world to open as normal.

### Steps To Reproduce:

1. Open up Minecraft world in Amulet and go to 3D Editor
2. (opt.) Make some changes and save the world 
3. Open world in Minecraft

### Environment:

- OS: Windows
- Minecraft Platform:Bedrock
- Minecraft Version: 1.20.81
- Amulet Version: 0.10.30

### Screenshots

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/69571355/87cf43e6-3733-4e9e-86e4-50dfe1749dfe)

### Worlds
unable to attach via Github as the files are approx 150mb each, max file size is 25mb. DM jord8n on Discord if full files are required.

**Comment by gentlegiantJGC** [comment]
have you closed the world in Amulet?
