### ISSUE TITLE
Dead Coral Plants convert to Living Coral Plants

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#106]
**Description**
Converting Dead Coral Plants from Java 1.16.1 to Bedrock 1.16.20 creates Regular (living) Coral Plants.
Dead Coral Fans and Dead Coral Blocks appear to convert properly as seen in screenshots.

**Screenshots**
![coral_java](https://user-images.githubusercontent.com/13902631/93031981-c1c99a00-f5fc-11ea-8ea1-1b89b9d41b19.png)
![coral_bedrock](https://user-images.githubusercontent.com/13902631/93031984-c42bf400-f5fc-11ea-95da-edf342d142ca.png)

**Comment by gentlegiantJGC** [comment]
Probably a bug left over from when they didn't have a dead state
