### ISSUE TITLE
[Feature Request] Would like to be able to select the number of CPU threads used or the percentage of occupancy

### ISSUE THREAD

**Issue by CreeperAWA** [Amulet-Team/Amulet-Map-Editor#1062]
### The Problem

I want to use more CPU threads to increase efficiency

### Feature Description

There can be a place to set the number of CPU threads used or the percentage of occupancy, or via the startup parameter

### Additional context

I have a very large world to convert and it uses only 10% of the CPU when it opens up and converts, but it's very slow
(Bedrock→Java)

The above is machine translated and may contain errors.

中文
### The Problem

我想使用更多的 CPU 线程来提高效率

### Feature Description

可以有一个设置使用的 CPU 线程数或占用百分比的位置，或者通过启动参数来实现

### Additional context

我有一个非常大的世界需要转换（Bedrock→Java），在打开和转换时只占用了 10%的 CPU，但速度非常慢

**Comment by gentlegiantJGC** [comment]
This is a limitation of python.
I am experimenting with moving some components to C++ to allow parallelism.

**Comment by CreeperAWA** [comment]
> This is a limitation of python. I am experimenting with moving some components to C++ to allow parallelism.

Can you give me an approximate completion time?
