### ISSUE TITLE
Chunks do not stay visible as I move around in chunk mode

### ISSUE THREAD

**Issue by VernonMcIntyreZBC** [Amulet-Team/Amulet-Map-Editor#1064]
### Current Behaviour:
While in chunk editor mode I assume, from watching videos, that the chunks should stay visible and active on the screen at all times.

### Expected behavior:
While I am in chunk mode and I use the right mouse button to move around and show more chunks, others disappear.  If I go to the left on the screen, chunks on the right disappear.  This is when they are still well on the screen and not even near the border of my screen.  I am zoomed out to do this.

### Steps To Reproduce:
Open a world
Click chunk
Let Amulet load visible chunks
Use mouse right button to move to the left and load more chunks
At some point in moving left, either the first or second time chunks beyond a certain point on the right will disappear even though they are still near the middle of the usable screen area.

### Environment:
- Windows 10 Home build 19045.4529
- Minecraft Platform: Bedrock
- Minecraft Version: 1.21.0.3.0
- Amulet Version: 0.10.32

I can attach the world if necessary, let me know.

**Comment by gentlegiantJGC** [comment]
Sounds like you need to increase your render distance.
