### ISSUE TITLE
[Bug Report] Amulet fails to install on MacOS

### ISSUE THREAD

**Issue by Chackapon** [Amulet-Team/Amulet-Map-Editor#1067]
### Current Behaviour:

Whenn I follow the steps to install Amulet (including setting up a virtual environment) something during the compilation of Cython prevents Amulet to build properly

This is what get in terminal: https://pastebin.com/Kb7w0vAM

### Steps To Reproduce:
Follow the installation steps on the website

### Environment:

- OS: OSX
- Minecraft Platform: Java 
- Minecraft Version: 1.20.1
- Amulet Version: 0.10

**Comment by gentlegiantJGC** [comment]
Please try the latest beta version. I removed this library.

**Comment by Chackapon** [comment]
The problem was with PyOpenGL_accelerate, right? I could successfully build and launch the beta build, but the editor itself is just void now
<img width="1440" alt="Screenshot 2024-06-19 at 18 40 06" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/30863200/b4a54009-4fcc-49fb-8f3f-45d8c0837143">

here's the log of the app running:
https://pastebin.com/Cne8zCur

right before the flood of errors there's a message that PyOpenGL_accelerate is missing/ When I try to install it via pip3 it gives me errors that look almost exactly like ones that I had when I tried to build the stable release:
https://pastebin.com/wtK4FH4J

I tried to see if I could install PyOpenGL_accelerate through homebrew, but it's not there unfortunately

**Comment by gentlegiantJGC** [comment]
Could be related to #1056

**Comment by gentlegiantJGC** [comment]
PyOpenGL_accelerate is an optional dependency that apparently speeds up some parts of the code but I don't know if we are using those parts. It also hasn't been maintained in a while.

**Comment by Chackapon** [comment]
I tried to install 3.1.6 of PyOpenGL_accelerate instead of 3.1.7 and it compiled (I also don't see the message about it missing in the log) But the world still won't load and there are a bunch of OpenGL errors in the log
https://pastebin.com/GsVUMKPW

**Comment by gentlegiantJGC** [comment]
Did you read the issue I linked?

**Comment by Chackapon** [comment]
Okay so the only thing that I got from the issue you linked is to download 0.10.29 and it does work. So is the solution to stay on this version?

**Comment by gentlegiantJGC** [comment]
This comment is the relevant part.
https://github.com/Amulet-Team/Amulet-Map-Editor/issues/1056#issuecomment-2155979144

This is the code that caused it to break.
https://github.com/Amulet-Team/Amulet-Map-Editor/commit/dd7146b079219948a974a0ff90c76b955ec2faf8

Specifically this bit. (lines 55-62)
https://github.com/Amulet-Team/Amulet-Map-Editor/commit/dd7146b079219948a974a0ff90c76b955ec2faf8#diff-ce4f855daf68bb50d1b06c083cdeacbe93278e81d6c704dc5b4ff33f4864372cR55

Try installing the new version and then going into the source files where it was installed and modifying those lines to work out what is needed to make it work.

Was it defining OpenGL 3.3 which broke it?
Was it added PlatformDefaults that broke it?
Was it removing Robust that broke it?
Was it removing ResetIsolation that broke it?
Does it work if they are in a different order?
