### ISSUE TITLE
Certain construction files are not saved correctly / won't load

### ISSUE THREAD

**Issue by SilverjetPlane** [Amulet-Team/Amulet-Map-Editor#109]
**Describe the bug**
Certain construction files cannot be loaded in worlds, the preview doesn't show, there is an error message saying 'ValueError: cannot call \`vectorize\` on size 0 inputs unless \`otypes\` is set'. From the log it seems some redstone components are not saved correctly, like sticky pistons, hoppers, droppers, noteblocks and maybe more. A different construction with solid blocks, slabs and stairs worked fine. Copying and pasting the area also worked fine. 

**To Reproduce**
I tested with a redstone circuit area from a Java 1.16.1 world, copying it to another J1.16.1 world via construction files. 
1. Exported the construction file with redstone components from a Java 1.16.1 world. There are no obvious error messages but in the amulet_core.log. 
2. Selected 'Import' on the second J1.16.1 world, the green selection cube is shown, there is no geometry preview.
3. Select 'confirm'. The loading window will show, but no progress is made. The error message mentioned above shows. See also screenshot and amulet_map_editor.log. 

**Expected behavior**
2. The geometry preview should be shown in the green selection cube. 
3. The geometry should load after selecting 'confirm'. 

**Screenshots**
![Step2-200916-1559](https://user-images.githubusercontent.com/71390652/93348500-90d4a980-f836-11ea-8b63-6d202f36a4d8.png)

**Desktop**
 - Windws 10 Home 64-bit
 - Amulet 0.7.1.0

**Additional context**
amulet_map_editor.log:
https://pastebin.com/sbW9mf2r
amulet_core.log: 
https://pastebin.com/GRwekxk9 
(I closed the program between the steps and reproduced the export after the import)

**Comment by gentlegiantJGC** [comment]
Are you able to share a file that reproduces the issue?

**Comment by SilverjetPlane** [comment]
https://cdn.discordapp.com/attachments/498974201416253443/755908388180721724/Redstone_test_1.16.1.construction

**Comment by gentlegiantJGC** [comment]
The construction file you have sent is empty. There must have been some issue with exporting it.
I have recently redesigned the way blocks are stored so this is most likely a bug due to that.
I have fixed the bug that stops this file from being imported but it is still an empty structure
