### ISSUE TITLE
[Feature Request] Add an option to force load chunck

### ISSUE THREAD

**Issue by daniell0999** [Amulet-Team/Amulet-Map-Editor#1094]
I was wondering if you could add a feature to force load chunks, since chunks are not always saved even if you were in them and on max simultation distance near the player on bedrock edition. Here is an example: I tried using the Biome override in the level.dat and set it to deep warm ocean(since monuments still generate) and i wanted to built on a monument, but no mater how many times i fly around some chunks are not loaded and just turn into their normal state when removing the biome override again.
<img width="560" alt="Screenshot 2024-08-17 013748" src="https://github.com/user-attachments/assets/7d6e77c9-ef87-4f0b-ae78-92411044fe3d">

**Comment by gentlegiantJGC** [comment]
We have no control over how the game operates or access to the chunk generator.
