### ISSUE TITLE
[Bug Report] Could not find translation for vanilla slabs

### ISSUE THREAD

**Issue by TheFelixLive** [Amulet-Team/Amulet-Map-Editor#1097]
## Bug Report
With the latest version of Minecraft Bedrock (1.21), the block ID of stone slab has been changed, which means that the Amulet no longer replaces them for Java

## 1.20 or older
Sandstone Slab has the id stone_slab

## 1.21 or newer
Sandstone Slab has the id sandstone_slab

### Current Behaviour:
 Simply skips the block

### Expected behavior:
Get translated to Java

### Steps To Reproduce:
1. Save a world that contains a slab that has the ID stone slab in the preview (for example: cut_sandstone_slab).
2. Convert it to Java using Amulet
4. See error in console

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock  to Java
- Minecraft Version: 1.21.0
- Amulet Version: v.0.10.35

**Comment by gentlegiantJGC** [comment]
I have not yet implemented translations for the new version

**Comment by gentlegiantJGC** [comment]
Should be fixed in the next release
