### ISSUE TITLE
Preparation: PIP Requirements Download; Error encountered.

### ISSUE THREAD

**Issue by yojokem** [Amulet-Team/Amulet-Map-Editor#11]
I am into using this **Amulet Map Editor** for some reasons.
So, I took preparations but some errors encountered when set up **Amulet-Core** and also this **Amulet Map Editor**.

**Comment by yojokem** [comment]
Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\yojok\appdata\local\programs\python\python38-32\python.exe' 'c:\users\yojok\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\yojok\AppData\Local\Temp\pip-build-env-7jzr8xwz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 41.2.0' 'cython >= 0.29.13' 'numpy == 1.15.2'
       cwd: None
  Complete output (291 lines):
  Collecting setuptools>=41.2.0
    Using cached setuptools-46.0.0-py3-none-any.whl (582 kB)
  Collecting cython>=0.29.13
    Using cached Cython-0.29.15-cp38-cp38-win32.whl (1.6 MB)
  Collecting numpy==1.15.2
    Using cached numpy-1.15.2.zip (4.5 MB)
  Installing collected packages: setuptools, cython, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\yojok\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yojok\\AppData\\Local\\Temp\\pip-install-tylo525d\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\yojok\\AppData\\Local\\Temp\\pip-install-tylo525d\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\yojok\AppData\Local\Temp\pip-record-7hu6oyj2\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\yojok\AppData\Local\Temp\pip-build-env-7jzr8xwz\overlay' --compile --install-headers 'C:\Users\yojok\AppData\Local\Temp\pip-build-env-7jzr8xwz\overlay\Include\numpy'
           cwd: C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\
      Complete output (276 lines):
      Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)


      C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\numpy\distutils\misc_util.py:474: SyntaxWarning: "is" with a literal. Did you mean "=="?
        return is_string(s) and ('*' in s or '?' is s)
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      blis_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blis not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      openblas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Found executable C:\Program Files\Git\usr\bin\DF.exe
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      atlas_3_10_blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      atlas_blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\numpy\distutils\system_info.py:625: UserWarning:
          Atlas (http://math-atlas.sourceforge.net/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [atlas]) or by setting
          the ATLAS environment variable.
        self.calc_info()
      blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\numpy\distutils\system_info.py:625: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      blas_src_info:
        NOT AVAILABLE

      C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\numpy\distutils\system_info.py:625: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE

      'svnversion'▒▒(▒▒) ▒▒▒▒ ▒Ǵ▒ ▒ܺ▒ ▒▒▒, ▒▒▒▒▒▒ ▒▒ ▒ִ▒ ▒▒▒α׷▒, ▒Ǵ▒
      ▒▒ġ ▒▒▒▒▒▒ ▒ƴմϴ▒.
      'svnversion'▒▒(▒▒) ▒▒▒▒ ▒Ǵ▒ ▒ܺ▒ ▒▒▒, ▒▒▒▒▒▒ ▒▒ ▒ִ▒ ▒▒▒α׷▒, ▒Ǵ▒
      ▒▒ġ ▒▒▒▒▒▒ ▒ƴմϴ▒.
      non-existing path in 'numpy\\distutils': 'site.cfg'
      F2PY Version 2
      lapack_opt_info:
      lapack_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      openblas_lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      openblas_clapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas,lapack not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\yojok\appdata\local\programs\python\python38-32\libs
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack not found in ['c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\yojok\\appdata\\local\\programs\\python\\python38-32\\libs']
        NOT AVAILABLE

      C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\numpy\distutils\system_info.py:625: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        self.calc_info()
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\yojok\AppData\Local\Temp\pip-install-tylo525d\numpy\numpy\distutils\system_info.py:625: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE

      c:\users\yojok\appdata\local\programs\python\python38-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win32-3.8
      creating build\src.win32-3.8\numpy
      creating build\src.win32-3.8\numpy\distutils
      building library "npymath" sources
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\yojok\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yojok\\AppData\\Local\\Temp\\pip-install-tylo525d\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\yojok\\AppData\\Local\\Temp\\pip-install-tylo525d\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\yojok\AppData\Local\Temp\pip-record-7hu6oyj2\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\yojok\AppData\Local\Temp\pip-build-env-7jzr8xwz\overlay' --compile --install-headers 'C:\Users\yojok\AppData\Local\Temp\pip-build-env-7jzr8xwz\overlay\Include\numpy' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\yojok\appdata\local\programs\python\python38-32\python.exe' 'c:\users\yojok\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\yojok\AppData\Local\Temp\pip-build-env-7jzr8xwz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 41.2.0' 'cython >= 0.29.13' 'numpy == 1.15.2' Check the logs for full command output.

**Comment by yojokem** [comment]
[error.txt](https://github.com/Amulet-Team/Amulet-Map-Editor/files/4332852/error.txt)
This is the file that contains the error messages.

**Comment by gentlegiantJGC** [comment]
Probably easiest if you get a compled build from here
https://github.com/Amulet-Team/Amulet-Map-Editor/releases
We will clean up the install instructions when things become more stable.

Out of interest what command did you even run?

**Comment by yojokem** [comment]
Oh, I didn't see that releases link...

I executed commands on the Amulet-Core installation instruction!
And when I install the Editor, just followed to 'pip install -r requirements.txt'

**Comment by gbaman** [comment]
So to add to this, this issue can be resolved by installing the "Build tools for Visual Studio 2019" option - https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019
Then select the C++ build tools (is about 5GB of stuff). Then you can get past that step.

Next was pyopengl was missing, which can just be grabbed off pypi
`pip3 install pyopengl`

Now though, I am hitting against
```
ModuleNotFoundError: No moduel named 'minecraft_model_reader' 
```
Specifically from canvas.py making the import.
I have found the library itself @gentlegiantJGC, but it lacks a setup.py file to properly handle an install https://github.com/gentlegiantJGC/Minecraft-Model-Reader

**Comment by gentlegiantJGC** [comment]
I will look into adding this

**Comment by gentlegiantJGC** [comment]
I may have fixed the setup.py issues

**Comment by gbaman** [comment]
Now we are getting a bit further, although also getting errors @gentlegiantJGC related to incompatible versions of numpy, with amulet-nbt and amulet-core being pinned to version 1.15.2 and amulet-map-editor being pinned to 1.17.4.

**Comment by gentlegiantJGC** [comment]
will fix

**Comment by gentlegiantJGC** [comment]
that might fix it

**Comment by gentlegiantJGC** [comment]
if this is still an issue please reopen it
