### ISSUE TITLE
Pasted structures are not placed as the given paste preview would indicate (Amulet Release 7.10)

### ISSUE THREAD

**Issue by Ixarias** [Amulet-Team/Amulet-Map-Editor#110]
**Describe the bug**
 - Pasting a structure distorts it as if some invalid rotation algorithm was applied

**To Reproduce**
1. Use Amulet 7.10 release for Windows 10
2. Copy a selection of world
3. Paste into new location

**Expected behavior**
 - The paste preview should match the resulting paste (Screenshots from 7.01)
![pre7.01](https://user-images.githubusercontent.com/11237136/93360605-789a6580-f809-11ea-8183-694987011a86.png)
![post7.01](https://user-images.githubusercontent.com/11237136/93360644-864feb00-f809-11ea-91e7-c3d5db744436.png)

**Screenshots**
 - No Rotation
![prenorot](https://user-images.githubusercontent.com/11237136/93361006-f199bd00-f809-11ea-881b-3044db79d581.png)
![postnorot](https://user-images.githubusercontent.com/11237136/93361029-f9596180-f809-11ea-95e2-6c8681a946d7.png)

 - Distortion is consistent between pastes
![image](https://user-images.githubusercontent.com/11237136/93361392-6f5dc880-f80a-11ea-99bb-4ee0a04c59fd.png)

 - RY Rotation
![pre](https://user-images.githubusercontent.com/11237136/93359611-69ff7e80-f808-11ea-98c2-7195d54ef9cd.png)
![post](https://user-images.githubusercontent.com/11237136/93359901-b77beb80-f808-11ea-8b62-37123f4d4423.png)
![pre2](https://user-images.githubusercontent.com/11237136/93359910-b945af00-f808-11ea-8119-7cf3ef1d58e9.png)
![post2](https://user-images.githubusercontent.com/11237136/93359916-bb0f7280-f808-11ea-952d-d5e5165b7b19.png)

 - RX Rotation
![pre_rx](https://user-images.githubusercontent.com/11237136/93360234-0e81c080-f809-11ea-8054-f4c1c23c1570.png)
![post_rx](https://user-images.githubusercontent.com/11237136/93360308-222d2700-f809-11ea-9d45-d0a62e968540.png)

**Desktop (please complete the following information):**
 - Windows 10 Version 2004 OS Build 19041.508
 - Amulet Version 7.10

**Additional context**
 - Problem does not occur in version 7.01 (expected behavior screenshots from 7.01)
 - Only tested in 7.01 and 7.10

**Comment by gentlegiantJGC** [comment]
Thanks for reporting this. It looks to be an issue related to some recent changes

**Comment by gentlegiantJGC** [comment]
This should be fixed in the newest build
