### ISSUE TITLE
[Bug Report] Remove command prompt window

### ISSUE THREAD

**Issue by thewanderingtraderm** [Amulet-Team/Amulet-Map-Editor#1102]
### Current Behaviour:

command prompt window open when starting the program
### Expected behavior:

no command prompt window
### Environment:

windows, latest amulet version
### Additional context

to make the cmd window not appear, when building with pyinstaller, add the "--noconsole" flag to the pyinstaller args
### Screenshots

![Screenshot 2024-09-11 231845](https://github.com/user-attachments/assets/32adb5f8-a07e-44c2-90f2-16ee7a6e514d)

**Comment by gentlegiantJGC** [comment]
This window is useful for debugging purposes.

Ideally we would have a custom logging dialog but we don't so this will have to stay for now.
