### ISSUE TITLE
[Bug Report] Chunks 

### ISSUE THREAD

**Issue by Banshee1TR** [Amulet-Team/Amulet-Map-Editor#1103]
When I open the map I'm playing in the application, some chunks do not load, do not open, and are not visible, and when I save the map, all the chunks that are not loaded are saved as deleted, corrupting the world.

Windows Minecraft Bedrock 1.21.23
Amulet Version 0.10.35
![Ekran Alıntısı](https://github.com/user-attachments/assets/fc2e3ad9-9d84-41e6-b658-761de2db43f7)

**Comment by gentlegiantJGC** [comment]
These chunks were never saved by the game.

The game needs to save the chunk for Amulet to be able to render them.
