### ISSUE TITLE
[Bug Report] Chunks don't seem to generate differently after [Delete Unselected Chunks]

### ISSUE THREAD

**Issue by wigwoo1** [Amulet-Team/Amulet-Map-Editor#1116]
So I have an existing world. I downloaded a mod that adds new ores to the caves. Ores do not appear after deleting chunks and regenerating them
### Current Behaviour:
After saving world in Amulet. Chunks appear identical with identical ores and locations for the ores

### Expected behavior:
I expect the terrain itself to remain the same, but for all the ore vains to be randomly regenerated so new veins with new ores are generated

### Environment:

- OS: Windows
- Minecraft Platform: Java 
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.37

**Comment by gentlegiantJGC** [comment]
Terrain generation is beyond the scope of Amulet.
Once Amulet deletes the chunk it is the game's job to recreate it.

Make sure you are actually deleting the chunk by first placing a block in game and deleting the chunk in Amulet.
If the block dissappears but the chunk looks the same then the terrain generator hasn't changed.
