### ISSUE TITLE
[Feature Request] UI/UX restrategize and modern multithreading/async operation

### ISSUE THREAD

**Issue by edferr** [Amulet-Team/Amulet-Map-Editor#1118]
### The Problem
interface appears very dated, not very feature dense.
interface regularly comes to an unpleasant halt on large block count copy/pastes (and i mean the interface becomes unresponsive/greyed out 'close' buttons/windows messages that literally say 'unresponsive'), i am getting the feeling its not multithreaded or async. please look to update this code to modern standards, it appears to be stagnating in the state of overly ambitious 9th grader programming project.

### Feature Description
better multithreading and more considerate design of user interface and experience.
maybe async methods for long block operation.
some kind of UI paradigm that is more common and acceptable.

### Additional context
while i understand the effort required for such updates to modern standards, these are some areas that are definitely holding back the repo. also i do not know why it is called 'Amulet'. that has nothing thematic to do with minecraft, nor is there any noticable branding in program that would explain why.

**Comment by gentlegiantJGC** [comment]
We are open to pull requests if you think you can help improve the code.
I am currently in the process of rewriting chunks of the core library in C++ and migrating to Qt.
I am going to close this ticket because it is a bit handwavey.
