### ISSUE TITLE
[Bug Report] Block textures doesn't loads or missing

### ISSUE THREAD

**Issue by Shirokograd** [Amulet-Team/Amulet-Map-Editor#1119]
### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.21 
- Amulet Version: 0.10.37

### Additional context
Hello Amulet team, sorry am new here and not yet familiar with the report formats, i like to report this recent bug that cause all blocks in my world have missing textures, for unknown reasons since this just happen to me recently, how can i fix this?

### Screenshots

![Untitled](https://github.com/user-attachments/assets/de317226-639e-4cd6-a59e-78de2e23db28)

**Comment by gentlegiantJGC** [comment]
0.10.38 should fix this.
