### ISSUE TITLE
[Bug Report] Bedrock Edition 1.21.5 textures & new log acting up

### ISSUE THREAD

**Issue by Paulmc099** [Amulet-Team/Amulet-Map-Editor#1120]
Current Behaviour:
Hanging Moss does not render in the new update, logs are facing the Y axis in the game but visually the x. 

### Expected behavior:
A correct image for hanging moss and logs

Steps To Reproduce:
Open a bedrock world through the minecraft launcher and go to a pale garden biome or spawn a pale oak tree
Close the world
Open the world in the latest version on amulet app in windows

![amulet 1](https://github.com/user-attachments/assets/dbe8bd0d-3b7a-432a-bf35-a3cb9d01edea)
![amulet 2](https://github.com/user-attachments/assets/e2d0eee6-8fe9-410a-8c4c-2536d68889e0)

**Comment by gentlegiantJGC** [comment]
This should be fixed in 0.10.39
