### ISSUE TITLE
[Bug Report] In my case,  " Could not find a matching interface for ('java', 4189) " is printed in error code.

### ISSUE THREAD

**Issue by ZUNAKITHEWORLD** [Amulet-Team/Amulet-Map-Editor#1122]
Firstly, I thank you - amulet team - sincerely.
I have a serious error while using the Amulet app.
When I open the world on Amulet, I can't see every chunk, including every structure I've built.
Instead, red blocks are seen on all the maps.
Hope to find the solutions, so that I could make my structure again.

## Bug Report
Error Code - amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 4189)
Red Blocks on every map.

### Current Behaviour:
I can't do anything...

### Expected behavior:
I believe in you guys. Thanks a lot.

### Environment:

- OS: Windows 11 ( 64 bit )
- Minecraft Platform: Java Edition
- Minecraft Version: 1.21.4
- Amulet Version: 0.10.38

### Additional context
Thank you very much for reading this issue.

### Screenshots
![image](https://github.com/user-attachments/assets/9ef78853-30ef-4b3f-84dc-9ff5b5be28b8)
![image](https://github.com/user-attachments/assets/87fbd7ad-7f02-4273-a84e-fa19360cf28e)

**Comment by gentlegiantJGC** [comment]
This should be fixed in 0.10.39

**Comment by ZUNAKITHEWORLD** [comment]
I really thank you for your rapid help!!

**Comment by ZUNAKITHEWORLD** [comment]
> This should be fixed in 0.10.39

You made my day.
Shut up and take my money!
I've donated 20 bucks for you guys.

Sincerely, ZUNAKI
