### ISSUE TITLE
[Bug Report] Poweder Snow

### ISSUE THREAD

**Issue by murat716** [Amulet-Team/Amulet-Map-Editor#1125]
## Bug Report

I'm trying to upgrade 1.19.3 world to 1.21.3 for my minestom server and have a issue.
Anvilloader (minestom feature) throw a exception like this

that java.lang.NullPointerException: Unknown block minecraft:poweder_snow

This issue can be caused by a amulet its looks like a typo error

### Environment:

- OS: Windows 
- Minecraft Platform: Java 
- Minecraft Version: 1.19.3 -> 1.21.3
- Amulet Version: v0.10 39

**Comment by gentlegiantJGC** [comment]
Is this still an issue?
