### ISSUE TITLE
[Bug Report] World textures not loading

### ISSUE THREAD

**Issue by rajsapru** [Amulet-Team/Amulet-Map-Editor#1128]
### Current Behaviour:
textures are the missing texture (all of them)

### Expected behavior:
all the textures load

### Environment:

- OS: Windows 11
- Minecraft Platform: Java 
- Minecraft Version: 1.19.2
- Amulet Version: 0.10.33b0

### Additional context
most are missing, and the others are invisible

### Screenshots
![Screenshot (11)](https://github.com/user-attachments/assets/8b5ceee1-1707-4124-9a31-8b08a3957ed6)

### Worlds
[New World (3).zip](https://github.com/user-attachments/files/18276294/New.World.3.zip)

**Comment by gentlegiantJGC** [comment]
You are using an old version of Amulet. Please update.
