### ISSUE TITLE
Failed to download the launcher manifest -> no textures

### ISSUE THREAD

**Issue by ZaytsevArtem** [Amulet-Team/Amulet-Map-Editor#115]
Hello, thanx a lot for the app, it looks very nice. A pity i can't use it.
I got
`minecraft_model_reader ERROR - could not download the launcher manifest. The resource pack is not present, blocks may not be rendered correctly.`

As a result the world is successfully loaded but is invisible.

Are unofficial launchers (if they have standard maps & resources format) forbidden to be supported by your app whenever (TLauncher in my case, a java edition launcher)?

I'm not dev-er, but i imagine like in theory it could load the "assets" folder without checking for any manifest... Why is it necessary? If it's used to differ the resources format (JE/BE/PE/..) then maybe there's another method or I could try to tell format by myself.
Or maybe I could cheat with some "false" manifest substitution? Is it possible?

I also noticed that there's a "resource_packs" subdir in the Amulet folder, I tried to place there a 1.15.x (my world is 1.15.2) res-pack template (downloaded from curseforge.com), but I have no idea how to plug it in or if it could even help. Should i dig in this way?

**Comment by gentlegiantJGC** [comment]
Which version of Amulet? It is trying to download the resource pack from the internet but not succeeding

**Comment by ZaytsevArtem** [comment]
0.7.1.1.
Why should it download it? It's here, in the assets folder.

**Comment by gentlegiantJGC** [comment]
It doesn't know what you have or what version it is so it downloads it.
I think there is a bug that makes custom resource packs not work

**Comment by ZaytsevArtem** [comment]
The log window doesn't tell me it downloads the pack. Only the 2 messages:
`2020-09-26 15:30:40,845 - minecraft_model_reader - ERROR - Failed to download the launcher manifest. This may cause problems if you have not used the program before. Make sure you are connected to the internet and https://mojang.com is not blocked.`
`2020-09-26 15:43:38,943 - minecraft_model_reader - ERROR - Could not download the launcher manifest. The resource pack is not present, blocks may not be rendered correctly.`

How can i know that mojang.com isn't blocked? When i type it in a browser - it redirects me to minecraft.net.

I'm not sure there's a bug. Maybe my launcher's pack is non-standard. But when i loaded my world with MCASelector - it showed it fine, so maybe my launcher's pack is ok.

I downloaded a standard 1.15 pack from curseforge.com (a template for self-made packs). How can i try to cheat the app by substituting the standard pack? I substituted the ".minecraft/assets" folder but it didn't help.

Here's amulet_map_editor.log:
`2020-09-26 15:43:39,131 - amulet_map_editor - INFO - Creating texture atlas`
`2020-09-26 15:43:39,146 - amulet_map_editor - INFO - Trying to pack textures into image of size 512x512`
`2020-09-26 15:43:39,162 - amulet_map_editor - INFO - Successfully packed textures into an image of size 512x512`
`2020-09-26 15:43:39,162 - amulet_map_editor - INFO - Finished creating texture atlas`
`2020-09-26 15:43:39,162 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL`

**Comment by ZaytsevArtem** [comment]
My launcher's assets folder differs much from the template.

**Comment by ZaytsevArtem** [comment]
Is this directory structure non-standard?

assets\
  indexes\
    ...
    1.15.json
    1.16.json
  objects\
    00\
      000c82756fd54e40cb236199f2b479629d0aca2f
      00b38fae5d28d99514a3e73a913af16359b12b7a
      ...
    0a\
      0a0bc1ffa05ac5ff00eb2b1bb9093818a35b85b9
      ...
    etc.

1.15.json:
{"objects":
	{
		"icons/icon_16x16.png":
{"hash": "bdf48ef6b5d0d23bbb02e17d04865216179f510a", "size": 3665},
"icons/icon_32x32.png": {"hash": "92750c5f93c312ba9ab413d546f32190c56d6f1f", "size": 5362},
"icons/minecraft.icns": {"hash": "991b421dfd401f115241601b2b373140a8d78572", "size": 114786},
"minecraft/icons/icon_16x16.png": {"hash": "bdf48ef6b5d0d23bbb02e17d04865216179f510a", "size": 3665},
etc.

Is this standard format?

**Comment by ZaytsevArtem** [comment]
Ok, i made it work.
I substituted `Amulet\minecraft_model_reader\resource_packs\java_vanilla_fix\assets` with my downloaded pack.
Still see some glitching blocks but i believe i'll manage it.

One last question: Is .construction format Amulet-only or some more wide standard? Is there any info about it to read?

**Comment by gentlegiantJGC** [comment]
I added a message about restarting the program if this is the case. I am not sure why sometimes it can't make the connection. Usually restarting solves the issue.
