### ISSUE TITLE
Biome type modified after moving/pasting blocks

### ISSUE THREAD

**Issue by BlackWolf-Kuzoku** [Amulet-Team/Amulet-Map-Editor#116]
Hi guys and girls, 

I'm using Minecraft 1.16.1/Vanilla, without mods and use Amulet to modify a server map. 
(deleting a row of blocks/moving a building etc per copy&paste)

I've noticed that some gras blocks had another color as before, so i checked via F3 the Biome type. 
Only the changed blocks have now a block- or biome- ID which says "minecraft:ocean" , nearby blocks have the origin biome type "minecraft:plains"

I cannot tell how this happend; but it would be cool if it's possible to change the ID back. 
Amulet seems to have the ability to change the biome type; but i dont know how it happens, because amulet seems to have no option or feature for that right now. #46 could help to fix this. 

I've attached two screenshots, showing you that i'm running 1.16.1/Vanilla
On the left side in the middle you can read the biome type. 
The blocks are minecraft:ocean in a single, huge minecraft:plains chunk. 
![image](https://user-images.githubusercontent.com/51968925/94619301-ef753b00-02ac-11eb-98c7-ecbbf16f32d1.png)
![image](https://user-images.githubusercontent.com/51968925/94619329-0320a180-02ad-11eb-8344-4df487a00c73.png)

EDIT:
As you can see this problem exists in the Nether, too. 
I've placed there netherrack and on another place dirt blocks. It changes the Biome to minecraft:ocean.
This makes it possible for creeper, zombies and bats to spawn in nether. 
![image](https://user-images.githubusercontent.com/51968925/94719325-52211200-0353-11eb-8e77-5aa1ca8eb55c.png)

**Comment by BlackWolf-Kuzoku** [comment]
P.S: This happens, too if i place a row of "netherrack" in the nether-world. 
it changes the biome type. it's funny to see zombies and bats spawning in the nether.

**Comment by gentlegiantJGC** [comment]
Thanks for reporting this. It was an issue with our undo/redo system
