### ISSUE TITLE
Blocks are not rotated inside structures.

### ISSUE THREAD

**Issue by free-vbucks** [Amulet-Team/Amulet-Map-Editor#135]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
Blocks are not rotated inside structures.

**To Reproduce**
1. Open a world in Amulet
2. Rotate something with blocks inside that do not look the same on all sides (stairs, torches, doors, ect.)
3. Save changes and open world in Minecraft.
4. See that stairs, torches, doors, and other blocks that do not look the same on all sides are all twisted relative to the structure. Some torches are not attached to walls. Presumably, other blocks are also not rotated, but the impact on them is not bad.

**Expected behavior**
The blocks will rotate locally with the whole object you are rotating.

**Screenshots**
**Expectation -**

![2020-11-20_20 16 54](https://user-images.githubusercontent.com/60723221/99865165-7fc55300-2b6d-11eb-97d3-86badeedbb16.png)
![2020-11-20_20 17 00](https://user-images.githubusercontent.com/60723221/99865171-8227ad00-2b6d-11eb-84f0-3ed24235b284.png)
![2020-11-20_20 17 05](https://user-images.githubusercontent.com/60723221/99865173-848a0700-2b6d-11eb-90f0-d5e947444f26.png)
**Reality -**

![2020-11-20_20 14 37](https://user-images.githubusercontent.com/60723221/99865194-a4212f80-2b6d-11eb-802c-d23dc8e13177.png)
![2020-11-20_20 15 06](https://user-images.githubusercontent.com/60723221/99865195-a5eaf300-2b6d-11eb-970f-524bc0f7fab6.png)
![2020-11-20_20 14 47](https://user-images.githubusercontent.com/60723221/99865197-a71c2000-2b6d-11eb-863b-b93e3c0708c8.png)

**Desktop (please complete the following information):**
Windows 10 x64 1909

**Additional context**
#74 is the exact same issue, but is labeled as a feature. This is a _bug_, and needs to be fixed for the application to work correctly as it is.

**Comment by gentlegiantJGC** [comment]
We need to implement a system to "rotate" the block states. Closed as duplicate
