### ISSUE TITLE
Datapack dimensions support

### ISSUE THREAD

**Issue by PopLopChop** [Amulet-Team/Amulet-Map-Editor#136]
At the moment, Amulet only supports vanilla dimensions (overworld, nether and end). If one has a datapack that adds a brand new dimension and they want to transport a very large structure into their custom dimension or simply alter their world, they would have to use structure blocks, which is a real pain, because Amulet does not support custom dimensions. It would be a lot more convenient if Amulet had this feature.

[A test world](http://www.mediafire.com/file/o7qpszrglyq34l7/custom+world+test.zip/file)

**Comment by gentlegiantJGC** [comment]
Okay. I have only added support for custom dimensions in the root directory with the folder name format `DIM-?[0-9]+` which at the time was the only format extra worlds had as far as I know.
It looks like the new official format stores them in a `dimensions` folder although they are nested in some way.
It looks to be `dimensions/<namespace>/<dimension_name>`

We have two options.
1) Parse the data pack to see which dimensions are supposed to be in the world. I would like to implement support for this at some point but I don't plan on doing it soon.
2) Scan the dimensions directory for folders (or region folders) matching the correct structure. This would allow you to see dimensions in an old data pack that were removed but I see this as a positive.

**Comment by gentlegiantJGC** [comment]
https://github.com/Amulet-Team/Amulet-Core/pull/94

**Comment by gentlegiantJGC** [comment]
I think this should be fixed in the next build. I noticed Amulet is resetting the biomes to plains because the custom biomes are not registered. We will need to set that up too. Not sure where vanilla Java stores the numerical to string biome map
