### ISSUE TITLE
Program controls

### ISSUE THREAD

**Issue by gbaman** [Amulet-Team/Amulet-Map-Editor#14]
A quick issue simply to ask about keyboard controls for the software? Although it opens and renders my Bedrock world (using the most recent Release), I can't actually figure out how to get it to do the clone I am looking for...

I am likely missing something simple, but a very quick published list of supported keyboard controls would be super helpful. Or perhaps I can be pointed to somewhere this is even roughly written up?

**Comment by gentlegiantJGC** [comment]
The keyboard control setup is currently very temporary. I want to make it all configurable but haven't gotten to that yet.
Middle click to toggle lock in the viewer
Normal movent controls for creative mode
Mouse wheel to change speed
Left click to select box
Right click to change mouse select mode

All subject to change and configuration

**Comment by gbaman** [comment]
This is much clearer now, thanks 👍
