### ISSUE TITLE
Add Sponge Schematics (improvement of -1.13 MCEdit schematics)

### ISSUE THREAD

**Issue by SkytAsul** [Amulet-Team/Amulet-Map-Editor#144]
**Has your feature request already been suggested? Please check if your suggested feature has already been suggested.**
I don't think so, every other issues were talking about MCEdit schematics.

**Is your feature request related to a problem? Please describe.**
Currently, Amulet only supports for "block storage": old MCEdit schematics, Bedrock .mcstructure, Construction. However, 1.13+ servers are often using the [new Sponge Schematics format](https://github.com/SpongePowered/Schematic-Specification), an improvement of the MCEdit one which supports 1.13+ blocks.

**Describe the solution you'd like**
Implement Sponge Schematics as a data storage format.

**Comment by gentlegiantJGC** [comment]
This has been added the latest alpha build
