### ISSUE TITLE
Export .nbt Schematics

### ISSUE THREAD

**Issue by Reenuip** [Amulet-Team/Amulet-Map-Editor#146]
Is exporting to .nbt in the works? I'm hoping to save premade structures for later placement in a Creative game without directly editing the world.

**Comment by gentlegiantJGC** [comment]
It is planned

**Comment by Reenuip** [comment]
> 
> 
> It is planned
Very cool. The progress so far is great.
I thought I had marked this as a feature request, but apparently not. I'll just close this issue and keep my eyes peeled.

**Comment by gentlegiantJGC** [comment]
I am going to track this in #385
