### ISSUE TITLE
OpenGL 3.0 or later is not supported by the OpenGL driver

### ISSUE THREAD

**Issue by 32Vache** [Amulet-Team/Amulet-Map-Editor#151]
![Screenshot_319](https://user-images.githubusercontent.com/42336759/103324029-db74dd00-4a45-11eb-9985-aa335497c1d2.png)
 The program says my opengl driver dosent support 3.0+ while it does. I have an Intel HD Graphics with openGL 3.1

**Comment by gentlegiantJGC** [comment]
You will need to update your graphics drivers

**Comment by gentlegiantJGC** [comment]
It turns out that some devices that were released after OpenGL 3.0 was released do not support OpenGL 3.0.
I have backported the renderer to handle OpenGL 2.1 which should hopefully solve this issue.
