### ISSUE TITLE
Downgrading Java Worlds from 1.16 does not work

### ISSUE THREAD

**Issue by HoarderofData** [Amulet-Team/Amulet-Map-Editor#152]
Downgrading Java worlds from 1.16.4 with a burner world in an earlier version does not copy over any of the player-created builds from 1.16.4

**Comment by gentlegiantJGC** [comment]
Please test the most recent build. I think this has been fixed.

**Comment by HoarderofData** [comment]
I just upgraded a copy of my world to 1.16.5 then created a Burner world in 1.14.4. I then converted my 1.16.5 world down to 1.14.4 and it worked thank you.
