### ISSUE TITLE
When filling in blocks, error occurs that causes the loading ton be very slow. For example, when filling a cave with stone it either doesnt work or it says loading and doesnt load. 

### ISSUE THREAD

**Issue by snieves0328** [Amulet-Team/Amulet-Map-Editor#158]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, linux]
 - Version [e.g. 0.6.11]

**Additional context**

**Comment by gentlegiantJGC** [comment]
Not enough info

**Comment by gentlegiantJGC** [comment]
Closing because not enough information
