### ISSUE TITLE
Cloning chunk issues

### ISSUE THREAD

**Issue by gbaman** [Amulet-Team/Amulet-Map-Editor#16]
So in copying some large structures from a world built in Bedrock 1.14.30, I have ended up with some peculiar results... 
Entire chunks of blocks have ended up with the wrong y axis value, with everything else correct...

Any suggestions or thoughts? (see below screenshots)

Version - Amulet release v0.5

![Screenshot](https://user-images.githubusercontent.com/833193/77451571-c00cdf80-6dec-11ea-9039-6985a03940a7.jpeg)

![Screenshot](https://user-images.githubusercontent.com/833193/77451582-c307d000-6dec-11ea-882c-b6913dee6a98.jpeg)

**Comment by gentlegiantJGC** [comment]
I am assuming it is a shift of 16 blocks

**Comment by gbaman** [comment]
@gentlegiantJGC yip, 16 blocks off on seemingly random chunks of blocks.

**Comment by gentlegiantJGC** [comment]
Can you try using v0.5.1 I think I fixed it in that version

**Comment by gbaman** [comment]
Can confirm, bug is fixed and copying is working as expected. Thanks for fixing!

![Screenshot](https://user-images.githubusercontent.com/833193/77459418-9c02cb80-6df7-11ea-9379-ef32262b3664.jpg)
