### ISSUE TITLE
Write it in assembly 

### ISSUE THREAD

**Issue by scrap** [Amulet-Team/Amulet-Map-Editor#162]
Please use assembly it is my favorite programming language ever it is so fast man! Right now amulet so laggy man, my pc run 6 rtx 3090 and it still lag man, also I have 69 tb of ram that I download from internet I bet it lag because amulet use python, so please please please use assembly man, I give you guys star on repo if you do

**Comment by Podshot** [comment]
This seems to be an issue submitted as a joke, so I'm going to be closing this
