### ISSUE TITLE
Schematics Importing

### ISSUE THREAD

**Issue by Rageouss** [Amulet-Team/Amulet-Map-Editor#164]
Importing the same small Schematic on version 8.0b5 took 3 minutes when it took 5 seconds on version 8.0b4. Thought this was considerable and wanted to report it. 

It's also copying air even though you have that unchecked. It's deleting blocks

**Comment by gentlegiantJGC** [comment]
I am looking into the air issue. This only happens when rotating the structure.
As for the times you are probably comparing non-rotated pasting to rotated pasting. Rotated pasting always took a while
