### ISSUE TITLE
Free Rotate and Mirror pasted structures

### ISSUE THREAD

**Issue by ShawnCawley** [Amulet-Team/Amulet-Map-Editor#169]
I'd like it so that you could not only rotate a structure 90 or 180 degrees but also be able to rotate some so that it would be diagonal as you could to this in MCedit but that doesn't work anymore so

**Comment by CarJem** [comment]
Taking a Block's **_XYZ_** Coordinate and Rotating it **_D_** degrees relative to a structure's bounding box **_B_** and getting the **_modified XYZ_** position of it back

A mathematical problem that could help out the situation if one could come up with the equation.

**Comment by gentlegiantJGC** [comment]
The back end code actually already supports this but I haven't added it to the UI yet

**Comment by CarJem** [comment]
Oh cool! Then I guess all we are really missing is just some shiny user accessible buttons!

**Comment by gentlegiantJGC** [comment]
The latest release adds a UI that can do this
