### ISSUE TITLE
Education Edition blocks

### ISSUE THREAD

**Issue by gbaman** [Amulet-Team/Amulet-Map-Editor#17]
Any chance we could get support for the 3 additional special blocks for Minecraft Education Edition?
https://minecrafteducation.zendesk.com/hc/en-us/articles/360001433327-Specialty-Blocks-Allow-Deny-Border-Structure-

- [Border block] - https://minecraft.gamepedia.com/Border
- [Allow/deny blocks] - https://minecraft.gamepedia.com/Allow_and_Deny_Blocks

Was trying to do some replacing using them.

**Comment by gentlegiantJGC** [comment]
These blocks are added to the main game as of the 1.16 update so I have added them to that version

**Comment by teacher45** [comment]
Has this issue been resolved? I see the "closed" circle in the top left-hand corner, however, none of the education edition blocks are visible in the 3d editor. Makes it difficult when creating lessons for class.
