### ISSUE TITLE
Block entities not applied in clone or paste operation

### ISSUE THREAD

**Issue by gbaman** [Amulet-Team/Amulet-Map-Editor#18]
Running release v0.5.1, it seems that some metadata attached to blocks is not cloning. A few examples includes
- Command block commands
- Sign contents
- Chests (see below), contents and joined status
- Armour stands

Things like redstone repeater delay ticks are though correctly cloned.

![Screenshot 2020-03-25 at 17 18 14](https://user-images.githubusercontent.com/833193/77566095-177a8080-6ebd-11ea-9db2-fed9d07cdc5d.png)

**Comment by gentlegiantJGC** [comment]
I believe I added this in one of the last builds however there are some issues with NBT (eg chest connection in Bedrock)

**Comment by gentlegiantJGC** [comment]
I am going to close this as I think it has been fixed
