### ISSUE TITLE
Unable to bind Arrow Keys

### ISSUE THREAD

**Issue by Uinquitous** [Amulet-Team/Amulet-Map-Editor#184]
Doesn't give me the option to change the movement keys to arrows, seems that they are hardcoded to handle moving between tabs, this is with Windows 10

EDIT: PageUp and PageDown do the same thing, seems overkill if this was intended

**Comment by gentlegiantJGC** [comment]
Can you confirm which version of Amulet you are using. I have just tested and I am able to set the arrow keys and page up/down keys.

**Comment by Uinquitous** [comment]
This is using 0.7.2.8, I will add that I can assign PageUp and PageDown in the controls, but not arrow keys

**Comment by gentlegiantJGC** [comment]
Can you try the latest beta

**Comment by Uinquitous** [comment]
Ok using 0.8.1a3 can now rebind both sets of keys.. but the application is not using the custom profile I created and swapping to any of the other profiles didn't work either, it appears as the original WASD profile is active instead

**Comment by gentlegiantJGC** [comment]
Yeh there is a bug in the latest alpha I noticed after releasing.
Can you try the latest beta

**Comment by Uinquitous** [comment]
I tried 0.8.0b6 which I hope is the latest beta, allows me to rebind PageUp/PageDown, does not allow me to bind arrows

**Comment by Uinquitous** [comment]
0.8.1a15 has sorted the issue, thanks
