### ISSUE TITLE
Use fallbacks for localisation

### ISSUE THREAD

**Issue by ALTB0ne** [Amulet-Team/Amulet-Map-Editor#186]
**Is your feature request related to a problem? Please describe.**
The translation used is currently based on the system language of the user and can't be set manually. While this isn't a huge deal in itself, there is a problem if the user's system is not _exactly_ the one available.

Example: if Amulet is started on a computer set in "fr_BE", it will defaults to "en_US" despite having a "fr_FR" to provide.

**Describe the solution you'd like**
Look for a language with a matching prefix if one exists.

Example: if "fr_BE" doesn't exist, then "fr_FR" should be used instead.

**Describe alternatives you've considered**
None. Even if there was a language selector inside Amulet, I think it should still fall back on a matching prefix.

**Additional context**
Without this solution, contributors would need to create a file for each variant of every language. It would result in duplicates to maintain for nothing.

Example: "fr_BE" can rely on "fr_FR" without any problem. I seriously doubt that Amulet will encounter any circumstance where it would need 2 different translations.

**Comment by jimbt** [comment]
I experience a different issue with locatization, but I think the immediate fix is the same.  I get a "Cannot set locale to language: English" warning dialog when Amulet Map Editor is started.  I think AME should default to the system locale in the absence of a user configuration.

lib/.../amulet_map_editor/api/framework/amulet_ui.py - line 54
```
        self.locale = wx.Locale(
            wx.LANGUAGE_ENGLISH
        )  # TODO: work out proper localisation
```
If "wx.LANGUAGE_ENGLISH is removed (i.e. no arguments) it seems the default locale is used.  An alternative for me is to replace with wx.LANGUAGE_ENGLISH_US, but if needed that should be a configuration setting.

**Comment by gentlegiantJGC** [comment]
That pull request should fix this issue.
The code first loads the en.lang file.
It then loads the lang file for your computers language ignoring the region. This allows multiple regions to share the same lang file if they are similar enough.
It then loads the region specific lang file if one exists.

**Comment by jimbt** [comment]
This is broken again in version 0.8.2.

Changing this (amulet_map_editor/api/framework/amulet_ui.py, line 54):
    self.locale = wx.Locale(wx.LANGUAGE_ENGLISH)
to this:
    self.locale = wx.Locale()
seems to resolve the warning dialog.

**Comment by gentlegiantJGC** [comment]
I knew there was a reason why I changed this but I couldn't find the reason. In future if your issue isn't the same create a new bug report.
#217 broke this because others were having issues with what it was changed to.
I am going to reopen that and continue from there
