### ISSUE TITLE
Bug: Amulet-v0.7.2.8-osx.zip's .exe does not exist

### ISSUE THREAD

**Issue by SpaceNerden** [Amulet-Team/Amulet-Map-Editor#188]
`Amulet-v0.7.2.8-osx.zip`'s `.exe` file is nonexistent, but i did find a `amulet_app` file with no `.exe` extension on it.

Steps to reproduce:
1. Download Amulet-v0.7.2.8-osx.zip
2. Unzip
3. Look for the `.exe`
4. Realise that there is a `x64` version
5. Download and unpack
6. Find the `.exe` with the same name as the `file` file in the other version
7. Issue a bug report

So I think one of you just forgot to put the extension.

**Comment by gentlegiantJGC** [comment]
OSX executables don't have the `.exe` extension
