### ISSUE TITLE
[Feature Request] Region Pruning Ability

### ISSUE THREAD

**Issue by TheGamersBrew** [Amulet-Team/Amulet-Map-Editor#190]
An ability to mass delete region files in order to prune down worlds in cases where people end up exploring to far out.  Paring this with an world 2d map view to help during the pruning process. You could add a 4th tab under the 3D Editor for a 2d map view to help find places.

**Comment by gentlegiantJGC** [comment]
The alpha build has a 2D view and pruning ability
