### ISSUE TITLE
Unable to rotate camera in 3D editor

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [Amulet-Team/Amulet-Map-Editor#196]
I have been looking at the documentation and the keybinds section, but it doesn't say how to rotate the camera (viewport) in the 3D Editor tab. Any help would be greatly appreciated.

System:                          Windows 10 Home 20H2 build 19042.804
Amulet Version:              v0.8.0b3-windows-x64
Minecraft World Type:     Java 1.16.4

**Comment by gentlegiantJGC** [comment]
Right click and move the mouse

**Comment by EvilSquirrelGuy** [comment]
Thanks, it works
