### ISSUE TITLE
Variable view height in 2D view

### ISSUE THREAD

**Issue by nl255** [Amulet-Team/Amulet-Map-Editor#197]
Currently the 2d rendering mode is pretty much useless in the Nether because it always shows a top down view from the very top of the world which means all you see is bedrock.  I would like to see that changed so that if you teleport to say Y=100 then it would show you a top down view of all blocks at or below Y=100 which among other things would make the 2d view usable in the Nether.

**Comment by gentlegiantJGC** [comment]
The chunk tool now has options to control the max and min displayed height
