### ISSUE TITLE
Cannot open 1.15.2 worlds

### ISSUE THREAD

**Issue by attichicco** [Amulet-Team/Amulet-Map-Editor#20]
I've used those installation steps
-installing python 3.8
-download Amulet-Map-Editor.zip from girhub
-opened a command prompt to Amulet-Map-Editor-master folder
-executed command "python3 -m venv ENV"
-executed command ".\ENV\scripts\activate.bat"
-executed command "python -m pip install --upgrade pip"
-executed command "pip install -r requirements.txt"

and I've run amulet using command "main.py" while still under ENV

program executed correctly (with error about image file not found after pressing select world)
only 2 out of 8 worlds appeared under java, neither of them 1.15.2
I've opened a 1.15.2 world using "Open another world" and selecting the world folder
the program trowed error "Failed to load image file E:\path\to\amulet\ENV\lib\site-packages\amulet\img\missing_world_icon.png 

now, I don't see why an error about an image would prevent amulet from opening a 1.15.2 world

if anything on my installation steps is wrong, please provide installation steps, some requirements are kind of confusing as you don't need to install them, since pip will install them for you...

**Comment by attichicco** [comment]
also I would love if you could make an installation script, I know this software is still in alpha, but right now there is no way to edit 1.15.2 worlds effectively, and this means Amulet is a much needed software as MCEdit is discontinued.

**Comment by gentlegiantJGC** [comment]
You should be able to directly run the exe in the compiled builds.
I need to work on the documentation a bit.
The image error is only an issue in the latest build due to a build error. The version before is fine

**Comment by attichicco** [comment]
I can't see the compiled builds, I am not sure where those are

**Comment by gentlegiantJGC** [comment]
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/v0.6
