### ISSUE TITLE
LevelDB Compression Error

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [Amulet-Team/Amulet-Map-Editor#209]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
No

**Describe the bug**

error during conversation b'Not implemented: encountered a block compressed with an unknown decompressor

**To Reproduce**
1. Go to 'Open World'
2. Click on 'Java World'
3. Scroll down to 'Convert'
4. Click on convert after choosing Bedrock World

**Expected behavior**
Converted world

**Screenshots**

It is not necessary because it has already been explained above what it is about so I am sure that no evidence in the form of an image is required for this case

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [0.8.0b6]

**Additional context**
No

**Comment by gentlegiantJGC** [comment]
1) Try opening with the latest alpha release. We have updated the leveldb library.
2) Open in game and exit then again in Amulet

**Comment by admin-elvistrujanovic** [comment]
Error during conversation WinError -529697949 Windows Error 0xe06d7363

**Comment by gentlegiantJGC** [comment]
Is this a marketplace world?

**Comment by admin-elvistrujanovic** [comment]
> Is this a marketplace world?

No, the world I am trying to convert is Equestria

**Comment by gentlegiantJGC** [comment]
We had someone on the discord server try opening a Marketplace world which gave this exact error.
`WinError -529697949 Windows Error 0xe06d7363`

**Comment by gentlegiantJGC** [comment]
If you can give me an example world that reproduces the issue I can look into it.

**Comment by admin-elvistrujanovic** [comment]
> If you can give me an example world that reproduces the issue I can look into it.

To use this world, first open it in Minecraft v1.12.2

[](https://www.sweetiebelle.org/brohoof.com/backups/equestria5.20160529-0401-full.7z)

**Comment by gentlegiantJGC** [comment]
I have just re-read the issue. The issue is going to be with the world you are selecting as the Bedrock destination world.
Can you open that world in the game to make sure the game is able to open it and if it is close and try opening it in Amulet.
If the error still happens please send over the world and I will have a look.
