### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [Amulet-Team/Amulet-Map-Editor#212]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
No

**Describe the bug**

Error during conversation WinError -529697949 Windows Error 0xe06d7363

**To Reproduce**
1. Go to 'convert'
2. Click on 'convert'
3. Go to to 'bedrock world'
4. Click on 'convert'
5. See error

**Expected behavior**
Converted world

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [0.8.1a16]

**Additional context**
/

**Comment by gentlegiantJGC** [comment]
From a quick google it looks like this is an issue with your computer so not an issue with Amulet
