### ISSUE TITLE
wx Locale assertion error

### ISSUE THREAD

**Issue by DieProgrammIDE** [Amulet-Team/Amulet-Map-Editor#217]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
I downloaded v0.7.28 and extracted it on Windows.
Then I ran amulet_app.exe and this Error appeared

`2021-03-15 11:43:28,105 - amulet_map_editor - CRITICAL - Amulet Crashed. Sorry about that. Please report it to a developer if you think this is an issue.                                                                                       Traceback (most recent call last):                                                                                        File "amulet_map_editor\__main__.py", line 16, in <module>                                                              File "amulet_map_editor\api\wx\util\ui_preferences.py", line 65, in __init__                                            File "amulet_map_editor\api\framework\amulet_ui.py", line 58, in __init__                                               File "amulet_map_editor\api\image\__init__.py", line 14, in bitmap                                                    wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.                                                                                         Things are going to break, please only change locale by creating wxLocale objects to avoid this!                                                                                                                                                Press ENTER to continue. `

**To Reproduce**
Download Amulet and try starting it (Computer Local is Germany, Language is English)

**Expected behavior**
Amulet starts

**Desktop (please complete the following information):**
 - Windows
 - 20H2/Latest (19042.867)

**Comment by gentlegiantJGC** [comment]
Can you see if this version fixes it.
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/0.8.1a16

**Comment by DieProgrammIDE** [comment]
No. Still the same ...

**Comment by Moesh** [comment]
```2021-03-21 09:54:16,215 - amulet_map_editor - CRITICAL - Amulet Crashed. Sorry about that. Please report it to a developer if you think this is an issue.
Traceback (most recent call last):
  File "amulet_map_editor\__main__.py", line 16, in <module>
  File "amulet_map_editor\api\wx\util\ui_preferences.py", line 65, in __init__
  File "amulet_map_editor\api\framework\amulet_ui.py", line 58, in __init__
  File "amulet_map_editor\api\image\__init__.py", line 14, in bitmap
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

Press ENTER to continue.```

Also received this error in 0.8.1a16 and 0.8.1a17.

0.8.1a15 opens without error.

**Comment by DieProgrammIDE** [comment]
> ```
> 
> 2021-03-21 09:54:16,215 - amulet_map_editor - CRITICAL - Amulet Crashed. Sorry about that. Please report it to a developer if you think this is an issue.
> 
> Traceback (most recent call last):
> 
>   File "amulet_map_editor\__main__.py", line 16, in <module>
> 
>   File "amulet_map_editor\api\wx\util\ui_preferences.py", line 65, in __init__
> 
>   File "amulet_map_editor\api\framework\amulet_ui.py", line 58, in __init__
> 
>   File "amulet_map_editor\api\image\__init__.py", line 14, in bitmap
> 
> wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
> 
> Things are going to break, please only change locale by creating wxLocale objects to avoid this!
> 
> 
> 
> Press ENTER to continue.
> 
> ```
> 
> 
> 
> Also received this error in 0.8.1a16 and 0.8.1a17.
> 
> 
> 
> 0.8.1a15 opens without error.

I'll try 0.8.1a15

**Comment by gentlegiantJGC** [comment]
I don't think we are actually using this since we are doing translations independently of WX so I will remove it.

**Comment by gentlegiantJGC** [comment]
I think this change may not have actually fixed the issue like I thought it would.
I have a test build here with the code as it was originally before I initially changed it which should solve it.
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/0.8.2a1

**Comment by gentlegiantJGC** [comment]
Here is what I have tried so far.
```py
1) self.locale = wx.Locale(wx.LANGUAGE_ENGLISH)  # this was present in 0.8.1a15 and before
2) self.locale = wx.Locale(wx.Locale.GetSystemLanguage())  # this was present in 0.8.1a16 and 0.8.1a17
3) # This code was removed between 0.8.1a18 and 0.8.1
4) self.locale = wx.Locale(wx.LANGUAGE_ENGLISH)  # this was readded as of 0.8.2a1

other options
5) self.locale = wx.Locale()  # this throws an assertion error for me
```

DieProgrammIDE (German Locale)
1) asserts and crashes
2) asserts and crashes
3) ?

Moesh (? Locale)
1) works fine
2) asserts and crashes
3) ?

jimbt (via #186)
1) Gives a dialog
2) ?
3) ?
5) Apparently works

**Comment by gentlegiantJGC** [comment]
@jimbt are you running from source or using the compiled builds? What OS are you running on? What is your computer locale set as? If running from source which version of python are you using?

**Comment by gentlegiantJGC** [comment]
I think the latest release fixes this. If anyone else has this issue comment below
