### ISSUE TITLE
Console log error ZeroDivisionError: float division by zero while pruning chunks.

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#228]
Console log error while performing a chunk prune operation on a large selection.

**Steps to reproduce the behavior:**
**1.** Open a Java 1.16.5 world in the 3D editor/viewer.
**2.** Go into chunk view and select a large area of at least 50x50 chunks or greater.
**3.** Run the prune chunks operation.
**4.** Notice in the console this error is present after it's done creating an undo point which takes several minutes and also makes sure to only be looking at the console during this time and have the main editor minimized.

![image](https://user-images.githubusercontent.com/17806994/112235788-bc858180-8c15-11eb-92be-25ab6f3a46eb.png)

 **NOTES** that this error was constantly showing in the console in a loop multiple times while chunks were pruning as soon as I maximized and unminimized the main editor window the errors stopped being printed.
 
  ```py
 Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\behaviour\pointer_behaviour.py", line 83, in _pre_draw
  File "amulet_map_editor\programs\edit\api\behaviour\chunk_selection_behaviour.py", line 128, in _update_pointer
  File "amulet_map_editor\programs\edit\api\behaviour\raycast_behaviour.py", line 102, in get_2d_mouse_location
ZeroDivisionError: float division by zero
 ```

**OS Information:**
 - OS: Windows
 - Device: Desktop
 - Version V0.8.1
 - I have a triple monitor setup if that means anything?

**Comment by yudonglin** [comment]
Based on the code:
```
width, height = self.canvas.GetSize()
z += 2 * self.canvas.camera.fov * self.canvas.mouse.delta_y / height
```
That means somehow the height become zero.

**Comment by gentlegiantJGC** [comment]
yeh that looks like the issue
