### ISSUE TITLE
error displaying the world in the 3D editor

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#244]
this error occurs in new versions of the Amulet Map editor.
error in the 3D graphics editor. part of the world space is not displayed, and the image is layered under the chunks on top of the world.
the error occurs immediately after launching the 3D world editor.
the error occurs in both the Java and Bedrock worlds.

my operating system is windows 10 PRO.

below I have provided screenshots of the problem. as you can see in the version of Amulet map editor v0.8.3b0.dev202103290706 there is no error and everything works fine. but in Amulet map editor v0.8.3a5 there is an image problem.

![Скриншот 02-04-2021 193201](https://user-images.githubusercontent.com/81485476/113480067-e491a200-94ab-11eb-813b-408ecaba9880.jpg)
![Скриншот 02-04-2021 172812](https://user-images.githubusercontent.com/81485476/113480115-2cb0c480-94ac-11eb-9c71-7c5b6a23c61d.jpg)

**Comment by gentlegiantJGC** [comment]
Apparently this still happens in the latest beta

**Comment by Max-RM** [comment]
> Видимо, это все еще происходит в последней бета-версии

yes

**Comment by SolarPH** [comment]
In the current beta, the blocks/chunks being "X-Rayed" disappears when you do a selection mid-air and keep your mouse inside one of the selection box's faces

**Comment by Max-RM** [comment]
> In the current beta, as well as the official 0.8.3 release, the blocks/chunks being "X-Rayed" disappears when you do a selection mid-air and keep your mouse inside one of the selection box's faces.

I know. I realized this a few days ago

**Comment by gentlegiantJGC** [comment]
I don't know if this will actually fix the issue you are having but it might. If this is still an issue in the next release reopen this issue or let me know.

**Comment by Max-RM** [comment]
> Я не знаю, действительно ли это решит вашу проблему, но может. Если проблема не исчезнет в следующем выпуске, откройте ее повторно или дайте мне знать.

Ок
