### ISSUE TITLE
Ubuntu 20.04 - Open GL Issue

### ISSUE THREAD

**Issue by gsbowlin** [Amulet-Team/Amulet-Map-Editor#248]
**Describe the bug**
I'm also running this from master on Linux (Ubuntu 20.04), and after setting the Drop Target, It looks like I'm getting an Open GL issue.

I'm also running from master

The traceback starts in

"Amulet-Map-Editor/amulet_map_editor/programs/edit/plugins/tools/select.py", line 345, in _on_draw
self.canvas.renderer.draw_sky_box()

And ends with an OpenGL error
OpenGL.error.Error: Attempt to retrieve context when no valid context

The error then repeats for what looks like the rest of the drawing sections.

Amulet-Map-Editor/amulet_map_editor/programs/edit/plugins/tools/select.py", line 348, in _on_draw
self._selection.draw()

Amulet-Map-Editor/amulet_map_editor/programs/edit/plugins/tools/select.py", line 347, in _on_draw
self.canvas.renderer.draw_level()

..etc for several screens.

**Comment by jimbt** [comment]
This appears the same as #247.

If you're using wxPython version 4.1.1 (pip list), a workaround is to downgrade to version 4.1.0.

**Comment by gentlegiantJGC** [comment]
Yeh
