### ISSUE TITLE
request to create a function to restore damaged worlds

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#251]
Sometimes people have a problem with world corruption if they have lost or accidentally corrupted world files: Level.dat, LOG, CURRENT, LOCK, MANIFEST-(random symbols) for bedrock edition. or many other corrupted files for java edition. in this case, only the ldb (for bedrock) or mca (for java) files remain from the world.

I would like to offer a feature to restore corrupted world files, so that they are restored with only the ldb (db) or mca (region).
after all if most of the world's data is still intact it is quite possible to restore world.

although the world generation data cannot be fully restored, so a separate button would be required for the user to choose the type of world generation and its sid.

**Comment by gentlegiantJGC** [comment]
I think this is beyond the scope of Amulet. In most cases manual intervention would be required to fix them if they are fixable at all.
