### ISSUE TITLE
Biomes are not converted correctly

### ISSUE THREAD

**Issue by MagnoBooter** [Amulet-Team/Amulet-Map-Editor#255]
**Describe the bug**
When converting a LevelDB world to the Anvil format, terrain in all generated chunks become _Ocean_, when the output world is loaded on a multiplayer server like [Paper](https://papermc.io).

**To Reproduce**
1. Open a bedrock server (LevelDB) world in Amulet.
2. Convert it to a java edition (Anvil format) world.

**Expected behavior**
Chunk biomes should be the same.

**Screenshots**
An example single chunk is shown in these screenshots. Around this single chunk, are chunks generated by the java version server (Paper), so these chunks have the _Forest_ biome.
![Screenshot from 2021-04-13 20-45-17](https://user-images.githubusercontent.com/3240114/114604508-4070dd80-9c99-11eb-9fcd-c41a3102e601.png)
![Screenshot from 2021-04-13 20-47-02](https://user-images.githubusercontent.com/3240114/114604650-74e49980-9c99-11eb-801a-2aa03a31c71f.png)
The selection shown here is near "the middle" of the chunk.
All other chunks coming from the LevelDB world also has the _Ocean_ biome.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: master branch as of 2021-04-12.

**World details**
 - Input world originated from a vanilla 1.16.201.02 bedrock server
 - Output world to a Paper server with Multiverse and WorldEdit.

**Additional context**
I can supply a link to a sample input world, but prefer not to publish it.
To the investigating devs: Please PM me on Discord for a link to it.

**Comment by gentlegiantJGC** [comment]
Can you test if the same issue happens when using the vanilla clients for both platforms?

**Comment by MagnoBooter** [comment]
When loading the output world in single player, biomes are correct. But when loading the world on a (PaperMC) server, the F3 debug output says Biome: ocean everywhere.
So... there is a difference somewhere. Because if I use [Chunker](https://chunker.app/) everything is ok, even when I load the world on my server.

**Comment by gentlegiantJGC** [comment]
Could you supply a world that works correctly (the one you mentioned from chunker) and the one that does not work.
I am tempted to say this is an issue with your modded client or server since it works correctly in singleplayer.

**Comment by gentlegiantJGC** [comment]
I think this was an issue on the paper server that got fixed recently.
