### ISSUE TITLE
Strange miscoloring: "stripy" terrain on Bedrock clients after conversion

### ISSUE THREAD

**Issue by MagnoBooter** [Amulet-Team/Amulet-Map-Editor#257]
**Describe the bug**
After converting a LevelDB world to a Anvil format world, grass_blocks and leaves are rendered in a slightly different color on every 4th Z coordinate, on Bedrock clients. Weird, because Java clients does not see this.

**To Reproduce**
1. Convert a LevelDB world to Anvil format, output it on a Java server (Paper/Spigot).
2. Join the server from a Bedrock client (this requires Geyser, a plugin to enable bedrock clients to join java servers).
3. Now watch the grass_blocks and the trees. Stripy.

**Expected behavior**
Same shade of green on grass_blocks, according to biome.

**Screenshots**
This is how it looks like, on the bedrock client. The chunk in the middle, coming from the LevelDB world, has stripes.
The neighboring chunks are generated on the java server.
Notice how stripes slowly fades away in the newly generated chunks, as you go farther away from the LevelDB chunk:
![Screenshot from 2021-04-13 18-38-14](https://user-images.githubusercontent.com/3240114/114628128-acae0a00-9cb6-11eb-87cc-f9191c870939.png)
The same chunk seen from a Java client:
![Screenshot from 2021-04-13 18-41-30](https://user-images.githubusercontent.com/3240114/114628349-01518500-9cb7-11eb-9c8f-ac720a4b3d4b.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: master branch as of 2021-04-12.

**World details**
- Input world originated from a vanilla 1.16.201.02 bedrock server
- Output world to a Paper server with Geyser, Multiverse and WorldEdit.

**Additional context**

**Comment by gentlegiantJGC** [comment]
Looks like this has been fixed in a newer version of the modded client.
