### ISSUE TITLE
Schematic support

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#26]
Going to use this as a landing page for those that want schematic support.

We are going to support importing schematics but not exporting because the schematic format is not able to support the new block formats.

We are working on a new format that will support the new block format as well as supporting data serialised to any of the version formats (any version of Bedrock/Java).

We will support importing and exporting this new format but there is a little more we need to do first.

We may also support importing some other structure formats.

**Comment by gentlegiantJGC** [comment]
Related to #23 and #24

**Comment by phit** [comment]
> We are working on a new format that will support the new block format as well as supporting data serialised to any of the version formats (any version of Bedrock/Java).

please consider this instead of creating a new format, or alternatively the vanilla structure block format

https://github.com/SpongePowered/Schematic-Specification
https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java

**Comment by gentlegiantJGC** [comment]
@phit Is that format able to handle Bedrock as well as Java data? How would programs that use it deal with the data in Bedrock format? It looks like it has been designed with Java in mind.

**Comment by MulverineX** [comment]
The default format could be a new one that works cross Java/Bedrock, but you should be able to convert/export it to the common formats like vanilla .nbt (I believe bedrock structure files are coming, will probably be a different format though) and either the sponge specification or the legacy mcedit one for schematic files (or both)

**Comment by SeberHusky** [comment]
Please keep in mind while developing that people like me, and many other users of [https://www.minecraft-schematics.com/](Minecraft Schematics) depend on the schematics feature and without MC Edit working anymore my map and gameplay of Minecraft has been crippled along with all other users of MC Edit that have asked all over reddit on what happened to the program. 

This change would also impact the Minecraft Schematics website so please get in touch with them too and see if there are ways to work in legacy support for the schematics system for this program.  All the other Schematic import programs do not let you specifically set placement of schematics like MC Edit did, that was what made it so unique.

Thank you.

**Comment by gentlegiantJGC** [comment]
This is now implemented in the latest version

**Comment by SeberHusky** [comment]
> 
> 
> This is now implemented in the latest version

Thank you so much!  I will check it out soon. You're the best!

**Comment by MulverineX** [comment]
Looks like you only implemented the legacy schematic format and the vanilla Bedrock structure format. It would really be fantastic to get an export/import for the modern schematic format (linked by phit, its the one worldedit currently uses). Also, Java structure support would be great for map makers & survival packs.

**Comment by gentlegiantJGC** [comment]
Yeh that is on the list. This report was specifically about the old schematic format

**Comment by Jhereg10** [comment]
I'm attempting to load some really large exported areas (like 500 x 1500 blocks each) with a VM running 16GB of RAM.  I've seen that I can finish the loading process with about 90% RAM usage.  When it attempts to load the menus you would use to manipulate the import location (but before the 'ghost' of the imported structure appears) it hangs as described above.  I'm going to let it run and see if it will eventually unfreeze, but it's possible I'm just being stupid aggressive.  I've got a 1.16 world that I'm trying to downgrade a large area to 1.12.

**Comment by MulverineX** [comment]
This is not the place, this is a closed feature issue please move to another issue or something. @Jhereg10
