### ISSUE TITLE
improving the maximum camera coordinates for bedrock edition world

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#266]
unlike Java Edition world which has a maximum world boundary of 30000000, Bedrock edition world has a maximum world boundary of 2147483647. but the amulet does not allow to enter a number greater than 30000000 in the maximum camera coordinates. therefore, need to modify the camera coordinates so that ppl can enter the coordinates of 2147483647 while editing bedrock edition world

**Comment by gentlegiantJGC** [comment]
Is there any reason for anyone to need to go that far out?
The game get super glitchy at about 10M blocks from the origin.
https://twitter.com/gentlegiantJGC/status/1314202800012713985
https://twitter.com/gentlegiantJGC/status/1314204043514834948

**Comment by Max-RM** [comment]
yes. there's only one reason - just exploring the world's edge. although it is impossible to play there and nothing can be seen at all https://discord.com/channels/579104065997242368/579104065997242370/812561871722643456

**Comment by Max-RM** [comment]
mojang lied to us about the infinite world. it has the edge of the world
