### ISSUE TITLE
Improvement: Show current coordinates

### ISSUE THREAD

**Issue by tomk2** [Amulet-Team/Amulet-Map-Editor#27]
It would be useful if I can see where I'm at. It would help in testing and I can much easier clone items to a specific predetermined spot rather than having to move a selection little by little.

**Comment by gentlegiantJGC** [comment]
This is on my to-do list. I wanted to do a bit of a UI overhaul before adding it.

**Comment by gentlegiantJGC** [comment]
Just added this
