### ISSUE TITLE
World from minecraftpe not rendered

### ISSUE THREAD

**Issue by luigikitten** [Amulet-Team/Amulet-Map-Editor#285]
**Describe the bug**
The attached world is not rendered, I get a empty landscape.
Many thanks!

**To Reproduce**
1. open amulet
2. open world
3. see that is empty

**Expected behavior**
See it rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/13120620/117502344-a93d3400-af7f-11eb-86fd-a158cab217eb.png)

**Desktop (please complete the following information):**
 - OS: linux ubuntu 20.04 - 64bit
[mondo_nicola.tar.gz](https://github.com/Amulet-Team/Amulet-Map-Editor/files/6444031/mondo_nicola.tar.gz)

 - Version 
amulet-core==1.2.5
amulet-map-editor==0.8.3
amulet-nbt==1.0.3.10
wxPython==4.1.0

**Additional context**

**Comment by gentlegiantJGC** [comment]
Most likely your world is not at 0, 0 where the camera starts at.
There is an issue on Linux that causes the UI not to draw which would show your coordinate.
Ctrl+g will bring up a UI that will allow you to teleport

**Comment by luigikitten** [comment]
Yes, correct! many thanks and sorry for the noise
