### ISSUE TITLE
Copy-paste large area (100x100x250 blocks) leaves big square areas missing in paste.

### ISSUE THREAD

**Issue by Nesh-stack** [Amulet-Team/Amulet-Map-Editor#291]
Copy-paste large area (100x100x250 blocks) leaves big square areas missing in paste.

This was a **Bedrock to Bedrock** transfer.

**To Reproduce**
1. Opened donor world in 3D
2. navigated to the area and switched to 2D
3. selected the breadth of the island visually
4. edited the height coordinates to 0 and 250 (not needing to copy the last few top layers of the world
5. hit copy
6. Opened the recipient world in 3d
7. navigated to the area and switch to 2D
8. hit paste and put it down in the required position
9. used the height adjustment on the left to fine tune the position
10. hit confirm
11. hit save

**Expected behavior**
That the copied area would arrive intact.

**Screenshots**
I hope these attached!
![unknown](https://user-images.githubusercontent.com/71952690/117959730-a5cef180-b35f-11eb-9d19-a07f0a41b635.png)

**Desktop (please complete the following information):**
 - OS: Win10

 - Version 0.8.4 in the launcher.

**Additional context**

**Comment by gentlegiantJGC** [comment]
From what I can tell so far, it only happens when paste air is enabled and a scale or rotation is applied.

**Comment by gentlegiantJGC** [comment]
In the end the error was a part of one line
