### ISSUE TITLE
Alt function error

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#292]
when using Alt, the block data should open, in the new amulet release, the data is no longer shown when Alt is pressed. 
an error appears in the console.

amulet_map_editor - ERROR - name 'BiomesShape' is not defined

![Скриншот 12-05-2021 194857](https://user-images.githubusercontent.com/81485476/117995866-1aebf800-b35b-11eb-9c15-1a0fd137e733.jpg)

this has never happened before

**Comment by Podshot** [comment]
What version of Amulet are you using?

**Comment by gentlegiantJGC** [comment]
This is the latest nightly build. I must have made a mistake in the core rewrite

**Comment by Max-RM** [comment]
in the latest version of the amulet, the error has been fixed
