### ISSUE TITLE
Program launching a barrage of errors, slowing down and crashing (screenshot included)

### ISSUE THREAD

**Issue by NancokPS2** [Amulet-Team/Amulet-Map-Editor#295]
**Describe the bug**
I have no issues loading worlds, even with modded ones, but as soon as i go to the 3D Editor the console starts spouting an endless barrage of errors relating to the UI (whenever the mouse hovers over a button and stuff) and the screen remains light blue with nothing else in it other than the UI
So Amulet slows down to a crawl and sooner than later crashes
This is NOT saved in the logs, but most other messages from the console see to get saved

**To Reproduce**
1. Load a world
2. Click on 3D Editor
3. Issues start

**Expected behavior**
Get a view of the world.

**Screenshots**
![sintitulo](https://user-images.githubusercontent.com/55665720/118754802-1b463080-b83e-11eb-921d-e223a1446ef6.png)
I held the mouse button to stop the console from scrolling, it basically repeats that error infinitely.
After "description=" it says "invalid operation" in spanish, but with other characters breaking up the word

**Desktop (please complete the following information):**
 - OS: [Windows 7 64 Bits]
 - Version [0.8.4]

**Additional context**
None.

**Comment by NancokPS2** [comment]
I want to add, moving the mouse around the editor causes the errors to change (i think, it's hard to know with the endless barrage of errors)

**Comment by gentlegiantJGC** [comment]
https://github.com/Amulet-Team/Amulet-Map-Editor/issues/293

**Comment by NancokPS2** [comment]
> 
> 
> #293

Might be related, altho the user says nothing about the barrage of errors, will report if the new version works when i have time

**Comment by NancokPS2** [comment]
> 
> 
> #293
Never used a whl file before, i managed to install it but i have no idea how to run what i installed. i even went to where the files where downloaded and tried to run _init_.py but nothing happened

**Comment by NancokPS2** [comment]
Update: managed to get it working by doing `pyhton _init_.py` and `pyhton _main_.py` on the downloaded folders until one opened the editor, not really practical but safe to say the error seems to be gone
I did notice some large sections devoid of chunks with lone ones in between, but i have the suspicion this is due to some mods i have (namely the world pregen mod)
Thanks
