### ISSUE TITLE
3D Renderer has strange visual overlay bug [Versions 0.8.4 and 0.8.3] (Windows)

### ISSUE THREAD

**Issue by Ixarias** [Amulet-Team/Amulet-Map-Editor#298]
**Describe the bug**
The ordering of rendering objects seems to be reversed

**To Reproduce**
Problem occurs as soon as a map is opened in the 3D Editor

**Expected behavior**
The 3D render displays graphics beginning with the closest object

**Screenshots**
![image](https://user-images.githubusercontent.com/11237136/119389060-b735c900-bc90-11eb-8f97-551a367b9704.png)
![image](https://user-images.githubusercontent.com/11237136/119389660-8bffa980-bc91-11eb-9b21-23c37a64fba2.png)
![image](https://user-images.githubusercontent.com/11237136/119388896-8190e000-bc90-11eb-80e8-39e50c64e806.png)
![image](https://user-images.githubusercontent.com/11237136/119388975-9bcabe00-bc90-11eb-9a0c-a172ebe48438.png)

**Desktop (please complete the following information):**
 - OS: Windows Version 20H2 Build 19042.928
 - Amulet versions 0.8.3 and 0.8.4 (problem tested to not occur in 0.8.1)
 - Also tested on separate computer running Windows Build 19042.985

**Additional context**
Having the select tool focused makes the issue disappear for as long as it is focused (See Image 4)

**Comment by gentlegiantJGC** [comment]
Is fixed in this release
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/0.8.5b0.dev202105240723
