### ISSUE TITLE
Minecraft Bedrock Edition crashes when playing on a converted world from Java

### ISSUE THREAD

**Issue by 1ordq** [Amulet-Team/Amulet-Map-Editor#299]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
It's been reported on Discord, but not officially on GitHub.

**Describe the bug**
When I convert my world from Java to Bedrock, the conversion works fine, no errors on the console. However, when actually playing the game, I can get to a small part of the world, but by just walking a few chunks (3 or 4), the game crashes. If I raise the render distance, the game crashes before even completely loading the map.

**To Reproduce**
1. Convert the world from Java to a Bedrock world
2. Open the world in Minecraft Bedrock Edition
3. Fly a bit to any direction (I can assure that you're getting the crash if you go in the direction of the sea)
4. Observe that the game will crash.

**Expected behavior**
The world being converted and working without any crashes.

**Desktop (please complete the following information):**
- OS: Windows 10 64 bit, updated (May 24, 2021)
- Minecraft Java version: 1.16.5
- Minecraft Bedrock version: 1.16.221
- Amulet Map Editor version: 0.8.4

**Additional context**
I have already talked about this bug with gentlegiantJGC#9219 on Discord. I have sent the world link to him via whisper on Discord as well, my tag is Hyouka#2334.

**Comment by gentlegiantJGC** [comment]
I am able to get in and view the town you have at about -3500 100 and move around a bit but I moved a bit north east and got a crash. It looks like the issue isn't in the town

**Comment by 1ordq** [comment]
As far as I could test, I think the issue is at multiple places. I deleted sets of chunks using MCA Selector and then converting the world, but the crash keeps happening. I have also talked to neonerz about this issue and we tested it together, he was thinking the problem was with entities or cauldrons, but I'm not so sure of that, since I tried removing all the entities from the world, again, using MCA Selector and then converting it, but the crash kept happening, also, I used WorldEdit to replace every cauldron in a really long radius, but it also didn't prevent the crashes from happening.

**Comment by gentlegiantJGC** [comment]
I am having a go at debugging the game using visual studio which I haven't done before but this might lead somewhere.
Perhaps just down a rabbit hole.

**Comment by 1ordq** [comment]
If there's anything I can do to help, or any information that you need, just HMU :)

**Comment by gentlegiantJGC** [comment]
I still need to do a bit of digging but I believe the issue is due to lecterns

**Comment by 1ordq** [comment]
You're totally right. I used WorldEdit on the Java edition and replaced all lecterns with obsidians and then converted the world. It worked perfectly, we've found our impostor 😄

**Comment by gentlegiantJGC** [comment]
Awesome. I tried replacing them in the converted world and it still crashed so I will need to look into what is causing the crash.

**Comment by 1ordq** [comment]
So, I've tested the world for about 2 hours and it's fine for now, the lecterns definitely were the problem. Thank you so much for the help!

**Comment by gentlegiantJGC** [comment]
I think I have fixed the issue. Hopefully it shouldn't be an issue in the next release
