### ISSUE TITLE
Areas not loading

### ISSUE THREAD

**Issue by gardenerste** [Amulet-Team/Amulet-Map-Editor#301]
This is a bedrock world 

I have a map I have been using and loaded it in amulet to flatten an area off.

I chose the area to be flattened and filled the top spaces with air to get rid of hills ect.

I then selected just the top 2 layers of what was left and replaced with grass.

All seemed to work fine except when loaded back up in game it's like large areas of space under the grass has been removed and is open to the void 

The flattened area is about 500 x 500 roughly

**To Reproduce**
1. Select layers to be flattened 
2. Fill with air
3. Select top 2 layers of now flattened land
4. Replace with grass

**Expected behavior**
Flattened land

**Screenshots**
![Screenshot_20210526-111138_Minecraft](https://user-images.githubusercontent.com/84844323/119643295-7c0fd300-be13-11eb-81d1-6042d4941bdd.jpg)

 - Version 1.16.221

**Comment by gentlegiantJGC** [comment]
What I think has happened is you have filled blocks into chunks that have not previously been generated.
These chunks that do not exist are marked as a black square in Amulet.

If this is the case we have to generate the chunks as void chunks and then apply your changes to them.
The game will not run the normal generation after that.
If you want the normal terrain below that you will need to delete them using the chunk tool, go back into game and fly around to let the chunks generate and then go back into Amulet and apply the changes.

**Comment by gardenerste** [comment]
Omg you was right.
I reloaded the map from a backup I have. Made sure I went around far and loaded all the chunks.
Went back into amulet and did the same thing again and it has worked perfectly :)

Thank you so much
Seems so obvious now Haha
