### ISSUE TITLE
Error:  LoadLibrary failed with error 87: The parameter is incorrect.

### ISSUE THREAD

**Issue by NolonDragard** [Amulet-Team/Amulet-Map-Editor#307]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
When I select the world to open in 3D Editor (Bedrock World) I get the error:
---------------------------
Error
---------------------------
LoadLibrary failed with error 87: The parameter is incorrect.

---------------------------
OK   
---------------------------

**To Reproduce**
Clicking "3D Editor" Throws error Copied above.

**Expected behavior**
The World opens in the 3D Editor

**Screenshots**
![image](https://user-images.githubusercontent.com/85267415/120577582-61bc9300-c3d9-11eb-9342-816f926692ba.png)

**Desktop (please complete the following information):**
 - OS: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎4/‎9/‎2021
OS build	19042.1023
Experience	Windows Feature Experience Pack 120.2212.2020.0
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
Installed RAM	32.0 GB

**Additional context**
Software works fine on my other computer.
Relevant Variables:
 MS Surface Pro 3 
 16GB RAM / i7 6650u 2.21 GHz

**Comment by NolonDragard** [comment]
I know I haven't updated to 8.5 or as the Screenshot shows I haven't.

But I did and the same error occurs.  I reverted to 8.4 when I saw that the software was still working on my MS Surface that hadn't been updated yet.

**Comment by gentlegiantJGC** [comment]
Is there an error in the console?
