### ISSUE TITLE
[Error 13] Permission denied: "resource_packs/readme.txt"

### ISSUE THREAD

**Issue by AbstractXavior61** [Amulet-Team/Amulet-Map-Editor#308]
I'm getting this error when loading a world and I have been trying to find a solution to fix this from other bugs, but no luck so far. It doesn't crash the software but it will not load the world.

Here is a screenshot on what the error says
![Amulet Bug](https://user-images.githubusercontent.com/85416827/120905861-a6833c80-c61a-11eb-9496-36ded8db7e19.png)

If there is anyway you could help with this bug, I would greatly appreciate it.

**Comment by gentlegiantJGC** [comment]
Try moving the whole program to somewhere else on your computer.
I am not sure why this happens but that usually fixes it.

**Comment by AbstractXavior61** [comment]
Fixed it, when I moved it to the .minecraft folder it managed to grab the textures from the folder location.

**Comment by gentlegiantJGC** [comment]
I will look into adding a more obvious error message to help users.
