### ISSUE TITLE
Unable to correctly render world

### ISSUE THREAD

**Issue by Kiernan531** [Amulet-Team/Amulet-Map-Editor#309]
**Describe the bug**
After choosing my Bedrock world to load and then selecting 3d I get an error that says it can not load Java resource pack.  I choose ok and when if finishes loading I just get a few blocks that are just pink and black blocks.

**To Reproduce**
Just choose world to load and then select 3D

**Expected behavior**
For the world to load correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/85450885/120931798-324fa400-c6c1-11eb-804f-67f0fcd15734.png)

![image](https://user-images.githubusercontent.com/85450885/120931837-4abfbe80-c6c1-11eb-8f17-8b944d554d1a.png)

**Desktop (please complete the following information):**
I'm using Windows 10 Pro version 20H2
got same results on both Amulet version 0.8.5 and 0.8.6b0

**Comment by gentlegiantJGC** [comment]
Try restarting Amulet. It usually fixes it

**Comment by gentlegiantJGC** [comment]
If not send a photo of the console

**Comment by Kiernan531** [comment]
> Try restarting Amulet. It usually fixes it

I have reopened and redownloaded multiple times and get the same results every time.  Here is the console once I am all the way in with 3d editor open.

![image](https://user-images.githubusercontent.com/85450885/120944559-284e9500-c703-11eb-8fd4-3c8ca25e2621.png)

**Comment by gentlegiantJGC** [comment]
I am not entirely sure what is causing this. I can only assume it isn't creating the directory for the file to be extracted to.

**Comment by gentlegiantJGC** [comment]
If this is still an issue in the next release let me know
