### ISSUE TITLE
Request: Go To / Move To 

### ISSUE THREAD

**Issue by TechSupportGo** [Amulet-Team/Amulet-Map-Editor#31]
I know this is early and you are still working out issues with compatibility, but could you please add a goto or move to button to move the camera to a specific location in the world? My map is over 1GB in size and manually moving from one side to the other even with the camera speed up takes a very long time. Thanks for creating this in a time when we are forced to be at home. It is much appreciated.

**Comment by gentlegiantJGC** [comment]
Ctrl+g
