### ISSUE TITLE
Modded blocks compatibility

### ISSUE THREAD

**Issue by GoddessSans** [Amulet-Team/Amulet-Map-Editor#314]
Are there any ways of Amulet succesfully reading a mod, being able of rendering the blocks with the right textures and ID? They just break whenever I copy and paste them, ending up in the task of fixing it manually, so I wanna make sure if I'm not doing this extra work for nothing...

(Didn't know in which category to put this "issue" in, my bad)

**Comment by gentlegiantJGC** [comment]
You can extract the resources from each of the mods into the resource pack format and put them in the Amulet resource pack folder and it should load them.

**Comment by gentlegiantJGC** [comment]
You should be able to use it without them but they will look like missing blocks.

**Comment by GoddessSans** [comment]
> You can extract the resources from each of the mods into the resource pack format and put them in the Amulet resource pack folder and it should load them.

I didn't know that was possible, it seems perfect :)
But it will prevent the block from losing the ID as well?

**Comment by gentlegiantJGC** [comment]
This only applies to 1.13+ mods that use the blockstate format in the chunk format.
Even without the resource pack (and with 1.12 and before worlds) you should be able to modify modded worlds just fine but the modded blocks will look like missing blocks since we don't have a model or texture for them.

**Comment by GoddessSans** [comment]
Aw, so there's no help with this corruption, huh?
This is something that can't be solved at all or you reckon it could be "fixed" in a later version of Amulet?

**Comment by gentlegiantJGC** [comment]
I am not really sure what the issue is.

**Comment by GoddessSans** [comment]
Okay, thank you so much for the help and developing an useful program as the likes of this!
