### ISSUE TITLE
Cannot load 3D export of world

### ISSUE THREAD

**Issue by Sayno-D** [Amulet-Team/Amulet-Map-Editor#316]
This is my first time downloading and trying Amulet editor, and I can’t seem to load the 3D export of the world. 

I’m using a bedrock world and when I check the black command screen ( I think that’s what it’s called) it tells me the following error

PermissionError: [Errno 13]  Permission denied: ‘resource_packs/readme.txt’

I seen a resource_pack folder in the amulet file but there’s no readme txt in there. I tried loading Amulet on different worlds too and got the same error. I also tried on worlds with no resource packs either and I still got the same error

**Comment by gentlegiantJGC** [comment]
#308
