### ISSUE TITLE
Corruption: Checksum Mismatch

### ISSUE THREAD

**Issue by sneakysandcrab** [Amulet-Team/Amulet-Map-Editor#319]
When trying to open a world i pulled off my server to reset chunks, i get this error.

**To Reproduce**
1. Open world. Select folder for world. error happens before it opens.

**Screenshots**
![1](https://user-images.githubusercontent.com/85461409/121580569-7d83f280-c9f2-11eb-9846-cab83ef469d9.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by kwellwood** [comment]
I had this problem too. It might just something amulet needs to document. Amulet could only open my world, copied from a bedrock server, after I had opened it as a local world with my minecraft bedrock client. It seems like minecraft slightly changes the file format when you do that.

The "how to download and play on your bedrock server world" tutorial from shockbyte helped:
https://shockbyte.com/billing/knowledgebase/186/How-to-Download-and-Play-on-Your-Bedrock-Server-World.html

**Comment by gentlegiantJGC** [comment]
If someone has an example world I could reproduce this issue with that would help solve it.
