### ISSUE TITLE
macOS leveldb.dylib is not backwards compatible

### ISSUE THREAD

**Issue by Agrrox** [Amulet-Team/Amulet-Map-Editor#327]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
I have seen mention about this on discord that was not addressed.

**Describe the bug**
Running amulet 0.8.8 from Source give error:

<details open><summary>error message</summary>

```
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet/libs/leveldb/libleveldb.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet/libs/leveldb/libleveldb.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet/libs/leveldb/libleveldb.dylib
macbooks-MacBook-Pro:amulet_map_editor macbook$ 
```

</details>

**To Reproduce**
1. Build from source or trough pip `python -m pip install amulet-map-editor==0.8.8 --upgrade`
2. use `python3 -m amulet_map_editor` to run
3. get error in terminal

**Expected behavior**
Should be compatible with older versions than 10.15

**System Specs and Amulet version**
 - OS: macOS 10.13.6 (High Sierra)
 - Version [0.8.8]

**Additional context**
I will provide any information that could help solving the issue. logs from terminal included bellow.

[build_from_source.log](https://github.com/Amulet-Team/Amulet-Map-Editor/files/6645840/build_from_source.log)
[run_pip.log](https://github.com/Amulet-Team/Amulet-Map-Editor/files/6645841/run_pip.log)

**Comment by gentlegiantJGC** [comment]
10.15 is the oldest OS that is available on GitHub actions so we can't build on older.
There might be a way to target an older OS in the build system though. I am not that knowledgeable with C and code compilation so if anyone knows what they are doing the help would be appreciated.

**Comment by Agrrox** [comment]
> 10.15 is the oldest OS that is available on GitHub actions so we can't build on older.
> There might be a way to target an older OS in the build system though. I am not that knowledgeable with C and code compilation so if anyone knows what they are doing the help would be appreciated.

in case it's not possible to target older OS, what should be done to get it successfully building? Maybe instructions on how to get it to work on OS older than 10.15 could be temporarily helpful.
