### ISSUE TITLE
Banner conversion issue J1.14 -> B1.14

### ISSUE THREAD

**Issue by Picorims** [Amulet-Team/Amulet-Map-Editor#33]
Banners miss a frame drawn on them (black frame layer), but other patterns are successfully converted. The world comes from Java 1.14 and got converted to Bedrock 1.14.
The world used is Project Zearth v14 which is a very big map of thousands by thousands of blocks.
I used Amulet v 0.6.4.

![21-04-2020-16-16](https://user-images.githubusercontent.com/41078963/79876571-8202db80-83eb-11ea-9eab-284f5de6dc9b.png)

**Comment by gentlegiantJGC** [comment]
what are the layers of the banner from the input world?

**Comment by Picorims** [comment]
This command will give you the right banner in the Java Edition:
`/give @p minecraft:red_banner{BlockEntityTag:{Patterns:[{Color:9,Pattern:"mc"},{Color:0,Pattern:"flo"},{Color:15,Pattern:"bo"}]}}`
Which is respectively a red background, a cyan circle, a white flower and a black frame.

**Comment by gentlegiantJGC** [comment]
I have just run that command in a Java 1.15.2 world and copied the blocks to a Bedrock 1.16 (beta) world and it looks like they have converted perfectly. It uses the same conversion system as the world converter. 

Can you try again and make sure it is still an issue. I don't know what could be causing the issue and I don't think I have changed this since you opened the report.

If you can reproduce the issue please send over the nbt of the Java block so I can test.

![image](https://user-images.githubusercontent.com/11940194/82054347-b601b180-96b6-11ea-8bca-08cce2331a11.png)

**Comment by Picorims** [comment]
I will make the conversion of the same map in different ways and see how it goes, then I will report back the results. If I cannot reproduce the bug I will also notify that. I may have a clue on the reason it wouldn't work but I need to confirm it.

**Comment by Picorims** [comment]
So, the converted worlds got corrupted for some reason after a Bedrock update (1.14.60, using Amulet 0.6.7), so I couldn't check if the bug happened. Anyway, here is the banner block data (from /data get block):
`{
    x:141,
    y:74,
    z:-152,
    id:"minecraft:banner",
    Patterns: [
        {Pattern: "hh", Color:14},
        {Pattern: "hhb", Color: 14},
        {Pattern: "mc", Color:14},
        {Pattern: "mc", Color: 0},
        {Pattern: "flo", Color: 0},
        {Pattern: "mc"; Color: 9},
        {Pattern: "flo", Color: 0}
        {Pattern: "bo", Color: 15}
    ]
}`
It happens to have much more patterns than what I thought, so I'm sorry for the wrong information provided.

![2020-06-06_14 01 04](https://user-images.githubusercontent.com/41078963/83943938-21472b00-a800-11ea-8a9d-887b59546a34.png)

**Comment by Picorims** [comment]
Additionally, using MCC toolchest PE, I explored the converted Bedrock world data, and found the following for the exact same banner:
![banner converted PZ Bedrock 141 74 -152](https://user-images.githubusercontent.com/41078963/83944313-e2ff3b00-a802-11ea-9ebe-cdd00ca3b34a.png)
What I notice here, is that the 2 last patterns got ignored. That includes the black border which is effectively missing when playing the world. Is the limit of patterns set to 6 on Bedrock Edition ? I know you can bypass this limit on the Java Edition through commands.

**Comment by gentlegiantJGC** [comment]
On further inspection it looks like Bedrock is capped at 6 layers and the game deletes anything beyond that.
Amulet saves everything out correctly so this isn't a bug in Amulet
