### ISSUE TITLE
Java chunk height issue with worlds taller than 512 blocks

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#331]
Java chunks previously used 9 bits per block to store height data.
It looks like this has increased based on the world height.

https://cdn.discordapp.com/attachments/498974201416253443/855495365570985984/world.zip

**Comment by gentlegiantJGC** [comment]
Doing a bit of digging through the Java edition decompiled source code it looks like the number of bits per entry is calculated based on the length of the block palette.
This is fine when saving because this should be the same as the maximum value in the block array.
The issue is when loading and the array is stored in greater than or equal to 11 bits per entry.
In all formats higher than this there is more than one bit size that corresponds to this number of long values so we cannot infer the bit size from the size of the long array.
We may have to get the calling code to pass in the bit size.

**Comment by Brittank88** [comment]
Very interesting - and thank you for looking into this!
