### ISSUE TITLE
Amulet wont Open

### ISSUE THREAD

**Issue by Coder5172** [Amulet-Team/Amulet-Map-Editor#332]
Only the console would open not the actual Application and may cause windows explorer not to respond when stared

**To Reproduce**
Just open Amulet

**Expected behavior**
The application should open up

**Screenshots**
![Screenshot (577)](https://user-images.githubusercontent.com/86161687/122648048-e3841e80-d144-11eb-823a-7fa62ae52b3b.png)

**Desktop (please complete the following information):**
 - OS: 
Processor	Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz   1.60 GHz
Installed RAM	3.92 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

 - 0.8.8

**Comment by chrishardin** [comment]
^

**Comment by gentlegiantJGC** [comment]
Have you tried leaving it for a bit?
I have had this before with the compiled build. I vaguely remember a pop-up from windows about it scanning the application or something. It started up within a minute.

**Comment by chrishardin** [comment]
From my experience, when you try opening the app, the console appears for .1 seconds, closes, and nothing happens after that. However, it works on the beta version, so I just switched to that.

**Comment by ringosham** [comment]
Yup, can't get it working either. I stared at a blank console for half an hour.
I can't get the beta version working either. Same thing.
Log files are empty. On Windows 10 x64

**Comment by gentlegiantJGC** [comment]
Just to confirm the simple. You have all extracted every part of the zip file.

**Comment by ringosham** [comment]
That is correct.

**Comment by gentlegiantJGC** [comment]
Do you have an antivirus program that might be stopping Amulet?

**Comment by ringosham** [comment]
I've paused the antivirus before launching Amulet. Still nothing. Sitting at 0% cpu
If I'm running the beta version, it pops up a message telling me to update, after that same thing.

**Comment by gentlegiantJGC** [comment]
that is odd that you get the update popup and not the main window. That implies that everything else is working.

**Comment by ringosham** [comment]
It's been a while since an update. I found out some things
I managed to get it running from source (inside a venv in Windows).
It is something wrong with the exe package?
