### ISSUE TITLE
Better Linux setup

### ISSUE THREAD

**Issue by uiytt** [Amulet-Team/Amulet-Map-Editor#335]
Currently, Linux user need to manually install wxPython in order to use Amulet.
This is because the default wxPython won't work for every linux os. 
So, some linux os can use pip to install it, and some other need to build it themselves

As mentioned in #281 , it could be possible to generate a specific requirement.txt for each OS in setup.py   
(It's possible to get the name of the Linux OS using `os.uname()[1]`)

**Comment by Cebtenzzre** [comment]
I don't get what you mean by "the default wxPython won't work for every linux os", `pip install wxPython` builds wxPython from source on Linux. [This directory listing](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/) shows builds for CentOS, Debian, Fedora, and Ubuntu, but those are only available via package managers and the wxPython website (AFAIK).

Having wxPython in requirements.txt doesn't stop users from installing their distro's wxPython package first to skip the long build time, but leaving it out is probably more confusing.

**Comment by uiytt** [comment]
> I don't get what you mean by "the default wxPython won't work for every linux os", `pip install wxPython` builds wxPython from source on Linux. [This directory listing](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/) shows builds for CentOS, Debian, Fedora, and Ubuntu, but those are only available via package managers and the wxPython website (AFAIK).
> 
> Having wxPython in requirements.txt doesn't stop users from installing their distro's wxPython package first to skip the long build time (~8 minutes on my computer), but leaving it out allows for a broken install which is probably more confusing.

This issue was initially risen by @gentlegiantJGC . It seems [from this website](https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html), that some OS need to actually build it with something else than just pip.
I personally agree that it's better to have something that work for most Linux os and leaving the other build their own version, instead of something that broke for all versions. (

This post is here to find something that would work for all OS and decide if yes or no wxPython should be installed automatically for Linux os.
