### ISSUE TITLE
Snow layers are generating upon a converted world in Bedrock Edition

### ISSUE THREAD

**Issue by Picorims** [Amulet-Team/Amulet-Map-Editor#34]
With the same setup as issue #33 , Snow layers are generated over the world, including builds. On the provided screenshot we can see one chunk that got ignored versus chunks with snow generation.

![2020-04-21-16-33](https://user-images.githubusercontent.com/41078963/79879091-8d0b3b00-83ee-11ea-856d-175bf99a0c05.png)

**Comment by Podshot** [comment]
This might be something to do with the existing biomes of the destination world. 

@gentlegiantJGC Do we copy over the biome data from the input world as well or do we use the biome data from the target?

**Comment by gentlegiantJGC** [comment]
I would need to check but I am fairly sure we do. Can you check what biome is there in the Java world

**Comment by Picorims** [comment]
I will check the source and destination biomes on and near the bug. Is it useful to recreate the world using the same seed (if we can do so in Bedrock as we can in Java) and check the biome here too ?

**Comment by gentlegiantJGC** [comment]
I don't know what you mean

**Comment by Picorims** [comment]
Sorry, my english is pretty bad. What I mean is, I have looked what is the biome of the bugged chunks on both editions of Minecraft (Java and Bedrock).
So, on the original Java world, is it snowy_tundra or frozen_river. On the destination world, before the conversion, these are plains or forests. I don't know how to get the chunk biome on the Bedrock edition so I can't tell what biomes have been set on the chunks with the bug.
The bug do not happen on every snowy_tundra chunks however.
