### ISSUE TITLE
Help! Map is not rendering.

### ISSUE THREAD

**Issue by Farhankhosravi** [Amulet-Team/Amulet-Map-Editor#343]
Hello
i just downloaded versions 0.8.8 and 0.8.9b of amulet, and they both can't reender any of my maps... this is what happens when i load a map:
![image](https://user-images.githubusercontent.com/77070895/123290961-ed33ca80-d526-11eb-984d-df7f0f4c443d.png)
what is the problem and what should i do now?...
i tried few different maps and results was same. using windows 10 64bit version (updated) and minecraft windows 10 edition 1.17.2 and android edition 1.17.2...

**Comment by gentlegiantJGC** [comment]
Are there any errors in the console?
Usually this issue is solved by restarting Amulet. There should have been a popup that said this.

**Comment by Farhankhosravi** [comment]
> e is solved by restarting Amulet. There should have been a popup that said this.

Thank you, i found out the problem... it was beqause of my VPN on, and looks amulet is unable to download resource pack while VPN is enabled (and it didn't give any errors! I searched cmd log to find out what is problem..)
thanks anyway.
