### ISSUE TITLE
How Do I open Amulet?

### ISSUE THREAD

**Issue by NinaMouselund** [Amulet-Team/Amulet-Map-Editor#347]
When I download Amulet, the folders show up in my downloads, but I have no clue how to actually open and run amulet. there is no open or run file, and nothing on my desktop or anything.

**Comment by Podshot** [comment]
You will need to extract the downloaded `.zip` file which should create a new `Amulet` directory. From there, there should be an `amulet_app.exe` in that directory that you can run to start Amulet
