### ISSUE TITLE
Stuck at save on exit, not responding

### ISSUE THREAD

**Issue by amatulic** [Amulet-Team/Amulet-Map-Editor#352]
Good thing I made a backup of my world first. I wanted to delete all chunks from the world except those around my two home bases.

Steps:
1. Made sure Minecraft isn't running, backed up my world (zip the db folder)
2. Opened the world in Amulet
3. Set render distance to 16 so I could see all chunks I want to keep
4. Clicked on Chunk
5. Set view
6. Selected 87 chunks to keep (two small islands and an ocean monument) out of about 4000 in the database
7. Clicked "Delete Unselected Chunks" with no recovery, waited for screen to finish updating
8. Exit program, select "Save" at the prompt
9. Progress dialog hangs with message "Not responding" in the title bar - no recovery after 1 hour

Trying this again, seemed to work OK if I selected "Save" from the drop-down menu first. This may be difficult to repeat. If there are any exception logs generated, I can attach them, but I don't know where they are if they exist.

Environment:
- Amulet 0.8.8
- Windows 10
- Bedrock Edition 1.17.0 (started the game in 1.14)
- Seed -513070979
- Explored almost the entire starting map (64x64 chunks)
- Selected chunks covering spawn island, nearby island, and nearby ocean monument

**Comment by gentlegiantJGC** [comment]
Which version of Amulet are you using?
I fixed an issue with this in the beta. It might have solved this issue

**Comment by amatulic** [comment]
I'm using 0.8.8, not the beta. I haven't been able to reproduce this, so I guess this can be closed. I'll re-open or re-report if it happens again.
