### ISSUE TITLE
180 degre  rotation mess-up block

### ISSUE THREAD

**Issue by frankicool2010** [Amulet-Team/Amulet-Map-Editor#353]
Bonjour, Hello,

I just discover something. went i do a copy and paste of a model and i flip it 180 degree, on any axys, the model became mess-up and parts are messing and the shape 

I have screenshot to show, but i'm not able to upload here.

i'm using a desktop windows 10 20H2

**Comment by gentlegiantJGC** [comment]
Is it the same issue as #74 ?

**Comment by frankicool2010** [comment]
here is the screen shoots.

The first image is in amulet it self and the other is in the game. you will see that th model was rotage correcly but the model is messy up.

Also you can see that there shadow creatated after a model was applies or some fill up with earth via amulet itself

![issue amulet](https://user-images.githubusercontent.com/86571003/123556500-92ce8000-d759-11eb-994a-f6dca292f591.JPG)
![2021-06-27_14 39 50](https://user-images.githubusercontent.com/86571003/123556531-af6ab800-d759-11eb-9c29-7d61cd609053.png)
![2021-06-27_14 40 43](https://user-images.githubusercontent.com/86571003/123556535-b265a880-d759-11eb-9a8e-e995fe12ea4a.png)
![2021-06-27_14 40 54](https://user-images.githubusercontent.com/86571003/123556536-b5609900-d759-11eb-8754-a288a52e3d49.png)

**Comment by gentlegiantJGC** [comment]
Yeh it is the same issue as #74
