### ISSUE TITLE
Replacing blocks

### ISSUE THREAD

**Issue by AndreTypovsky** [Amulet-Team/Amulet-Map-Editor#365]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
The blocks are replaced with other random blocks after the launch Amulet.

**To Reproduce**
1. Create World with CavesAndCliffs datapack (minecraft version 1.17 candidate 2 and later);
2. Create something building or structure with height over 255 block (or transfer .schematic or .schem on WE or Amulet);
3. Load world via Amulet_map_editor (from code source or compiled);
4. Save and load World via minecraft 

**Expected behavior**
 Look at strange areas 16x16x16 that replaced random blocks

**Screenshots**
https://disk.yandex.ru/d/WDye850nMuhyWg
https://disk.yandex.ru/i/2kfmXahDaLtUbg
https://disk.yandex.ru/i/I4M7drsSez__kQ

**Desktop (please complete the following information):**
 - OS: Windows
 - Version after 0.8.7b0

**Additional context**
0.8.7b0 work withoun this bug
Datapack from CavesAndCliffs
https://disk.yandex.ru/d/Ek-Zc7-ckqHDmA

**Comment by gentlegiantJGC** [comment]
Can you try using a newer version of Amulet to see if it is still an issue.
The .schematic format is limited to blocks from 1.12. Are you exporting to this format and then importing again?

**Comment by AndreTypovsky** [comment]
I used all version newer 0.8.7b0  and I saw this bug. 
The world was converted from 1.16 to 1.17 in Amulet and tested in minecraft 1.17. This bug has not been presented in minecraft or Amulet v. 0.8.7b0. After I saved this world as backup.
The problem occurred in newer versions Amulet. Everytime I loaded backup world in 0.8.7b1, 0.8.7b2, ... 0.8.8. etc and everytime this bug appeared. To check Amulet, the backup was loaded again.

Import is applied to correct building. The .schematic format is used for migration buildings from 1.12 and there is no bug. It's the same with the .schem.

**Comment by AndreTypovsky** [comment]
[Test2Backup.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/6758588/Test2Backup.zip)
1. Open world in minecraft 1.17 and check facade.
2. Open world in latest version Amulet
3. Try to fix the changed areas.
4. Save after editing
5. Open world in minecraft

**Comment by gentlegiantJGC** [comment]
I had another user on discord report what I think is the same issue as this.
I was not entirely sure what the issue was before. I think I have a fix for it though

**Comment by AndreTypovsky** [comment]
This bug removed after fixing amulet/level/interfaces/chunk/anvil/anvil_1444.py. Thanks you!
