### ISSUE TITLE
Hanging on windows when trying to load a schematic, then fails

### ISSUE THREAD

**Issue by RooRay** [Amulet-Team/Amulet-Map-Editor#366]
**Describe the bug**
The windows app hangs when importing schematic files into a java world. The program shows as "not responding" and takes a long time then doesn't import the file.

**To Reproduce**
1) Open the 3D editor
2) Import a schematic file [I used this one](https://drive.google.com/file/d/1IawbsJL1Di5eabVdK5erIgfps_KuQrrE/view)

**Expected behavior**
I expected the editor to open the file.

**Screenshots**
https://imgur.com/3pn9xSi

**Desktop (please complete the following information):**
OS: Windows 10
Version: Build 19041

**Additional context**
None.

**Comment by gentlegiantJGC** [comment]
Which version of Amulet are you using?
It looks like an old version

**Comment by RooRay** [comment]
> Which version of Amulet are you using?
> It looks like an old version

0.8.10 if I remember correctly, I only tested it about 24 hours ago and I installed it for the first time then.

**Comment by gentlegiantJGC** [comment]
The screenshot on mobile was low resolution but it loads fine on desktop.
The version you have screen shotted is really old and is the reason why you are having these issues.
