### ISSUE TITLE
The Java resource pack fails to download

### ISSUE THREAD

**Issue by vinnyg0621** [Amulet-Team/Amulet-Map-Editor#367]
"Failed to download the latest Jave resource pack.
Check your internet connection and restart Amulet.
Check the console for more details.
"There is no item named 'pack.mcmeta' in the archive""

I'm connected to my internet. I don't know what it means that there's no item named 'pack.mcmeta'

1. Go to the console
2. Scroll down to the bottom
3. See that there is no item named 'pack.mcmeta'

I was gonna export a structure, but this just happened 😭

 - OS: Windows
 - Version 10

**Comment by gentlegiantJGC** [comment]
You need to update Amulet

**Comment by vinnyg0621** [comment]
thanks, it worked! :D
