### ISSUE TITLE
When using inspect it doesn't show all the nbt value stuff

### ISSUE THREAD

**Issue by biomseed** [Amulet-Team/Amulet-Map-Editor#370]
I wanna be able to see it all

**Comment by Podshot** [comment]
Could you be a little more specific in what you are wanting to see? Are you wanting to see the NBT data of block entities, such as chests?

**Comment by biomseed** [comment]
> Could you be a little more specific in what you are wanting to see? Are you wanting to see the NBT data of block entities, such as chests?

Yes, but I also want to see all the NBT data of everything, not just block entities

**Comment by biomseed** [comment]
At the end it cuts off and has a "..."

**Comment by gentlegiantJGC** [comment]
This will be implemented in #112
