### ISSUE TITLE
Feature request: Open world argument

### ISSUE THREAD

**Issue by A2va** [Amulet-Team/Amulet-Map-Editor#374]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to open world from command line arguments

**Describe the solution you'd like**
I think a simple solution will be like this;
```amulet_app path/to/world```

**Additional context**
I work on a implementation for supporting Amulet on MultiMC see:
MultiMC/MultiMC5#3713 but I realized that no arguments to open a world are available

**Comment by gentlegiantJGC** [comment]
I plan to add some command line arguments to do various things but I need to rewrite some of the UI stuff to do that.
0.9 we are going to switch UI library to Qt which will mean it will all get rewritten so this will get done then.
There is a bug report already open for command line arguments so I am going to close this as a duplicate.
