### ISSUE TITLE
Small typo orignal -> original on chunk delete window form

### ISSUE THREAD

**Issue by sparks0** [Amulet-Team/Amulet-Map-Editor#379]
**Describe the bug**
A small typo where "original" is spelled incorrectly as "orignal" in the form title and label of the popup when you try to delete chunks.

**To Reproduce**
1. Open a Bedrock world
2. Open the world viewer
3. Switch to 2D view and to the chunk selection tool
4. Select a region of chunks.
5. Click "delete unselected chunks"
6. Observe the popup's text.

**Expected behavior**
Orignal should be spelled original in the form title and body.

**Screenshots**
![Screenshot_269](https://user-images.githubusercontent.com/11044584/126135220-56bb3f8a-48f4-4af9-8719-3eb3da7ffe48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Desktop
 - Version 0.8.12

**Comment by Podshot** [comment]
Closed by #380
