### ISSUE TITLE
Windows OpenGL Core Profile error

### ISSUE THREAD

**Issue by Kitas712br** [Amulet-Team/Amulet-Map-Editor#39]
So, I basically opened my minecraft 1.15.2 world and i wanted to go to the 3d editor, and then this error appeared. 
"Core OpenGL profile is not supported by the OpenGL driver"
Does someone know how to fix this bug?
(sorry if i made any english mistake)

**Comment by Podshot** [comment]
Can you give us a screenshot of the console window? As well some information on what OS and computer hardware you are using?

**Comment by gentlegiantJGC** [comment]
What graphics card/hardware do you have? AMD, NVIDIA, ...
Are you graphics drivers up to date?

**Comment by Kitas712br** [comment]
> Can you give us a screenshot of the console window? As well some information on what OS and computer hardware you are using?

![erro amulet_editor 14-05-20](https://user-images.githubusercontent.com/65303232/81962949-d8c69400-95ea-11ea-8ba4-da2c9fddd5ac.PNG)
![console1](https://user-images.githubusercontent.com/65303232/81962953-da905780-95ea-11ea-9257-40ff1c0c82b1.PNG)
![console 1a](https://user-images.githubusercontent.com/65303232/81962964-dc5a1b00-95ea-11ea-9fa6-527fae524462.PNG)

**Comment by Kitas712br** [comment]
> Can you give us a screenshot of the console window? As well some information on what OS and computer hardware you are using?

I don't know exactly what is my Hardware. But I know that the processor is a Intel Core i3 380M, 4GB RAM and the OS is a Windows 10 Pro.

**Comment by Kitas712br** [comment]
> What graphics card/hardware do you have? AMD, NVIDIA, ...
> Are your graphics drivers up to date?

How can I verify if they are?

**Comment by gentlegiantJGC** [comment]
Based on the processor I am assuming this is a laptop. Most likely integrated graphics since you would probably know if you have a dedicated GPU.

Press the start button and type `dxdiag` and then enter. It should bring up a window with more hardware information. Can you screenshot the system and display tabs and send them over

**Comment by gentlegiantJGC** [comment]
We enabled core profile because there was an issue with a linux user when it was in comparability mode. I forget the specifics. By the looks of it we will probably have to make it dynamic based on some criteria. I do not know enough about opengl to know what the proper solution should be

**Comment by Kitas712br** [comment]
> Ativamos o perfil principal porque houve um problema com um usuário Linux quando este estava no modo de comparabilidade. Eu esqueço os detalhes. Pela aparência, provavelmente teremos que torná-lo dinâmico com base em alguns critérios. Eu não sei o suficiente sobre o opengl para saber qual deve ser a solução adequada

![toleran qua cero](https://user-images.githubusercontent.com/65303232/81969366-39a69a00-95f4-11ea-8937-cefe73f37a2e.PNG)

**Comment by gentlegiantJGC** [comment]
And the second page?

**Comment by gentlegiantJGC** [comment]
I don't know what graphics you have but it is presumably intel HD graphics (integrated)

The drivers you need will be dependant on what you have but it is probably one of these.

https://downloadcenter.intel.com/product/80939/Graphics-Drivers

**Comment by Kitas712br** [comment]
> I don't know what graphics you have but it is presumably intel HD graphics (integrated)
> 
> The drivers you need will be dependant on what you have but it is probably one of these.
> 
> https://downloadcenter.intel.com/product/80939/Graphics-Drivers

through this link i can update my drivers?

**Comment by Kitas712br** [comment]
> And the second page?

![Capturar](https://user-images.githubusercontent.com/65303232/81971084-e5e98000-95f6-11ea-9026-a8e970836950.PNG)

**Comment by Kitas712br** [comment]
Do you know how to fix it? Or is it a bug from my laptop?

**Comment by gentlegiantJGC** [comment]
Did you update your graphics drivers?

**Comment by Kitas712br** [comment]
> Did you update your graphics drivers?

how can I update? Downloading in this link? https://downloadcenter.intel.com/product/80939/Graphics-Drivers
And will it demands more memory ram of the computer?

**Comment by gentlegiantJGC** [comment]
It might be but I can't be of much help. Look up some tutorials based on your hardware

**Comment by gentlegiantJGC** [comment]
Please confirm if this is still an issue in the latest release.
