### ISSUE TITLE
Light block missing model

### ISSUE THREAD

**Issue by Dhranios** [Amulet-Team/Amulet-Map-Editor#395]
**Describe the bug**
Light blocks show as missing textures

**To Reproduce**
1. Place a light block and observe

**Expected behavior**
A model would be shown, like with barriers

 - OS: Windows
 - Version 0.8.18

**Comment by fennectech** [comment]
I think it should be treated like air unless a toggle is enabled.

**Comment by gentlegiantJGC** [comment]
I have just added the required model files to allow these to display.
This will be fixed in the next release.
