### ISSUE TITLE
glazed_terracotta missing supported bedrock data values 0-1

### ISSUE THREAD

**Issue by jigarbov** [Amulet-Team/Amulet-Map-Editor#396]
glazed terracotta on bedrock supports data values 0 and 1 as valid for all colors, but when you edit blocks in a chunk with those blocks they get saved as the "default" data value of 2.
This can cause issues with mechanics when using them for technical reasons and changed the look of builds since the 2 rotation is different to 0 and 1.
![image](https://user-images.githubusercontent.com/30274167/129384989-cd33023f-13bb-4695-9809-9c8b62c1b652.png)

**Comment by gentlegiantJGC** [comment]
This should now be fixed in the translator.
https://github.com/gentlegiantJGC/PyMCTranslate/commit/cedf855a90c60f0b1b5edf6c2695652e56c48688
https://github.com/gentlegiantJGC/PyMCTranslate/commit/49f54f878f69cfd002fa44d5dc9c54d567028563
