### ISSUE TITLE
template/component support

### ISSUE THREAD

**Issue by jonshern** [Amulet-Team/Amulet-Map-Editor#397]
**Has your feature request already been suggested? Please check if your suggested feature has already been suggested.*
I looked but i cannot find it.

**Is your feature request related to a problem? Please describe.*
I create a cool house and i want to make it into a template so i can add to different worlds.
Because i go in and create things and then the kids just destroy it, so i want a easy way to save a house, component, etc.  open an arbitrary world and just apply so it appears

**Describe the solution you'd like**
In theory i would want to be able to select a box, and click save to template.  The template or component or unit (not sure the term) would be saved, and then any world that i wanted to apply it in would be a matter of opening it, selecting the template and then it would insert it.

**Describe alternatives you've considered**
i considered just saving the commands and a collection of fill commands, or making an extension.  However the extension would basically hold a template of a fixed set of templates, vs. something that is configurable.

**Additional context**

**Comment by gentlegiantJGC** [comment]
Sounds like you just want to select an area and click copy then open the new world and paste it in.
You can also export to a file on your computer but that is not required if you do not close Amulet
