### ISSUE TITLE
Unable to convert from 1.15.2 Java -> 1.12 Java

### ISSUE THREAD

**Issue by Buzzbugs** [Amulet-Team/Amulet-Map-Editor#4]
errors in pastebin below 

https://pastebin.com/jDzhUwAy

**Comment by gentlegiantJGC** [comment]
I think this is due to a typo I made when changing a print call to a log call. I will have a new build out in a few days to see if that is the issue

**Comment by Buzzbugs** [comment]
> 
> 
> I think this is due to a typo I made when changing a print call to a log call. I will have a new build out in a few days to see if that is the issue

roger that, thank you for your efforts.

**Comment by gentlegiantJGC** [comment]
Please can you check if this has been fixed in v0.2

**Comment by Buzzbugs** [comment]
> 
> 
> Please can you check if this has been fixed in v0.2

will do that now, thanks!

**Comment by gentlegiantJGC** [comment]
I believe I fixed this a little while ago
