### ISSUE TITLE
Custom namespace and base-name in pick block tool

### ISSUE THREAD

**Issue by FamiliarGecko** [Amulet-Team/Amulet-Map-Editor#40]
The ability to input a custom Base name and Namespace when doing operations.

The current dropdown menu is nice because you don't have to memorise every block id, but it only contains the vanilla blocks, so you can't really do operations with modded blocks apart from cloning them.

(I imagine there could be a "custom" option on top of the dropdown menus, where if you select it, you could input your own Base name or Namespace.)

(Apologies if this is something that can already be done, and I've looked over it...)

**Comment by gentlegiantJGC** [comment]
This is something I have considered and want to implement I just haven't worked out how is best to achieve it

**Comment by gentlegiantJGC** [comment]
This is going to get improved in the future but you should now be able to define custom namespaces and block names in the pick block tool
