### ISSUE TITLE
error of file schematics and barriers.

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#400]
when I save the area containing the barrier to the schematic and then upload it to the world the area is damaged
![19-08-2021_184649](https://user-images.githubusercontent.com/81485476/130080463-a0e79bd7-cd48-4033-a872-22d98583feeb.jpg)
![19-08-2021_184303](https://user-images.githubusercontent.com/81485476/130080467-76b4a886-21bf-4a62-986a-25c806f651db.jpg)

the place next to the barrier is damaged in some places and turned into glass, and numeric. and bedrock turned into a tree.

(the area files have already been sent to GentlegiantJGC.)

**Comment by gentlegiantJGC** [comment]
Is this still an issue?

**Comment by Max-RM** [comment]
> Is this still an issue? If so can you provide some more details so I can debug the issue. Did you just export barrier blocks to a schematic file and then import it again?

I sent you schematin of this machine a long time ago. ok I'll just download the new version of amulet map editor and check if there is still this error

**Comment by Max-RM** [comment]
> 

Yea. I export it then import it using schematic. Even newest amulet beta still have this problem
![unknown](https://user-images.githubusercontent.com/81485476/168464873-7a7eba83-26d9-4b46-8264-d27a80ed7909.png)

**Comment by Max-RM** [comment]
If you need I can send schematic in DM. 

Btw, the new beta version of the amulet no longer has an error related to UI and texture pack downloading

**Comment by gentlegiantJGC** [comment]
Is this a .schematic or .schem file?

**Comment by gentlegiantJGC** [comment]
Here is a full list of information that I need:
What kind of schematic did you export it as?
What platform and version did you select when you exported it?
When you press alt and hover on the purple and black checker block what does it say (screenshot)
What do the errors in the console look like?

**Comment by gentlegiantJGC** [comment]
I have just exported and re-imported a schem and schematic file in various formats and all worked fine.
![image](https://user-images.githubusercontent.com/11940194/168467586-22ff8d45-d946-4be6-b2c4-566dc8cff6dd.png)

**Comment by Max-RM** [comment]
> Is this a .schematic or .schem file?

Schematic

**Comment by Max-RM** [comment]
> Here is a full list of information that I need: What kind of schematic did you export it as? What platform and version did you select when you exported it? When you press alt and hover on the purple and black checker block what does it say (screenshot) What do the errors in the console look like?

Bedrock Edition 
![unknown](https://user-images.githubusercontent.com/81485476/168468372-21e031a7-7732-4a07-81da-f307a4c01768.png)


![unknown](https://user-images.githubusercontent.com/81485476/168468398-4dc595ef-1545-4a16-ab9e-b11628377f71.png)

**Comment by Max-RM** [comment]
Console



2022-05-16 15:34:32,200 - amulet_core - INFO - Loading level D:м\3D Minecraft objects\Schematic_files\2022_test0.schematic
2022-05-16 15:34:33,855 - pymctranslate - WARNING - Could not find translation information for block minecraft:numerical[block_data=0,block_id=256] to universal in PyMCTranslate.Version(bedrock, (1, 12, 0)). If this is not a vanilla block ignore this message
2022-05-16 15:34:40,195 - pymctranslate - WARNING - Could not find translation information for block minecraft:numerical[block_data=0,block_id=256] from universal in PyMCTranslate.Version(java, (1, 18, 0)). If this is not a vanilla block ignore this message

**Comment by gentlegiantJGC** [comment]
Can you share the schematic file here so I can have a look at it. You will need to put it in a zip file and then you can just drag it into the comment box to add it as an attachment.
Something odd is happening because the block id for barrier blocks was 166 on java and 416 on bedrock.

Are you running the compiled version of Amulet (the one from the website) or installed through pip?

Here is a file I exported from my install
[bedrock_barrier.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8694814/bedrock_barrier.zip)

**Comment by Max-RM** [comment]
> Can you share the schematic file here so I can have a look at it. You will need to put it in a zip file and then you can just drag it into the comment box to add it as an attachment. Something odd is happening because the block id for barrier blocks was 166 on java and 416 on bedrock.
> 
> Are you running the compiled version of Amulet (the one from the website) or installed through pip?
> 
> Here is a file I exported from my install [bedrock_barrier.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8694814/bedrock_barrier.zip)

I use compiled beta. Schematic in dm

**Comment by Max-RM** [comment]
note that 2 of the barrier walls are intact, but the other 2 are damaged. maybe it has something to do with the x and y axes

**Comment by gentlegiantJGC** [comment]
Okay I can reproduce this from importing and exporting the construction file you sent me.

**Comment by Max-RM** [comment]
![Скриншот 16-05-2022 193300](https://user-images.githubusercontent.com/81485476/168478510-a7028fc6-84e5-4d53-aba3-877f84a0faae.jpg)
![Скриншот 16-05-2022 193333](https://user-images.githubusercontent.com/81485476/168478513-d3ccf1d6-c206-44a6-b1ac-ce1246231771.jpg)
