### ISSUE TITLE
[Bug Report ] Light Block texture is missing in Minecraft Bedrock in 1.17.11.1

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#403]
**Describe the bug**
The light blocks are missing a texture for Minecraft Bedrock 1.17.11.1

**To Reproduce**
1. Load a Minecraft Bedrock 1.17.11.1 world that has light blocks light value 15 placed in the world.
2. Once you move to the area you placed your light blocks in look at the texture you will notice it to be purple & black.

**Expected behavior**
The texture is supposed to render with the light block possibly use the item texture on all 6x sides would be a good alternative unless using a custom asset may be better?

**Screenshots**
![image](https://user-images.githubusercontent.com/17806994/130366058-3ae3fbc8-80fd-46e2-8212-2feb8422ba77.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version V0.8.10

**Additional context**
N/A

**Comment by gentlegiantJGC** [comment]
?
