### ISSUE TITLE
Hope to support the higher world of version 1.17+

### ISSUE THREAD

**Issue by TACGqwq** [Amulet-Team/Amulet-Map-Editor#406]
In version 1.17+, mojang gave a data packet interface that can reach a height of 2032, but now all map editors can't work perfectly.

And neither mojang nor other third-party authors can make the world that uses data packets in version 1.17 can be converted to the future version 1.18

**Comment by TACGqwq** [comment]
My english is not good, forgive me

**Comment by gentlegiantJGC** [comment]
We don't support snapshot worlds because the format changes too quickly.
We will support 1.18 once it gets to full release
