### ISSUE TITLE
Windows OpenGL glBindTexture error

### ISSUE THREAD

**Issue by Wuyue552** [Amulet-Team/Amulet-Map-Editor#41]
![屏幕截图(57)](https://user-images.githubusercontent.com/65454323/82121570-b5554200-97c0-11ea-88ee-82c452c37f20.png)

**Comment by gentlegiantJGC** [comment]
What does the console say?

**Comment by Wuyue552** [comment]
> What does the console say?

![屏幕截图(58)](https://user-images.githubusercontent.com/65454323/82122088-06b30080-97c4-11ea-941e-fdd84f4ec945.png)

**Comment by gentlegiantJGC** [comment]
Does this happen every time you open the program or only some of the time?

**Comment by gentlegiantJGC** [comment]
Please confirm if this is still an issue in the latest release.
