### ISSUE TITLE
Override World

### ISSUE THREAD

**Issue by Argoneon1810** [Amulet-Team/Amulet-Map-Editor#410]
**Has your feature request already been suggested? Please check if your suggested feature has already been suggested.**

**Is your feature request related to a problem? Please describe.**
Recently 1.17.30.24 faced a severe bug which is nether chunk lowering (https://bugs.mojang.com/browse/MCPE-140436).
By this, even myself personally am experiencing difficulty to find any solution to recover my nether world.
If it is about complete resetting (turning nether into whole new state) there are few how-to videos in the internet, but there is no tutorial for recovering nether from a previous saved state.
Yes, I have my world's backup, and currently, because of the bug, I havent made any intentional change into nether other than 64blocks lowering, caused by bug.
However, in the current solution, I have to find every single unloadable, red marked sections from the corrupted world, select equivalent area from backup world, and then replace it. Every steps are time consuming, and I believe it doesnt have to be.
Unfortunately the internet does not provide which ldb file is nether and which is not, but it seems you know which is which. Please, make an option to override nether from backup so that 1.17.30.24 bug experiencers can recover our nether farms.

**Describe the solution you'd like**
Without read-and-render, find nether ldb files from target, wipe it, and replace them with the one from backup world. Ask player's consent as the one might have accessed it accidently.

**Describe alternatives you've considered**

**Additional context**

**Comment by gentlegiantJGC** [comment]
Each dimension is distributed across the ldb files and each file can store data for more than one dimension. It isn't anything like the Java setup.
Your best bet is just copying from a backup.
