### ISSUE TITLE
[Bug Report] Water logged blocks didn't get copied when pasting

### ISSUE THREAD

**Issue by TrainedPro** [Amulet-Team/Amulet-Map-Editor#411]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
Water logged blocks are not water logged after being pasted.

**To Reproduce**
1. Copy water logged blocks
2. Paste water Logged blocks

**Expected behavior**
Water logged blocks to be transferred

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.8.13a11

**Additional context**

**Comment by gentlegiantJGC** [comment]
What game platform and version are you copying from and to?

**Comment by gentlegiantJGC** [comment]
https://discord.com/channels/324647192583340043/498974201416253443/885044646324084779

**Comment by TrainedPro** [comment]
My apologies, the game platform was Minecraft Bedrock and it was the latest version 1.17.11.04 (Not sure if that's the exact number)

**Comment by gentlegiantJGC** [comment]
I can't reproduce this in 0.9.3b0 so this may have been fixed at some point in the past.
I tested on Bedrock 1.18.30 with some sea grass.
If this is still an issue please let me know.

**Comment by gentlegiantJGC** [comment]
https://discord.com/channels/324647192583340043/405249314131017730/980140365195669574

**Comment by Miruzaa** [comment]
still an issue in 0.9.2, however it only apply when there's any rotation when pasting. I tested on Bedrock 1.18.31, both i try with copy pasting the structure and importing mcstructure

**Comment by gentlegiantJGC** [comment]
All the tests I have run work as I expect.
If this is still an issue please can someone add more information.

**Comment by gentlegiantJGC** [comment]
I was testing with seagrass which is always waterlogged.
I can reproduce this issue with other blocks.
