### ISSUE TITLE
height rendering error

### ISSUE THREAD

**Issue by xBrayanR** [Amulet-Team/Amulet-Map-Editor#414]
The height displayed in the editor is incorrect (≈63 blocks less). Then it does not generate the blocks of height 62 down by being in y<0 in the conversion a bedrock world to java

https://www.mediafire.com/file/ehpi3y92n55jf8p/ArcadeDownload.mcworld/file
-bedrock world import file with error
![2021-09-15](https://user-images.githubusercontent.com/90773462/133444410-81296aeb-cc67-4dcd-8fe9-434e855e2515.png)

**Comment by gentlegiantJGC** [comment]
This may be fixed in the latest Amulet beta that we released yesterday
