### ISSUE TITLE
World doesn't render properly (AMD issue?)

### ISSUE THREAD

**Issue by Wapply** [Amulet-Team/Amulet-Map-Editor#415]
Windows 10 Pro (2004)
CPU: i7 4790k
GPU: AMD R7 260x (21.3.1)
RAM: 8GB

https://user-images.githubusercontent.com/88293580/133462896-fe756242-bc66-4408-9535-d970b5bf4579.mp4

**Comment by gentlegiantJGC** [comment]
This is a duplicate of #405
