### ISSUE TITLE
Option to Select language / Disable locale detection

### ISSUE THREAD

**Issue by jupiterbjy** [Amulet-Team/Amulet-Map-Editor#425]
### Is your feature request related to a problem? Please describe.
Recently added Korean translation is making Amulet more challenging to use due to bad translation. Some menus are misleading - I suspect machine translation.

### Describe the solution you'd like
- option to select language

or

- option to disable locale detection - so one can remain in English language.

### Describe alternatives you've considered
If time isn't an issue, I'd like to see and help Korean translation after the semester.

**Comment by atmos6767** [comment]
I'm a Korean and was quite frustrated to see weird translations. I don't much about software developing, but can translate english in to korean. I'd be happy to give help

**Comment by gentlegiantJGC** [comment]
A language selection button has been added to the main menu.
