### ISSUE TITLE
opengl 3.0 error 

### ISSUE THREAD

**Issue by Axolotyl25** [Amulet-Team/Amulet-Map-Editor#427]
win10
8 g ram
toshiba laptop

Reading told me that this was previously solved, but I am getting the error - which isn't the first time I have had this damn error, been all through intel compatiblilities and checks and new dll etc.  no good.

**Comment by Kheiku** [comment]
Também estou com esse problema

**Comment by CodeKid0** [comment]
You may want to update your graphics card driver. Or download new version of amulet editor.

**Comment by gentlegiantJGC** [comment]
I have modified the OpenGL code and may have fixed this issue.
Please can you try again with the 0.10 betas
