### ISSUE TITLE
Ability to export .schematic for mine-imator

### ISSUE THREAD

**Issue by DearFox** [Amulet-Team/Amulet-Map-Editor#432]
I really want to have an alternative to mine-imator's built-in .schematic exporter. Yes, I can export to the old .schematic, but it does not support the new blocks that I often use in buildings.
[Here is an example of a file that I would like to receive when exporting.](https://drive.google.com/file/d/10bZEd_7ZL8QzrlN-VmfShDKkKqeAn643/view?usp=sharing)

I think this will be useful not only for me, but also for everyone who uses mine-imator.

**Comment by DearFox** [comment]
Unfortunately mine-imator only supports this format.
yes, there is a built-in program for creating such files from worlds, but this is sometimes extremely inconvenient and problematic.

This program has no name of its own, but I found a repository with it. Perhaps this will help somehow. But the repository hasn't been updated for a long time, and I'm not sure if the program hasn't been updated since then.
https://github.com/stuffbydavid/Mine-imator-world-importer

I can also give you the exe file of this program which is used to create such files. Or you can find it yourself in the mine-imator files. It is built-in by default.
You can find it along this path: ...\Mine-imator\Data\import.exe

**Comment by PREMIEREHELL** [comment]
The proper header for sponge export is missing, I believe it should have Schematic, This would make it compatible with a renamed I believe. I wasn't able to edit the header in NBT Studio,
  all you need to do is take a working Schematic file and copy over the data to that file and save and it works.

**Comment by DearFox** [comment]
> The proper header for sponge export is missing, I believe it should have Schematic, This would make it compatible with a renamed I believe. I wasn't able to edit the header in NBT Studio,
> all you need to do is take a working Schematic file and copy over the data to that file and save and it works.

This doesn't sound like a good alternative to the built-in tool.
I wanted to be able to use amulet to create .schematic files compatible with mine-imator.
Maybe someone could write a simple program that would turn new schematic files into the .schematic I need, but I'm more of a web developer and can't do that myself.

It's just a matter of convenience, but thanks for the suggestion, I'll try it as an option.

**Comment by gentlegiantJGC** [comment]
Okay that should be a simple fix

**Comment by DearFox** [comment]
I checked and it seems that it still doesn't work (I'm using the latest stable version 0.8.17)

**Comment by DearFox** [comment]
I was able to get it to work, but it's clearly not the result I'd like x)
![image](https://user-images.githubusercontent.com/59219907/153256171-caef9ddc-0402-4990-8ced-cf025847ad95.png)
Region in the program
![image](https://user-images.githubusercontent.com/59219907/153256972-5a16179d-6898-4f31-bee2-5bf2b5ab7541.png)
I export it as schem
rename to schematic
change version from 2 to 1 (this is the only way Mine-Imator opens this scheme)
![image](https://user-images.githubusercontent.com/59219907/153257645-8a37cd75-b7c3-41ac-9050-49ea1dcfcb4f.png)
It is imported but broken
![image](https://user-images.githubusercontent.com/59219907/153258103-001c5177-b98d-485d-aede-f309aecb7356.png)
