### ISSUE TITLE
Observers

### ISSUE THREAD

**Issue by PoppyMonster970** [Amulet-Team/Amulet-Map-Editor#438]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
I don't Think so.

**Describe the bug**
The program confuses upward and downward facing observers with each other.  Sometimes they are mix match to where some observers are correct, and others are not.  This is problematic because I can't move my redstone slime machines without breaking them.  I also can't use the fill and replace command as a substitute because not all of the observers get reversed.

**To Reproduce**
Edit any object with upward or downward facing observers.

**Expected behavior**
if you spawn you redstone machines with upward or downuward facing observers, many of them will be reversed in the edited chunks.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 10.0.22000.194

**Additional context**
I would greatly appreciate a fix to this issue.  Ever since Minecraft update 1.17.30, I have had to keep Minecraft downgraded to use programs like Mcedit.  Most of my work involves building massive slime machines and observers are detrimental to there functionality.  Keep up the great work with this application, I'm rooting for you guys( :

**Comment by PoppyMonster970** [comment]
Every version I have tried has this issue; including v0.8.12, v0.8.13a10, and v0.8.13b


![Amulet V0 8 13b0 10_30_2021 1_27_49 PM](https://user-images.githubusercontent.com/92261730/139554850-dfe7d3f0-105c-4eeb-b803-a49301136645.jpg)
![Amulet V0 8 13b0 10_30_2021 1_28_23 PM](https://user-images.githubusercontent.com/92261730/139554851-ca9286e8-f351-42f6-a1f6-f3222be9df99.png)
![Minecraft 8_17_2021 3_13_39 PM](https://user-images.githubusercontent.com/92261730/139554861-31770909-fb81-4dd8-8e08-49228a74d870.png)

0.

**Comment by gentlegiantJGC** [comment]
I can't reproduce this issue in Bedrock 1.18.30 and Amulet 0.9.3b0.
Is this still an issue?

**Comment by PoppyMonster970** [comment]
No, I figured out it was an issue with MC edit.  The fix was to generate all of the chunks around the machine before loading Amulet.  The glitch was caused by spawning newly altered blocks added with MC edit.
