### ISSUE TITLE
When I select world and this rendered I don't see world. And in console show this error: Could not find a matching interface for ('java', 2836)

### ISSUE THREAD

**Issue by Andruha656** [Amulet-Team/Amulet-Map-Editor#441]
I describe bug in title. What to do with this?
![image](https://user-images.githubusercontent.com/34016757/137182481-372d98f6-f2f3-43e3-bbe0-f028c5d0daa9.png)
![image](https://user-images.githubusercontent.com/34016757/137182569-714bcc5a-0544-44a0-b853-e791e206c399.png)

**Comment by gentlegiantJGC** [comment]
We don't support snapshot versions

**Comment by Andruha656** [comment]
Oh. Okay I open not snapshot world and this loaded. Thank you!
