### ISSUE TITLE
Jerky Movments while rendering the map

### ISSUE THREAD

**Issue by MyIDisMine** [Amulet-Team/Amulet-Map-Editor#443]
Hello, 
I'm experiencing jerking movements on my whole system while trying to use Amulet.
This makes it almost impossible to use precisely on all kind of map rendering.

It reports the bug to the whole system as long as Amulet is running.
I'm using Amulet 64 Bits for Windows 0.8.15 directly out of the box.
Windows 7 64 Bits Enterprise
System reports :
CPU usage around 50 to 60%, Memory usage below 60% and Hard Disk Usage below 20 % so I suppose this is more like a dependancy issue rather than ressources issues. I tried with very small maps too.

Didn't seen any other bad behavior so far but I haven't been able to test everything.

Can you help me investigate ?

Many Thanks

**Comment by gentlegiantJGC** [comment]
There are momentary lag issues when some long running processes run. I want to work out how to minimise this but these issues are normally minimal.
What is the usage on your GPU like? I don't know if task manager shows this for integrated GPUs

**Comment by gentlegiantJGC** [comment]
I think the newer versions should behave better. If you still have issues let me know.
