### ISSUE TITLE
Amulet Seemingly corrupted world.

### ISSUE THREAD

**Issue by FalcoKick** [Amulet-Team/Amulet-Map-Editor#445]
Used Amulet to copy and paste a building today, logged back in and there was random leaves floating around and some other seemingly regenerated blocks across my world. Logged back into Amulet to see what was up and a lot of chunks were missing and sky had red blocks in it.

**Comment by FalcoKick** [comment]
![Minecraft 10_21_2021 8_47_20 PM](https://user-images.githubusercontent.com/69649815/138376059-dcad827f-98db-4934-b4ff-8ed70b575982.png)
![Minecraft 10_21_2021 8_49_48 PM](https://user-images.githubusercontent.com/69649815/138376063-545e4a41-8031-4934-8863-5f0e52a4f985.png)
![Minecraft 10_21_2021 8_49_18 PM](https://user-images.githubusercontent.com/69649815/138376064-5935fa50-b406-456d-b14d-34c80932091c.png)
![Minecraft 10_21_2021 8_47_35 PM](https://user-images.githubusercontent.com/69649815/138376067-152850ed-fa1d-4ad3-bf13-11830b8647ab.png)

**Comment by gentlegiantJGC** [comment]
I am going to close this because I believe it is an issue with the game with the 1.18 experimental features enabled.
We don't support experimental versions.

**Comment by lizardpeter** [comment]
> I am going to close this because I believe it is an issue with the game with the 1.18 experimental features enabled.
> We don't support experimental versions.

My world was corrupted on 1.17.4 without experimental features enabled.

**Comment by gentlegiantJGC** [comment]
This bug report is about a Bedrock world not a Java world

**Comment by lizardpeter** [comment]
> This bug report is about a Bedrock world not a Java world

Yeah, I’m talking about a Bedrock world too.

**Comment by gentlegiantJGC** [comment]
1.17.4 isn't a version on bedrock

**Comment by lizardpeter** [comment]
> 1.17.4 isn't a version on bedrock

I guess I meant 1.17.40, which is a version of Bedrock.

https://minecraft.fandom.com/wiki/Bedrock_Edition_version_history
