### ISSUE TITLE
Does not work with Java 1.18 snapshot worlds

### ISSUE THREAD

**Issue by GameParrot** [Amulet-Team/Amulet-Map-Editor#451]
**Describe the bug**
When opening a Java world in a 1.18 snapshot, like 21w43a, you cannot use the 3D Editor or convert it.

**To Reproduce**
1. Create a Java world in 21w43a
2. Open the world in Amulet
3. Try to use the 3D editor

**Expected behavior**
The 3D editor and conversion should work on worlds from 1.18 snapshots

**Screenshots**
![Screen Shot 2021-11-02 at 11 56 57 AM  11-2-21](https://user-images.githubusercontent.com/85067619/139888877-fb7464ef-9cd6-4bad-8a02-8e881bffcb10.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - Version 0.8.15

**Additional context**

**Comment by gentlegiantJGC** [comment]
We do not support snapshot versions.
Most likely though your amulet-core library is out of date.
