### ISSUE TITLE
The latest version do not support bedrock 1.17.40 worlds

### ISSUE THREAD

**Issue by VoryWork** [Amulet-Team/Amulet-Map-Editor#452]
THE MOJANG HAD UPDATED ITS WORLD FORMAT
So That the newest world will ocurr a error in 0.8.15 version amulet.
The chunks which edited by 1.17.40+ will be marked red in Amulets world editor.

**Comment by gentlegiantJGC** [comment]
From my understanding that only happens with the experimental features enabled which we don't support

**Comment by VoryWork** [comment]
Thank you for your answer. It seems the error caused by using the deeper(-64 to 384) world.

**Comment by XoRazzor** [comment]
Do you have any plans in the future to support experimental worlds?

**Comment by XoRazzor** [comment]
Do you have any plans in the future to support experimental worlds?
