### ISSUE TITLE
[Feature Request] Add a open operations/plugins directory button & shortcut.

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#453]
Here's a feature request that adds a quick shortcut & button to open the current instance would open up a file explorer window with the current amulet operations folder.

Add a simple way to open the operations directory easily from the Amulet UI and to be able to press a shortcut key for opening the folder as **ALT + P** or **ALT + O** possibly another one entirely.

![image](https://user-images.githubusercontent.com/17806994/140447886-b36983f0-3b0d-4bee-b407-ff59e768ca92.png)

**Comment by gentlegiantJGC** [comment]
This is added in 0.10
