### ISSUE TITLE
Mac OS texture pack does not display

### ISSUE THREAD

**Issue by Delipan123** [Amulet-Team/Amulet-Map-Editor#456]
I have the latest version of Mac OS version 11.6 Big Sur. amulet editor is not displaying the texture pack.
<img width="1680" alt="Screen Shot 2021-11-10 at 6 56 34 PM" src="https://user-images.githubusercontent.com/49510539/141223678-98a2adbc-c4e3-4daa-8e0b-72c80ab8d327.png">

**Comment by waterbang** [comment]
me too

**Comment by gentlegiantJGC** [comment]
Most likely you haven't installed the certificates that allow python to access the internet.
There will be a certificate file in your python instillation that you will need to run.
If you have already done that then it might just be another issue with downloading resource packs.
Those issues are going to managed in #419

**Comment by Delipan123** [comment]
That worked thank you
