### ISSUE TITLE
Error recognizing Y border height for custom worlds

### ISSUE THREAD

**Issue by CreativeTechniworks** [Amulet-Team/Amulet-Map-Editor#459]
in java edition, there is an issue when it comes increasing the height of the editor's 'save zone'. 

What I was running in to is that whenever i'd generate a custom world with height above 256, the editor wouldn't recognize it. This is because custom worlds have gotten an extra update in 1.17.1 where the height is now controlled internally instead of a datapack. I think amulet isn't recognizing the .json script for world generation.

https://misode.github.io/world/ you can go here to get your own script quickly if you want. Just find the .json file generated using the "import settings" button on your new world and you can generate a map with these settings.

Example of this error; this world had a setting of 512 height but amulet was only noticing it was at 256. 
The attached image was run with version 1.17.1 release, multiMC 5, using the fabric mod set with all dimension world height and when dungeons arise. Using java sdk. I don't think that would impact it but information included just in case.

![unknown](https://user-images.githubusercontent.com/94184600/141488896-c5a5805b-7d72-4455-8a2a-997e42daa81a.png)
.

**Comment by gentlegiantJGC** [comment]
Can you link an example json file/resource pack that has this issue.
I can't reproduce the issue on 1.17.1.
I can create a json file with the extended height embedded and I can create a data pack with the extended height separate (caves and cliffs bp) but both of these work as intended.

I have found and fixed the same issue in 1.18 (presumably because the default height changed)

**Comment by gentlegiantJGC** [comment]
Is this still an issue? Without a world to test with I can't debug this. I tried using the link you sent but I couldn't reproduce the issue.

**Comment by gentlegiantJGC** [comment]
I am going to close this because I can't reproduce the issue.
If you can still reproduce the issue please send me a reproducible example so I can debug it.
