### ISSUE TITLE
Feature: Setbiome

### ISSUE THREAD

**Issue by Dy1anBy1an** [Amulet-Team/Amulet-Map-Editor#46]
The feature to set an area that does not have to be chunk aligned to a specific biome, including all the new biomes introduced in 1,13+, The Void only on Java, and Legacy Frozen Ocean only on Bedrock would be a very nice feature to have.

**Comment by A2va** [comment]
In the same idea it would be great to implement the features of BiomePainter (https://mblaine.github.io/BiomePainter/).

**Comment by gentlegiantJGC** [comment]
That is the kind of thing I had in mind. Biomes in the newer Java versions are 3d so we would also need to account for that somehow
