### ISSUE TITLE
Bedrock file size not reduced after deleting chunks

### ISSUE THREAD

**Issue by lostmeow17** [Amulet-Team/Amulet-Map-Editor#462]
so i deleted 80% of chunks in the overworld and the end in bedrock world that worth 1.94GB and its dident really reduce the file size it went from 1.94GB to 1.91GB and i need to transfet it to java edition but it says the file is too big...
why's that? i heared it reduces alot of the size by deleting chunks... (i saved) 
thanks for the support.

**Comment by gentlegiantJGC** [comment]
Can you explain the steps that you did

**Comment by lostmeow17** [comment]
sure]

**Comment by lostmeow17** [comment]
ok so i selected a world it worked and i opened the overworld then i tapped on "chunks" below and mark my base and then tapped on "delet unmarked chunks" or something like that i waited for it to finish then i pressed "save" and the same thing in the end....

**Comment by lostmeow17** [comment]
> Can you explain the steps that you did

oh i forgot to reply sorry

**Comment by lostmeow17** [comment]
> Can you explain the steps that you did

are u here?

**Comment by gentlegiantJGC** [comment]
Have you tried closing the world in Amulet?
Database compaction only happens when you close the world

**Comment by lostmeow17** [comment]
> Have you tried closing the world in Amulet? Database compaction only happens when you close the world

ohhhh righttttt i will try
ty sm

**Comment by lostmeow17** [comment]
> Have you tried closing the world in Amulet? Database compaction only happens when you close the world

no change :<

**Comment by lostmeow17** [comment]
thare is a way to reduce the world size without deleting things like me base so i can transfer it into java edition on chunker.app
???

**Comment by gentlegiantJGC** [comment]
Double check that you are inspecting the same world that you are editing.
If you edit the world in Amulet and save the folder size will change in some way.
If it doesn't then you are editing the wrong world.

**Comment by gentlegiantJGC** [comment]
It had not occurred to me that some of this data could be in other dimensions.
The delete unselected chunks feature only works on the currently active dimension.
Have you repeated this for all dimensions?

Using ctrl+a will put a box around all the chunks that are generated in the level to give you an idea where the chunks are in that level.

**Comment by gentlegiantJGC** [comment]
I have just tested this with a world a user sent in.
I deleted most of the chunks and saved and closed.
After closing the size of the db directory reduced from about 300MB to 1.7MB
