### ISSUE TITLE
[Bug] struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by KadTheHunter** [Amulet-Team/Amulet-Map-Editor#464]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
Not that I can see, but I'm no code genius so maybe I missed it.

**Describe the bug**
When loading in a bedrock world to view in 3D or to Convert to Java, a lot (more than half I estimate) of the chunks don't load, and the console has this error, with different coordinates for each chunk of course:
```
2021-11-15 13:00:04,312 - amulet_core - ERROR - Error loading chunk -6 13 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 481, in _load_chunk
  File "amulet\level\formats\leveldb_world\format.py", line 239, in _decode
  File "amulet\level\interfaces\chunk\leveldb\base_leveldb_interface.py", line 151, in decode
struct.error: unpack requires a buffer of 4 bytes
```

**To Reproduce**
1. Open Amulet
2. Select a Bedrock world
3. Open in 3D or Convert and join the world in Java
4. See the error in console + the red chunks/empty chunks.

**Expected behavior**
Expected Amulet to View or Convert my entire world, not just fragments of it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version	10.0.19042 Build 19042 (latest, basically)

**Additional context**
I can provide the world if needed. 
It loads fine in Bedrock for me, and I've flown around and viewed all the chunks that Amulet has an issue loading.

**Comment by gentlegiantJGC** [comment]
Yes please send the world.
Does the issue happen in other worlds?

**Comment by KadTheHunter** [comment]
https://www.mediafire.com/file/iqcqpzwyv8jwdsk/LevelDB-city.mcworld/file
https://www.mediafire.com/file/sbwqvpcw9mqsjrj/LevelDB-freebuild.mcworld/file

The issue happens with both these.

I also just created a brand new world on Bedrock and attempted to load it into Amulet, but it has issues that match #454

**Comment by KadTheHunter** [comment]
![image](https://user-images.githubusercontent.com/47439649/142240467-e5ea0908-5808-4bb4-964d-4259ff55e4ac.png)
![image](https://user-images.githubusercontent.com/47439649/142240601-eb7f37d4-f2dd-4fb7-85c0-185a821a2d5c.png)
This is Amulet failing to load the chunks in the freebuild world, and then what it looks like in Bedrock for comparison

**Comment by gentlegiantJGC** [comment]
And you don't have the experimental 1.18 features enabled?

**Comment by KadTheHunter** [comment]
No, none of the 3 worlds above 1.18 features enabled (or any experiments enabled).

**Comment by KadTheHunter** [comment]
Making a new world with no experiments enabled works fine in Amulet. 
I realized the new world I made a few minutes ago had it on.
To clarify: 
- The 3 worlds I linked do not have experiments enabled, and only partially load in Amulet
- A new world with experiments enabled won't load at all in Amulet (#454)
- A new world with*out* experiments enabled loads fine in Amulet.

**Comment by kabluinc** [comment]
I've been experiencing this error with a 1.12 bedrock world too. Both when trying to open in 3d view and converting to java too. Please try and fix this :(

World download: https://1drv.ms/u/s!Aq30uaNRzcxLgTdGhL8OtVIONILC?e=kgZqud

**Comment by gentlegiantJGC** [comment]
This should be fixed in the next release.
