### ISSUE TITLE
Your Discord invite has expired

### ISSUE THREAD

**Issue by erich666** [Amulet-Team/Amulet-Map-Editor#468]
On your page https://www.amuletmc.com/ is a link to Discord at the top. When I click it, I get:

![image](https://user-images.githubusercontent.com/803995/143615854-6fec343a-5a60-43ba-bf28-4e0c0135cc0d.png)

I suspect you used the default Discord invite link length of 7 days. You want to do this instead:

In Discord at your server you'll see this in the upper left:

![image](https://user-images.githubusercontent.com/803995/143615934-2a3667cf-e7c6-4ece-ab7e-7170d770ef9b.png)

Click it. Now, at the very bottom of the dialog that comes up, click the way-too-tiny "Edit invite link":

![image](https://user-images.githubusercontent.com/803995/143616005-504934f9-05b5-4eff-8acd-0f3d09d39b14.png)

Set the invite to never expire:

![image](https://user-images.githubusercontent.com/803995/143616041-d4bfe679-3557-4319-9a53-16b9b68ee287.png)

And then, of course, put the link generated on your homepage.

I wanted to visit your Discord page and say "thanks," if nothing else. I'm the author of Mineways and I'm thrilled to see that Amulet exists! It looks like a nice, free way to convert from Bedrock to Java, which is what Mineways reads. My instructions for this are [here ](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#mcpe)- if there's a better way, let me know. <-- And that's what I wanted to post on Discord.

**Comment by gentlegiantJGC** [comment]
Thanks. I edited this recently so I probably broke it then.
I have just fixed this

**Comment by erich666** [comment]
Aha, looking on https://www.amuletmc.com/readme, the Discord link there worked for me.
