### ISSUE TITLE
Error installing from source in linux KDE

### ISSUE THREAD

**Issue by jurassicjordan** [Amulet-Team/Amulet-Map-Editor#469]
**Describe the bug**
Attempting to install from source utilizing the command "python -m pip install amulet-map-editor==0.8.15 --upgrade" results in errors during wheel build

**To Reproduce**
1. paste "python -m pip install amulet-map-editor==0.8.15 --upgrade" from website install page
2. hit enter
3. python proceeds normally through dependency download and installation
4. errors arise during wheel build process
5. Fails to build wxPython
6. Fails to build wxWidgets
7.  Command errored out with exit status 1

**Expected behavior**
for the program to install and be executable via "python -m amulet_map_editor"

**Screenshots**
Command output from terminal
https://pastebin.com/QG7YTjBX

**Desktop (please complete the following information):**
 - Linux Pop!_OS 21.04 
 - KDE plasma version 5.21.4
 - KDE framework 5.80.0
 - Qt 5.15.2
 - Kernal 5.13.0-7620-generic

**Additional context**
running in a virtual environment in Anaconda did not change outcome
running using python3 did not change outcome

**Comment by OwenKelly05** [comment]
I have the same error. I'm running it on macOS 12.0.1 with M1 Pro. I know there is a fix for the "libleveldb.dylib" not working on M1 but I couldn't even get to that step. Same result while installing beta or full release.

**Comment by OwenKelly05** [comment]
I've found a fix. The newest python version doesn't work. Use version 3.9.

**Comment by gentlegiantJGC** [comment]
Looks like an issue with your os and wxpython.
I am going to close this because it isn't an issue with Amulet and it looks like you have solved it.
