### ISSUE TITLE
Block class _gen_blockstate potentialy inconsistent

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#47]
https://github.com/Amulet-Team/Amulet-Map-Editor/blob/impl-entities/src/api/block.py#L157

This line may cause issues when two blocks are created with the same properties but with the properties in different orders.

{'note': '1', 'instrument': 'harp', 'powered': 'false'}
{'instrument': 'harp', 'note': '1', 'powered': 'false'}

These two property dictionaries are the same but are in different orders. In python equating them with == returns True however doing this list comprehension will keep the order they were defined in the dictionary. When the hash of this string is subsequently calculated they will be seen as different objects. Sorting them alphabetically should solve the issue

'instrument=harp,note=1,powered=false'
'note=1,instrument=harp,powered=false'

**Comment by Podshot** [comment]
From my testing, this issue stems from 2 different methods of creating a Block object:
1. If you create the Block from a blockstate string, we'll parse the string once a specific aspect of that string is requested (IE: `<block>.properties` or `<block>.base_name`). However, the `<block>.blockstate` will always keep that value of the string that was passed in, so we need to parse the string (or just the properties) to re-order the properties
2. If you create the Block from the `namespace`, `base_name`, `properties` keyword arguments, the properties dictionary will have to be sorted to resolve this.

I currently have a fix for 2, but I will work on a way to just parse the properties from the blockstate string
