### ISSUE TITLE
NixOS support?

### ISSUE THREAD

**Issue by jakobneufeld** [Amulet-Team/Amulet-Map-Editor#470]
**Has your feature request already been suggested? Please check if your suggested feature has already been suggested.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I went NixOS support

**Describe alternatives you've considered**

**Additional context**
I can write the nix derivation, I just need some help

**Comment by jakobneufeld** [comment]
I just want to be able to run this on NixOS.

**Comment by jayhawker6** [comment]
Have you not just tried WINE with the windows version?

**Comment by jayhawker6** [comment]
Otherwise I think this would probably be low on their priority list until the software reaches a more stable and fully developed point... It's not worth the time and effort to make a whole separate version if by the time you are done, even the main branch is light years ahead of you and your version still has issues being fixed.

**Comment by jakobneufeld** [comment]
Ah, I did not know the software is unstable. Anyway I will try wine version.

**Comment by jakobneufeld** [comment]
error: builder for '/nix/store/ml8nz6s46nfpl9i3917bkjsy5mw6vnkx-python3.8-wxpython-4.1.1.drv' failed with exit code 1;
       last 10 log lines:
       >     raise Errors.BuildError(self.producer.error)
       >   File "/build/wxPython-4.1.1/bin/.waf3-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Errors.py", line 26, in __init__
       >     WafError.__init__(self,self.format_error())
       >
       > Build failed
       >  -> task in '_core' failed with exit status 1:
       >  {task 140737325917344: cxx sip_corewxCollapsiblePane.cpp -> sip_corewxCollapsiblePane.cpp.3.o}
       > ['g++', '-fPIC', '-pthread', '-pthread', '-I/nix/store/pfsdv4yr03x1pwi1wjsqim8s2hi3k287-gtk+3-3.24.27-dev/include/gtk-3.0', '-I/nix/store/h7rgpbcmx1fxjqnkkq2fcfi3br47ifh5-atk-2.36.0-dev/include/atk-1.0', '-I/nix/store/nzi9p088wi0cdvv4dx2xjzpr3hlsc27d-glib-2.68.1-dev/include', '-I/nix/store/nzi9p088wi0cdvv4dx2xjzpr3hlsc27d-glib-2.68.1-dev/include/glib-2.0', '-I/nix/store/3bk62syy5yxkfxwvfrzildgwrd7xbzyx-glib-2.68.1/lib/glib-2.0/include', '-I/nix/store/r7qsj7wllf1smim2rdsvay1npxssnp1x-cairo-1.16.0-dev/include/cairo', '-I/nix/store/s3lxfwy99i23nrih6b6f9lax5v54a0k4-freetype-2.10.4-dev/include/freetype2', '-I/nix/store/s3lxfwy99i23nrih6b6f9lax5v54a0k4-freetype-2.10.4-dev/include', '-I/nix/store/ak5ivql43zn9d57cwdfssh06i9ra1ns8-gdk-pixbuf-2.42.6-dev/include/gdk-pixbuf-2.0', '-I/nix/store/mzpyyln79b07hfhjcmvbxf7gdm91nb3n-pango-1.48.4-dev/include/pango-1.0', '-I/nix/store/61d8p42sjqnzd0kvd82vm1h7rf5z70v6-harfbuzz-2.8.0-dev/include/harfbuzz', '-UNDEBUG', '-DSIP_MODULE_NAME=wx.siplib', '-DSIP_MODULE_BASENAME=siplib', '-g', '-g', '-fwrapv', '-O3', '-I/nix/store/8859v8a6xb2sfflnh4473mr25qldp4fr-wxwidgets-3.1.4/lib/wx/include/gtk3-unicode-3.1', '-I/nix/store/8859v8a6xb2sfflnh4473mr25qldp4fr-wxwidgets-3.1.4/include/wx-3.1', '-Isip/siplib', '-I../../../../sip/siplib', '-Iwx/include', '-I../../../../wx/include', '-Isrc', '-I../../../../src', '-I/nix/store/hq6mrm0pc6xn6j8y6lm4qcgg9rwmqd8q-python3-3.8.9/include/python3.8', '-DPYTHONDIR="/usr/local/lib/python3.8/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python3.8/site-packages"', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_WX=1', '-DHAVE_WXADV=1', '-DHAVE_WXSTC=1', '-DHAVE_WXHTML=1', '-DHAVE_WXGL=1', '-DHAVE_WXWEBVIEW=1', '-DHAVE_WXXML=1', '-DHAVE_WXXRC=1', '-DHAVE_WXRICHTEXT=1', '-DHAVE_WXMEDIA=1', '-DHAVE_WXRIBBON=1', '-DHAVE_WXPROPGRID=1', '-DHAVE_WXAUI=1', '-D_FILE_OFFSET_BITS=64', '-DWXUSINGDLL', '-D__WXGTK__', '../../../../sip/cpp/sip_corewxCollapsiblePane.cpp', '-c', '-o/build/wxPython-4.1.1/build/waf/3.8/gtk3/sip/cpp/sip_corewxCollapsiblePane.cpp.3.o']

**Comment by jakobneufeld** [comment]
I get this error while building

**Comment by jayhawker6** [comment]
¯\_(ツ)_/¯ only other solution I can think of atm is to boot up that good ol' windows 10 KVM

**Comment by jakobneufeld** [comment]
I fixed it! thanks for the bad joke
