### ISSUE TITLE
Large edited areas don't save

### ISSUE THREAD

**Issue by Yekul10** [Amulet-Team/Amulet-Map-Editor#471]
My main world that I use, used to have mods installed which caused (after uninstalling them and vowing never to do such a thing to my world again) the bedrock at the bottom of the world to be missing or replaced with netherrack. I wanted to fill it in with bedrock so the new caves would generate underneath. I selected all loaded chunks and lowered each selection to be from 0-1, then I used the fill operation. I could see it had worked in Amulet but after saving and opening the world, nothing had changed. The netherrack was still there as well. I tried this twice and waited for **three hours _each_** waiting for it to finish saving. The same results. Opening it back up in Amulet shows the bedrock missing as well.

1. Edit a very large area
2. Save the world until finished
3. Open world
4. Nothing changed

Possible causes may be that a small portion of the world was briefly loaded in 1.18 which caused a little of the map to be red, but I assume it should have just ignored that bit as it couldn't read it.
If anyone has another solution on how to put the bedrock in place (or to force the new caves to generate,) I would be very happy to hear it.

 - OS: Windows
 - Version 0.8.15

**Comment by gentlegiantJGC** [comment]
If the world is loaded in 1.18 amulet will save out the chunks in 1.18 format but we don't support that format yet so it probably just spat out a load of errors in the console and didn't save anything

**Comment by Yekul10** [comment]
Is there a way I can still make it work?

**Comment by gentlegiantJGC** [comment]
You will need to wait until we get 1.18 support

**Comment by Tsoccerguy3** [comment]
I think a lot of people want to repair the bedrock layer in 1.17.x and below maps  before updating to 1.18. On older maps players have destroyed the bedrock in large areas , sometime replacing the bedrock with any random blocks. On conversion to 1.18 this map will have holes down to the new bedrock layer. If World Edit was used in areas , their could be entire regions that don't generate.

I tested a map 16K x 16K , selecting just the bedrock layer on the entire map . Amulet will not complete or save the map edit . This should be a quick and fast edit , but Amulet after 3 hours crashed and did not save anything .
