### ISSUE TITLE
V0.8.16a4 No blocks rendered below y zero

### ISSUE THREAD

**Issue by PREMIEREHELL** [Amulet-Team/Amulet-Map-Editor#473]
**Describe the bug**
No blocks rendered below Y zero
Cant add or edit Blocks below Y zero

**To Reproduce**
https://cdn.discordapp.com/attachments/858645423928508416/916394120266792980/AchT.mcworld
Open in V0.8.16a4 and try

**Comment by wpeterson-dev** [comment]
I as well have the same issue with the same version
![same thing](https://user-images.githubusercontent.com/42956431/144697213-a918d63e-1e40-45e8-b2e8-dd2fc937419d.jpg)
.

**Comment by mikezimm** [comment]
Same bug, different scenario for me:

I converted a Java world and in both chunks that were last loaded in 1.17 as well as chunks loaded and blended in 1.18 Java, there is void under y=0

![image](https://user-images.githubusercontent.com/49648086/144767994-465b5199-7df8-4976-8f73-fb5294b9cf6e.png)

**Comment by gentlegiantJGC** [comment]
This is a slightly different bug. Can you open a new report with all the details

**Comment by gentlegiantJGC** [comment]
I think this bug should have been fixed in the last alpha release. Let me know if it is still an issue.
