### ISSUE TITLE
Changing Biomes in Bedrock 1.18 Crashed Game

### ISSUE THREAD

**Issue by dlawton18** [Amulet-Team/Amulet-Map-Editor#475]
After changing the biome of a chunk in the 1.18 bedrock alpha, the game crashes immediately upon trying to load that chunk. 

**To Reproduce**
1. Open any 1.18 map in amulet. 
2. Select a chunk (s) and change the biome. 
3. Save and exit. 
4. Open the map in Minecraft. 
5. Try to load the edited chunks. 

**Expected behavior**
The chunk to load normally with the new biome rules applied. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [1.18.0]

**Additional context**
I can add the map I ran into the problem with if you're unable to recreate it.

**Comment by pipesqueak** [comment]
I’m experiencing this bug as well.

**Comment by gentlegiantJGC** [comment]
Which version of amulet are you using?
Can you send a copy of the world

**Comment by pipesqueak** [comment]
I’m using version 0.8.17a0, and the world file should be attached (: 

a note: my world is a bit old (made around 1.14) so the chunks near spawn that I wanna change are pre-1.18. I experimented by pruning the chunks and THEN changing the biome and the world opened, So I suspect it might have to do with trying to change the biome of pre-1.18 terrain, but that’s just a guess. 

Hope I helped and thanks for the response!
[KLKtYd+jAAA=.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7659133/KLKtYd%2BjAAA.zip)

**Comment by dlawton18** [comment]
Ah, this makes sense, the biomes I attempted to change were in pre 1.18 chunks as well. I can upload the map I ran into the issue on when I get a chance as well.

**Comment by pipesqueak** [comment]
[k2KyYfvhAQA=.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7688522/k2KyYfvhAQA.zip)

0.8.18a1 is still crashing upon attempt to change the biome. Here is a world file if it helps (:

**Comment by dlawton18** [comment]
I have actually ended up deleting the map I ran into the initial issue with. The issue was with the first alpha, I attempted to recreate the the issue using the second alpha last night and was unable to, it appeared to work as intended.

**Comment by pipesqueak** [comment]
That’s weird…. I managed to get it to work a single time, but if the area I was trying to edit was too large it wouldn’t open. I’ll have to try going chunk by chunk, but for now it’s still not working consistently for me. It’s weird

**Comment by gentlegiantJGC** [comment]
Let me know if this is still an issue in 0.8.17a2

**Comment by pipesqueak** [comment]
> Let me know if this is still an issue in 0.8.17a2

Just made the desired changes and it worked perfectly! Thank you so much for everything!
