### ISSUE TITLE
Minecraft Bedrock 1.18 error

### ISSUE THREAD

**Issue by AWESOME4504** [Amulet-Team/Amulet-Map-Editor#477]
I tried to reset chunks on my bedrock world and this error occurred
![error](https://user-images.githubusercontent.com/95524885/144718844-354c7720-6322-4859-bf09-f24513a0f186.png)

**Comment by gentlegiantJGC** [comment]
Can you link a world please

**Comment by gentlegiantJGC** [comment]
https://discord.com/channels/324647192583340043/916714414873391124/916749127008788480

**Comment by AWESOME4504** [comment]
Here's the link for the world
https://drive.google.com/drive/folders/18CjQFVmfYL-dyzRt8WShJ4cWjiUoC8fK?usp=sharing

**Comment by gentlegiantJGC** [comment]
I think the latest alpha release should fix this issue.
