### ISSUE TITLE
3D Editor does not load at all

### ISSUE THREAD

**Issue by TanksAlotYT** [Amulet-Team/Amulet-Map-Editor#479]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.** No

**Describe the bug**
3D Editor doesn't load when I open my world in Amulet (scroll down and click the lick under **Screenshots**

**To Reproduce**

**Expected behavior**

**Screenshots**

I recorded what happened - https://imgur.com/xEhY8Sl 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, linux]
 - Version [e.g. 0.6.11]
 I use Windows and the latest version of windows

**Additional context**

**Comment by gentlegiantJGC** [comment]
The version of Amulet you are using does not support 1.18
