### ISSUE TITLE
Re-add selection box UI

### ISSUE THREAD

**Issue by Xaxicza** [Amulet-Team/Amulet-Map-Editor#48]
I'm testing the release v0.6.7.0 and it looks like the bar on the left which used to show selection coordinates (x1,y1,z1,x2,y2,z2) is gone. Back in 0.6.5.1 it was working fine and it was a great way to adjust the size of a selection. Is there some other way to do it? If not, is there a way to bring it back?

**Comment by gentlegiantJGC** [comment]
You can now click on the box itself and move to resize

**Comment by Xaxicza** [comment]
I noticed that and it's great, but it has limitations. For example if the corner is underground / inside the terrain I can't reach it at all. Or if I want to move a corner along a specific axis, say one or two blocks, now I have to take time to position myself correctly. It was easier to increase the value by just clicking next to it. What I used to do very often was: drawing a rough selection and adjusting the corners with several clicks and it was done. Also, there are times when I know the exact coordinates of my intended selection, in which case typing them is way faster than flying around and positioning corners.

Resizing by hand? Awesome feature. But why not keep both? More ways to skin a cat.

Keep up the good job. I really appreciate it.

**Comment by gentlegiantJGC** [comment]
I intend to reintroduce something like the UI that was there before but I need to do some other UI work before that

**Comment by Xaxicza** [comment]
That's great. I'm looking forward to it.

**Comment by gentlegiantJGC** [comment]
This is reimplemented in the release that is coming out shortly
