### ISSUE TITLE
 Is there a test version yet?

### ISSUE THREAD

**Issue by llronaldoll** [Amulet-Team/Amulet-Map-Editor#48]
I'm using 1.14 and would like to test this project

**Comment by TrazLander** [comment]
Me too man.

**Comment by TrazLander** [comment]
Join the discord and ask questions in #amulet-discussion

**Comment by llronaldoll** [comment]
What amulet discord?

**Comment by TrazLander** [comment]
https://discord.gg/BTm6jnf

**Comment by demaree** [comment]
I'm also interested in this. I tried grabbing your GitHub files to help
work on this and couldn't get your container to run. Is there some special
library I need to use?

**Comment by Podshot** [comment]
@demaree Were you getting an error?

**Comment by demaree** [comment]
I'd have to look at it again when I get back to my computer. Do I have to
spin the program up in a docker container? I tried to run the make.bat and
it didn't do anything (if I remember correctly). Is the makefile written in
Golang? Do I have to build it?

**Comment by Podshot** [comment]
@demaree The `make.bat` is only for building our documentation. You don't need a docker container unless you want to use one. You need to set up a python 3.7 virtual environment, install the modules from `requirements.txt` and then run the `main.py` file from the command-line. The program can only load and make a few changes to the world, but can't save anything.
