### ISSUE TITLE
Fractured Y level for 1.18 Worlds

### ISSUE THREAD

**Issue by theKIEgit** [Amulet-Team/Amulet-Map-Editor#481]
**Describe the bug**
When loading 1.18 worlds the y level is fractured. (Version 0.8.17a0)

**To Reproduce**
1. Update 1.17 world into 1.18
2. Explore/ build in some chunks
3. Load amulet

**Expected behavior**
World displays level instead of fractured.

Note:
Updating the chunk by placing blocks in them will correct the chunk in amulet.

**Screenshots**
![image](https://user-images.githubusercontent.com/77963947/144762135-fa92b9ad-90d0-4e0d-afab-184234e9614f.png)

**Comment by Black-Rock-Shooter** [comment]
I have the same problem. However, I can seem to get it to load properly if I go in-game and manually cause at least one block update in the lower chunks. This usually causes the chunk to correct itself to the higher level. A temporary solution, but it seems to work at least for me.

**Comment by theKIEgit** [comment]
> I have the same problem. However, I can seem to get it to load properly if I go in-game and manually cause at least one block update in the lower chunks. This usually causes the chunk to correct itself to the higher level. A temporary solution, but it seems to work at least for me.

Yea updating the chunk by either placing blocks or walking into them seems to correct it, I’ll put a note in the post.

**Comment by Black-Rock-Shooter** [comment]
Okay so after deciding to try manually raising the chunks back up to the proper y level in Amulet, I saved and exited. After doing this, the world crashes minecraft upon trying to load it. The only idea I had was that I had pasted air blocks above y level 320 accidentally, but after selecting everything above my world back in Amulet and deleting it, it still crashes upon reaching the "Building Terrain" text in minecraft. Any ideas, or is updating the chunks in game still best for now you rhink?

**Comment by theKIEgit** [comment]
From what I've tested editing old chunks in anyway in amulet will cause the game to crash when you load the edited chunks, so it seems manually updating them is the best solution for now.

**Comment by theKIEgit** [comment]
> 

From what I've tested editing old chunks in anyway in amulet will cause the game to crash when you load the edited chunks, so it seems manually updating them is the best solution for now.

**Comment by gentlegiantJGC** [comment]
Let me know if this is still an issue in 0.8.17a1
