### ISSUE TITLE
5 biome warnings - converting from Java 1.17 to Bedrock 1.18 

### ISSUE THREAD

**Issue by mikezimm** [Amulet-Team/Amulet-Map-Editor#482]
Thanks @gentlegiantJGC,
I did manage to convert my world using 8.16a4 without to many errors this time.

**Describe the bug**

I noticed the following warnings which I summed up below.  Since some of my java chunks were loaded in Java 1.18 and some were not, I think it just needs a few "old" vs "new" biomes added to a table somewhere.

If you can point me to what file has that cross reference, I'd be happy to contribute some work and figure out the missing references I come across.

**To Reproduce**
1.  Partially Converted Java 1.17 world to Java 1.18 by loading chunks in the game.
2. Converted Java world to Bedrock 1.18 with Amulet v0.8.16a4

**Expected behavior**
Java 1.18 chunks would get mapped to the corrosponding Bedrock 1.18 chunks

**Screenshots**
These are the errors I did find... not to many :)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/KMZIM_~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/KMZIM_~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

1.18   Java Biome | 1.18 Bedrock Biome
-- | --
minecraft:old_growth_birch_forest | birch_forest?
minecraft:sparse_jungle | sparse_jungle?
minecraft:stony_shore | stony_shore?
minecraft:windswept_forest | windswept_forest
minecraft:windswept_savanna | windswept_savanna
minecraft:wooded_badlands | wooded_badlands
  |  
  |  
Row   Labels | Count of   Message
Error processing biome   minecraft:old_growth_birch_forest. Setting to plains. | 2
Error processing biome   minecraft:sparse_jungle. Setting to plains. | 220
Error processing biome   minecraft:stony_shore. Setting to plains. | 28
Error processing biome   minecraft:windswept_forest. Setting to plains. | 34
Error processing biome   minecraft:windswept_savanna. Setting to plains. | 93
Error processing biome   minecraft:wooded_badlands. Setting to plains. | 619
Grand Total | 996

</body>

</html>

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/49648086/144729530-41f242f6-154e-4956-864b-525710ceb158.png)

**Comment by gentlegiantJGC** [comment]
Thanks. I need to set up a system to automatically find changes in biomes like I have with blocks.

**Comment by DaveAsh1969** [comment]
I got a snowy_plains to plains warning in my conversion from Java to Bedrock.

**Comment by gentlegiantJGC** [comment]
Thanks for reporting this. In 1.18 they removed a number of old biomes and merged them into less biomes.
This should be fixed in the next alpha release.

**Comment by gentlegiantJGC** [comment]
Let me know if this is still an issue in 0.8.17a1

**Comment by mikezimm** [comment]
@gentlegiantJGC ,
When testing issue #490 in 0.8.17a1, I did get similar errors.  I don't see the actual biome names but this is what the error log said:

Got these errors:
2021-12-10 16:26:26,705 - pymctranslate - INFO - PyMCTranslate Version 160
2021-12-10 16:27:26,539 - pymctranslate - WARNING - Could not find registered value for biome 17. Reverting to plains
2021-12-10 16:27:31,861 - pymctranslate - WARNING - Could not find registered value for biome 164. Reverting to plains
2021-12-10 16:27:57,723 - pymctranslate - WARNING - Could not find registered value for biome 22. Reverting to plains
2021-12-10 16:28:02,913 - pymctranslate - WARNING - Could not find registered value for biome 162. Reverting to plains
2021-12-10 16:28:54,151 - pymctranslate - WARNING - Could not find registered value for biome 18. Reverting to plains

**Comment by gentlegiantJGC** [comment]
Does this issue come from a Bedrock or Java world?
It might be best opening a new issue since this report is about Java 1.18 biomes and that is not

**Comment by mikezimm** [comment]
@gentlegiantJGC 
It was originally a Java 1.17.1 world converting to Bedrock.

Also, to confirm it is not just my pruned world files,
I created a brand new 1.17.1 world.
Set render distance to just 2 chunks.
Went into unmodified new 1.17.1 world to load the game.
Converted that world to a brand new Bedrock world.

I don't have all the same biomes since this was a non-modified world.

I got these 2 biome errors:
2021-12-10 16:38:43,658 - pymctranslate - INFO - PyMCTranslate Version 160
2021-12-10 16:40:10,659 - pymctranslate - WARNING - Could not find registered value for biome 28. Reverting to plains
2021-12-10 16:40:12,101 - pymctranslate - WARNING - Could not find registered value for biome 18. Reverting to plains

**Comment by mikezimm** [comment]
@gentlegiantJGC ,
In this latest test, it was straight Java 1.17.1 world, no Java 1.18.
So it seems to be consistent error of unknown biomes.   
The difference between Java 1.17 and Java 1.18 source world is in
Java 1.18 source world, I get the word of the biome.
Java 1.17 source world, I get a number for the biome.

Do you think it needs 2 issues still?

**Comment by gentlegiantJGC** [comment]
I haven't checked all the numbers but all of the biome IDs you sent that I have looked up are invalid biomes.
https://minecraft.fandom.com/wiki/Biome/ID

**Comment by mikezimm** [comment]
@gentlegiantJGC , this is a long shot but in your array or lookup of Biomes in the code, which ones are at index 18 and 28?

**Comment by gentlegiantJGC** [comment]
I sent the list in my last message
