### ISSUE TITLE
Upon opening the 3D editor, no chunks load and the program crashes

### ISSUE THREAD

**Issue by randomusrn4me** [Amulet-Team/Amulet-Map-Editor#484]
I open a world that has been generated by MC 1.18 (not just one, but all worlds that I try to load), I click on 3D Editor, and it does its loading thing. Then the interface opens, for a second it freezes (the background is blue, no chuncks are loaded), I can't click on anything, and after that it just closes. It managed to open my world once though, 1 out of 10.

**Comment by randomusrn4me** [comment]
*Java edition

**Comment by gentlegiantJGC** [comment]
Any errors in the console?

**Comment by randomusrn4me** [comment]
![image](https://user-images.githubusercontent.com/62748345/144879279-446d8f47-74df-442b-970c-2307dfae18a2.png)
It doesn't display anything else before exiting.

**Comment by gentlegiantJGC** [comment]
Can you try running it from the command line. There might be an error that gets printed but you don't get time to see it.
This might also get saved in a log file

**Comment by randomusrn4me** [comment]
Same output.

**Comment by randomusrn4me** [comment]
In the new alpha I wasn't able to reproduce the issue yet.

**Comment by randomusrn4me** [comment]
In the new alpha I wasn't able to reproduce the issue yet.
