### ISSUE TITLE
Recurring Error when converting from Java to Bedrock

### ISSUE THREAD

**Issue by DaveAsh1969** [Amulet-Team/Amulet-Map-Editor#486]
Just wanted to give you a recurring error I found when converting from Java to Bedrock since 1.18.

Thank you for this software.

![image](https://user-images.githubusercontent.com/95668570/144962782-df5f89da-fe8d-4457-83b2-936c1e56c5d0.png)

**Comment by gentlegiantJGC** [comment]
The version of Amulet you are using does not support 1.18. You need the alpha release
