### ISSUE TITLE
Making changes to a chunk removes contents from cauldron

### ISSUE THREAD

**Issue by Braboware** [Amulet-Team/Amulet-Map-Editor#487]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
This has not been reported

**Describe the bug**
Any chunk modifying operation (additions & deletions) removes cauldron contents for all cauldrons within that chunk. Surrounding chunks are unaffected.

**To Reproduce**
1. Open world with filled cauldron
2. Make chunk modifying operation to chunk containing cauldron (copy & paste, delete blocks, clone, fill, set biome, waterlog)
3. Save & close world
4. Load world in-game
5. See that cauldrons are empty

**Expected behavior**
The cauldron should remain filled with whatever it was filled with.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.8.17a0-Windows-x64

**Additional context**
Copying and pasting the filled cauldron from one chunk to another leaves the source cauldron filled, but the destination cauldron in the other chunk is empty. 

Standalone water, lava, and powdered snow blocks are unaffected, just the cauldrons that contain those.

**Comment by gentlegiantJGC** [comment]
This should be fixed in the next release.
