### ISSUE TITLE
Alpha Release Java to Bedrock

### ISSUE THREAD

**Issue by DaveAsh1969** [Amulet-Team/Amulet-Map-Editor#489]
I am using the v0.8.17a0 release.  I get this error repeated when converting now from Java to Bedrock.  Thank you guys for all the work.

![image](https://user-images.githubusercontent.com/95668570/145097466-11cb62ef-7578-4745-9af1-92cacd27452d.png)

**Comment by mikezimm** [comment]
This is the same as #482 and could be merged.
