### ISSUE TITLE
Editing pre 1.18 chunks will cause crash in game

### ISSUE THREAD

**Issue by theKIEgit** [Amulet-Team/Amulet-Map-Editor#491]
**Describe the bug**
If you edit a pre 1.18 chunk Minecraft will crash when it's loaded

**To Reproduce**
1. Load a pre 1.18 world into amulet
2. edit anything in pre 1.18 chunks
3. save then load the world in minecraft

**Expected behavior**
Edits appear in game, no crash happens.
**Actual behavior**
Game will crash when the edited chunks are loaded.

**Additional context**
Used amulet v0.8.17a1
Used Bedrock edition

On the world given most of the void chunks are not updated to 1.18 you can use them to recreate the issue.
You can visualize it easier using v0.8.17.a0 as non updated chunks appear lower

[amulet pre 1.18 chunk crash.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7685742/amulet.pre.1.18.chunk.crash.zip)
r

**Comment by gentlegiantJGC** [comment]
Can you provide some more details.
Are you referring to Bedrock or Java?
Can you link a world that crashes when edited but loads correctly before

**Comment by theKIEgit** [comment]
> Can you provide some more details. Are you referring to Bedrock or Java? Can you link a world that crashes when edited but loads correctly before

I have updated my report, sorry for the missing detail.

**Comment by gentlegiantJGC** [comment]
Testing:
Opening the world linked directly in 1.18 opens without issue
Filling bedrock blocks above the world and saving does cause the game to crash when the world is opened.
Time to do some debugging.

**Comment by gentlegiantJGC** [comment]
More testing:
It is absolutely an issue with biomes.
I have found a chunk that causes a crash and deleted all the other chunks.
I then messed with the database to work out what was causing the crash.
After deleting the biome data it loads the chunk correctly.
Now to work out what it doesn't like about it.

**Comment by gentlegiantJGC** [comment]
It may be that all sub-chunks that define blocks also need to define biomes.
Duplicating the data from a single sub-chunk for each sub-chunk seems to allow it to load correctly.

**Comment by gentlegiantJGC** [comment]
I think the issue is that if a biome array is defined all arrays below that one will also need to be defined.
This is fine for 1.18 where the arrays are pre-generated by the game but for older worlds Amulet does not generate them.
I will need to write some code when saving to populate them.

**Comment by gentlegiantJGC** [comment]
Also at least one biome array needs to be defined.

**Comment by gentlegiantJGC** [comment]
I have just added in some code to test that and it works

**Comment by gentlegiantJGC** [comment]
Let me know if this is still an issue in 0.8.17a2
