### ISSUE TITLE
Resource packs not working with modded textures

### ISSUE THREAD

**Issue by ADON15c** [Amulet-Team/Amulet-Map-Editor#495]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
Modded textures still display as missing even while a resource pack is loaded

**To Reproduce**
1. Use a resource pack with modded textures
2. Boot up a world with modded blocks
3. Vanilla textures in the minecraft namespace will show, but modded textures will not work

**Expected behavior**
The modded textures will not display

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.8.15

**Additional context**
This was done with a create above and beyond 1.1 world with a resource pack that had a namespace for biomes o plenty with all the textures in it. I tested the resource pack on minecraft itself and it did work. Here is the pack below
[above_and_beyond_1_16_5.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7700317/above_and_beyond_1_16_5.zip)

**Comment by PixusPanic** [comment]
I'm having a similar issue, albeit with 0.8.17b0 and on 1.18.1 with a handful of mods, namely Create and Pipez. I created a small test world to try and see if I can view some blocks and only the Mechanical Bearing seems to view fine; the pipes from Pipez also have their models, but not their textures.

![2022-01-05 (7)](https://user-images.githubusercontent.com/68515252/148330006-9907adf3-cb24-4d34-9961-1290c55d30da.png)

**Comment by gentlegiantJGC** [comment]
Looks like when I wrote this I assumed that the block namespace was the default namespace
