### ISSUE TITLE
OpenGL no valid context

### ISSUE THREAD

**Issue by frazor** [Amulet-Team/Amulet-Map-Editor#496]
**Describe the bug**
When world is loaded, and I click 3d render, the log starts spamming and when finished the screen looks exactly like the second screenshot in #448 .

I also have flickering, in that if I click the blue, sometimes the control buttons appear for a tenth of a second. If I resize window the controls appear whilst resizing. #127 ?
If I drag around with my left mouse button clicked, the controls appear and numbers change, all whilst everything keepsbeing  sky blue.
I can load multiple worlds and start multiple 3d editors. Log spams everytime I switch tab between worlds.

**To Reproduce**
1. Load 1.17.1 world
2. Click 3d editor tab
3. See stacktrace below:

**Expected behavior**
3D editor shows my loaded world.

**Screenshots**

![image](https://user-images.githubusercontent.com/471144/145912052-d2f119ed-af2e-44f1-a13d-297626bfe512.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.12
 - Python: conda create -n mcedit python=3.9 wxpython
 - Amuet: python -m pip install amulet-map-editor (0.8.15)

**Additional context**
Stacktrace, too many to count of these:

> Traceback (most recent call last):
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 358, in _on_draw
>     self.canvas.renderer.draw_level()
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/renderer.py", line 246, in draw_level
>     self.render_world.draw(self.canvas.camera.transformation_matrix)
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/level.py", line 273, in draw
>     self._chunk_manager.draw(camera_matrix, self.camera_location)
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/region.py", line 96, in draw
>     region.draw(camera_matrix, cam_cx, cam_cz)
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/region.py", line 282, in draw
>     chunk.draw(transformation_matrix)
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 153, in draw
>     self._setup()
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/chunk/chunk.py", line 56, in _setup
>     super()._setup()
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 92, in _setup
>     self._setup_opengl_attrs()
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 102, in _setup_opengl_attrs
>     glVertexAttribPointer(
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/OpenGL/latebind.py", line 63, in __call__
>     return self.wrapperFunction( self.baseFunction, *args, **named )
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
>     contextdata.setValue( key, array )
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/OpenGL/contextdata.py", line 58, in setValue
>     context = getContext( context )
>   File "/home/user/miniconda3/envs/mcedit/lib/python3.9/site-packages/OpenGL/contextdata.py", line 40, in getContext
>     raise error.Error(
> OpenGL.error.Error: Attempt to retrieve context when no valid context

Appreciate any help I can get!

**Comment by gentlegiantJGC** [comment]
This may be fixed by the changes in #678

**Comment by dridri** [comment]
same problem on current version 0.10.32 under Debian unstable

**Comment by gentlegiantJGC** [comment]
Please see #1056 
I made some opengl changes recently which may have broken some things.
