### ISSUE TITLE
Converting Realm (Imported World) to 1.18 Bedrock Edition

### ISSUE THREAD

**Issue by KommandoBrando** [Amulet-Team/Amulet-Map-Editor#497]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

As soon as I load into the program with the world file open, it immediately begins showing red chunks. No idea why. I'm not too sure if the program has been updated to convert Bedrock to 1.18, but am just trying to figure out what is going on. Thanks.

**Screenshots**
![image](https://user-images.githubusercontent.com/96115776/145981945-dd8e69a5-d9cf-41bf-84ee-cb5ec7da2907.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, linux]
 - Version [e.g. 0.6.11]
 - WINDOWS

**Additional context**

**Comment by gentlegiantJGC** [comment]
You need to use the alpha version for 1.18 support
