### ISSUE TITLE
Typing text in location box makes location -30000000

### ISSUE THREAD

**Issue by theKIEgit** [Amulet-Team/Amulet-Map-Editor#498]
**Describe the bug**
Typing text in location box makes number go to -30000000

**To Reproduce**
1. Copy a build
2. Click paste
3. Type any text (Not integer like 42gne2 ) into the location box
4. Click anywhere on the screen
5. See error

**Actual behavior**
Location goes to -30000000

**Expected behavior**
Location input does not allow text to be inputted.

**Screenshots**
![image](https://user-images.githubusercontent.com/77963947/145991987-fc09355b-1d45-4dc3-bfc0-663aa2348293.png)

**Additional context**
Scale and rotation do not allow text to be inputted.
Amulet V0.8.17.a2

**Comment by BusterBeachside** [comment]
This is super annoying as I do this all the time by accident trying to move around with WASD to double-check I am selecting the right area lol. Would be nice if typing non-numeric characters in there would just get ignored instead of this.

**Comment by cole00cole00** [comment]
I am glad i am not the only person who keeps ruining their own day by doing this :)
