### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by Buzzbugs** [Amulet-Team/Amulet-Map-Editor#5]
Hello,

I have been trying to convert my 1.15.2 world to 1.12 world. There were no errors in the log this time, and it was going smoothly. However over time, my other programs on my computer began to fail and close down. I checked task manager, and Amulet was using 99% of my computers memory (I have 16GB). I had to force-close the application because my computer screens were starting to blink black.

**Comment by Buzzbugs** [comment]
I should mention that my 1.15.2 world is around 3gb in size for reference

**Comment by gentlegiantJGC** [comment]
We need to deal with memory management. We currently hold everything in memory until saved back to disk

**Comment by Buzzbugs** [comment]
Okay, I am looking forward to when that is changed. I don't think this was good for my computer to try it again for now.

**Comment by gentlegiantJGC** [comment]
You should be fine to run it on a smaller input world

**Comment by Buzzbugs** [comment]
> 
> 
> You should be fine to run it on a smaller input world

I would like to, but it is my main (3gb world) that I need the conversion for.

**Comment by gentlegiantJGC** [comment]
Since it is Java a workaround is to duplicate the world and go into the region and DIMX/region directories and delete a bunch of the files to get the file size down to perhaps 200MB and then convert that. Repeat with leaving different files until you have converted all the files.
Hope that makes sense

**Comment by Buzzbugs** [comment]
> 
> 
> Since it is Java a workaround is to duplicate the world and go into the region and DIMX/region directories and delete a bunch of the files to get the file size down to perhaps 200MB and then convert that. Repeat with leaving different files until you have converted all the files.
> Hope that makes sense

would that mean I would lose areas of my world? My world is for an online server, and there are builds everywhere that I cannot afford to lose.

**Comment by gentlegiantJGC** [comment]
You would be trimming the world down for each conversion but if each time you trimmed it down to different region files and keep track which ones you have included you can convert the whole world.
The converter only modifies chunks in the destination world that exist in the source world

**Comment by Buzzbugs** [comment]
EUREKA! It worked! It took several hours because I could only do 130MB at a time, but it worked! Thank you!

**Comment by gentlegiantJGC** [comment]
Glad I could help. I might concentrate on memory management for the next release because it is a fairly core feature

**Comment by Buzzbugs** [comment]
> 
> 
> Glad I could help. I might concentrate on memory management for the next release because it is a fairly core feature

of course. Efficiency should be the core of any great program. Best of luck to you!

**Comment by gentlegiantJGC** [comment]
Copied from discord:
Here is my proposal on how we should go about handling memory management. Currently we do a lot of chunk loading but we don't have any way to unload the chunks which leads to a very high (even crippling) memory usage on larger worlds
https://docs.google.com/document/d/138w6vbBM53KU0yDTl5DA-jOMTpSl8w9sDOuKNsq-ZyA

**Comment by gentlegiantJGC** [comment]
@Buzzbugs Please can you try this version out and tell me how it goes. I think there may still be some memory issues but I have added some code to unload chunks where possible.
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/v0.3

**Comment by gentlegiantJGC** [comment]
I have found some more issues with Chunk not getting unloaded which I have fixed since that release. They will be in the next one.

**Comment by Buzzbugs** [comment]
> 
> 
> I have found some more issues with Chunk not getting unloaded which I have fixed since that release. They will be in the next one.

roger that. I will wait for this update.

**Comment by gentlegiantJGC** [comment]
I think I have fixed the issues in the recent versions. Please can you have a play around again and let me know if it works better.

**Comment by gentlegiantJGC** [comment]
Yeh the lighting issue will be further down the line
