### ISSUE TITLE
Chunks loading problem

### ISSUE THREAD

**Issue by HughLegend** [Amulet-Team/Amulet-Map-Editor#500]
**Describe the bug**
When I load chunks in my world in order to see them on amulet, some of the chunks won't load on amulet, leaving empty squares all around the map.

**To Reproduce**
1. Go to a new world and load a big area of chunks
2. Go to amulet and open that new world
3. Wait for random chunks to not load

**Expected behavior**
All chunks loaded in the world would load on amulet leaving no empty squares

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.8.17a2

**Comment by gentlegiantJGC** [comment]
What colour are the chunks?
Which game platform and version are you using?

**Comment by HughLegend** [comment]
Oh sorry, forgot to say its on Bedrock (Windows 10 edition) and version 1.18.2 (the latest one I think).
And with the colour of the chunks, you mean the color on amulet of the not loading chunks? They are gray and black as if I hadn't loaded them in the game, but I have.

**Comment by gentlegiantJGC** [comment]
Have you placed blocks in these chunks?
Bedrock does not save many chunks around the player despite rendering further

**Comment by HughLegend** [comment]
No I haven't. I was just loading the area so I could modify the biomes

**Comment by gentlegiantJGC** [comment]
Amulet doesn't generate chunks it just displays the chunks that have been been generated by the game. These chunks just haven't been generated.

**Comment by HughLegend** [comment]
I know I know, I meant that I was loading the area in the game, not in Amulet.
And I spent a long time flying around the area but lots of the chunks I know I went through weren't displayed

**Comment by gentlegiantJGC** [comment]
I am not sure what to tell you. Amulet can only display chunks that the game saved.
Increasing the simulation distance should increase the save distance.

**Comment by HughLegend** [comment]
So the problem must be Minecraft not saving chunks that are loaded I guess.
I will try increasing the simulation distance.
Thanks!
