### ISSUE TITLE
Not loading chunks in 1.18.2

### ISSUE THREAD

**Issue by Cyrinicstrife3** [Amulet-Team/Amulet-Map-Editor#501]
As far as i know this is a bug only i am reporting

**Describe the bug**
Whenever i load up my world, The overworld will not load up many of my chunks, even the ones where my main base is at that i spend a lot of time in. I have screenshots posted below but i now have the issue of chunks appearing red as well

**To Reproduce**
1. this is a 1.17 world
2. I deleted all chunks that were in my world except where my base and spawn were
3. Amulet continued to world until 1.18 was released, then i began encountering these problems. In the End we noticed the surrounding area where the spawn is was removed as well, we know this because the bridges we built to the islands were gone
4. Below is screen shots of the issues we are having

**Expected behavior**
for the over world, all chunks to be loaded into the program. For the End it is expected that after altering the overworld, the end would not change
![Image 3](https://user-images.githubusercontent.com/96199947/146239076-330509aa-fbbd-458b-8c42-0355829499cb.png)
![Image 4](https://user-images.githubusercontent.com/96199947/146239080-291fa842-4a1e-4dc8-a6b0-df0000d7130d.png)
![Image 6](https://user-images.githubusercontent.com/96199947/146239085-c71e790b-043c-440f-a3a2-965af749ba89.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows 10 edition
 - Version [1.18.2]

**Additional context**
In one of the images you can see where for some reason Amulet is appearing to actually be missing a texture, rendering the block pink and black

**Comment by gentlegiantJGC** [comment]
The version of Amulet you are using does not support 1.18.
You need to use the alpha version.

**Comment by Cyrinicstrife3** [comment]
Thank you so much kind sir
