### ISSUE TITLE
Chunks not loading below Y-0 

### ISSUE THREAD

**Issue by ebaystudio** [Amulet-Team/Amulet-Map-Editor#504]
Ive been testing the Beta with 1.18.2 and found some more issues. 

All of these are below Y - 0.  I confirmed that all the chunks below Y - 0 were generated in the world to be copied on a Bedrock Windows 10 install. 

However when loaded into Amulet any area that wasn't near a cave structure is failing to load. Again this only happens with random chunks below Y-0. Everything above seems to be working fine so far. 
![Image1](https://user-images.githubusercontent.com/39779766/146594072-572334f5-2102-44bb-a274-9bbab54007a3.jpg)

**Comment by ebaystudio** [comment]
As requested this is how to reproduce this issue. 
The attached world was designed in 1.17 and converted to 1.18 when it came out. 

On Windows 10 the world loads perfectly fine. I made sure to load all the new 1.18 chunks for the entire island I'm working on. Its roughly 4k x 4x. My PC can load up to 80 chunks so it wasn't hard to do the entire map. Besides the issue is even at spawn so I don't think thats the issue. 

Now again in bedrock I can dig down below Y-0  and I can see the new 1.18 chunks have all loaded. I can save/close and reopen the world and all the new chunks load as they should. 

After saving/closing Bedrock and then trying to open the same world into Amulet is when all the chunks go missing and it looks like the above photo. Now to be clear as long as I don't make any changed to the world I can close it on Amulet and reopen in Bedrock and its still perfectly fine. But if I make a change in Amulet anywhere then save the change and reopen the world on Bedrock the world is then a mess below Y-0. No matter what I cant get the 1/18 chunks to generate correctly. 

On a side note. When opening a world to edit I get 2 Edit buttons. 
Also, the map will sometimes refuse to close out saying a world is still open even though I've cleared out any changes. The only way to close after that is to do it with Task Manager or to close it from the traskbar. 

I tried to add a zip file to this reply but its not loading. Here is a Mediafire link https://www.mediafire.com/file/s3c9uonrg5n4lb4/negative_y_bug_world.zip/file

**Comment by ebaystudio** [comment]
Just and FYI. At spawn you will see some sand near the shore with one Deepslate block. Remove it and you'll have a direct path to bedrock.

**Comment by ebaystudio** [comment]
Still testing. Just created a new world and then tried to edit using beta. I made sure all chunks below 0 were loaded. I coped a tree and when I opened that world in Bedrock the chunk below it under 0 was completely removed. Everything above 0 seems to be working.

**Comment by gentlegiantJGC** [comment]
Bedrock is a bit deceiving with the render distance.
There are two distances you need to be concerned with.
The first is simulation distance. All chunks within this region will get simulated and changes will get saved back out.
There is then render distance which is the distance that is rendered in game.
All chunks between the simulation distance and the render distance are not saved unless you move closer to them so that they are in your simulation distance.

I assume that is what is happening here. The chunk data that has been saved just has not been updated.

**Comment by ebaystudio** [comment]
I wish it was that simple. The chunks you see missing have all been visited and saved. This world has a few hundred hours on it. Any area edited prior to 1.18 will not load the chunk below y0. Unedited chunks do load as they should.  I even took a fresh copy of the world prior to any editing, loaded it into 1.18, generated all the chunks by spamming the entire map below Y0. In Minecraft/bedrock all the chunks render. However after adding back the structures above Y0 evener thing below that is wiped out again. I even tried to copy the chuncks from the fresh map that does work over to the map that is missing the chunks to fill them in and they still dont save.

**Comment by gentlegiantJGC** [comment]
Are you trying to say that in amulet you can't paste blocks below y=0?

From your photo it looks like the game has updated some of the chunks but not all of them.
The game will only update chunks that are stored in the 1.17 format and below.
Amulet will save the edited chunks in the newest format the world can support which means that the game will not update them if they have been edited in Amulet. This means that you need to force the game to update and generate the region below y=0 before editing in Amulet.

**Comment by gentlegiantJGC** [comment]
It sounds like you think the game has updated all the chunks but in fact it hasn't.

You can use Amulet to see the true state of the chunks before editing them. If there are no blocks below y=0 in Amulet then the game has not updated them and you will need to fly nearer them to force them to update.

**Comment by ebaystudio** [comment]
That's exactly what I did, several times now. I made sure to spam all those chunks. (fly by and even dig in the ones right under my main build in Minecraft to make sure those chunks are loaded and saved. I can open the world before any edits and all those chunks are there. The problem happens after edits are made. After and edit the chunk right below each edit is then completely deleted. Ive tried both coping the entire chunk -65 to 250+ or just Y0 to 250 or whatever the height is and its always the same. Any data below Y0 of any edited area is deleted. No matter if I physically dung that area, flown within the chunk or not. Always the same outcome. Ive rebuild the world at least a dozen times now and its always the same result. I sent you the world file. Try it yourself.

**Comment by gentlegiantJGC** [comment]
Okay. I will have a look.

**Comment by gentlegiantJGC** [comment]
Okay so I have opened your world in Amulet and it looks roughly the same as your screenshot
![image](https://user-images.githubusercontent.com/11940194/149368718-9e8e6eb7-1610-4f36-83ba-20dfa4b9c701.png)

**Comment by gentlegiantJGC** [comment]
For some reason I can't open this world in 1.18

**Comment by gentlegiantJGC** [comment]
I have just deleted a load of chunks and I still can't open this world. It just gets stuck on building terrain.

**Comment by gentlegiantJGC** [comment]
yeh I don't know what it is about this world. I have deleted all the chunks and it still won't load.

**Comment by gentlegiantJGC** [comment]
Can you do the following steps and take screenshots at each stage.
1) Open the world in Amulet. Don't make any modifications. Got to x=2459 z=1349 and take a screenshot. It should look like screenshot I sent above
2) Close Amulet
3) Open the world in game and go to the same coordinates.
4) Go to the bottom of the world and take another screenshot. If what you are saying is true this should just look like bedrock at -64
5) Fly around a bit and break some blocks in some of the chunks that are not updated in the first screenshot as well as some that were
6) Close Minecraft
7) Open the world again in Amulet
8) You should see the chunks that you flew near and placed blocks in have updated and now extend down to -64

Once you have done that we can work out the next steps

**Comment by LongDrong** [comment]
This hapened to me too. Any solution?

**Comment by LongDrong** [comment]
Loaded really old versions of the world to generate new sub zero blocks and when opened with amulet still hapens the same
