### ISSUE TITLE
"Set biome" does not work

### ISSUE THREAD

**Issue by HughLegend** [Amulet-Team/Amulet-Map-Editor#507]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
If you try to change the biome of a selected area, it just won't do anything. The biome is not changed, everything remains the same.

**To Reproduce**
1. Select an area
2. Click on "operation"
3. "Set biome"
4. Select a biome (different from the original)
5. "Run operation"
6. Save and quit
7. Go to Minecraft to check if something has changed

**Expected behavior**
The biome selected is the one that will be loaded on Minecraft.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.8.17b0

**Comment by HughLegend** [comment]
Update: I managed to change the original biome to some specific biomes, but not every biome works. For example, seems impossible to turn land into ocean.

**Comment by gentlegiantJGC** [comment]
Are you using Minecraft Bedrock or Java?

**Comment by HughLegend** [comment]
Nevermind it works well now! 

Just one question to be sure if it is working as expected or not. 
If I copy a jungle chunk, paste it on an ocean and change the biome to jungle biome, should mobs such as pandas and parrots spawn there?

I'm using Bedrock and yes, I am closing the fame before opening amulet.

Thanks!

**Comment by gentlegiantJGC** [comment]
I think I have just spotted an issue with the biome arrays being loaded incorrectly

**Comment by gentlegiantJGC** [comment]
This might be fixed by the array rotation bug that was fixed in the pull request linked above.
If it is still an issue in 0.8.17 then let me know.

**Comment by HughLegend** [comment]
Perfect! If I notice anything I will let you know.
Thanks!
