### ISSUE TITLE
Error open custom dimensions in Amulet 

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#508]
Minecraft china bedrock edition together with the Mcstudio program allows peopels to add bedrock edition 2147489647 dimensions to the world. And although the Amulet Map Editor can display these dimensions in the list
![Скриншот 07-12-2021 100626](https://user-images.githubusercontent.com/81485476/146663825-5374d1da-77c5-4e01-a0a3-5ea4dc69c3eb.jpg)

But when I try to view a custom dimension in the amulet, it is transparent and invisible. The error that appears in the console

`Exception: The dimension exists but there is not selection registered for it. Please report this to a developer "DIM3" <amulet.level.formats.leveldb_world.format.LevelDBFormat object at 0x000001D9DA21DA90>
`
![Без названия168_20211219094351](https://user-images.githubusercontent.com/81485476/146664200-54235bf8-3ca9-4c7a-85fb-c314bf92efda.png)

You can also use this world to conduct experiments on it [Link](https://www.transferfile.io/bafybeigpcxcnnuleqzwgebdhs4mcvvpxar3zd7upncjfwux4lophwxathu)  this world has more than 3 dimensions.

I hope you will correct this error.

There is also problem for the worlds of java edition 20w14 infinite. All custom dimensions are displayed there, but so that the world opens in the amulet

![20211219_095143](https://user-images.githubusercontent.com/81485476/146664452-306d8392-e8cb-4f8b-81ea-c079dbdc5404.jpg)

**Comment by Max-RM** [comment]
@gentlegiantJGC

**Comment by Goldenlion5648** [comment]
I am experiencing this issue on 1.19.3 when using a datapack that adds a dimension, is there a fix in this case since level.dat is still named the normal name of level.dat?

**Comment by Max-RM** [comment]
Are you use MCBE or MCJE?

**Comment by gentlegiantJGC** [comment]
@Max-RM @Goldenlion5648 please can you test this in the newest version.
I changed the code the other day and I can't reproduce this issue.

**Comment by Max-RM** [comment]
> @Max-RM @Goldenlion5648 please can you test this in the newest version. I changed the code the other day and I can't reproduce this issue.

Will try now

**Comment by Max-RM** [comment]
> @Max-RM @Goldenlion5648 please can you test this in the newest version. I changed the code the other day and I can't reproduce this issue.

Amulet 0.10.21 still have this issue.
About MCBE: 

ERROR - Error loading chunk -7 4 DIM3
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 489, in _load_chunk
  File "amulet\level\formats\leveldb_world\format.py", line 323, in _decode
  File "amulet\api\wrapper\format_wrapper.py", line 234, in bounds
Exception: The dimension exists but there is no selection registered for it. Please report this to a developer "DIM3" <amulet.level.formats.leveldb_world.format.LevelDBFormat object at 0x00000161A5EFD8B0>

(This error repeats endlessly).

About MCJE 20w14infine: can't load world just because it uses (special_level.dat) instread of just (level.dat) (if rename file amulet will open world without problems).

**Comment by gentlegiantJGC** [comment]
We won't support the april fools update.
Your original world link no longer works. Please can you share another world.

**Comment by gentlegiantJGC** [comment]
I missed that this is for Bedrock

**Comment by Max-RM** [comment]
> . Please can you share another world.

Ok

**Comment by Max-RM** [comment]
> Please can you share another world.

https://drive.google.com/file/d/1RakjLDvjJF2SAGEk6oC77wNEZ6hJV9w3/view?usp=drivesdk

**Comment by gentlegiantJGC** [comment]
So it looks like this is a feature of the netease edition.
Dimensions can be added with a JSON file in `netease_dimension/dimension_config.json`
That file specifies ~~the dimension name and~~ the numerical value used in the DB.
Any idea where the world height is specified?

**Comment by Max-RM** [comment]
> netease_dimension/dimension_config.json

this is the official Netease format. their Chinese MCBE by default has 21 dimensions instead of 3. you can get into other dimensions there without any addons, using the command /changedimension @p dm<3-20> ~ ~ ~ but all other dimensions have generation and seed like overworld.

**Comment by Max-RM** [comment]
> Any idea where the world height is specified?

in the overworld settings, it most likely cannot be changed through addons and it will always be 256 (for old versions) and 384 (for new versions).

**Comment by gentlegiantJGC** [comment]
All the dimensions in the two worlds you sent start at y=0 so I am going to assume they have the old world height.

**Comment by Max-RM** [comment]
> All the dimensions in the two worlds you sent start at y=0 so I am going to assume they have the old world height.

Yes, you're right. even in the world of 1.18.33, the maximum height of other dimensions is 256.

Btw here you can see, that Netease's MCBE has 21 dimensions by default without any addons: https://youtu.be/fgTTXZPulhU

**Comment by Max-RM** [comment]
The portal addon just give survival players ability to move to other dimensions without cheats like that command (/changedimension).

**Comment by Max-RM** [comment]
![IMG_20230927_192211_986](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/81485476/a7dc89e3-d078-4872-8ec4-11a4f12ee3f8)
Now works
