### ISSUE TITLE
If your taskbar is set to the top, the opening world window hides behind the taskbar

### ISSUE THREAD

**Issue by t3hero** [Amulet-Team/Amulet-Map-Editor#51]
Windows 10 Issue here, when I open the "Open World" window it hides behind the taskbar, making it impossible to close or move around. 

See screenshot below

![Taskbar at the top](https://t3.lc/98527.png)

**Comment by gentlegiantJGC** [comment]
I will have a look into this. I don't know how we could detect that. I think for the moment you can right click on the task bar and select one of the "show windows ..." options to get the windows back

**Comment by gentlegiantJGC** [comment]
I have resolved this by having the window spawn a little lower down.
The whole window could do with a bit of a redesign if I am honest.
