### ISSUE TITLE
[Bug Report] Amulet renders extra "Convert" and "3D Editor" tabs

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#511]
Amulet renders extra "Convert" and "3D Editor" tabs on the left side of the Amulet after loading a 1.18.1 java world.

**Describe the bug**

**To Reproduce**
1. Load Amulet V0.8.17b0 from the latest beta version.
2. Load a 1.18.1 Java savegame in Amulet.
3. Look to your left-hand side of the amulet to notice the graphical issue take place.

**Expected behavior**
For there to only be one convert tab and one 3D editor tab when loading a world.

**Screenshots**
![image](https://user-images.githubusercontent.com/17806994/146804631-8a9e0672-7501-4539-9a07-ebcd0510452d.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Version 10.0.19041 Build 19041

**Additional context**
N/A

**Comment by gentlegiantJGC** [comment]
Does the issue reproduce with other worlds in this version?
Does the issue happen in the previous alpha?
I bumped the version of pyinstaller so this may have effected that.

**Comment by StealthyExpertX** [comment]
I haven't tested that, just know I've recently run into this with a 1.18.1 java world and so did somebody in the bedrock channel in the Discord.

Yes, it seemed to have happened in the previous alpha.

**Comment by HughLegend** [comment]
Same happens to me in this version. But it didn't happen to me in the previous alpha version

**Comment by erich666** [comment]
This happens to me with the beta, 17b0, opening a Bedrock world:
![unknown](https://user-images.githubusercontent.com/803995/146949089-fc89a2cc-1a5f-4960-bfcd-6c3effbea06e.png)

**Comment by LaserSlime** [comment]
Can also confirm this. Thought it was intentional for some reason.

**Comment by gentlegiantJGC** [comment]
Looks like one of the newer versions of PyInstaller fixed an issue that I was previously working around.
Now that it is fixed my code is finding it again.
