### ISSUE TITLE
Copy pasted selections in 2d mode disappear after reopening the world.

### ISSUE THREAD

**Issue by LaserSlime** [Amulet-Team/Amulet-Map-Editor#517]
**Describe the bug**
Copy pasted selections in 2d mode disappear after reopening the world.

**To Reproduce**
1. Open a word. (I recommend to use a void world for this with some floating stuff you can move around)
2. Select an area in 2d mode and cut it out using Ctrl + X.
3. Press Ctrl + V and paste it somwhere (still in 2d mode).
4. If you now save, close and reopen the world, the area you pasted is nowhere to be found. You can also open it in singleplayer.

**Expected behavior**
The pasted section should be saved and reappear after closing.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004 .64
 - Version: V0.8.17b0

**Additional context**
This keeps happening pls fix.

**Comment by gentlegiantJGC** [comment]
You need to click confirm to confirm your placement and apply it to the world before saving.

**Comment by LaserSlime** [comment]
> You need to click confirm to confirm your placement and apply it to the world before saving.

I did just that. They only disappear after saving and closing and reopening.

**Comment by gentlegiantJGC** [comment]
Can you send a screenshot of what it looks like in the 3D view. It is possible it is at a different height

**Comment by LaserSlime** [comment]
What do you mean by different height? I made sure to select everything on the y axis from 0 to 255 when moving.
