### ISSUE TITLE
macOS: 3D Editor GUI only visible when resizing the window [amulet-map-editor=0.8.17b0]

### ISSUE THREAD

**Issue by nik-field** [Amulet-Team/Amulet-Map-Editor#522]
On macOS (Catalina 10.15.4) using 0.8.17b0, I can only see the gui/hud overlay in the 3D Editor when i'm actively resizing the window, otherwise the 3d world view seems to be over top of the gui elements.

https://user-images.githubusercontent.com/47613489/147606247-e75a8b92-118a-4a43-80a1-2951f93a1bde.mp4

**Comment by gentlegiantJGC** [comment]
This is the same issue as #127
