### ISSUE TITLE
Set biome function setting random biomes.

### ISSUE THREAD

**Issue by PolyframeX** [Amulet-Team/Amulet-Map-Editor#523]
When settings a biome, for some unknown reason the biome will be completly random, in small areas.

I am Amulet v0.8.17b0
Minecraft Bedrock 1.18.2

**Steps to reproduce the behavior:**
1. Open Amulet
2. Select a Bedrock World
3. Select a area
4. Click "Operation"
5. Set Operation to "Set Biome"
6. Set the biome to redwood_taiga_hills_mutated

**Expected behavior**
The biome should be set correctly in the selected location.

**Screenshots**
<img width="272" alt="image" src="https://user-images.githubusercontent.com/80133652/147700432-109a982c-302d-416b-852d-948c60694db4.png">

**Desktop**
 - OS: Windows 11
 - Version 22000.376

**Additional context**
I am using a client to see F3 on Bedrock. I have checked and found it is not the client bugging out. Due to seeing nether biomes fog everywhere.

**Comment by gentlegiantJGC** [comment]
This might be fixed by the array rotation bug that was fixed in the pull request linked above.
If it is still an issue in 0.8.17 then let me know.

**Comment by FreeWorldYT** [comment]
@gentlegiantJGC , This problem still persists within the latest version of amulet. I should've said I was changing it all to one biome.

**Comment by gentlegiantJGC** [comment]
Can you better explain what you are trying to do and what you expect to happen.
Your previous explanation is a bit cryptic.

**Comment by FreeWorldYT** [comment]
I was trying to select a slightly big area and change its biome to a taiga biome.

**Comment by FreeWorldYT** [comment]
I tested amulet v0.9.2 and this bug is still present.

**Comment by gentlegiantJGC** [comment]
What client are you using to see biomes on Bedrock?

**Comment by gentlegiantJGC** [comment]
I have tried reproducing it using the steps you gave but it works as expected.
Everywhere I selected was changed to redwood_taiga_hills_mutated with the exception of chunks that did not exist but were in the selection. The set biome operation only runs on chunks that already exist so this behaviour is intended.
There was an issue setting biomes below y=0 and above y=256 reported in #683 which I have fixed.

Can you provide some screenshots of the selection and operation you are running so I can better understand what you are doing.

**Comment by FreeWorldYT** [comment]
I am using Onix Client. On a flat world. Should I send a file of the world?

Here is the video: https://drive.google.com/file/d/1_xDhsI5Gy66UqedEGatXsb-J_X_kawIb/view?usp=sharing

**Comment by PolyframeX** [comment]
Issue is no longer present, world was possibly corrupted causing the issue.
