### ISSUE TITLE
0.8.17b0 requires the user to save changes otherwise it will not close the active world

### ISSUE THREAD

**Issue by abrightmoore** [Amulet-Team/Amulet-Map-Editor#526]
**Describe the bug**
Changes cannot be discarded. 0.8.17b0 requires the user to save changes otherwise it will not close the active world

**To Reproduce**
Open a world, run an operation, if changes are shown as made and pending then try to close the edit session. "Do you want to save changes" has Yes/No/Cancel. Choosing 'No' dismisses the dialog and doesn't close the tab/session.
See animation here: https://discordapp.com/channels/324647192583340043/498974201416253443/928883637204709457

**Expected behavior**
Selecting 'No' to discard changes should close the edit session.

**Screenshots**
See https://discordapp.com/channels/324647192583340043/498974201416253443/928883637204709457

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 and 11

**Additional context**
This possibly may contribute to level.db corruption if the process is killed to avoid saving pending changes.
![2021207a_closeworlds](https://user-images.githubusercontent.com/2847385/148664092-e65b7545-c066-4866-b4e2-f7ca1d4baceb.gif)

**Comment by gentlegiantJGC** [comment]
Looks like this is related to the duplicated tab issue.
