### ISSUE TITLE
When converting maps from Java version to Bedrock version, some chunks are lost, showing the void.

### ISSUE THREAD

**Issue by sunung0110** [Amulet-Team/Amulet-Map-Editor#528]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
In the latest stable release and the latest beta, when I try to transform the map, the transformed part is fine, but the outside of the transformed part is missing chunks that fall into the void.

**To Reproduce**
1. java map open
2. click convert
3. select converted map in bedrock
4. and open bedrock version, you can see borcken world

**Expected behavior**
chunk will not lost

**Screenshots**
https://drive.google.com/drive/folders/18eQfZkkhiDOBT0u7JcRhU5yivXuBvWKA?usp=sharing

**Desktop (please complete the following information):**
 - OS: windows
 - Version : 0.8.15 and 0.8.17b0

**Additional context**
In version 0.8.15, I converted using Java version 1.17.1 and Bedrock version 1.17.40.6, and in version 0.8.17b0, I used Java version 1.18.1 and Bedrock version 1.18.2.3.

**Comment by sunung0110** [comment]
ok, I found the cause of the problem.
https://drive.google.com/drive/folders/1SpUHPigkc2t0EzwfPUwkl5mE3EqlbWcC?usp=sharing

**Comment by gentlegiantJGC** [comment]
It is probably a partially generated chunk. I will need to modify the conversion code to not convert these
