### ISSUE TITLE
Installed everything correctly but doesn't open program

### ISSUE THREAD

**Issue by sixamscrew** [Amulet-Team/Amulet-Map-Editor#53]
**Describe the bug**
After cloning the project Amulet editor and installing all the python requirements, I don't know why src/main.py doesn't run the program.

**To Reproduce**
1. Go to Amulet-Map-Editor/src
2. Click on 'main.py'
3. See error flashing in console:
"There is only a command line version for now."
NotImplementedError: There is only a command line version for now. To start it, you should use the argument '--comand-line'

**Expected behavior**
Amulet editor program opens

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - How to know it?

**Additional context**
I don't know how to run this program, If I type in Windows cmd: Amulet-Map-Editor --command-line, it shows:  'Amulet-Map-Editor' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Podshot** [comment]
Amulet is still not ready for normal use yet (saving has not be added in yet) and doesn't have a UI to use yet, it only has a very rough and basic command-line version. 

However, if you would still like to try out the command-line version, you can run the following in command prompt `python src/main.py --command-line`
