### ISSUE TITLE
Problem with exported structure not importing as a replica

### ISSUE THREAD

**Issue by JinJinJinT** [Amulet-Team/Amulet-Map-Editor#54]
This may just be the transitional issue you guys are currently fixing but when I exported a selection into a .construction format, the reimported structure seems to have a few incorrect blocks and item placement. Ex: all glass were quartz slabs instead. A few torches one block above where they should be, etc. Copy and pasting the same structure in the same world seems to work fine though.

The exported structure:
![amulet1](https://user-images.githubusercontent.com/60024162/84966842-60f6f800-b0c7-11ea-8fe2-23ebcd198e50.png)

The same structure imported:

![amulet2](https://user-images.githubusercontent.com/60024162/84966874-766c2200-b0c7-11ea-9c66-aa74a2a7c903.png)

**Comment by gentlegiantJGC** [comment]
Can you send over the construction file for us to investigate

**Comment by gentlegiantJGC** [comment]
I think it might be related to this issue that was reported in our discord server.
https://cdn.discordapp.com/attachments/498974201416253443/720629171235192953/CONFARM.construction
(for my future reference)

**Comment by JinJinJinT** [comment]
Here is the construction File
[construction.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/4806241/construction.zip)

**Comment by gentlegiantJGC** [comment]
Thanks for reporting this. Turns out they were two separate issues which are both fixed now. The fix will be in the next build.
