### ISSUE TITLE
Proper way to run on Linux (using python virtual environment in-place of root while installing the requirements)

### ISSUE THREAD

**Issue by juozaspo** [Amulet-Team/Amulet-Map-Editor#54]
### Describe the bug

**Problem 1:** To install all required dependencies, one needs to run `pip install -r requirements-dev.txt` which might fail on Linux, as some packages tries to write to the system directories which fails due to `Permission Denied` error. 
**Problem 2:** Using root might cause problems when using versions provided by the package manager, pip might want to uninstall or overwrite them, which might break other system packages and cause even more problems.
**Problem 3:** The program needs Python 3.7, it doesn't work with Python3.6 or earlier as there are errors shown when one attempts to launch it.
**Workaround (on Ubuntu):** first install `virtualenv` and `python-3.7` packages them use virtualenv to build python3.7 environment, activate it then install dependencies as follows:
```
virtualenv -p python3.7 ENV #create new env in directory named ENV, with python 3.7 as default
. ENV/bin/activate #enter (activate) the env
pip install -r requirements-dev.txt
deactivate #exit out of the env
```
You can use python `venv` module (`python3.7-venv` on Debian & Ubuntu) in place of `virtualenv` program and create an env using command `python3.7 -m venv ENV `
After installation of deps, you can run the app inside env, each time activating the env using `. ENV/bin/activate` command and deactivating with `deactivate` command.

**Edit:** added information about problems using pip to install deps while on root, also done some re-wording and reorganizing of the description for better readability.
**Edit2:** Included the alternate method to create virtual environment, when the virtualenv program is not desired, as shown in the changes to README.md made by PR #52 
### To Reproduce

1. Clone app from github link
2. Try to install requirements when not on root, fail, try next step
3. Use python virtual environment created using virtualenv or python venv module, verify that installed version of python is not 3.7 or older, fail when trying to run from source

### Expected behavior

There should be a documentation how to run properly on Linux, such as of using python virtual environment created using `virtualenv` or other methods, and any other workarounds that also might be possible.

### Desktop

 - OS: Ubuntu Linux 18.04 LTS, default python: python2, python2: version 2.7, python 3: version 3.6
 - Program Version (commit): 7d1d2243fc29095b3cffe8aa4979235444ba6738

**Comment by Podshot** [comment]
We should definitely improve our development installation instructions in general, but more specifically to account for needing to install Python 3.7 into a virtual environment for operating systems that come with a version of python already installed. We'll update our instructions to be more clear and in-depth much as we can.

**Comment by Podshot** [comment]
@juozaspo Could you please describe the steps you needed to do to install python 3.7 on linux? I know each distribution (more or less) has it's own method, but I would like to at least include an "example" so others can follow the similar steps

**Comment by juozaspo** [comment]
@Podshot I don't know for other Linux distributions, but on Ubuntu there's a `python-3.7` package, installed by using _apt_ package manager. To install latest version run (from command line):
```
sudo apt-get update
sudo apt-get install python-3.7
```
To verify that it's installed you can run `dpkg -l python3.7` from command line too.

**Comment by juozaspo** [comment]
My process of building python3.7.4 (with command line comments where needed, `command #explanation`) is as follows, similar to process described in `README.rst` file for python, found in `Python-3.7.4.tgz` downloaded from official sources page:
```
#sudo apt-get build-dep python3.7 #make sure sources are enabled in apt settings (check/edit `/etc/apt/sources.list` or use tool such as `software-properties-gtk` if it's installed), uncomment this and comment out one line below if you want apt to install all required dependencies automatically
sudo apt-get install libffi-dev #needed to build module _ctypes, otherwise make install command might fail, use this instead if not using above
mkdir /home/yourname/python #or any path you prefer, replace yourname with your unix user name
tar -zxvf Python-3.7.4.tgz
cd Python-3.7.4
./configure --prefix=/home/yourname/python
make -j $(nproc)
#make test #run tests, takes some more time
make altinstall #or make install, both works
```
To create virtualenv with this python run `virtualenv -p /home/yourname/python/bin/python3.7 ENV`
test it:
```
. ENV/bin/activate
#do ususual stuff, etc
deactivate
```
If you have any issues with custom python build, post it here or create a new issue, referencing this, I don't know which is better.

**Comment by juozaspo** [comment]
As #52 is merged, I don't see keeping this open. If there's a problem related to this not yet solved, post a comment and I'll reopen this issue.
