### ISSUE TITLE
[Bug Report] WARNING - Could not find registered value for biome 18. Reverting to plains

### ISSUE THREAD

**Issue by didaquis** [Amulet-Team/Amulet-Map-Editor#545]
### Current Behaviour:
After opening a world, this warning appears on the terminal: 
`pymctranslate - WARNING - Could not find registered value for biome 18. Reverting to plains`

### Expected behavior:
I expected not to see any warning message

### Steps To Reproduce:

1. Open Amulet
2. Select a world
3. Open the world

### Environment:
- OS: MacOS (11.6.1)
- Minecraft Platform: Java
- Minecraft Version:  1.18.1
- Amulet Version: V0.8.17b0

**Comment by didaquis** [comment]
I tried the same steps on another world (with the same OS and the same Amulet version) and got this warnings on the terminal:


<img width="1021" alt="terminal" src="https://user-images.githubusercontent.com/6883041/150659175-ec083209-7a47-4476-a93e-c431cea9ea7d.png">

**Comment by gentlegiantJGC** [comment]
Can you share a world that reproduces the issue.
It looks like it should be minecraft:wooded_hills in 1.17 and before but 1.18 removed numerical biome ids so this should not be used.

**Comment by didaquis** [comment]
> Can you share a world that reproduces the issue 

You can download the world on this link: https://we.tl/t-iI3dvDXGGa

**Comment by gentlegiantJGC** [comment]
Sorry it has taken me a while to get around to this.
I have flown around your world a bunch and I am not able to reproduce that issue in the latest version of Amulet.
What coordinates can I go to to get those warnings?

I was able to reproduce #359 in this world somewhere but that is a different issue I need to look into
