### ISSUE TITLE
[Bug Report] Impossible delete some chunks

### ISSUE THREAD

**Issue by didaquis** [Amulet-Team/Amulet-Map-Editor#546]
### Current Behaviour:
I have selected a set of chunks to delete. When I start the operation, it seems that the application is "frozen" (not responding).

### Expected behavior:
When the "Running Operation" modal appeared, I expected the process to finish at some point.

### Steps To Reproduce:

1. Open Amulet
2. Open a world
3. Select some chunks
4. Click on button "Detele Chunks"
5. Confirm that I want delete all selected chunks

### Environment:
- OS: MacOS (11.6.1)
- Minecraft Platform: Java
- Minecraft Version: 1.18.1
- Amulet Version: V0.8.17b0

### Screenshots 
The application is frozen on this point for more than one hour. The image shows that the number of chunks selected is not large. 

<img width="727" alt="Captura de pantalla 2022-01-23 a las 0 35 53" src="https://user-images.githubusercontent.com/6883041/150659017-ac2a68d3-f7d5-44b5-bb87-0dd6db528b47.png">

**Comment by gentlegiantJGC** [comment]
Are there any errors in the console?

**Comment by didaquis** [comment]
> Are there any errors in the console? 

No, no errors on console. Just the application frozen. The application is not responding.

**Comment by gentlegiantJGC** [comment]
Are you able to delete any chunks?
Is there something about these chunks causing the issue?
Does it happen every time?
An area of chunks that small should run rather quickly so I don't know why it is getting stuck.

**Comment by didaquis** [comment]
> Are you able to delete any chunks?

No, I could not delete any chunk

> Is there something about these chunks causing the issue?

I don't think so. They are chunks generated in some old version, but they do not contain constructions. Nor have they been altered with any program or mods have been used in this world

> Does it happen every time?

yes

**Comment by didaquis** [comment]
> Are you able to run other operations? 


To be honest, I did not try to do any other operation.

**Comment by gentlegiantJGC** [comment]
Without more information I don't know how I could debug what the issue was.
Can you try running some other operations and let me know if they run correctly.
This will tell us if it is an issue with the loading UI or the actual operation.
