### ISSUE TITLE
[Bug Report] Massive Holes

### ISSUE THREAD

**Issue by EmilianoMorghen** [Amulet-Team/Amulet-Map-Editor#550]
## Bug Report
**Amulet deletes whole chunks instead of selected blocks.**
I've tried to cut an hole from `0 0 0 xyz`  all the way to `10k 391 -1k xyz`.

### Current Behaviour:
It did cut the blocks, but cut millions more than it needed. 

### Expected behavior:
It should have deleted block above `~ 0y ~` but instead looks like it deleted entire chunks. From sky limit down to bedrock.

### Steps To Reproduce:
Generate classic world.
Load world data in Amulet.
Select anything above 10k * 391 * 1k
Click Delete
Click Save

### Environment:
- OS: Windows 
- Minecraft Platform: Java 
- Minecraft Version: 1.18.1
- Amulet Version: 0.8.17

## Attachments
[worldgen_settings_export.json](https://drive.google.com/file/d/1CUnKTzkQ1GHJP-MyT9W6DUv4MZvA9vAs/view?usp=sharing)

### Screenshots
![2022-01-24_19 35 57](https://user-images.githubusercontent.com/9059989/150844972-b90d1ded-2ab1-43d4-9c33-0a19762b68dc.png)
![2022-01-24_19 36 01](https://user-images.githubusercontent.com/9059989/150844976-c188af6a-b4ac-4a65-b839-76d679a3b68f.png)
![2022-01-24_19 36 33](https://user-images.githubusercontent.com/9059989/150844981-d320815d-0980-4b46-888a-e3d25b2464cd.png)
![2022-01-24_19 36 49](https://user-images.githubusercontent.com/9059989/150844988-3d48a59c-187c-4fb1-a535-c31c039fef5e.png)

### Worlds
[World](https://drive.google.com/file/d/1sLMm5ZNlhaQ2U6Vtpborp5LQJ_Dp8jvb/view?usp=sharing)

**Comment by gentlegiantJGC** [comment]
My guess is that the void chunks were chunks that did not exist when you pressed delete.
The delete operation currently works by filling air in the selection.
I will look into making it not apply to chunks that do not exist.
