### ISSUE TITLE
Error loading Java resource pack

### ISSUE THREAD

**Issue by Hema-Chandra06** [Amulet-Team/Amulet-Map-Editor#553]
![sdiojdlmp;oeifjlm](https://user-images.githubusercontent.com/96871624/151353834-d721a3f1-8b77-4235-a463-df3705ce8897.JPG)

**Comment by gentlegiantJGC** [comment]
are you able to access this url?
https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by Hema-Chandra06** [comment]
> are you able to access this url? https://launchermeta.mojang.com/mc/game/version_manifest.json

yes

**Comment by gentlegiantJGC** [comment]
I should look into adding retry support for this and a manual fallback for the user to specify a jar file.

**Comment by gentlegiantJGC** [comment]
I am going to close this as a duplicate of #419 
While not the exact same error the result is the same
