### ISSUE TITLE
[Bug Report] Missing chunks after performing Bedrock -> Java world conversion

### ISSUE THREAD

**Issue by JustTalDevelops** [Amulet-Team/Amulet-Map-Editor#555]
## Bug Report
Attempting to do a conversion between Bedrock 1.18 and Java 1.18, but when converting, I noticed a bunch of missing chunks around the map. The map loads just fine in vanilla Bedrock and BDS, but whenever loading it in Amulet, it loses a couple of chunks.

### Current Behaviour:
Converted map loses chunks that should exist.

### Expected behavior:
Conversion results in no missing chunks.

### Steps To Reproduce:
1. Load the world attached below using Amulet, and open the 3D editor or attempt a conversion.
2. Notice the 'red chunks' in the 3D editor, or the missing chunks in game versus the original world.

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.18.0
- Amulet Version: 0.8.7

### Screenshots
![image](https://user-images.githubusercontent.com/39247615/151831441-a83cdadf-27a5-450d-852e-2f2acd4266cf.png)
![image](https://user-images.githubusercontent.com/39247615/151831511-b1f20bd2-e5d1-4720-81d2-0b37c975f4ae.png)
![image](https://user-images.githubusercontent.com/39247615/151831591-c88bc88a-aff3-4d7c-92ec-23771a172ff6.png)

### Worlds
[mushroom_castle.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7972384/mushroom_castle.zip)

**Comment by gentlegiantJGC** [comment]
I have added code to support this case even though the game does not like them that much.
