### ISSUE TITLE
[Feature Request] fix high dpi of win10/11 适配dpi缩放

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [Amulet-Team/Amulet-Map-Editor#562]
### The Problem

font blur if dpi not 100%不是100%缩放的界面会变糊
### Feature Description

fix dpi of windows

**Comment by gentlegiantJGC** [comment]
Could you give some more details of the issue.
Perhaps screenshots of the issue.

**Comment by gentlegiantJGC** [comment]
I am going to close this because of the little information and inactivity
