### ISSUE TITLE
[Bug Report] set biome not working in the Nether

### ISSUE THREAD

**Issue by BioJawn** [Amulet-Team/Amulet-Map-Editor#565]
Bug Report:
Set Biome is not working in the Nether.

Current Behaviour:
Biomes in The Nether are not changing/updating. Biomes in OverWorld are changing and working as expected.

Expected behavior:
When using Set Biome in the Nether, Biomes would be set accordingly.

Steps to Reproduce:

1. In Amulet Go to any Loaded chunks in the Nether
2. Click on Set Biome
3. Set biome to something distinct and noticeable from normal environment (Wastes to Warped).
4. Click Save
5. Load world and enter Chucks. Notice Nether Particles have not changed to correct Biome and Spawning of correct mobs for Biome set has not changed.

 Environment:
- OS: Windows 11
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.18.10
- Amulet Version: 0.8.17

Additional context
 I am trying to setBiome in the Nether and the biomes will not change. Set Biomes work in Overworld. I have tied column and block selections to set biome and nothing changes. I am using  version 0.8.17 on windows 11. Minecraft Version 1.18.10. All chunks have been fully loaded with blocks placed inside chunks to be sure. No error messages in Amulet. Amulet completes the tasks, I hit save and exit. Open the world In Minecraft and nothing has changed. Any help here is greatly appreciated.

**Comment by gentlegiantJGC** [comment]
It looks like there are some issues with the vertical offset in the nether. I will need to look into that.
It is probably a bug from when the overworld floor position changed.

**Comment by BioJawn** [comment]
Just a heads up guys, in response to bug fix #565 in 0.8.19. I am still having the same issue. Biomes in Nether are setting correctly above Y=65 is seems, but not below.
Minecraft version 1.18.12

**Comment by gentlegiantJGC** [comment]
Do you have a world this issue can be reproduced in?

**Comment by BioJawn** [comment]
I do, however I do not want it public yet, can I send it privately?

**Comment by gentlegiantJGC** [comment]
I have just tried reproducing this issue and as far as I can see it works as intended.
I can set biomes using the column and selection modes and inspect the biomes that were set in game using the developer tools in the private version of the game (not sure why the public version does not have this feature).
Most of the biomes do not change the effects that much. The most noticeable change is `warped_forest` which has red particles and `basalt_deltas` which has lots of grey particles. The sky colour does not change that much. I have not tested spawning.

The biomes in the screenshots below were set using the box mode and were screenshotted within the same session (so they both exist there at the same time).
![image](https://user-images.githubusercontent.com/11940194/166432464-3d8f02c7-cc0a-4c7c-9838-33db8bf5ce05.png)
![image](https://user-images.githubusercontent.com/11940194/166432611-88fb8d33-dd39-40f5-8839-696208c114b9.png)

**Comment by BioJawn** [comment]
This was a bedrock bug

**Comment by gentlegiantJGC** [comment]
Yes. The screenshots I sent are from the windows 10 bedrock edition
