### ISSUE TITLE
[Bug Report] Weird artifacts on previously ungenerated chunks

### ISSUE THREAD

**Issue by g3gg0** [Amulet-Team/Amulet-Map-Editor#566]
## Bug Report
Converting a 1.18.10 map to another 1.18.10 map causes weird artifacts on ungenerated chunks.

Story:
I had a map where I had kind of a defective ender dragon - I spawned it, I killed it but still the audio and the block-deleting effect was still flying around and chasing me.
There was no chance to kill it, as there was no entity associated. Also killing all entities did not stop that sound, air swirl and block deleting.
Using amulet I could "convert" it and the buggy effect disappeared as it seemingly only copies block data and proper entities.
Great tool, thanks.

### Current Behaviour:
However when flying a bit away from the already explored area, where chunks seem to generate when flying towards,
there are weird artifacts, like if their seed was different from the block next to it.
So you have huge walls of sand or stone, depending on the biome. Or huge holes in the ground, chunk-sized.

### Steps To Reproduce:
open map, selected a random other map and started conversion.
fly 30s around and see those weird chunks.

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.18.10
- Amulet Version: v0.8.18

### Screenshots
![grafik](https://user-images.githubusercontent.com/479231/153729529-a0983deb-629f-446b-9819-7c208c07fddc.png)

Is this reproducible for anyone?
If not, i will try to upload the map.

**Comment by gentlegiantJGC** [comment]
presumably the seed is different in the two worlds which means the world generation is different.
One side is the terrain converted from the other world and the other side is terrain generated in the new world.
If you want them to match you will need to make a new world with the same seed as the source world.

**Comment by g3gg0** [comment]
thanks a lot!

**Comment by g3gg0** [comment]
confirmed. saved into a world with the correct seed and deleted generated chunks.
thanks for your help.

recommendation - warn about seed mismatch:

"**Warning:** you are about to save your current world into a wold file with a different seed (or different seeding algorithm).
If you do this, explored chunks and newly generated chunks from seed will cause biome/and or landscape discrepancies."
