### ISSUE TITLE
When is this going to be officially released.

### ISSUE THREAD

**Issue by DestructiveBurn** [Amulet-Team/Amulet-Map-Editor#57]
Hi, when is this going to be officially released with a .exe for Windows.
Running from the source seems to be irritating.  Not sure if Numpy and pyglet is extensions or what.  So it would be nice if it can be compiled and released in versions like MC-Edit was.

**Comment by Podshot** [comment]
Amulet is still not fully suitable for actual use yet, so we aren't building binary executables until our first alpha release. 

If you are having issues with installing Numpy and/or pyglet (pyglet isn't currently used in our codebase, so if all other packages install, you can ignore the error message for it's installation), you can either post your error messages on this issue (we can't guarantee that we'll be able to diagnose or fix them on our end) or you can open issues on their respective repositories:

- [Numpy](https://github.com/numpy/numpy/issues)
- [pyglet](https://github.com/pyglet/pyglet/issues)

**Comment by DestructiveBurn** [comment]
> Amulet is still not fully suitable for actual use yet, so we aren't building binary executables until our first alpha release.
> 

Thanks for a reply back.   Maybe I'll wait for the Alpha release.  Is there a date you fellas have before the first release?

**Comment by Podshot** [comment]
We're hoping to have the first alpha release out this fall. We don't have an exact date yet, but we're hoping sometime in the next month to month-and-a-half.
