### ISSUE TITLE
Rendering incompatibility with 1.16 textures

### ISSUE THREAD

**Issue by Alexeijn** [Amulet-Team/Amulet-Map-Editor#57]
I tested 0.6.7, 0.6.8 and 0.6.9.
Today is 1.16 release. At time, there is no Bedrock 1.16, expected today.

I'm testing my Bedrock map, 1.14.60.5.0 

Yesterday was working perfectly.

Seems like textures codes changed on 1.16?
![image](https://user-images.githubusercontent.com/679456/85414616-b5c0c580-b542-11ea-9ebc-6b678beaab8d.png)

![image](https://user-images.githubusercontent.com/679456/85414679-ccffb300-b542-11ea-9655-23ae1db7d4f2.png)

**Comment by gentlegiantJGC** [comment]
Yeh it has downloaded the 1.16 resource pack but it seems like something went wrong.
Going to close this as it is a duplicate of #56
