### ISSUE TITLE
[Bug Report] MCBE 1.18.20.25 map cannot open

### ISSUE THREAD

**Issue by xc1984759471** [Amulet-Team/Amulet-Map-Editor#573]
It returned this error:
Unsupported level.dat version 9
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 167, in _open_world
  File "amulet_map_editor\api\framework\pages\world_page.py", line 68, in __init__
  File "amulet\level\load.py", line 28, in load_level
  File "amulet\level\load.py", line 57, in load_format
  File "amulet\level\formats\leveldb_world\format.py", line 108, in __init__
  File "amulet\level\formats\leveldb_world\format.py", line 46, in __init__
  File "amulet\level\formats\leveldb_world\format.py", line 61, in load_from
amulet.api.errors.ObjectReadError: Unsupported level.dat version 9

**Comment by gentlegiantJGC** [comment]
Which version of Amulet are you using? This should be fixed in yesterday's release

**Comment by xc1984759471** [comment]
The amulet version I use is build202202200722, this map is also extracted on the mobile phone, I am using the latest beta version 1.18.20.25 on the mobile phone, but when I use Amulet to open the map archive, I got the error"Unsupport Level.dat version 9", I would like to ask if there is a plan for the latest Beta version? Or is it adapted to have the latest Beta version? Currently known the latest Beta version of the map unable to open in any old version (including 1.18 stable version
![remmina_快速连接_zjk fm20 cn:304_2022220232935](https://user-images.githubusercontent.com/53083866/154870000-42987a22-75ba-40ba-ab9e-20f0d2e17c74.png)
)

**Comment by xc1984759471** [comment]
On my phone's version:
![Screenshot_2022-02-21-07-53-15-156_com mojang minecraftpe](https://user-images.githubusercontent.com/53083866/154871334-2a7733d9-d15a-48c9-b49f-7842002e6735.jpg)

**Comment by xc1984759471** [comment]
On my phone's version:
![Screenshot_2022-02-21-07-53-15-156_com mojang minecraftpe](https://user-images.githubusercontent.com/53083866/154871334-2a7733d9-d15a-48c9-b49f-7842002e6735.jpg)

**Comment by xc1984759471** [comment]
Sorry,build202202200712

**Comment by gentlegiantJGC** [comment]
Okay I think there was an issue with our build system. I think this should be fixed in 0.8.20

**Comment by xc1984759471** [comment]
OK,it works in 0.8.20 release version.Thanks!
![remmina_快速连接_zjk fm20 cn:304_202231412217](https://user-images.githubusercontent.com/53083866/158090225-d60fbc5c-e9b8-4ea2-aa2b-90fb1633fe5f.png)
