### ISSUE TITLE
[Bug Report] Grove biome malfunction

### ISSUE THREAD

**Issue by HughLegend** [Amulet-Team/Amulet-Map-Editor#576]
## Bug Report

Setting grove biome does not behave as it should

### Current Behaviour:

Grove biome is a biome with trees covered in snow. When changing the biome of a chunk full of snowy trees, all the snow in the trees disappears.

### Expected behavior:

Snow should not melt

### Steps To Reproduce:

Change the biome of a chunk with snowy trees to grove biome

### Environment:

- OS: Windows 
- Minecraft Platform: Bedrock
- Minecraft Version:  1.18.12
- Amulet Version:  v0.8.20b0

**Comment by HughLegend** [comment]
I just noticed that the same happens with cold taiga biome

**Comment by gentlegiantJGC** [comment]
I am not sure what would trigger this.
This is related to #532 
This must be the game melting the snow because Amulet does not modify the blocks if you just change the biome.

**Comment by gentlegiantJGC** [comment]
I am going to close this issue and continue tracking it in #532
