### ISSUE TITLE
[Feature Request] Paste Biomes Checkbox

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#578]
### The Problem
You should be able too to preserve biomes in the selection but currently, this isn't possible with the paste tool.

### Feature Description
There should be a "paste biomes" checkbox in the paste selection feature and when checked true it would paste the saved biomes in the copied selection or schematic or construction file.

When this is checked false no biomes would be written to the selection while pasting.

When this is checked true all saved biomes would be written to the selection when pasting.

Here's a screenshot mockup of how this would be applied if implemented.
![image](https://user-images.githubusercontent.com/17806994/155888151-211c5d47-82d1-46bb-9046-4a449298c261.png)

### Alternatives
I don't have any for this particular feature idea?

### Additional context
Possible use cases include:

1. Preserving biomes from world to world by deleting the blocks and only copying the biomes.
2. Pasting structures while preserving the biome in the structure or in the existing selection.
3. Overlaying multiple biome layers in 3D/2D space.

**Comment by gentlegiantJGC** [comment]
I would like to implement this but I need to do some more work on our biome handling to better support both 2d and 3d biomes

**Comment by StealthyExpertX** [comment]
Yeah, I figured just thought it best to make a feature request on it so it can be tracked.

**Comment by gentlegiantJGC** [comment]
Just realised this duplicates #241
