### ISSUE TITLE
Missing texture block for Scafolding blocks

### ISSUE THREAD

**Issue by Alexeijn** [Amulet-Team/Amulet-Map-Editor#58]
Well, this bug was in 0.6.7, I think, and continues on 0.6.9.1. That load bug was present before 1.16 texture updates and now too.

Scafolding hovering air texture is loading as "Missing texture block."

![image](https://user-images.githubusercontent.com/679456/85476055-b7fc4180-b58d-11ea-9d33-db95c7f48c33.png)

As you can see, all the scafolding with blocks or scafoldings above renders correctly.

**Comment by gentlegiantJGC** [comment]
Will be fixed in the next build
