### ISSUE TITLE
[Bug Report] The "Level" type should not appear in Java 1.18 worlds

### ISSUE THREAD

**Issue by erich666** [Amulet-Team/Amulet-Map-Editor#583]
### Current Behaviour:

When converting a Bedrock world to Java 1.18, the Level type is present in the 1.18 world's data. This should not be visible in 1.18 worlds (1.17 and earlier, yes). Here is what it looks like:
![image](https://user-images.githubusercontent.com/803995/156254801-18de2755-e991-4ffa-820d-ec0bd3ec1ad4.png)

### Expected behavior:

Here is a typical 1.18 world's data from one generated in Java Minecraft itself. Note there is no "Level" element:
![image](https://user-images.githubusercontent.com/803995/156254906-59ede967-61f7-4ea9-a6ec-1d32a7a3aa25.png)

Note how xPos and zPos are also available in this file - in the Amulet version, these values are instead tucked into "Level".

### Steps To Reproduce:

Convert an .mcworld to 1.18. I cannot provide one - this problem was reported to me by a user, so I cannot pass on his world data.

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.18
- Amulet Version:  0.8.19

### Additional context

A user reported it - I did not take time to attempt to reproduce the problem. He said he used the latest Amulet for conversion.

**Comment by erich666** [comment]
I've put the original Bedrock world and the 1.18 Java conversion Amulet made here: https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/AmuletBug583/ , with the creator's permission.

**Comment by erich666** [comment]
Drat, this bug is still open - I was hoping to delete my test files from my site. Hope you can look at this one someday.

**Comment by gentlegiantJGC** [comment]
I know why this is happening but I haven't gotten around to fixing it.
I have downloaded the files and put them on our google drive if you want to delete them from your website.
