### ISSUE TITLE
[Bug Report] 1.17.1 - 1.12.2 Java conversion issue

### ISSUE THREAD

**Issue by WizzardLeDgenT** [Amulet-Team/Amulet-Map-Editor#586]
### Current Behaviour:

My 1.17.1 world converted to the 1.12.2 version. Amulet Editor shows that the world has been converted, but in Minecraft, you cannot see any blocks at the same coordinates.
### Expected behavior:

We should see blocks in the 1.12.2 version like on Amulet Editor.
### Steps To Reproduce:

1. Download the map (see attachments) in your "saves" file, load some chunks and write down some coordinates
2. Open a 1.12.2 world.
3. Open Amulet Editor and take as an input world the Mineopolis Modern City and as the output the void world.
4. Convert and take a look at the map with the coordinates you wrote down before. (look in Amulet Editor and in Minecraft)
### Environment:

- OS: Windows 10
- Minecraft Platform: Java 
- Minecraft Version:  1.17.2 / 1.12.2
- Amulet Version:  Amulet-v0.9.0a2-Windows-x64

## Attachments

City world: https://www.planetminecraft.com/project/mineopolis-modern-city/
### Worlds

1.12.2 World after being converted: https://www.dropbox.com/sh/pc3wno3n55qc0dy/AADemGT-dW5r96IxG6KgerPOa?dl=1
These coordinates may help you to understand: 334 100 -63

**Comment by gentlegiantJGC** [comment]
You will need to convert the world again.
