### ISSUE TITLE
[Feature Request] Search Function

### ISSUE THREAD

**Issue by prototype464** [Amulet-Team/Amulet-Map-Editor#587]
### The Problem
Trying to search for certain things in a world file is not currently possible, as you can only view / edit worlds.

### Feature Description
Add a function that would allow you to search for blocks in a world (I.E. signs or chests)

### Alternatives
No known alternatives.

### Additional context
That's pretty much it!

**Comment by gentlegiantJGC** [comment]
duplicate of #320
