### ISSUE TITLE
[Bug Report] Amulet purges information in jigsaws when operating in the same chunk

### ISSUE THREAD

**Issue by GentlemanRevvnar** [Amulet-Team/Amulet-Map-Editor#588]
## Bug Report

Amulet purges information stored in jigsaw blocks when modifying a chunk

### Current Behaviour

Using replace function in a chunk to modify blocks, and then saving the changes deletes the information stored in jigsaw blocks

### Expected behavior:

Jigsaw blocks to remember their data

### Steps To Reproduce:

Place two jigsaws in separete chunks, made a midification of an area using amulet, save changes, return to the game. See that one jigsaw forgot it's informations. Better presented in screenshots below

### Environment:
- OS: Windows 10 64bit
- Minecraft Platform: Java Edition
- Minecraft Version: 1.18.2 vanilla
- Amulet Version: v0.8.20 Windows x64

### Additional context
...

## Attachments
...

### Screenshots

Place jigsaws in separate chunks.
![2022-03-05_18 30 31](https://user-images.githubusercontent.com/100436143/156894248-3b8782dc-dbd8-4f91-a57a-ad94a91047b7.png)

I will select the iron blocks, and replace them with glass
![Zrzut ekranu 2022-03-05 183122](https://user-images.githubusercontent.com/100436143/156894282-647ad7ba-4553-4d91-bcf2-32f384d92883.png)

![Zrzut ekranu 2022-03-05 183219](https://user-images.githubusercontent.com/100436143/156894297-1206c884-0b94-4693-909e-2ad3823ae48f.png)

After saving the changes, i return to the world and see that the jigsaw in the same chunk forgets it's information.

![2022-03-05_18 32 55](https://user-images.githubusercontent.com/100436143/156894330-52cf642f-2b78-4dce-b409-b215a9b67d44.png)

### Worlds
...

**Comment by gentlegiantJGC** [comment]
I have just fixed this. It will be in a future release.
