### ISSUE TITLE
[Feature Request] Missing blocks addition

### ISSUE THREAD

**Issue by HughLegend** [Amulet-Team/Amulet-Map-Editor#591]
### The Problem

Blocks such as coarse dirt, leaves or trees logs are not included on amulet.

### Feature Description

Some blocks can not be found when, for example, replacing blocks. I dont know if there are others, those are the ones I have noticed that are missing.

### Alternatives

Adding those blocks

**Comment by gentlegiantJGC** [comment]
Which version format are you using the pick the blocks in?
Those blocks should exist but they may be a state of another block.

**Comment by HughLegend** [comment]
I'm using native 1.18.0 and it's on bedrock.
Should I use a different one?

**Comment by gentlegiantJGC** [comment]
Looking at the wiki
- coarse dirt is a state of dirt
- logs are `log` and `log2` and states of those two blocks
- leaves are the same as logs
