### ISSUE TITLE
[Bug Report] Rotation

### ISSUE THREAD

**Issue by Zhargon** [Amulet-Team/Amulet-Map-Editor#599]
Hallo Amulett-Team.

Das Tool ist ja nicht schlecht, aber leider gibt es es bei der Rotation erhebliche Fehler, egal welchen Rotations-Grad man benutzt, die Blöcke (egal welche Blöcke) werden nicht richtig rotiert, so das die Blöcke falsch stehen und platziert werden. Hier liegt ein schwerwiegender Bug vor. Bitte um baldige Behebung, da man die Rotation so nicht nutzen kann.

**Comment by gentlegiantJGC** [comment]
Duplicate of #74 
Please use the search tool before opening a new issue.
