### ISSUE TITLE
amuletmc.com/readme Spelling Error

### ISSUE THREAD

**Issue by tgifford** [Amulet-Team/Amulet-Map-Editor#601]
### Current Behaviour:

Stated on https://www.amuletmc.com/readme

We do not expect Amulet to corrupt any worlds but please create **coppies** before editing them.

### Expected behavior:

Stated on https://www.amuletmc.com/readme

We do not expect Amulet to corrupt any worlds but please create **copies** before editing them.

### Steps To Reproduce:

1. Access Amulet homepage at https://www.amuletmc.com/ in web browser of choice (chrome)
2. Click "Read before downloading" link, URL address https://www.amuletmc.com/readme
3. Read carefully
4. Notice misspelling of "coppies"
5. Lose sleep
6. Lose mind
7. Have stroke
8. Fill out bug report on Github

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version: 
OS: Windows
Browser: Chrome

### Additional context

Context is "Amulet" homepage.  Please forward on to whomever maintains the site.

**Comment by gentlegiantJGC** [comment]
thanks
