### ISSUE TITLE
[Bug Report] ERROR: Could not build wheels for amulet-nbt For WIndows OS

### ISSUE THREAD

**Issue by TheAndersMan** [Amulet-Team/Amulet-Map-Editor#603]
### Current Behaviour:

Amulet can not install on windows OS due to wheels error

### Environment:

- OS: Windows
- Minecraft Platform: N/A
- Minecraft Version: N/A
- Amulet Version: 8.2.0

**Comment by gentlegiantJGC** [comment]
We would need the actual error do debug the issue.

**Comment by gentlegiantJGC** [comment]
I am going to close this due to inactivity. If you have more information please comment and open the issue again
