### ISSUE TITLE
[Bug Report] Paper server chunk error

### ISSUE THREAD

**Issue by 11Den11xz00** [Amulet-Team/Amulet-Map-Editor#608]
### Current Behaviour:
When installing the schematics using amulet on the server map,  involved chunks become damaged

### Expected behavior:
amulet will not damage chunks

### Environment:
- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.18.1 (server core: puprpur)
- Amulet Version: all before 0.8.17

### Additional context
where the schematics were installed with help of an amulet, chunks are broken, in their place territory is re-generated

### Screenshots
![Снимок экрана (175)](https://user-images.githubusercontent.com/34819905/159285747-5aa0e895-89e1-4139-92c2-14630a09907a.png)

### Worlds
maps 1.17(1)

**Comment by gentlegiantJGC** [comment]
Does the same issue happen with a vanilla server?

**Comment by gentlegiantJGC** [comment]
I have just tested editing a world with paper and purpur servers and I was not able to reproduce this issue.
I tested Purpur-1.18.2-1623 and Paper-1.18.2-333
Is this still an issue with the the latest version of Amulet and Purpur?
If so can you provide the version of the Purpur server you are using and a schematic you imported that caused the error.
