### ISSUE TITLE
[Bug Report] when installing schematics using an amulet, data of chests and spawners is absent

### ISSUE THREAD

**Issue by 11Den11xz00** [Amulet-Team/Amulet-Map-Editor#609]
### Current Behaviour:
when installing schematics using an amulet, data of chess and spawners is absent

### Expected behavior:
there should be loot in chests, and necessary mobs in spawners

### Steps To Reproduce:
1. installing schematics
2. I go to map
3. there is no loot

### Environment:
- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.17 - 1.18+
- Amulet Version: since version 0.8.17

### Additional context
schematics were done on 1.12.2

### Worlds
maps 1.17 - 1.18+

**Comment by gentlegiantJGC** [comment]
Duplicates #155 and #171
