### ISSUE TITLE
[Bug Report] empty superflat chunks become regular biomes

### ISSUE THREAD

**Issue by Viggo2** [Amulet-Team/Amulet-Map-Editor#610]
### Current Behaviour:

Empty chunks in my bedrock superflat world become regular Java biomes on conversion, leading to a massive stone wall on the edge of a regular world at the edge of my city world - like the screenshot.
### Expected behavior:

All of the superflat world looks exactly like, or mostly similar to, my previous Bedrock city world.
### Steps To Reproduce:

1. Open Amulet editor, open bedrock world in it, select Java world as output.
2. Convert it to Java.
3. Open it in Java.
4. Find an empty chunk.
### Environment:

- OS: Windows 11
- Minecraft Platform: Bedrock, converting to Java
- Minecraft Version: 1.18.12 (Bedrock), 1.18.2 (Java)
- Amulet Version: 0.8.20

### Screenshots

![image](https://user-images.githubusercontent.com/65341832/159559530-66766e74-7ba1-4b67-b4d5-7e980c5f85db.png)

**Comment by gentlegiantJGC** [comment]
The converter only converts existing chunks. The rest will be generated by the game.
If you want a superflat world you will need to make a superflat world in Java to convert into.
#460 suggests adding an option to copy seed so perhaps we will also add an option to copy the generator.
