### ISSUE TITLE
[Feature Request] Better Inspection panel

### ISSUE THREAD

**Issue by WORMSS** [Amulet-Team/Amulet-Map-Editor#612]
### The Problem
Kinda like a Feature Request / Bug.. 
If you try to inspect a Spawner, there just isn't enough space to get to see all the information.

![image](https://user-images.githubusercontent.com/1384537/160111712-1d310e42-e77d-4d4c-aea7-cd3d87a2af74.png)

### Feature Description
Some type of panel to open to view all all?

### Alternatives
Format the information so it can fit and scroll on the popup

### Additional context
Same for Chests would be nice.

**Comment by gentlegiantJGC** [comment]
see #112
