### ISSUE TITLE
[Bug Report] Paste button on bottom bar doesnt work

### ISSUE THREAD

**Issue by cole00cole00** [Amulet-Team/Amulet-Map-Editor#618]
### Current Behaviour:
Clicking the Paste button down the bottom of the screen after copying a selection only brings up greyed out paste menu

### Expected behavior:
Paste function should start working same as if you clicked the paste button in sidebar
### Steps To Reproduce:
1.Select an area
2.Click copy
3. Click paste button at the bottom of the screen

### Environment:

- OS: Windows 10
- Minecraft Platform: Bedrock
- Minecraft Version: 1.18
- Amulet Version: Nightly 0.9.0b1.dev202203310714 
### Additional context
It has never worked since I started in amulet the other week, I have had a bunch of versions now,

**Comment by gentlegiantJGC** [comment]
This will be fixed in 0.10
