### ISSUE TITLE
[Bug Report] Purple Move Point button moves point without keypresses

### ISSUE THREAD

**Issue by cole00cole00** [Amulet-Team/Amulet-Map-Editor#619]
### Current Behaviour:
When clicking on the purple move point button when making a selection it sometimes start running away from the camera without the user touching any keyboard keys
### Expected behavior:
The purple move point button does not move on its own and it well behaved like the green one.

### Steps To Reproduce:
1. make a selection using mouse
2. adjust the corners using the move point button
3. move camera around with right click held, or accidentally double clicking
4. use the purple move point button again and sometimes it moves alone and you have to use wsad/shift/space to fight with it

### Environment:

- OS: Windows 10
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version:  1.18.0 
- Amulet Version: Nightly 0.9.0b1.dev202203310714

### Additional context
this happened rarely in in 0.90a, and would behave once any key was pressed but in this latest version once it starts running it does it consistently. I can try figure how to record my screen if someone cannot reproduce.

**Comment by gentlegiantJGC** [comment]
Could you get a video to explain.
Can you also fill in the title

**Comment by cole00cole00** [comment]
> Could you get a video to explain. Can you also fill in the title

Ok i will do it tomorrow. Sorry i missed the title box.
