### ISSUE TITLE
[BUILD] tiff.h missing build error for wxPython on M1 Macs

### ISSUE THREAD

**Issue by jkrauska** [Amulet-Team/Amulet-Map-Editor#622]
### Current Behaviour:

Unable to build wxpython during pip install.
error:

imagtiff.cpp:37:14: fatal error: 'tiff.h' file not found
          #include "tiff.h"

Workaround:
CXXFLAGS=-I/opt/homebrew/include  python3 -m pip install amulet-map-editor==0.9.0b0 --upgrade

### Expected behavior:

pip install works

### Environment:

- OS: MacOS
- Amulet Version:  all tried

**Comment by gentlegiantJGC** [comment]
wxPython is a UI library not created or managed by us. We just use it.
You would need to report this to them for it to get fixed.

**Comment by ViRb3** [comment]
You have an issue with your include path. Check #597 for full step-by-step.
