### ISSUE TITLE
OpenGL 3.0 or later is not supported by the OpenGL driver.

### ISSUE THREAD

**Issue by Winter2055** [Amulet-Team/Amulet-Map-Editor#628]
Minecraft Bedrock
Windows 10
HP Laptop
![16492645088201531668968161275268](https://user-images.githubusercontent.com/103137037/162028726-4118650c-ac99-4988-a721-5002c2a652ae.jpg)
![1649264533546403959630911623765](https://user-images.githubusercontent.com/103137037/162028770-3a47d114-3ab2-462a-aa39-30fbef14d3e0.jpg)
![16492645542467783446574442897376](https://user-images.githubusercontent.com/103137037/162028848-8178ef8d-514d-4ca0-9d90-7f1f0564c991.jpg)

**Comment by gentlegiantJGC** [comment]
This might be fixed by #678

**Comment by Protype1** [comment]
how was the issue resolved i myself have run into the same issue and would like to fix if possible

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/174932505-87924546-23e4-4d78-a6e6-6987974a05de.png)
Encounted with the same problem in newest release version

**Comment by yqs112358** [comment]
Version 0.9.6

**Comment by gentlegiantJGC** [comment]
@Protype1 @yqs112358 are you still getting this issue in 0.10?

**Comment by Protype1** [comment]
I'm honestly not sure, I ended up upgrading my GPU to something much stronger and it worked just fine, Xbox no longer allows for content transfer so unfortunately I haven't been able to use the program as I intended
    On Sunday, October 2, 2022 at 02:05:52 a.m. PDT, gentlegiantJGC ***@***.***> wrote:  
 
 


@Protype1 @yqs112358 are you still getting this issue in 0.10?
