### ISSUE TITLE
Error installing wxPython on linux

### ISSUE THREAD

**Issue by katamari1992** [Amulet-Team/Amulet-Map-Editor#629]
Been trying to install any minecraft editor for the last day none will work for me I don't know what I haven't done
tried following the instructions here https://www.amuletmc.com/installing-from-source
and I get this error [https://justpaste.it/825yz](url)

**Comment by gentlegiantJGC** [comment]
Have you tried installing one of these?
https://extras.wxpython.org/wxPython4/extras/linux/

**Comment by gentlegiantJGC** [comment]
I am going to close this because it is an issue with wxpython and not Amulet
