### ISSUE TITLE
[Bug Report] Amulet cannot read nbt data schematic

### ISSUE THREAD

**Issue by 11Den11xz00** [Amulet-Team/Amulet-Map-Editor#630]
## Bug Report
Please report one issue per report.
If you have multiple issues then open another report.
### Current Behaviour:
- Amulet cannot read nbt data in chematic

### Expected behavior:
- working schematics

### Steps To Reproduce:
1. add a schematic to map with of an amulet
2. save
3. data of chests and spawners are not transferred (null)

### Environment:
- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.18+
- Amulet Version: 0.9.0

**Comment by gentlegiantJGC** [comment]
We do not yet support items or entities.
See #171 and #155
