### ISSUE TITLE
[Bug Report] Void Chunks On Conversion

### ISSUE THREAD

**Issue by TheKidThatCodes** [Amulet-Team/Amulet-Map-Editor#644]
### Current Behaviour:

So I got a bedrock 1.18.12 world and converted it to java 1.18.2
when i opened it, it had void chunks that had not been generated in bedrock
i tried to delete the empty chunks in amulet and regen them on my fabric server and on my client
they kept generating as void chunks
### Expected behavior:

the chunks would be filled in with java generation (chunk borders may be visible but doesn't matter for me), not all air (and no bedrock)
### Steps To Reproduce:

make bedrock world
close bedrock
open world in amulet
convert to mc java world
open in mc java
see to your dismay that void chunks replace any chunks that you did not generate in bedrock edition
### Environment:

- OS: MacOS 12, Python 3.9.1
- Minecraft Platform: Java and Bedrock
- Minecraft Version: Java 1.18.2, Bedrock 1.18.12
- Amulet Version: 0.9.0 

### Additional context
Does a fabric server and geysermc affect the world?
if so, that explains this

### Screenshots

Ignore my client side mods
![2022-04-15_13 11 22](https://user-images.githubusercontent.com/78447517/163602033-aecd6e22-61a6-4e45-9338-6984c4fea2c0.png)

**Comment by gentlegiantJGC** [comment]
Does the same issue happen with a vanilla client?

**Comment by gentlegiantJGC** [comment]
What are the chunk generator settings of the Java world you are converting into?
Are you converting into a void world?
