### ISSUE TITLE
[Bug Report] Crashed during conversion

### ISSUE THREAD

**Issue by jrodr10** [Amulet-Team/Amulet-Map-Editor#651]
### Current Behaviour:

did not finish convert only half the spawn is there
### Expected behavior:

full convert of Java 1.18.x world to Bedrock 1.18.30 world
### Environment:

- OS: Windows 
- Minecraft Platform: Java | Bedrock 
- Minecraft Version: 
- Amulet Version: Latest

**Comment by gentlegiantJGC** [comment]
Are there any bugs in the console?
Which version of Amulet are you using?

**Comment by gentlegiantJGC** [comment]
I think this is a duplicate of #563
