### ISSUE TITLE
Blocked space after destruction block on the copied part of the map

### ISSUE THREAD

**Issue by Viandar** [Amulet-Team/Amulet-Map-Editor#652]
Moved the building between worlds, game version 1.16.5, amulet version 0.9.2, win10. After the destruction of the block (the one that was copied) on the copied part of the map, the place that remains after it is blocked and it is impossible to put a new block on it, but I can pour liquids and, for example, use lava and water to create obsidian there, but destroying the obsidian does not unlock the place and it is still impossible to put any block there. Perhaps someone faced such a problem. How to unlock space.

**Comment by gentlegiantJGC** [comment]
Can you share a world this issue exists in.
Java 1.16.5? Is this world modded?
You copied a building from one world to another. Both Java 1.16.5?
You destroyed a copied block in game or in Amulet?
What was the block that you broke?
You can't place a block at the location but you can create blocks at the location by pouring liquids.
Does the issue persist after closing the world and opening it again?

If I had to guess there is an entity at that location which is stopping you from being able to place a block.
