### ISSUE TITLE
[Bug Report] Import errors to bedrock

### ISSUE THREAD

**Issue by Henka2** [Amulet-Team/Amulet-Map-Editor#655]
### Current Behaviour:

Running release V0.9.2
When importing structures to Bedrock worlds, some entities do not appear correct:
* Signs
* Chests ( orientation and connection/large chests)
* Doors

Problem seems similar to this old bug (closed) : https://github.com/Amulet-Team/Amulet-Map-Editor/issues/18 

### Expected behavior:

* Signs should have same text as when exported
* Chests should connect as when exported
* Doors should be placed as when exported

### Steps To Reproduce:

1. Create a world in java with a sign with text, a large ("double") chest and a few doors
2. Export as .construction
3. Import .construction in a bedrock world

### Environment:

- OS: Windows (client)
- Minecraft Platform: Java & Bedrock ( bug at least present from java to bedrock
- Minecraft Version: 1.18.31
- Amulet Version: 0.9.2

### Additional context

Bug https://github.com/Amulet-Team/Amulet-Map-Editor/issues/18  mentions that:
"I believe I added this in one of the last builds however there are some issues with NBT (eg chest connection in Bedrock)"

**Comment by gentlegiantJGC** [comment]
You are exporting an area of a Java world and exporting to a construction file.
Which Java edition version are you using?
Which format are you exporting to in the construction file? (bedrock/java and version number)

**Comment by gentlegiantJGC** [comment]
I have just tried reproducing this with the steps you provided and it worked as intended.
Can you please provide the details in my previous message and some screenshots of the issues.

**Comment by Henka2** [comment]
After testing this some more with various exports and imports, it seems like everything is working properly.
Seems I was using some old .construction files (from 2021) that caused the errors I reported, when doing new exports and imports everything seems very much in order. Closing this issue and sorry for the trouble. Great work on the editor :)
