### ISSUE TITLE
[Bug Report] Chunks disappeared

### ISSUE THREAD

**Issue by MERRYACS** [Amulet-Team/Amulet-Map-Editor#672]
Bug Report:
After editing the map I saved it and run it on 1.12.2 Client. The chunks which edited was disappeared.
and there is no crash report/error report
I did the same step and run it on 1.14 client, Chunks wasn't disappear. 

Amulet Version:
I tried both Release 0.9.2 and Beta 0.9.3b0, having the same problems

Screenshot:
![image](https://user-images.githubusercontent.com/17223128/167680787-4bae748c-c2ea-4664-b31f-d78bd9fad533.png)

**Comment by MERRYACS** [comment]
![ezgif-1-af4d900639](https://user-images.githubusercontent.com/17223128/167976272-7fba2249-08fa-4b8a-8672-ef80beb6f689.gif)

**Comment by MERRYACS** [comment]
![ezgif-1-618c329846](https://user-images.githubusercontent.com/17223128/167976316-4353a94c-ab58-48db-9c4b-d7f432aec5a2.gif)

**Comment by MERRYACS** [comment]
I can't upload map, it too big, 300mb and github only allow me to upload anything less than 10mb

**Comment by MERRYACS** [comment]
https://mega.nz/folder/YZkRXCZY#7VbART2NkZXLOB73mVZXig
I upload it on mega

**Comment by gentlegiantJGC** [comment]
You need to close the world in Amulet before opening in game.
I will have a look at the world save

**Comment by gentlegiantJGC** [comment]
Sorry I thought this issue was fixed in 0.9.3b0 but I have just realised it was not included.
0.9.3b1 should fix it.

**Comment by MERRYACS** [comment]
This issue was fixed in beta 0.9.3b1. Thanks!
