### ISSUE TITLE
[Bug Report] Set Biome operation not affecting blocks below y:0 and above y:256

### ISSUE THREAD

**Issue by Codubreku** [Amulet-Team/Amulet-Map-Editor#683]
## Bug Report

When I use the Set Biome operation, Blocks below Y level 0 and above y level 256 are unchanged.
### Current Behaviour:

Using the Set Biome operation does not affect any blocks below y:0 nor any above y:256. Both methods of selection, Box and Column, are affected by this bug.
### Expected behavior:

When I use the Set Biome operation, all blocks selected within the box, or contained within the selected columns, are changed by the operation; including those below y:0 and above y:256.
### Steps To Reproduce:

1. Select an area you wish to change the biome of.
2. Press ALT while hovering over a block in the selected area to see it's biome information.
3. Repeat Step 2 with a block below level y:0
4. Repeat Step 2 with a block above y:256
5. Click the operation button, and select 'Set Biome' from the drop-down menu. Make sure Selected Column is the current selection method.
6. Select a biome in the list to be one that does not match what the blocks in steps 2, 3 & 4 had.
7. Execute the operation.
8. Repeat Steps 2, 3 & 4 after the operation. 

Tested and reproduced with 2 different worlds from completely separate projects.

### Environment:

- OS: Windows 10
- Minecraft Platform: Bedrock
- Minecraft Version:  1.18.31 (World data version 1.18.31.4.0)
- Amulet Version:  V0.9.2

### Additional context

Issue seems to be limited to only block heights added with 1.18, (-1 - -64) & (257 - 320). I would be not surprised if this would also affect bedrock worlds with custom world heights that go beyond the 1.18 world height bounds. If this is behavior enforced by vanilla MC, apologies for wasting your time.

### Screenshots

-Before-
Above Ground
![Before1](https://user-images.githubusercontent.com/66836049/168633302-2b4756aa-ba9f-4373-92e4-65dc32fbe8d5.png)
Below ground
![Before2](https://user-images.githubusercontent.com/66836049/168633316-b73b3e4d-8aa1-474c-8d02-52085a3790ef.png)
Below 0
![Before3](https://user-images.githubusercontent.com/66836049/168633330-f3539f55-c8ef-4e99-8096-068be0ae0858.png)
Above 256
![Before4](https://user-images.githubusercontent.com/66836049/168634553-f3ae51ed-f39c-40da-b423-c16513c2697c.png)
After (Blocks viewed were not the same, but were in the same area affected.)
Above ground
![After1](https://user-images.githubusercontent.com/66836049/168633385-fb227e4a-25ca-495a-a88f-97f5998e3d33.png)
Below ground
![After2](https://user-images.githubusercontent.com/66836049/168633392-cac20768-8c42-42f4-9efd-9081157c4c0a.png)
Below 0
![After3](https://user-images.githubusercontent.com/66836049/168633414-f398c0a8-3f11-4e78-af9a-603c5e4bf604.png)
Above 256
![After4](https://user-images.githubusercontent.com/66836049/168634592-b074dc96-6f91-456a-a2cb-be3c25d2cb04.png)

**Comment by gentlegiantJGC** [comment]
Is it possible to change the world height in Bedrock? I thought this was only a feature in Java edition.

**Comment by gentlegiantJGC** [comment]
I am able to reproduce this issue. I am probably not accounting for the world height.
