### ISSUE TITLE
[Bug Report] Converting a world past Java 1.12 turns the top half of double tall plants into large ferns

### ISSUE THREAD

**Issue by axollyon** [Amulet-Team/Amulet-Map-Editor#696]
### Current Behaviour:
When using the Convert tab in Amulet to upgrade a Java 1.12 world to a post-flattening version, the top block of all vanilla double tall plants are mistakenly given the `fern` plant type.

### Expected behavior:
The plant type of the top block should match what it was previously, as well as matching its lower half.

### Steps To Reproduce:
1. Create a world in 1.12.2
2. Create a world in any version past 1.12.2 (in my case, 1.16.5)
3. Open the 1.12.2 world in Amulet
4. Use the Convert tool to overwrite the 1.16.5 world
5. View any double tall plant in the 3D Editor or ingame

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.12.2, 1.16.5
- Amulet Version: V0.9.2

### Screenshots
![image](https://user-images.githubusercontent.com/20480418/171990157-c25bc9c9-13c1-4758-a669-d8b42791fa3d.png)
![image](https://user-images.githubusercontent.com/20480418/171990169-3586280b-41ea-4eba-b494-45d08829c6d1.png)

**Comment by gentlegiantJGC** [comment]
Thanks. Looks like I programmed it wrong.
This is one of those blocks where the top block data is not fully defined.
It depends on the block below it to get the material.
