### ISSUE TITLE
[Bug Report] Redstone not displayed in 3d-editor

### ISSUE THREAD

**Issue by erstervonelf** [Amulet-Team/Amulet-Map-Editor#699]
### Current Behaviour:

In current status, redstone dust wasn´t showing up on blocks and generally in the world
### Expected behavior:

I expected that it would show up, if I would reload the world, but It didn´t
### Steps To Reproduce:

1. Go to 'Amulet Main Menu'
3. Click on 'Open World' **(Please open a world where you´ve built redstone constructions!)**
4. Click on '3D-Editor'
5. Go to a point in the world, where you´ve placed redstone dust in the past
6. See error, redstone dust isn´t showing up actually

### Environment:

- OS: Windows
- Minecraft Platform: Java 
- Minecraft Version: 1.18.2
- Amulet Version: 0.9.3

### Additional context

In the version before, 0.9.3b1, no redstone dust displaying problems were showing up.
Since 0.9.3 (no beta), no redstone is showing up. I think the Minecraft 1.19 optimization of Amulet Editor is causing problems on older versions of Minecraft, like 1.18.2, eventually.

**Comment by erstervonelf** [comment]
> ## Bug Report
> ### Current Behaviour:
> In current status, redstone dust wasn´t showing up on blocks and generally in the world
> 
> ### Expected behavior:
> I expected that it would show up, if I would reload the world, but It didn´t
> 
> ### Steps To Reproduce:
> 1. Go to 'Amulet Main Menu'
> 2. Click on 'Open World' **(Please open a world where you´ve built redstone constructions!)**
> 3. Click on '3D-Editor'
> 4. Go to a point in the world, where you´ve placed redstone dust in the past
> 5. See error, redstone dust isn´t showing up actually
> 
> ### Environment:
> * OS: Windows
> * Minecraft Platform: Java
> * Minecraft Version: 1.18.2
> * Amulet Version: 0.9.3
> 
> ### Additional context
> In the version before, 0.9.3b1, no redstone dust displaying problems were showing up. Since 0.9.3 (no beta), no redstone is showing up. I think the Minecraft 1.19 optimization of Amulet Editor is causing problems on older versions of Minecraft, like 1.18.2, eventually.
> 
> ## Attachments
> ### Screenshots
![image](https://user-images.githubusercontent.com/78137780/172438230-deb8428e-d66a-41d0-a402-cdf83f43902d.png)

> ### Worlds
[Experimental Binary.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8855071/Experimental.Binary.zip)

**Comment by gentlegiantJGC** [comment]
If you press alt while hovering on a block that should be redstone does it say that it is redstone?
Just wondering if it is a translation issue or a rendering issue.
