### ISSUE TITLE
Simplify folder structure

### ISSUE THREAD

**Issue by fennectech** [Amulet-Team/Amulet-Map-Editor#701]
We should rename amulet_app.exe to _amulet_app.exe to bring it to the top of the list when sorting by name   
![image](https://user-images.githubusercontent.com/11953665/172498380-dd7cd8d0-2f37-4ea7-8842-cc9cfd807b8d.png)

**Comment by gentlegiantJGC** [comment]
I understand your point but in programming a proceeding underscore is usually used to indicate that something is private.
Perhaps we could move the actual code down a directory and add a shortcut to make it easier.

**Comment by fennectech** [comment]
That would work too!

**Comment by gentlegiantJGC** [comment]
The correct solution to this is to have a proper installer so that the files are more hidden from the user and it can be opened by a shortcut.
That is something that we plan to add.

**Comment by fennectech** [comment]
if you do that than an update mechinism is also necessary
