### ISSUE TITLE
[Feature Request] Add auto not in use Actorprefix removing? to fix MCPE-155283.

### ISSUE THREAD

**Issue by gtr3qq** [Amulet-Team/Amulet-Map-Editor#702]
### The Problem

  In the update 1.18.30, Microsoft introduced New method for Actor Storage in Minecraft: Bedrock Edition (https://docs.microsoft.com/en-us/minecraft/creator/documents/actorstorage) , which look cool on paper. 
But as time went by , i realised that the Actorprefix data **_don't get cleaned up. The "actorprefix"  and the NBT data that is stored under them are left behind and don't ever get removed after entities are killed or despawned. Thousands are left dangling outside any chunk pointer key ( digp ) wasting space. They may have forgotten a  clean-up function for the expired entities,_** as tradition. (https://bugs.mojang.com/browse/MCPE-155283) Leaving the dummy data and the problem to the community.

### Feature Description

A BUTTON to say good bye to all unused Actorprefix keys.

### Alternatives

A MCC Toolchest-alike GUI to edit LevelDB. Or a plugin will do.

### Additional context

It really shouldn't be much of a problem for normal use, as the bug report talked **_left dangling outside any chunk pointer key ( digp )_**,so not loaded, **_With compression this does not actually amount to much data_**, "usually" don't take up much space.
However, as **_gentlegiantJGC_** stated **_I can see this becoming an issue at scale on servers with lots of users._**

Being an Admin in Zirconium Networks, I CAN confirm that gentle's vision is becoming a reality. With total users of 400+ daily 20+, the VPS1 save file boom from only 800 ish megs ,to a whopping 1.66 GIGABITE. nearly two times of data in just three mouths, while on 1.18.30 .31 .32 .33 of course. VPS2 maneuvered over this bug by starting a new world.

At the beginning , i thought I was some player doing something unholy, but I quickly discover there are over 800mb of dummy in the save file that are confirmed not chunks not pendingticks maps portals or **entities**(entities i can access normally that is). So I kinda un-ziped it with aumlet-core lib. And lord and behold, there are over  9793989  keys in whats left of the levelDB. I didn't dare to continue inflate, but I eye-ball it that there were only a few Kilo keys are not actorprefix.(A sample is possible...later...if needed.)

  I then ask about in undisclosed places, I wasn't the only one. One admin gimme his server save file, i punged it, it also have 200mb of  
 dummy. Some admins just give in, start agin. One said **_just delete the dummy .ldb files._** I do not know how much he/she knows about LevelDB, but I can almost see what he/she meant is to do a chemo on it, then hope for the best.

Knowing the fact, that a save file will drag down system preformece if grow over 1 gigabyte (some said 4gigabyte is the point you can notice) due to the way save file is mounted in game vastly different from Anvil. The negative effect of this can spread wide if M$ don't patch it. And they didn't in 1.19 or the next version, that s two more mouths for this to brew.

After which, I found the bugreport Dan Martin (PremiereHell) and gentlegiantJGC submitted. Where he stated **_do I need to remove these manually?_** implies such function could be achived. Hence the Feature Request.

Sadly,I can not register a jaire account to upvote or contact Mr.Martin himself for this. But I do know he and gentle is in amulet project. Hence why I choose to submit here. Pls,dont hurt me. QwQ.

**Comment by gtr3qq** [comment]
@gentlegiantJGC

**Comment by gentlegiantJGC** [comment]
Hi, yes I thought this might become an issue.

**Comment by gtr3qq** [comment]
> Hi, yes I thought this might become an issue.

would you like a sample via google drive?

**Comment by PREMIEREHELL** [comment]
I will add a button to the EntitiesPlugin to delete all dead/unlinked entities within the dimension.

**Comment by gtr3qq** [comment]
> I will add a button to the EntitiesPlugin to delete all dead/unlinked entities within the dimension.
Awsome! Thank you! should close this or let admin do it?

**Comment by PREMIEREHELL** [comment]
its now added https://github.com/PREMIEREHELL/Amulet-Plugins/blob/main/EntitiePlugin.py

**Comment by gtr3qq** [comment]
> its now added https://github.com/PREMIEREHELL/Amulet-Plugins/blob/main/EntitiePlugin.py

OMG, I was expecting days before i can here any update! Thank you so so much！
