### ISSUE TITLE
[Bug Report] Hanging mangrove propagule does not convert properly

### ISSUE THREAD

**Issue by YeSheepMan** [Amulet-Team/Amulet-Map-Editor#703]
### Current Behaviour:
When converting a Java world with a hanging propagule to Bedrock, the propagule turn into the "update!" block and are labeled "unknown". When converting a Bedrock world with a hanging propagule to Java, the propagule disappears entirely. Interestingly enough, this only affects the hanging variant.
### Expected behavior:
When converting a Java world with a hanging propagule to Bedrock, the propagule should appear. When converting a Bedrock world with a hanging propagule, the propagule should appear.
### Steps To Reproduce:
1. Go to a Java world and grow a mangrove tree with hanging propagules.
2. Then convert the world to Bedrock.
3. Load the Bedrock world.
4. See error.
---
1. Go to a Bedrock world and grow a mangrove tree with hanging propagules.
2. Then convert the world to Java.
3. Load the Java world.
4. See error.

### Environment:
- OS: Windows 10
- Minecraft Platform: Java | Bedrock
- Minecraft Version: Java 22w15a - Bedrock 1.19.0
- Amulet Version: Amulet V0.9.3

### Screenshots
I think it is pretty self explanatory
### Worlds
[1_19 Pano.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8865140/1_19.Pano.zip)
[1.19 Pano Transfer.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8865141/1.19.Pano.Transfer.zip)

**Comment by gentlegiantJGC** [comment]
I think they have changed the block specification since the last beta I had access to.
Irritatingly I can't see how to export the full block palette from the full release of the game.

**Comment by YeSheepMan** [comment]
Thanks bro
