### ISSUE TITLE
Fabric Worlds Reported as Forge

### ISSUE THREAD

**Issue by Avakining** [Amulet-Team/Amulet-Map-Editor#71]
Any modded world, whether Forge or not, is reported as being Forge. This includes worlds created/loaded in a [Fabric](https://fabricmc.net/) version (which is still modded). 

I'd recommend changing the Forge message to saying 'Modded' instead.

**Comment by gentlegiantJGC** [comment]
The forge support is very temporary. It just checks if the FML key exists which it sounds like it must for that world

**Comment by gentlegiantJGC** [comment]
Do you have a level.dat file from one of these worlds I can take a look at

**Comment by gentlegiantJGC** [comment]
I think this was just an issue with the forge checking code. Should be fixed now.
Although there are probably other issues that stop Amulet working with the world if it is modded
