### ISSUE TITLE
Slab block state errors

### ISSUE THREAD

**Issue by ScottyDog10** [Amulet-Team/Amulet-Map-Editor#711]
### Current Behaviour:
Several blocks not being rendered.

### Expected behaviour:
The blocks should be appearing

### Steps To Reproduce:
1. Load amulet editor

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.19.0.5.0
- Amulet Version: 0.9.4

### Screenshots
![image](https://user-images.githubusercontent.com/107417351/173375432-31d69c15-3656-4048-a656-fb504cf442fe.png)
![image](https://user-images.githubusercontent.com/107417351/173375483-a9dc6251-245d-4694-9f17-c69b9b3ad0a8.png)

### Worlds

https://drive.google.com/file/d/1VTYRHehdP3zJ9S4ZaYq84bjLQ42j06L8/view?usp=sharing

**Comment by gentlegiantJGC** [comment]
Looks like they changed the block state for slabs.
