### ISSUE TITLE
[Bug Report] internalComponents was not valid for actor b'actorprefix\x00\x00\x01\xf0\x00\x01\xa4\xfe'. Skipping.

### ISSUE THREAD

**Issue by yqs112358** [Amulet-Team/Amulet-Map-Editor#717]
## Bug Report
"internalComponents was not valid for actor b'actorprefix\x**\x**\x**\x**\x**\x**'. Skipping."
This string is printed line with line on console when i was editing my map, and it is strange that there is no any actor (aninal, mob...) can be seen and exported by editor

### Current Behaviour:
Screenshot of console:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/37969157/174976005-b80f079c-c2b5-4423-973f-d24e0ae42c18.png">

### Steps To Reproduce:
Enter a map of Bedrock 1.19 and walk around

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19
- Amulet Version: 0.9.6

**Comment by Notacod3r** [comment]
I have this in my console as well. Would be great to know what it is.

**Comment by yqs112358** [comment]
I guess that this may be related with problem about encoding (like unicode actor names?)
But this is just a speculation

**Comment by gentlegiantJGC** [comment]
Can you share a world this issue exists on so I can debug it.
I tried creating a new world and spawning some sheep but I don't get the errors.

**Comment by yqs112358** [comment]
Thanks so much! 
But since my world is so large,  I will try to spawn a more little world with the same problem and send here

**Comment by Notacod3r** [comment]
Here is a copy of my world, same issue. 
[NW4 06.20.22.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9229350/NW4.06.20.22.zip)

**Comment by gentlegiantJGC** [comment]
It looks like some actors just don't have the `internalComponents` tag that we were using to determine if the actor was an entity.
There is no documentation on this format which makes handling it rather difficult.
I have a solution but I don't know if this will cause other issues.

**Comment by Notacod3r** [comment]
I would love to delete these actors if they are causing problems to my world. 

To give you a little background on my world. It's a fresh 1.18 world. However, some schematics were imported from a world that once was on PS4 Legacy -> Updated to Bedrock -> Then transferred to PC through realms before coping the schematics over to this world through Amulet's "Construction" file
