### ISSUE TITLE
[Bug Report] Loss all BlockActor data (like chest content / sign text) when importing .mcstructure in 1.19

### ISSUE THREAD

**Issue by yqs112358** [Amulet-Team/Amulet-Map-Editor#718]
## Bug Report
When **import** a .mcstructure by amulet, all BlockActor data (like the content of chests, text on sign...) will loss. I have tested impoting .construction and it works well with no problem
Version Bedrock 1.19

### Current Behaviour:
As above. Screenshot as below
![FY5NOTMG%C5TWQ4FPQROQDX](https://user-images.githubusercontent.com/37969157/175279066-f383dcbd-9330-4a06-9ff9-7fbaa829acb1.png)

### Expected behavior:
All blocks and contents imported currectly 

### Steps To Reproduce:
1. Open a map
2. Go to 3D Editor function
3. Use 'Import'
4. Import the example .mcstructure I gave below
5. Go into the house high in the sky to see the situation

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.0
- Amulet Version: 0.9.6

## Attachments
[cywhome.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8966327/cywhome.zip)
When you import this .mcstruction directly in game by structure block, you will find everything well. But when imported by amulet all block actor data will loss

**Comment by gentlegiantJGC** [comment]
This seems to work correctly in the latest beta. Can you try and reproduce it in 0.10

**Comment by yqs112358** [comment]
Problem is fixed in newest version! Thanks a lot🥰
I will close this issue
