### ISSUE TITLE
[Feature Request] Improve the speed of closing the level

### ISSUE THREAD

**Issue by yqs112358** [Amulet-Team/Amulet-Map-Editor#719]
### The Problem
I am curious that why it takes so much time to close the world even I have done nothing but only open the map and then close it.
And I want to know that is it safe to operate the world after the console outputs "Finished saving changes to level xxxx"? Or I must wait until amulet close its UI completely and then I can copy or operate the level opened safely?

If the second is true, improvement of the speed of closing the level need to be optimized, I think, since it always takes minutes to close a world and during the time I can do nothing but wait it for finished.

### Feature Description
As above

### Additional context
![image](https://user-images.githubusercontent.com/37969157/175483270-72765fe4-ce13-4b7b-9b64-86498374d8c5.png)
"Time Left" data is not accurate, in fact.
It always takes minutes to finish.

**Comment by gentlegiantJGC** [comment]
You haven't specified if it is a Bedrock or Java world.
I am going to assume it is Bedrock. We run database compaction when closing the world which can take a little while.
We could move this to during saving or just not run it at all but the world size will grow if we don't run it.

**Comment by yqs112358** [comment]
> You haven't specified if it is a Bedrock or Java world. I am going to assume it is Bedrock. We run database compaction when closing the world which can take a little while. We could move this to during saving or just not run it at all but the world size will grow if we don't run it.

Thanks for your explanation. Yes, it is a bedrock world. 
And I just have an advice that if possible, maybe database compaction can be finished in a seperated thread after you save the chunk, as I am managing a Bedrock Delicated Server now and BDS's auto-compaction thread works like this.

This is not a serious problem in fact, I think. 😀

**Comment by gentlegiantJGC** [comment]
We have disabled the compaction step so it shouldn't do this any more.
