### ISSUE TITLE
Fill operation does not set block entity

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#723]
### Current Behaviour:
Broken behavior when getting BlockEntity data while using;
`
chunk = world.get_chunk(cx, cz, dimension).block_entities
`
It would not get the data for the chest and return an empty BlockEntity Dict in the console, my bet would be this happens with other BlockEntity data too not just the chest when the chest was set with the fill tool in an empty chunk.

The issue also seems to only happen when using the fill tool in Amulet and then try running the plugin with that code on the chest block entities but it doesn't always work 100% of the time.

### Expected behavior:
I expected `chunk = world.get_chunk(cx, cz, dimension).block_entities`
to return a chunk with block entity data and print it to the console, which it did not in some cases.

### Steps To Reproduce:
1. Load the Minecraft Bedrock (1, 19, 0) world in Amulet that I have provided below in the attachments.

2. Once loaded try using the fill tool to place the chest in a none existent chunk that is in a 2-block high stack that is also 6 blocks long and 3 blocks wide so like 6x2x3 the fill operation will set the Chest blocks and the Block Entity data you will notice the data when holding al will appear correct.

3. Now you will also notice when using the WIP template plugin provided in attachments that it returns the chunk being empty as in it doesn't contain block entity data at all, you may check this in the **Console Log.**

4. You may have to repeat this process a few times including on some grass blocks in chunks that are populated before the issue will appear.

### Environment:
- OS: Windows 10 Pro
- Minecraft Platform: Bedrock
- Minecraft Version: (1, 19, 0)
- Amulet Version: V0.9.6

### Additional context
The issue seems to only happen when using the fill operation in an empty chunk to set Chest blocks with BlockEntity data.

**These are the test results of the chests that worked fine in the console.**
`
Started loading...
Chunk(2, -6, UnboundedPartial3DArray(dtype=<class 'numpy.uint32'>, shape=(16, inf, 16)), EntityList([]), BlockEntityDict(
        (45, -60, -89):BlockEntity[universal_minecraft:chest, 45, -60, -89]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (45, -60, -88):BlockEntity[universal_minecraft:chest, 45, -60, -88]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (45, -60, -87):BlockEntity[universal_minecraft:chest, 45, -60, -87]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (46, -60, -89):BlockEntity[universal_minecraft:chest, 46, -60, -89]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (46, -60, -88):BlockEntity[universal_minecraft:chest, 46, -60, -88]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (46, -60, -87):BlockEntity[universal_minecraft:chest, 46, -60, -87]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (47, -60, -89):BlockEntity[universal_minecraft:chest, 47, -60, -89]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (47, -60, -88):BlockEntity[universal_minecraft:chest, 47, -60, -88]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
        (47, -60, -87):BlockEntity[universal_minecraft:chest, 47, -60, -87]{NBTFile("":{utags: {isMovable: 1b, Findable: 0b, Items: []}})}
))
(45, -60, -89)
(45, -60, -88)
(45, -60, -87)
(46, -60, -89)
(46, -60, -88)
(46, -60, -87)
(47, -60, -89)
(47, -60, -88)
(47, -60, -87)
Chunk loaded at (2, -6)
dict_keys([(45, -60, -89), (45, -60, -88), (45, -60, -87), (46, -60, -89), (46, -60, -88), (46, -60, -87), (47, -60, -89), (47, -60, -88), (47, -60, -87)])
minecraft:overworld
`

**Here are the results of the test I ran into the issue in the console where the test did not work.**
`
Started loading...
Chunk(3, -7, UnboundedPartial3DArray(dtype=<class 'numpy.uint32'>, shape=(16, inf, 16)), EntityList([]), BlockEntityDict(
))
Chunk loaded at (3, -7)
dict_keys([])
Started loading...
Chunk(2, -7, UnboundedPartial3DArray(dtype=<class 'numpy.uint32'>, shape=(16, inf, 16)), EntityList([]), BlockEntityDict(
))
Chunk loaded at (2, -7)
dict_keys([])
minecraft:overworld
`

## Attachments
Here's the Amulet plugin that I was using to discover the issue.
[template_plugin.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8985981/template_plugin.zip)

### Screenshots
Here's the screenshot of the chest test that worked fine.
![image](https://user-images.githubusercontent.com/17806994/175799165-ea6fb514-31fe-42a6-a252-9714e9c53245.png)

Here's the screenshot of the chest test that did not work.
![image](https://user-images.githubusercontent.com/17806994/175822168-82765186-3673-425d-861a-3c71f6b3ece8.png)

### Worlds
Here are the world files with a world with and without the world that worked.
[world_files_zipped.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8985980/world_files_zipped.zip)

**Comment by gentlegiantJGC** [comment]
The issue is that the fill operation doesn't set the block entity. Perhaps it should.
The block entity you are seeing in the `alt` bubble is from the translator pulling the default block entity.

When saving it tries accessing the block entity and when it can't find it it pulls the default value.
