### ISSUE TITLE
[Bug Report]Couldn't create OpenGL content on a virtural computer

### ISSUE THREAD

**Issue by xhm12345abcde** [Amulet-Team/Amulet-Map-Editor#724]
### Current Behaviour:

Couldn't create OpenGL content on a virtural computer
error code:
Traceback (most recent call last):
  File "OpenGL\latebind.py", line 43, in __call__
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 157, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 50, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 93, in __init__
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 58, in __init__
  File "amulet_map_editor\api\opengl\canvas\event_canvas.py", line 12, in __init__
  File "amulet_map_editor\api\opengl\canvas\canvas.py", line 47, in __init__
  File "OpenGL\latebind.py", line 47, in __call__
  File "OpenGL\wrapper.py", line 678, in wrapperCall
  File "OpenGL\wrapper.py", line 671, in wrapperCall
  File "OpenGL\platform\baseplatform.py", line 415, in __call__
  File "OpenGL\error.py", line 234, in glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
	baseOperation = glGenTextures,
	pyArgs = (
		1,
		<object object at 0x0000024D6D7D64E0>,
	),
	cArgs = (1, array([0], dtype=uint32)),
	cArguments = (1, array([0], dtype=uint32))
)

### Steps To Reproduce:

open 3d editor in a vmware virtural computer
### Environment:

- OS: Windows(vmware virtural computer)
- Minecraft Platform: Java
- Minecraft Version: 1.18
- Amulet Version: 0.9.6

### Worlds

![error](https://user-images.githubusercontent.com/106918817/175814172-d3b1fd65-aee8-433f-ae1e-7769bfe97e68.JPG)

**Comment by yqs112358** [comment]
Same problem. I have tried aumlet on my Tercent-Cloud machine and it had the same error response.
Maybe the reason is that VM environments currently used cannot restore the real graphics environment very well.

**Comment by ranchester2** [comment]
I fixed this issue by installing Mesa for Windows, this is easy now with the "OpenGL and OpenCL compatibilty pack", https://apps.microsoft.com/store/detail/opencl%E2%84%A2-and-opengl%C2%AE-compatibility-pack/9NQPSL29BFFF?hl=en-us&gl=US, which converts OpenGL to Direct3D and Windows has a good default software renderer for Direct3D, but an absolutely terrible and ancient OpenGL software renderer (another solution is to install llvmpipe, but it isn't on the Microsoft store, or use vm software which supports 3D acceleration)

**Comment by yqs112358** [comment]
> I fixed this issue by installing Mesa for Windows, this is easy now with the "OpenGL and OpenCL compatibilty pack", https://apps.microsoft.com/store/detail/opencl%E2%84%A2-and-opengl%C2%AE-compatibility-pack/9NQPSL29BFFF?hl=en-us&gl=US, which converts OpenGL to Direct3D and Windows has a good default software renderer for Direct3D, but an absolutely terrible and ancient OpenGL software renderer (another solution is to install llvmpipe, but it isn't on the Microsoft store, or use vm software which supports 3D acceleration)

Sure, this package is so convinent
But it is sad that my server is Winserver 2016, and this package is limited to Windows10 1904 or higher (server 2019).
So I tried to find OpenGL drivers for windows and then I found this pre-built Mesa3D driver: https://github.com/pal1000/mesa-dist-win

However, after installation, Amulet reports with the same problem. I'm wonder that if any extra config operation is needed to adapt Amulet to custom OpenGL Drivers on virtual machines?

**Comment by gentlegiantJGC** [comment]
@xhm12345abcde @yqs112358 
Can you please test the latest 0.10 beta.
I refactored the OpenGL code which I believe has fixed this issue.

**Comment by yqs112358** [comment]
Thanks a lot! Version 0.10b2 works well on virtual machines
<img width="688" alt="image" src="https://user-images.githubusercontent.com/37969157/187053994-84a385e2-d2b1-48ba-9f2a-973fd53b4b45.png">

**Comment by yqs112358** [comment]
Report another bug when I tested Amulet v0.10.2b: (These "name conflict")
<img width="449" alt="image" src="https://user-images.githubusercontent.com/37969157/187054041-c84616dd-016f-41ae-9ee8-85ec170c2e37.png">
And I have encounted with the same problem on my laptop. So it is not related to virtual environment, I think.
Need I to create a new Issue? @gentlegiantJGC

**Comment by gentlegiantJGC** [comment]
Good to know it is fixed finally.
I am aware of that other issue but there isn't a ticket for it. If you could open one that would be great.

**Comment by xhm12345abcde** [comment]
Thanks for fixing. it works on the virtural computer now.
