### ISSUE TITLE
[Bug Report] Program does not start.

### ISSUE THREAD

**Issue by StishStash** [Amulet-Team/Amulet-Map-Editor#730]
## Bug Report
The program does not start when I click the executable.

### Current Behaviour:
When I click the executable, the command windows opens, stays blank, and the program does not start.

### Expected behavior:
When I click the executable, the command windows opens, displays some text real quick, and the program opens.

### Steps To Reproduce:
1. Download latest version from the website.
2. Extract the zip file.
3. Click on the executable.
4. Wait for the command window to open.

### Environment:
- OS: Windows 10
- Minecraft Platform: Java installed through Curseforge/Overwolf
- Minecraft Version: 1.16.5 is the version of the map I want to edit.
- Amulet Version: 0.9.6 compiled version from the website.

### Additional context
I have two monitors hooked up to my PC. I'm only mentioning this because I know that RPG Maker MV has issues starting up with multiple monitors and I seem to be the only person in the world having that issue, so I might be the only person in the world having a similar issue with Amulet. But I want to make sure it's not user error or a bug in the program first.

### Screenshots
![image](https://user-images.githubusercontent.com/52259412/176970460-a8a7011a-7470-4bb2-805e-727ad66d1918.png)

**Comment by gentlegiantJGC** [comment]
A number of people have had this issue in the past but I have never been able to work out why it is happening.
Try following the issues listed here to see if any of them solve your issue.
https://github.com/Amulet-Team/Amulet-Map-Editor/issues/332#issuecomment-1038044943

That issue was open for a while with those instructions but no one got back to me to let me know if they worked.

**Comment by StishStash** [comment]
The second suggestion fixed it!

For future reference to everyone else: Make sure you allow it both through windows firewall and add an exception for both the exe and the program folder as a whole in your anti-virus.
