### ISSUE TITLE
[Bug Report] Amulet truncates world chunks using Bedrock 1.18 and 1.19 support for custom heights within the range y=-512 to y=511

### ISSUE THREAD

**Issue by abrightmoore** [Amulet-Team/Amulet-Map-Editor#733]
## Bug Report
Amulet truncates world chunks using Bedrock 1.18 and 1.19 support for custom heights within the range y=-512 to y=511

### Current Behaviour:
Amulet ignores blocks set above and below what appears to be an internal chunk limit (y=-64 to y=319)

### Expected behavior:
Amulet should on setting a block at an arbitrary y position:
1. Allocate subchunks where not present, and
2. Persist the subchunk when saving

### Steps To Reproduce:
1. Configure a vanilla world for custom height range y=-512 to y=511. Use a small Behavior Pack as described here: https://docs.microsoft.com/en-us/minecraft/creator/documents/datadrivenoverworldheight
2. In Amulet 0.9.6 use an Operation to place blocks throughout this range. I drew a sphere shell of diameter 1024
3. Save the edited world
4. Exit and explore the world in game, and note that the sphere has its top and bottom missing

### Environment:
- OS: Windows 11
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.19.2 (and earlier to 1.18)
- Amulet Version: 0.9.6

### Additional context
Discord chat: https://discordapp.com/channels/324647192583340043/992280219387957268/992280221342507070
Contact me for sample BP and world.

**Comment by StealthyExpertX** [comment]
I can add, that I'm also being affected by this in some of the worlds that I have in development and will have to wait until this issue has been resolved.

**Comment by gentlegiantJGC** [comment]
There really is very little documentation on this feature. I can't even find a Minecraft wiki page for it.
Is it possible to change the height of other dimensions?
Is it possible to change the generator type to the default? (That page says that only `dimension_bounds` is changable)

**Comment by gentlegiantJGC** [comment]
It looks like it only supports the overworld.
From the exe `currently only "minecraft:overworld" is supported by behavior pack dimension data`
I may implement support for all dimensions just so I don't have to edit too much in the future.

**Comment by gentlegiantJGC** [comment]
I think the data is encoded into the database in `LevelChunkMetaDataDictionary` so I don't need to parse the resource pack to get this data.
The format is a bit odd though. It is NBT packed into a list but there are 8 bytes for each entry that I have no idea the format of.

**Comment by gentlegiantJGC** [comment]
The 8 bytes is a key for the level settings that is stored in the chunk key `?`

**Comment by gentlegiantJGC** [comment]
I think as you have found Amulet's code will load all sub-chunks regardless of where they are.
The issue is that it only saves chunks within the "buildable region" which is currently hard coded.
As I said before there is a key in the chunk that points to a value in LevelChunkMetaDataDictionary.
I will experiment to see if that key is actually required.
The simple solution here is to load LevelChunkMetaDataDictionary and find the minimum and maximum y coordinates and use that as the bounds.

**Comment by gentlegiantJGC** [comment]
The game seems happy with the extra chunks even if Amulet doesn't write the extra chunk data.

**Comment by gentlegiantJGC** [comment]
@abrightmoore @StealthyExpertX I think that should fix this. Please can you try it out and report back.

**Comment by abrightmoore** [comment]
I'll need to run from source to test. Apologies if this takes some time to allocate a window to setup and test...

**Comment by gentlegiantJGC** [comment]
I am going to merge this for the next release. Let me know if there are any issues
