### ISSUE TITLE
Buffer or Chunk Range World Load Option.

### ISSUE THREAD

**Issue by PREMIEREHELL** [Amulet-Team/Amulet-Map-Editor#738]
Feature Request
The Problem
Large worlds are very slow. about 1GB or bigger

Feature Description
     A setting to select a range of chunks to load and ignore the rest with an option to refresh the range.

Alternatives
     Instead of loading everything grab the needed resources at load time for the renderer, and load in the chunks directly from the save as needed based on the render distance.

**Comment by Zackhq** [comment]
Yea I myself am having this issue with my own big world and I don't have the greatest PC around, would 100% love this customization to speed the process up.

**Comment by gentlegiantJGC** [comment]
The real solution for this is to add a less memory heavy mesh generator for further away chunks.
This is tracked in #193

**Comment by PREMIEREHELL** [comment]
> The real solution for this is to add a less memory heavy mesh generator for further away chunks. This is tracked in #193

You have explained to me that amulet Loads the entire world file. this really has nothing to do with render distance, this would make a 3 GB world load as fast as a 10MB world if you manually set what was loaded. And you could make it so the render distance builds the list of loading chunks.  and Im 100% sure this is possible.

**Comment by PREMIEREHELL** [comment]
I guess I will just make a plugin that does it.
