### ISSUE TITLE
[Bug Report] Build from source fails on latest macOS

### ISSUE THREAD

**Issue by EthanZeigler** [Amulet-Team/Amulet-Map-Editor#740]
## Bug Report
Building from source fails on macOS 12.4 and python 3.10.5. This may be an upstream issue but wanted to make a report of the problem here since it renders the package unusable.

### Current Behaviour:
Building from source fails in wxpython.

### Expected behavior:
Building from source works

### Steps To Reproduce:
1. run `python -m pip install amulet-map-editor==0.9.6 --upgrade` in a clean venv

### Environment:

- OS: macOS 12.4
- Minecraft Platform: N/A
- Minecraft Version: N/A
- Amulet Version: 0.9.6

### Additional context
N/A

## Attachments
[build log (gist)](https://gist.github.com/EthanZeigler/53e537a173a6749fcc9f0fb2d23ebd0f)
### Screenshots
N/A

### Worlds
N/A

**Comment by gentlegiantJGC** [comment]
Please use Python 3.7-3.9.
Wxpython is a third party library out of our control

**Comment by EthanZeigler** [comment]
You may want to note on the readme that the range is 3.7-3.9. It only says 3.7+ at the moment which is misleading.

**Comment by gentlegiantJGC** [comment]
I must have updated the website but not the readme
