### ISSUE TITLE
[BUG ONLY BEDROCK EDITION] Chunks do not load properly when opening Amulet.

### ISSUE THREAD

**Issue by merrysc23** [Amulet-Team/Amulet-Map-Editor#746]
Has this bug been reported yet? Check if there is already a bug report open that matches this.
Nothing specifically for minecraft bedrock edition.

describe the mistake
When loading a world of minecraft bedrock, the already loaded chunks are not appreciated, but in the game they already are, thus being the Amulet problem, which does not load the already loaded chunks and only considers them as if it were "Chunks not loaded"" or ""New Chunks""

To play
Load a pre-populated world, mine is specifically a world where I explore everything around me. Enter Amulet and you will see that although you have explored many chunks, some appear as if they are new or there is nothing there.

expected behavior
When a world is loaded, I expect everything to load completely, however this problem only happens in Bedrock Edition but not in Java, only BEDROCK, I have already tried all versions.

Captures
MY VIDEO sorry my english i'm peruvian :(

Desk (please complete the following information):
Operating system: Windows 10
Version 21H2 Windows-x64

https://user-images.githubusercontent.com/109096641/179286224-3e0734da-5fef-49f2-84af-4fd2f3b1fc00.mp4

**Comment by merrysc23** [comment]
Maybe it's not very important, but recently I had a problem that when importing a build in one of those empty chunk places, automatically my build was imported but with an empty chunk next to it...

**Comment by merrysc23** [comment]
The problem with this error is that when you want to import a build and it is close to that unloaded chunk, it is automatically imported but with an EMPTY CHUNKS NEAR.

**Comment by gentlegiantJGC** [comment]
From our FAQ page
![image](https://user-images.githubusercontent.com/11940194/179346467-e96b3705-8366-4481-82bd-01b5836fdd7e.png)

**Comment by gentlegiantJGC** [comment]
If you have placed blocks in the chunks that are not rendered then let me know.
If this is a marketplace world then see #721

**Comment by merrysc23** [comment]
> Si ha colocado bloques en los fragmentos que no se representan, hágamelo saber. Si este es un mundo de mercado entonces vea [el #721](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/721)

When placing blocks it is solved, but hopefully it is like java that you can see everything :(, it stresses me out a lot to see it like this

**Comment by gentlegiantJGC** [comment]
It isn't a bug. We can only display the chunks that exist on disk.
Bedrock just doesn't save all chunks.
