### ISSUE TITLE
[Feature Request] Add selection size amount number

### ISSUE THREAD

**Issue by Josh65-2201** [Amulet-Team/Amulet-Map-Editor#747]
### The Problem

Currently when selecting large amounts of chunks/block i have to manualy count them.

### Feature Description

Add a number on the size representing x,y,z showing the size of block/chunks.

**Comment by gentlegiantJGC** [comment]
In the select tool there is a label in the menu on the left showing the shape of the current selection.
We could expand that information.
I would like the ability to export the selection information to text for easy importing later. I think there is already a ticket open for that but we could add more information along with that.

**Comment by Josh65-2201** [comment]
it doesnt show for the chunk selection mode and it would be nice to show the size as its beeing dragged also

**Comment by gentlegiantJGC** [comment]
I have added a label showing the volume of the active box.
