### ISSUE TITLE
[gui-concern] [cixon] Blacked out buttons.

### ISSUE THREAD

**Issue by Cixon** [Amulet-Team/Amulet-Map-Editor#750]
I cannot see the buttons.
### Screenshots

![Screenshot (39)](https://user-images.githubusercontent.com/69068153/179432321-06b29203-3dae-4a5c-88b3-c0b5d7e5ad86.png)

**Comment by gentlegiantJGC** [comment]
Looks like a similar issue to #127 
Can you try out the demo example here to see if it works.
https://github.com/Amulet-Team/Amulet-Map-Editor/issues/127#issuecomment-907820305

We are in the process of switching to a different UI library that should fix these issues.

**Comment by Cixon** [comment]
updating windows .NET Framework fixed the issue.
