### ISSUE TITLE
[Bug Report] Java to Bedrock converted Maps severely disrupted by chunk errors 

### ISSUE THREAD

**Issue by McMeddon** [Amulet-Team/Amulet-Map-Editor#751]
### Current Behaviour:

Rendering Vanilla Chunks within any custom worldpainter world

Bedrock Area https://cdn.discordapp.com/attachments/271345875584942080/998649587055214612/Minecraft_7_18_2022_7_54_10_PM.png?width=943&height=530

### Expected behavior:

Java Original Area: https://cdn.discordapp.com/attachments/271345875584942080/998649623994450010/2022-07-18_19.56.31.png?width=966&height=512

### Steps To Reproduce:

- Exported in Worldpainter: 2.10.13
- played map in java
- created new  map in Bedrock: 1.19.10
- converted to new created bedrock map in Amulet v0.9.6
- started bedrock map, 
- tada chunk errors

### Environment:

- OS: Windows 
- Minecraft Platform:  Java / Bedrock 
- Minecraft Version:  Java1.19 /  Bedrock1.19.10
- Amulet Version: v0.9.6 and earlier .9 versions

## Attachments

- World DL: https://drive.google.com/drive/folders/1fUZnjZUU-UhzZbdNf4L63Ycer6L4G9f_?usp=sharing

### Screenshots

Bedrock Area: https://cdn.discordapp.com/attachments/271345875584942080/998649587055214612/Minecraft_7_18_2022_7_54_10_PM.png?width=943&height=530

Java Original Area: https://cdn.discordapp.com/attachments/271345875584942080/998649623994450010/2022-07-18_19.56.31.png?width=966&height=512

### Worlds

- Coordinates ca: 700, 900
- Original Java World DL: https://drive.google.com/drive/folders/1fUZnjZUU-UhzZbdNf4L63Ycer6L4G9f_?usp=sharing

**Comment by gentlegiantJGC** [comment]
Thanks for pointing this out.
It was an issue loading biomes from the Java world.

**Comment by McMeddon** [comment]
![image](https://user-images.githubusercontent.com/62025134/189493619-16ff3d25-c223-4a15-8b24-bc7437d3acc7.png)

still an issue  in 0.10.0 :(

saw in the cmd window, that it had once issues converting (waterlogged?) mangrove leaves with [distance=1-5]

**Comment by gentlegiantJGC** [comment]
The original issue is about a bug loading a chunk from a Java world which I believe has been fixed.
The new screenshot looks like a new issue. Please open a new ticket with the relevant information for me to debug.
