### ISSUE TITLE
[Bug Report] Java to Bedrock converted maps dont convert ores within custom terrain

### ISSUE THREAD

**Issue by McMeddon** [Amulet-Team/Amulet-Map-Editor#752]
### Current Behaviour:

Amulet removes generated ores on any custom worldpainter world

Bedrock Area https://cdn.discordapp.com/attachments/271345875584942080/998649587394936862/Minecraft_7_18_2022_7_35_14_PM.png?width=943&height=530

### Expected behavior:

Keeping generated ores in place
Java Original Area: https://cdn.discordapp.com/attachments/271345875584942080/998649624896208976/2022-07-18_19.43.20.png

### Steps To Reproduce:

- Exported in Worldpainter: 2.10.13
- played map in java
- created new  map in Bedrock: 1.19.10
- converted java map to the new created bedrock map in Amulet v0.9.6
- started bedrock map, 
- resut: no ores in the terrain
- quirk: ores within assets i created did get converted (?!)

### Environment:

- OS: Windows 
- Minecraft Platform:  Java / Bedrock 
- Minecraft Version:  Java1.19 /  Bedrock1.19.10
- Amulet Version: v0.9.6 and in earlier 0.9. versions

### Screenshots

Bedrock Area https://cdn.discordapp.com/attachments/271345875584942080/998649587394936862/Minecraft_7_18_2022_7_35_14_PM.png?width=943&height=530

Keeping generated ores in place
Java Original Area: https://cdn.discordapp.com/attachments/271345875584942080/998649624896208976/2022-07-18_19.43.20.png

### Worlds

- Coordinates ca: 700, 900
- Original Java World DL: https://drive.google.com/drive/folders/1fUZnjZUU-UhzZbdNf4L63Ycer6L4G9f_?usp=sharing

**Comment by gentlegiantJGC** [comment]
My assumption of what is happening here is that world painter isn't actually generating the ores but setting the chunk state to partially generated so that the next time it is visited in game the game will generate the ores.
I will need to look to see if it is possible to copy this data across to Bedrock.

**Comment by McMeddon** [comment]
-oh right! One of the options in worldpainter is to "let Minecraft populate the terrain" to gain the benefits of "decorated" lush/dripstone caves, and more. 

thanks for the answer and thanks for the amazing work on amulet

**Comment by McMeddon** [comment]
- Seems to be fixed

in conversions with Amulet 0.10.x ores seem to be placed again :) 
![Minecraft 9_11_2022 1_27_22 PM](https://user-images.githubusercontent.com/62025134/189524949-88f785ac-ab8b-4b54-9ab8-f452ea35f46d.png)
