### ISSUE TITLE
v0.10.0b1 - Copying a chest removes its content. Copying a sign removes its text. Banners become black if any edits are done near them.

### ISSUE THREAD

**Issue by Notacod3r** [Amulet-Team/Amulet-Map-Editor#762]
Hi, 

Major issues with this new release sadly. Copying a chest removes its content. Copying a sign removes its text. Banners become black if any edits are done near them in Amulet. 

### Current Behaviour:
- Copied a chest with content. When I pasted the chest no longer had items. 
- Copied a sign with text. After pasting the text is gone. 
- Copied and pasted a chest near an existing banner in the world. Saved. When I open Minecraft the banner is now black color. This was tried with other banners elsewhere and it happened as well.

### Expected behavior:
- Chest should have its content copied over.
- Signs should have their text copied over.
- Banners should keep their pattern without turning black.

### Steps To Reproduce:

1. Go to any chest and try copy paste. Same with signs. 
2. Copy and paste a chest near a banner to turn it black.

### Environment:

- OS: Windows 
- Minecraft Platform: Bedrock
- Minecraft Version: Latest to date.
- Amulet Version: v0.10.0b1 

### Worlds

[NW4 06.20.22.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9229341/NW4.06.20.22.zip)

**Comment by gentlegiantJGC** [comment]
I have just updated your report with a template to fill out to give us the details that we need.
Please edit your post  to fill in the details.

**Comment by Notacod3r** [comment]
Done.

**Comment by lizishu666** [comment]
海晶灯有时会消失
Sea lanterns sometimes disappear

**Comment by gentlegiantJGC** [comment]
This was due to a bug in the new NBT library. Thanks for pointing it out.
I think sea lanterns are a different issue that I will look into.
