### ISSUE TITLE
10.0a4 - 10.0b1  Not Garbing block entity data.

### ISSUE THREAD

**Issue by PREMIEREHELL** [Amulet-Team/Amulet-Map-Editor#763]
### Current Behaviour:
You can not copy Block entity data. 
The API has lost access to the Items array.

### Expected behavior:
Access to Block Entities Items Data.
Ability to copy All Block entity data

Appears to only affect Bedrock.

**Comment by gentlegiantJGC** [comment]
Probably a duplicate of #762 
I will put out a beta with this fix now.
