### ISSUE TITLE
The NBT of command block is missing(in regard to `.mcstructure`)

### ISSUE THREAD

**Issue by Happy2018new** [Amulet-Team/Amulet-Map-Editor#767]
When you export a `.mcstructure` with a command block, you'll notice that the NBT named `conditionalMode` is missing from the `.mcstructure`.
Because of this problem, the command block is unconditional forever after loading the `.mcstructure`.

Platform: Windows 11

**Comment by Happy2018new** [comment]
Supplementary: The platform is `Minecraft Bedrock Edition`

**Comment by gentlegiantJGC** [comment]
Is this still an issue in 0.10?
I just tried placing two command blocks in game and setting one to conditional and then exporting them both in Amulet to an mcstructure file and then importing them again.
Inspecting them in game the values are as expected.

**Comment by Happy2018new** [comment]
This issue may have been fixed by accident.
Because that, I can't trigger this Bug again now.
