### ISSUE TITLE
[Bug Report] Noteblocks don't work properly when importing schematics.

### ISSUE THREAD

**Issue by wowdabug** [Amulet-Team/Amulet-Map-Editor#768]
## Bug Report
Please report one issue per report.
If you have multiple issues then open another report.
### Current Behaviour:
Noteblocks are all the same note.

### Expected behavior:
The noteblocks should not all be the same note.

### Steps To Reproduce:
1. Import a schematic with noteblocks in it.
2. See error

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.19.11
- Amulet Version: 0.9.6 This can be found in the top left corner of the editor.

**Comment by gentlegiantJGC** [comment]
Which version of Amulet are you using?

**Comment by gentlegiantJGC** [comment]
Just realised you had put most of your report in comments so I couldn't see it. I have edited it to show it correctly.

**Comment by gentlegiantJGC** [comment]
@WowDaBug I have tried exporting a group of noteblocks from Amulet to schematic and schem formats and reimporting both of them and the note was correct.

Please can you provide some more details and a file that I can import to see the issue.
