### ISSUE TITLE
CPU Cores

### ISSUE THREAD

**Issue by centuryx476** [Amulet-Team/Amulet-Map-Editor#771]
Is there a way to use more than one core when converting a bedrock world to java world ? 
My bedrock world is nearly 2GB in size. So any speed can help me out...
Thank You

**Comment by gentlegiantJGC** [comment]
We use numpy where possible that is able to use multiple cores but python as a while is only able to use a single core.

**Comment by minestargate** [comment]
> We use numpy where possible that is able to use multiple cores but python as a while is only able to use a single core.

How am I going to do that? Please give me a simple tutorial
