### ISSUE TITLE
[Bug Report] The world dont load

### ISSUE THREAD

**Issue by KEIVID** [Amulet-Team/Amulet-Map-Editor#772]
in bedrock version, I export the map but it doesn't load, it's on a blue screen
![16608499408825231883761061565135](https://user-images.githubusercontent.com/111533568/185475614-1307a069-9d4b-4095-beb9-daee590e61cf.jpg)

**Comment by gentlegiantJGC** [comment]
Is there anything to report from the console?
If it is a large world it may take a little while to load.

**Comment by KEIVID** [comment]
um mundo pesa quase 600mb, eu ja queria usar o aplicativo para diminuir esse tamanho, eu ja esperei bastante uma vez, mas vou tentar de novo, pode ser que meu notebook esteja lento também

**Comment by gentlegiantJGC** [comment]
Please can you try with a small world to see if it is an issue with the world size or if there is a different issue.

**Comment by kontho** [comment]
![屏幕截图 2022-09-03 000548](https://user-images.githubusercontent.com/100288782/188203694-92373f3d-2e6b-4546-8348-4eb3fb40ed02.png)

**Comment by kontho** [comment]
java

**Comment by gentlegiantJGC** [comment]
@kontho your issue is a different issue that has been fixed in 0.10

**Comment by StealthyExpertX** [comment]
@gentlegiantJGC I am unable to use any worlds in the 0.10 latest Beta builds

Amulet refuses to load the world, it loads the texture pack which takes longer than any previous builds to compile/download not sure why this is the case in the newer builds.

The other issue which is the main one is that when it finally does download no terrain loads or structures and amulet stops responding it never loads even after 2 hours of waiting.

OS: Windows 10 Pro
Amulet Version: V0.10.0b2
World Version: [1, 19, 22, 1, 0], 1.19.22.1.0
```
INFO - PyMCTranslate Version 197
INFO - Loading level E:\Downloads\WorldName
INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Name conflict with blockshape cross_texture_green
Duplicate class name CrossGreen
Name conflict with blockshape tree
Duplicate class name Tree
Name conflict with blockshape slab_double
Duplicate class name SlabDouble
Name conflict with blockshape portal_frame
Duplicate class name PortalFrame
Name conflict with blockshape pumpkin_lit
Duplicate class name PumpkinLit
Name conflict with blockshape red_dust
Duplicate class name RedDust
Name conflict with blockshape door1
Duplicate class name Door1
Name conflict with blockshape door3
Duplicate class name Door3
Name conflict with blockshape door5
Duplicate class name Door5
Name conflict with blockshape lilypad
Duplicate class name LilyPad
Name conflict with blockshape cross_texture
Duplicate class name Cross
Name conflict with blockshape furnace_lit
Duplicate class name FurnaceLit
Name conflict with blockshape door
Duplicate class name Door
Name conflict with blockshape furnace
Duplicate class name Furnace
Name conflict with blockshape fence
Duplicate class name Fence
Name conflict with blockshape pressure_plate
Duplicate class name PressurePlate
Name conflict with blockshape ladder
Duplicate class name Ladder
Name conflict with blockshape piston_arm
Duplicate class name PistonArm
Name conflict with blockshape door6
Duplicate class name Door6
Name conflict with blockshape bubble_column
Duplicate class name BubbleColumn
Name conflict with blockshape water
Duplicate class name Water
Name conflict with blockshape vine
Duplicate class name Vine
Name conflict with blockshape repeater
Duplicate class name Repeater
Name conflict with blockshape cube
Duplicate class name Cube
Name conflict with blockshape pumpkin
Duplicate class name Pumpkin
Name conflict with blockshape pumpkin_carved
Duplicate class name PumpkinCarved
Name conflict with blockshape door2
Duplicate class name Door2
Name conflict with blockshape farmland
Duplicate class name FarmLand
Name conflict with blockshape comparator
Duplicate class name Comparator
Name conflict with blockshape double_plant
Duplicate class name DoublePlant
Name conflict with blockshape door4
Duplicate class name Door4
Name conflict with blockshape slab
Duplicate class name Slab
Name conflict with blockshape turtle_egg
Duplicate class name TurtleEgg
Name conflict with blockshape air
Duplicate class name Air
Name conflict with blockshape chest
Duplicate class name Chest
Name conflict with blockshape enchanting_table
Duplicate class name EnchantingTable
Name conflict with blockshape piston
Duplicate class name Piston
Name conflict with blockshape wall
Duplicate class name Wall
Name conflict with blockshape cross_texture0
Duplicate class name Cross0
Name conflict with blockshape greencube
Duplicate class name GreenCube
Name conflict with blockshape cake
Duplicate class name Cake
INFO - Downloading java launcher manifest file.
INFO - Finished downloading java launcher manifest file.
INFO - Downloading Java resource pack for version 1.19.2
INFO - Finished downloading Java resource pack for version 1.19.2
INFO - Creating texture atlas
INFO - Trying to pack textures into image of size 4096x4096
INFO - Successfully packed textures into an image of size 4096x4096
INFO - Finished creating texture atlas
INFO - OpenGL Version 4.6.0 NVIDIA 512.15
INFO - Finished setting up texture atlas in OpenGL
```

Console Screenshot:
![image](https://user-images.githubusercontent.com/17806994/188254279-d53a842e-210e-47ee-9e44-65095b896763.png)

World Didn't Load Screenshot:
![image](https://user-images.githubusercontent.com/17806994/188254357-33204f27-fa19-46a0-b966-54abc0772761.png)

Here's another zipped world that it happens with which is even newer.
[test.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9481744/test.zip)

**Comment by gentlegiantJGC** [comment]
@StealthyExpertX Do you have a Bedrock resource pack in Amulet's resource pack directory?
I don't get the resource pack issues with the world that you sent and it loads just fine.

**Comment by gentlegiantJGC** [comment]
I will look into the duplication issue but I don't think that is the cause of it not loading.
I will track that in #776

**Comment by gentlegiantJGC** [comment]
Yeh the duplication lines are just warnings which should not effect the behaviour of the program.
I have fixed the code and will put out a new release soon.

I still do not know what is causing it to hang.

**Comment by kontho** [comment]
Thanks, I hope it will be better

gentlegiantJGC ***@***.***> 于2022年9月5日周一 16:27写道：

**Comment by StealthyExpertX** [comment]
@gentlegiantJGC I looked seems it does exist.

![image](https://user-images.githubusercontent.com/17806994/188494951-61e94287-0926-406e-af2a-86206488391c.png)

**Comment by gentlegiantJGC** [comment]
The duplication warnings should be fixed in the latest beta but I believe that is an independent issue to this issue.
Let me know if you still experience this issue.

**Comment by Harsh555555** [comment]
I am also experiencing the same issue how can I solve

**Comment by gentlegiantJGC** [comment]
@StealthyExpertX
does the issue happen for you with all worlds or just some?
Are you able to move around in the editor?

I am going to treat this as a different issue to #793 because they have an error printed to the console and you are not.

**Comment by Harsh555555** [comment]
In all world

**Comment by Harsh555555** [comment]
I have also putted the issue

**Comment by gentlegiantJGC** [comment]
@KEIVID @StealthyExpertX 
Any new information that would let me diagnose this issue?
