### ISSUE TITLE
[Bug Report] Copy/Paste

### ISSUE THREAD

**Issue by PineappleGus** [Amulet-Team/Amulet-Map-Editor#774]
Copy feature works fine, but when it comes to pasting, it’s completely missing. I tried reinstalling program but it’s still missing.

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by PineappleGus** [comment]
![Uploading image.jpg…]()

**Comment by gentlegiantJGC** [comment]
Your image did not upload.
You have not provided enough information for me to debug the issue.
Please fill out the issue template.

**Comment by PineappleGus** [comment]
<img width="960" alt="COPY-PASTE-BUG" src="https://user-images.githubusercontent.com/112037925/188323122-28c077d4-da2e-4eff-b6f6-4a9e83d4938c.png">

There's no paste button

**Comment by gentlegiantJGC** [comment]
This has been fixed in the 0.10 beta version

**Comment by PineappleGus** [comment]
My bad, I saw that earlier shortly after posting but didn't have time to reply. Thank you!
