### ISSUE TITLE
[Bug Report] Amulet world conversion error 

### ISSUE THREAD

**Issue by username100099** [Amulet-Team/Amulet-Map-Editor#779]
### Current Behaviour:

Amulet world spams errors after conversion from bedrock to java and inventories and chests are empty.

### Expected behavior:
Amulet worlds dont spams errors after conversion from bedrock to java and inventories and chests are not empty.

### Steps To Reproduce:
convert a bedrock world to java and put it in a purpur server

### Environment:

- OS: Windows
- Minecraft Platform: bedrock
- Minecraft Version: bedrock 1.19.22 & java 1.19.2
- Amulet Version: V0.9.6

## Attachments
here is the log:
[log.txt](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9490321/log.txt)

**Comment by gentlegiantJGC** [comment]
One issue at a time please. Item conversion already has its own ticket.

It looks like a corrupted region file.

I have refactored the region management code in the latest beta so it may have been fixed.
Please can you try recreating the issue with 0.10.1
https://github.com/Amulet-Team/Amulet-Map-Editor/releases
