### ISSUE TITLE
Cant open any worlds in amulet anymore

### ISSUE THREAD

**Issue by amplifyaltitude** [Amulet-Team/Amulet-Map-Editor#780]
it worked fine yesterday i was able to open everything just fine i tried opening up a world today and attached is a picture of what popped up and wont let me edit anything or even open the world please help!!!
![Screenshot 2022-09-07 074141](https://user-images.githubusercontent.com/113028699/188870050-787b7b49-42de-405a-bc6a-a2306d9fde1b.png)

**Comment by gentlegiantJGC** [comment]
This has been fixed in the 0.10 beta versions

**Comment by amplifyaltitude** [comment]
Thank you much i was able to open my world again. just deleted original amulet and downloaded the beta .10. i appreciate the fast response as well.
