### ISSUE TITLE
[Bug Report] Memory Leak

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#783]
https://discord.com/channels/324647192583340043/498974201416253443/1018208569369296938

**Comment by Justash01** [comment]
Amulet Editor consumes an insane amount of memory when I am just in the editor, I have completed a replace operation and then left the editor the same as it, after like 20-30 minutes when I came back, I realized it was using ~43GB RAM out of my 128GB RAM

Some settings I currently have which might be worth mentioning:
- Render distance: 236
- World Size, I am not really sure about this one but the world is insanely large
- 3D Editor open with a selected area (around ~1-2 million blocks selected)

**Comment by gentlegiantJGC** [comment]
I forgot I massively increased the maximum render distance.
That is probably what did it. It will keep generating geometry until it hits the render distance.
Try reducing the render distance and see if it drops back down.
