### ISSUE TITLE
[Feature Request] Error log report button or Error log report file .txt

### ISSUE THREAD

**Issue by McMeddon** [Amulet-Team/Amulet-Map-Editor#786]
### The Problem

catching/reporting errors is hard when errors in the console zoom by during conversion of huge landscape projects (1-4gb)

### Feature Description

- Catch from the console reported "errors" or chunk failures in a .txt file for easier reporting.
- Sent error log report button
- accessible from the (main-) menu

**Comment by gentlegiantJGC** [comment]
The output log is already sent to a file in the logs directory next to the application.
I think the rest of your request is covered by #323
