### ISSUE TITLE
[Bug Report] Sculk Vein blocks have wrong direction after conversion

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#791]
## Bug Report
Sculk Veins do not convert with proper facing direction

### Current Behaviour:
When converting a build with sculk vein blocks either from java to bedrock, or bedrock to java, the sculk seems to be rotated incorrectly for some of the directions. 

### Expected behavior:
Sculk Vein blocks should keep their expected orientation after conversion.

### Steps To Reproduce:
1. Create world
2. Locate Ancient City
3. Convert world
4. Load same coordinates in destination build
5. See sculk veins in incorrect rotation

### Environment:
- OS: Windows
- Minecraft Platform: Java 1.19 | Bedrock 1.19.22
- Minecraft Version: Java 1.19 | Bedrock 1.19.22
- Amulet Version: 0.10.1

### Screenshots
![image](https://user-images.githubusercontent.com/13902631/190013494-a3be0acc-b9d7-478d-9b11-fbaecafe041f.png)
![image](https://user-images.githubusercontent.com/13902631/190013797-b55ea987-11b4-422b-bda2-e8306c1f6876.png)

**Comment by gentlegiantJGC** [comment]
Thanks for pointing this out. It is an issue in glow lichen as well.
This will be fixed in the next build.
