### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by Harsh555555** [Amulet-Team/Amulet-Map-Editor#793]
### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by Harsh555555** [comment]
![Uploading IMG_20220917_115009_512.jpg…]()

**Comment by Harsh555555** [comment]
![IMG_20220916_195217_734](https://user-images.githubusercontent.com/113535120/190843538-c5509afc-f8a9-4369-94af-3556a996bfbc.jpg)

**Comment by Harsh555555** [comment]
![IMG_20220917_115007_860](https://user-images.githubusercontent.com/113535120/190843559-f87a9c3e-3f9e-4797-a185-1baa6b3b858e.jpg)

**Comment by Harsh555555** [comment]
Pls give me solution of this

**Comment by gentlegiantJGC** [comment]
Please can you send the latest log file from the Amulet log directory.

**Comment by Harsh555555** [comment]
Ok

**Comment by Harsh555555** [comment]
i am unable to find file amulet log directory

**Comment by gentlegiantJGC** [comment]
Okay. The information that I would quite like is at the top of the console output.
Can you open Amulet to the 3D editor like you did to get this error and once it starts printing those errors go back to the main menu. That should stop it printing more errors.
Then scroll to the top in the console and send a screenshot of the start.
It should mention the OpenGL version.

Also could you share what graphics processor you have. If you don't have a dedicated GPU then send the CPU model.

**Comment by Harsh555555** [comment]
Ok

**Comment by Harsh555555** [comment]
> 
[opengl.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9613531/opengl.zip)

**Comment by Harsh555555** [comment]
Where is console output

**Comment by Harsh555555** [comment]
![Uploading Screenshot 2022-09-21 115106.jpg…]()

**Comment by Harsh555555** [comment]
![Screenshot 2022-09-21 115216](https://user-images.githubusercontent.com/113535120/191430001-6c440d02-173c-49f8-a4f9-101cdca88344.jpg)

**Comment by Harsh555555** [comment]
![Uploading Screenshot 2022-09-21 115106.jpg…]()

**Comment by Harsh555555** [comment]
> > 
> 
> [opengl.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9613531/opengl.zip)

I have send open gl file

**Comment by gentlegiantJGC** [comment]
> > 
> 
> [opengl.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9613531/opengl.zip)

This isn't what I asked for.

**Comment by gentlegiantJGC** [comment]
It should look something like this
```
INFO - PyMCTranslate Version 197
INFO - Loading level C:\Users\james_000\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\pZjmYtiIAQA=
INFO - OpenGL_accelerate module loaded
INFO - Using accelerated ArrayDatatype
INFO - Downloading java launcher manifest file.
INFO - Finished downloading java launcher manifest file.
INFO - OpenGL Version 4.6.0 NVIDIA 516.01
```

**Comment by Harsh555555** [comment]
Ok

**Comment by Harsh555555** [comment]
![Uploading IMG_20220929_091346_973.png…]()

**Comment by Harsh555555** [comment]
![Uploading IMG_20220929_091346_973.png…]()

**Comment by Harsh555555** [comment]
![IMG_20220929_091346_973](https://user-images.githubusercontent.com/113535120/192933891-7d7678a9-438f-4662-a64a-cb1c8aa61a22.png)

**Comment by Harsh555555** [comment]
Pls give solution

**Comment by gentlegiantJGC** [comment]
Amulet needs at least opengl 2.0. Try updating your graphics drivers.
If your computer is very old it may not support it.

**Comment by Harsh555555** [comment]
Do you mean it's my computer fault

**Comment by gentlegiantJGC** [comment]
Yes. Try what I suggested in my previous comment. It may fix your issue but it may not.

**Comment by smertz001** [comment]
I am having this similar issue with the World not loading.  And when I try to shutdown Amulet, the window freezes, and I have to Control-C in the terminal window to get it to shutdown.  

I was using Amulet 0.9(something) and things were working fine.  I then upgraded to 0.10.6 and the world does not load.

I'm using:
Bedrock Server: 1.19.40.02

Desktop: 
MacOS: 13.0.1
Python: 3.9.6
Amulet: 0.10.6

(Amulet) steve@Steves-Mac-Pro logs % cat amulet_99169.log
2022-12-10 09:42:51,549 - amulet.level.load - INFO - Loading level /Users/steve/Documents/Python/Amulet/worlds/Skwatch Land 5.119
2022-12-10 09:42:57,431 - OpenGL.acceleratesupport - INFO - OpenGL_accelerate module loaded
2022-12-10 09:42:57,439 - OpenGL.arrays.arraydatatype - INFO - Using accelerated ArrayDatatype
2022-12-10 09:43:00,117 - minecraft_model_reader.api.resource_pack.java.download_resources - INFO - Downloading java launcher manifest file.
2022-12-10 09:43:00,197 - minecraft_model_reader.api.resource_pack.java.download_resources - INFO - Finished downloading java launcher manifest file.
2022-12-10 09:43:01,583 - amulet_map_editor.api.opengl.canvas.canvas - INFO - OpenGL Version 2.1 ATI-4.9.48
2022-12-10 09:43:02,074 - amulet_map_editor.api.opengl.resource_pack.resource_pack - INFO - Finished setting up texture atlas in OpenGL
2022-12-10 09:43:18,781 - amulet.level.formats.leveldb_world.dimension - WARNING - Extra components found CompoundTag({})
2022-12-10 09:44:14,857 - amulet.level.formats.leveldb_world.dimension - WARNING - Extra components found CompoundTag({})
2022-12-10 09:44:15,284 - amulet.level.formats.leveldb_world.dimension - WARNING - Extra components found CompoundTag({})
2022-12-10 09:44:22,301 - amulet.level.formats.leveldb_world.dimension - WARNING - Extra components found CompoundTag({})

stdout/stderr output is in attached file, gathered with: python3 -m amulet_map_editor >amulet.debug 2>&1 

[amulet.debug.txt](https://github.com/Amulet-Team/Amulet-Map-Editor/files/10200409/amulet.debug.txt)

**Comment by gentlegiantJGC** [comment]
> I am having this similar issue with the World not loading.

That issue is being tracked in #597
