### ISSUE TITLE
[Bug Report] 'roofed_forest' biome not applied on Bedrock Edition

### ISSUE THREAD

**Issue by Marc-Phenix** [Amulet-Team/Amulet-Map-Editor#798]
## Bug Report

The operation 'set biome' doesn't work for 'roofed_forest' on a bedrock world.
### Current Behaviour:

The 'roofed_forest' biome isn't applied and the biome stay the same as prior to the 'set biome' operation.

### Expected behavior:

The 'roofed_forest' biome should be applied and should replace the biome that was into the selection prior the the 'set biome' operation.

### Steps To Reproduce:

1. Create bedrock world.
2. Open the world in Amulet.
3. Select a region and replace the biome to 'roofed_forest' with the 'set biome' command.

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.22
- Amulet Version: V0.10.1

**Comment by gentlegiantJGC** [comment]
How are you checking that the biome is not set correctly?

**Comment by gentlegiantJGC** [comment]
I have set roofed_forest in Amulet and inspecting the value in game shows the biome set correctly.

Are you expecting generation or anything visual to change when setting the biome?
The set biome operation only changes the biome value which effects things such as spawning and grass colour. It doesn't change generation in the chunk.

**Comment by Marc-Phenix** [comment]
I check if the grass has changed color after 'set biome' command. All the time, the grass color wasn't changing at all. I was only expecting a change in grass color. Can you confirm that you used 'roofed_forest' as the biome name and not 'dark_forest'.

**Comment by gentlegiantJGC** [comment]
Yes I did pick `roofed_forest`.
Can I suggest setting the biome to an obviously different colour biome and then setting back to roofed_forest to see if it changed back.

If it doesn't change can you send a screenshot of the set biome options.
Your original post does not include any info on the settings you chose in the set biome operation other than the biome name.

**Comment by unco656** [comment]
Bedrock currently has a bug where the roofed forest biome (along with a few others) does not use the correct grass colour, it is using the plains grass colour instead. It has been around since 2015. Leaf blocks will still be displayed with the correct colour though.

[](url)https://bugs.mojang.com/browse/MCPE-34936

**Comment by gentlegiantJGC** [comment]
Thanks for the info. Most likely not an issue with Amulet then.
@Marc-Phenix if you still think this is an issue please add more information.
If not this issue will automatically be closed.

**Comment by unco656** [comment]
This issue has been fixed. The Bedrock 1.19.40 changelog mentions that the Roofed Forest, Savannah Mutated and Birch Forest Biomes will use the correct grass colour. And the bug report has been marked as resolved.

[](url)https://bugs.mojang.com/browse/MCPE-34936
