### ISSUE TITLE
Lighting Issues with Reverted Biomes

### ISSUE THREAD

**Issue by Buzzbugs** [Amulet-Team/Amulet-Map-Editor#8]
https://i.imgur.com/e5yWvXf.png

Above is an error which occurs in the log occasionally during the Java 1.15 -> 1.12 process.

A biome change is not a problem, and can be easily address with other tools. However this is what these areas now look like in-game.

https://i.imgur.com/JpteqIa.png

These are the chunks that have been converted to plains by the amulet converter. There is an issue with relighting in these chunks, And I have tried adding light sources and also relighting the chunks using Mcedit to no avail.

**Comment by gentlegiantJGC** [comment]
Do you know what that biome is supposed to be? I can't find any reference to it online.
The lighting issue is a separate issue. Currently we do not recalculate lightning or heightmaps when converting but at some point in the future it will be supported.
Please can you edit your post so it only has one of the issues and open another for the other

**Comment by Buzzbugs** [comment]
The issues are both related. The chunks where this lighting error occurs are the chunks where the biomes are "Reverted".

It seems to be happening to the ocean Biome only, but can't be too sure without more extensive testing.

**Comment by gentlegiantJGC** [comment]
How do you know that the biome issue originates from that chunk?

**Comment by Buzzbugs** [comment]
Because these were ocean biomes before the conversion, and are now a plains biome after conversion.

**Comment by gentlegiantJGC** [comment]
What kind of ocean does it say it is?

**Comment by Buzzbugs** [comment]
none of the 1.13 oceans (deep ocean, frozen ocean, etc). Just 'Ocean'

**Comment by gentlegiantJGC** [comment]
That is the default value because there is currently no biome of 255.
The biome issue I am going to put down as works as intended but the lighting is interesting. It should set everything as max brightness iirc so I would expect it to look like it does on the right. Can you place blocks in both lit and unlit chunks and convert again to confirm that the converter created both

**Comment by Buzzbugs** [comment]
Do I place the blocks down in the already converted world (with the shadow bug) and then convert? Or do I have to do it on the 1.15.2 world before converting it to 1.12? Also could you please explain what you mean by the converter creating both?
