### ISSUE TITLE
[Bug Report] Bedrock World Crash After Converting to Java, Editing With Worldpainter, Converting Back to Bedrock

### ISSUE THREAD

**Issue by Catzilla2018** [Amulet-Team/Amulet-Map-Editor#805]
## Bug Report
I have a Bedrock world that I converted to Java edition to edit it with Worldpainter. Then, I converted it back to Bedrock edition. For some reason, when loading chunks around 0,0, (the area where most man-made builds are, but not all) the game crashes. I know this could be caused by probably a number of other things, but I figured I should ask here as it probably has to do with the world conversion. The edited world works completely fine in Java edition, and Bedrock only crashes when loading a certain area in the world. I know its these specific chunks because this is the second time attempting this. The first time my player-character was in a different location and I was able to move around the crash-causing chunks. Also, the chunks I believe area causing the crash were not edited with Worldpainter,

### Current Behaviour:
When loading chunks around 0,0, game crashes. 

### Expected behavior:
Game not supposed to crash

### Steps To Reproduce:
1. Load world attached
2. Game crashes immediately due to player being in crash-causing area.

### Environment:

- OS: Windows 10
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.30
- Amulet Version: 0.10.1

### Worlds
[](https://drive.google.com/drive/folders/1PNdxCjiGMLhbdz9QPA8yDIxbnRT9e3_M?usp=sharing)
https://drive.google.com/drive/folders/1PNdxCjiGMLhbdz9QPA8yDIxbnRT9e3_M?usp=sharing

**Comment by gentlegiantJGC** [comment]
I can't access the world that you have shared.
