### ISSUE TITLE
[Bug Report] LevelDB unusual size growth

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#820]
## Bug Report
Some users have reported that the size of their worlds has expanded massively after opening in Amulet.
https://discord.com/channels/324647192583340043/405249314131017730/1036383188320276590
https://discord.com/channels/324647192583340043/405249314131017730/1035962767506677872
https://discord.com/channels/324647192583340043/405249314131017730/1035588886040166500
https://discord.com/channels/324647192583340043/405249314131017730/1034815445968109630

### Current Behaviour:
The database balloons to 100-1000 times its original size when opened in Amulet/delete chunks.
This needs more information from the users that can reproduce the issue. I have not been able to reproduce it myself.

### Expected behavior:
File size should not expand uncontrollably

### Steps To Reproduce:
?

### Environment:
?

### Additional context
?

**Comment by toxiclim3** [comment]
### Steps to reproduce:
1. Open a world in amulet
2. Make any changes
3. Save world
4. Open Minecraft and see the results
Additional context: Playing on bedrock edition, have generated (but not changed) many chunks,After editing in Amulet, my world went from ~360MB to ~ 1,4GB
The world: https://drive.google.com/file/d/12Pc1dJPoOsSX-E35BwwqCtRbTiOhdzIg/view?usp=share_link

**Comment by gentlegiantJGC** [comment]
I was eventually able to reproduce the issue.
You don't actually need to modify the world you just have to have it open for a little while.
The issue was that the compression algorithm was disabled due to an issue with default arguments in Cython.
I am looking into the fix.

**Comment by terminal-cs** [comment]
dang, hope this gets a fix soon, having a 100 gb - 1 tb world folder wouldn't be very good

**Comment by gentlegiantJGC** [comment]
> dang, hope this gets a fix soon

It should be fixed in 0.10.5 that was released yesterday.
I forgot to update this ticket.
You may need to run this operation to force it to run the compression.
https://github.com/Amulet-Team/Amulet-Operations/blob/main/compress_leveldb.py
