### ISSUE TITLE
[Bug Report] .schematic files not importing

### ISSUE THREAD

**Issue by Ctave9** [Amulet-Team/Amulet-Map-Editor#823]
### Current Behaviour:
when I try to import a .schematic file using the import tool, the file imports but you can't confirm placing

### Expected behavior:
supposedly when you press confirm after positioning the build, it should work

### Steps To Reproduce:
1. Load a world
2. Press the import tool
3. Select your .schematic file
4. Press import
5. Postion and press "confirm". This comes up with an error

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.19.2
- Amulet Version: 0.9.6 python version (for some reason I can't update my version)

### Screenshots
![image](https://user-images.githubusercontent.com/83621795/199178461-7476ee5e-1a1c-4f17-924c-3795e6feecdf.png)

**Comment by gentlegiantJGC** [comment]
This issue has been fixed in the newer versions.
