### ISSUE TITLE
[Feature Request] Know how many blocks there are in total, in a selected area

### ISSUE THREAD

**Issue by mastermdc** [Amulet-Team/Amulet-Map-Editor#824]
I would recommend, that when selecting an area. We knew how many blocks there are in total in the selected area. Multiplying the value "X", with the value "Y", with the value "Z"
Kind of something like that....

![=](https://user-images.githubusercontent.com/112048485/199367210-fa2bef60-28ce-46f3-a50a-3b5e4778e127.png)

**Comment by gentlegiantJGC** [comment]
Good suggestion. Should be easy to implement.
