### ISSUE TITLE
[Bug Report] some error in Termux

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#826]
after installing Amulet in the root user, the permission denied error was fixed. now in Termux I can even open the world menu

![Screenshot_2022-11-03-13-39-35-126_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/199679517-fbb57fe0-13c2-4366-9461-8c87d6572067.jpg)

but when trying to open 3d editor, an error occurs:
![Screenshot_2022-11-03-13-40-01-228_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/199679750-032f4fdd-3f11-44dc-bc1c-f10316136ead.jpg)

Error log: [log.txt](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9926809/log.txt)

this error also occurs on my PC with lubuntu 20.04 x64

So I hope this can be fixed.

**Comment by gentlegiantJGC** [comment]
Duplicate of #449
