### ISSUE TITLE
[Bug Report] Can't save my world

### ISSUE THREAD

**Issue by alina-lag** [Amulet-Team/Amulet-Map-Editor#829]
## Bug Report
I have an issue, that when i click or use a shortcut to save the world, it doen't let me and instead says:
Exception while running operation
The lock on the object <amulet.level.formats.anvil_world.format.AnvilFormat object at 0x000001E0366B2148> has been lost. It was probably opened somewhere else.
NoneType: None
But the only program that uses this world is the amulet itself
### Current Behaviour:
I keep trying to save the world, but it keeps saying this
### Expected behavior:
I expected it to save normally
### Environment:
- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.18.2
- Amulet Version: V0.10.5
file:///C:/Users/User/YandexDisk-alineplastun/Скриншоты/2022-11-11_21-44-17.png screenshot of error

**Comment by gentlegiantJGC** [comment]
The only way this would happen is if the world has been opened somewhere else.
It may be in Minecraft, another instance of Amulet or another editing program.
Closing the world in Amulet and everywhere else and then opening in Amulet again should fix the issue.
