### ISSUE TITLE
[Bug Report] China Edition Worlds

### ISSUE THREAD

**Issue by Brick-web** [Amulet-Team/Amulet-Map-Editor#830]
Traceback (most recent call last):
  File "amulet\level\formats\leveldb_world\format.py", line 345, in _reload_world
  File "src\\leveldb\\_leveldb.pyx", line 216, in leveldb._leveldb.LevelDB.__init__
leveldb._leveldb.LevelDBEncrypted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 183, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 71, in __init__
  File "amulet\level\load.py", line 32, in load_level
  File "amulet\api\level\world.py", line 14, in __init__
  File "amulet\api\level\base_level\base_level.py", line 63, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 337, in open
  File "amulet\level\formats\leveldb_world\format.py", line 397, in _open
  File "amulet\level\formats\leveldb_world\format.py", line 382, in _reload_world
leveldb._leveldb.LevelDBException: It looks like this world is from the marketplace.
These worlds are encrypted and cannot be edited.

**Comment by gentlegiantJGC** [comment]
Is it a marketplace world?

**Comment by Brick-web** [comment]
This is minecraft Bedrock Edition

**Comment by gentlegiantJGC** [comment]
Did the world come from the Minecraft Marketplace?

**Comment by Brick-web** [comment]
no,it form the chinese WangYi mobile edition

**Comment by gentlegiantJGC** [comment]
Please share the world and I can look into it.

**Comment by Brick-web** [comment]
The size of this world file is over 25MB.How should I send it to you?

**Comment by gentlegiantJGC** [comment]
Upload it to a file sharing site like google drive or dropbox and send the link.

**Comment by Brick-web** [comment]
I'm sorry to keep you waiting for so long. Google Cloud Hard Drive is not available in China, so I have adopted other methods.
http://www.pay8.top/8iHdYjVrKQA.zip
This may take a long time to download

**Comment by gentlegiantJGC** [comment]
It looks like a very different structure to the vanilla Bedrock worlds.
We don't currently support this world format.
I will leave this open but I doubt we will ever support it.

**Comment by Brick-web** [comment]
This is the mobile version download address of NetEase's official website
Official website：https://mc.163.com/
download：https://adl.netease.com/d/g/mc/c/gwnew?type=android

**Comment by LiBohr** [comment]
I have the same problem either.

**Comment by LiBohr** [comment]
Please send me an email: 837270180@qq.com

**Comment by LiBohr** [comment]
I found how to solve the problem: https://www.bilibili.com/read/cv17910125

**Comment by Confidence1337** [comment]
用我的世界开发者启动器打开解密

**Comment by Brick-web** [comment]
> 

不行，已经试过了

**Comment by Confidence1337** [comment]
我可以解密 可以添加我的qq1058350495

**Comment by Max-RM** [comment]
> It looks like a very different structure to the vanilla Bedrock worlds. We don't currently support this world format. I will leave this open but I doubt we will ever support it.

I think it's just a world from the Marketplace analog from Netease.

Even mc china dev can't open it. 

![IMG_20221215_222654](https://user-images.githubusercontent.com/81485476/207927832-6eadcd32-6741-4cef-b518-8b607692da00.jpg)

this world is just encrypted like ordinary worlds from the Marketplace that's why amulet can't open it, but at the same time its format is exactly the same as that of a regular MCBE. I know this because Amulet supports worlds from MC china and even newer than 1.18.0 

about that link from the top that people can use MC studio to unlock worlds. not many non-Chinese people have an account from MC Studio and besides, it's illegal for regular marketplace worlds (not Chinese).

**Comment by Brick-web** [comment]
> > 它看起来像一个与原版基岩世界截然不同的结构。我们目前不支持这种全球格式。我将对此保持开放，但我怀疑我们永远不会支持它。
> 
> 我认为这只是来自网易的市场模拟的一个世界。
> 
> 即使是mc中国开发人员也无法打开它。
> 
> ![IMG_20221215_222654](https://user-images.githubusercontent.com/81485476/207927832-6eadcd32-6741-4cef-b518-8b607692da00.jpg)
> 
> 这个世界就像市场上的普通世界一样被加密，这就是为什么护身符无法打开它的原因，但同时它的格式与普通 MCBE 完全相同。我知道这一点，因为护身符支持来自 MC 中国的世界，甚至比 1.18.0 更新
> 
> 关于顶部的链接，人们可以使用MC工作室解锁世界。没有多少非中国人拥有MC Studio的帐户，此外，对于常规市场世界（不是中国人）来说，这是非法的。

我已经找到了方法，感谢你的回复

**Comment by Max-RM** [comment]
> 我已经找到了方法，感谢你的回复

I just had to inform GetlegiantJGC that this is not another world structure. this world is just blocked like the usual marketplace worlds.
