### ISSUE TITLE
Why does the concrete powder in the map turn into a wrong block after converting？

### ISSUE THREAD

**Issue by Confidence1337** [Amulet-Team/Amulet-Map-Editor#840]
### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by gentlegiantJGC** [comment]
Please can you provide more information.
What versions are you converting between?
What blocks are you using and what are they converting to?

**Comment by Confidence1337** [comment]
很抱歉让您等待了几天，我从JAVA版1.19.2 转换到 基岩版1.18.0 地图中的混凝土粉末和海晶石转换之后会变成错误的块

**Comment by gentlegiantJGC** [comment]
Concrete Powder and Prismarine
Java 1.19.2 to Bedrock 1.18.0

**Comment by gentlegiantJGC** [comment]
Which version of Amulet are you using?
I think I fixed some issues related to those blocks in a recent release.

**Comment by gentlegiantJGC** [comment]
This duplicates #788 so I will continue tracking it there.
