### ISSUE TITLE
Security in the way of downloading 10.6 Amulet

### ISSUE THREAD

**Issue by Jagermeisterme99** [Amulet-Team/Amulet-Map-Editor#842]
Would not say it's a bug but my Norton security is considering the 10.6 update a threat and deleting the files that are needed for the app to run properly. I know this seems obvious but is there any easy fix? I disabled the auto protect; is there a way I can have Norton functioning while using this version of Amulet?

**Comment by gentlegiantJGC** [comment]
Antivirus programs seem to just blanket block all python programs bundled with PyInstaller.
I don't know what settings you would need to change to let Norton allow it to run.
You can report it to Norton here: https://submit.norton.com/?type=FP
