### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by Delipan123** [Amulet-Team/Amulet-Map-Editor#844]
File "amulet_nbt/_array.pyx", line 1, in init amulet_nbt._array
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
a********@MacBook-Pro-2 ~ % 

On Mac, this error is coming back when running from source. in the terminal.

**Comment by gentlegiantJGC** [comment]
What version of Numpy do you have installed?
A stackoverflow post I found seems to suggest it is a bug in and old version of Numpy.
Try running this and try again. `pip install --upgrade numpy`
