### ISSUE TITLE
[Bug Report] Some Chunks Missing Blocks Below Y Level 0 [Bedrock 1.19.50]

### ISSUE THREAD

**Issue by HazeTheHawk13** [Amulet-Team/Amulet-Map-Editor#848]
I am using Version 1.19.50 of Bedrock Edition on Windows 11. 

Whenever I use the Select, Delete Blocks, Copy, Cut, Paste, or Operation Tool to make changes to a world and go back into game I find that some chunks, usually near where I used said tool are missing all blocks below Y Level Zero get covered with Bedrock Blocks and everything below it is gone. Multiple Chunks like the appear. I have tested this on Multiple Worlds and it is always the same Result.

![image](https://user-images.githubusercontent.com/120433465/207215981-8d27be7f-5737-4b3f-a87e-c6b128aef6aa.png)

**Comment by gentlegiantJGC** [comment]
I assume the chunks that stop at y=0 were created before 1.18.
There is a marker in the chunk if the lower terrain has been updated and we don't currently have a nice way to handle that.
The easy solution is to open the world in game before opening in Amulet and force the game to generate the terrain by placing a block in each chunk.

**Comment by gentlegiantJGC** [comment]
I am going to mark this as working as intended.
Amulet doesn't have the capacity to generate chunks as would be required to update correctly.
When converting across this border Amulet will just carry the data exactly as it is.
If you want to have an extended chunk you will need to update all the chunks before opening them in Amulet.
