### ISSUE TITLE
some optimization suggestions

### ISSUE THREAD

**Issue by Grey-Wind** [Amulet-Team/Amulet-Map-Editor#850]
### Feature Description
Change the new window of switching languages to use the drop-down bar to switch
Remove or hide the command window (the black window, I'm not sure how to describe it exactly)
Create help documents using compiled html files (.chm files)
Read the module file to support and optimize the world containing the module
I use translation software to translate part of the content. If you have any requirements, you can see the Chinese part below
将切换语言弹出新窗口改为使用下拉栏切换
去除或隐藏命令窗口(就是那个黑色窗口，我不太清楚怎么准确的描述)
使用编译的html文件制作帮助文档(.chm文件)
读取模组文件来对含有模组的世界进行支持与优化

**Comment by gentlegiantJGC** [comment]
I agree with drop down. I am prototyping a rewrite and have switched it to a drop down there.
The command window is useful to view silent errors.
We do want to improve mod support but it is low on our priorities.
