### ISSUE TITLE
No module named amulet_map_editor

### ISSUE THREAD

**Issue by Fortress937** [Amulet-Team/Amulet-Map-Editor#851]
![image](https://user-images.githubusercontent.com/119410273/208226547-d82fb575-dc4e-45c4-8076-7f10f6957eae.png)

i already installed it using python, but i cannot run it, it says that no module named amulet_map_editor.

**Comment by gentlegiantJGC** [comment]
Looks like you either haven't installed it or you have installed it with a different version of python.
You will need to use python 3.7-3.9 as the instructions say.

**Comment by Fortress937** [comment]
i use python 3.11.0

**Comment by Fortress937** [comment]
if i have to install using python 3.7-3.9 versions, that means i have to downgrade the python versions?

**Comment by Fortress937** [comment]
is there anyway to download and run without using python?

**Comment by gentlegiantJGC** [comment]
If you are using Windows you can just run the compiled version.
You can have multiple versions of python installed. You will just need to configure the command line name.

**Comment by Fortress937** [comment]
i downloaded it and which apps i should execute? in the Amulet file, there are many executable stuff, which one is used to open amulet editor?

**Comment by gentlegiantJGC** [comment]
https://www.amuletmc.com/installing-from-source

**Comment by Fortress937** [comment]
sorry for late response, looks like it was fixed, thanks
