### ISSUE TITLE
[Bug Report] Installation fails

### ISSUE THREAD

**Issue by UltraBlackLinux** [Amulet-Team/Amulet-Map-Editor#852]
## Bug Report
Trying to install this on linux via pip3 yields weird errors:
Firstly, it complained:
`ModuleNotFoundError: No module named 'attrdict'`
then, after manually installing it via pip3:
```
        File "/home/me/.local/lib/python3.10/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

### Environment:
- OS: Arch Linux (thus no aur package, since it's borked since forever)
- Amulet Version: 0.9.6 (Weirdly, I was not able to install the version mentioned on your website, only this old version is available.)

**Comment by UltraBlackLinux** [comment]
bruh. Installing python-wxpython fixed it. Janky stuff. Seems like the pip package is done for

**Comment by gentlegiantJGC** [comment]
You need a python version between 3.7 and 3.9.
