### ISSUE TITLE
c

### ISSUE THREAD

**Issue by mastermdc** [Amulet-Team/Amulet-Map-Editor#857]

**Comment by MasterDiegoCreations** [comment]
> Amulet tiene virus ![image](https://user-images.githubusercontent.com/112048485/209480311-66c8753c-795c-4f25-9a89-29f2589baccc.png) Y esto no es photoshop Si no me creen, miren



> Amulet tiene virus ![image](https://user-images.githubusercontent.com/112048485/209480311-66c8753c-795c-4f25-9a89-29f2589baccc.png) Y esto no es photoshop Si no me creen, miren
