### ISSUE TITLE
structure_block not changeable with replace command

### ISSUE THREAD

**Issue by logicsequence** [Amulet-Team/Amulet-Map-Editor#860]
Fairly simple, i have an old MC world that had some custom blocks from mods in it, it loads into Amulet fine, but many of the blocks are obviously missing. Those are easily replaced by using the bulk replace command and selecting the block by numerical ID.  However, it seems some of the old modded blocks use the ID now used for structure_blocks, and no matter how i input the block (by selecting it or by numberical ID) the replace command will not replace the structure_blocks with a new block.  The fill command will work, but it's a major pain to replace 10,000s of structure blocks in odd configurations all over the section of the map i want to use.  Any ideas?

**Comment by gentlegiantJGC** [comment]
We don't currently support versions prior to 1.12 so Amulet is assuming that those blocks are structure blocks based on the id.

Fixing this would require backdating the translator to support older versions. That is tracked in #521

**Comment by gentlegiantJGC** [comment]
I would suggest using MCEdit Unified for older worlds.

**Comment by logicsequence** [comment]
Thanks for the info!
