### ISSUE TITLE
Unable to install on Arch Linux

### ISSUE THREAD

**Issue by Android-Piepaint** [Amulet-Team/Amulet-Map-Editor#862]
I am trying to install it on Arch Linux, but it returns an error :

`[zhongli@zhongli-workstation amulet-map-editor-0.10.7]$ python -m pip install amulet-map-editor --upgrade`
`Defaulting to user installation because normal site-packages is not writeable`
`Collecting amulet-map-editor`
  `Using cached amulet_map_editor-0.9.6-py3-none-any.whl (1.7 MB)`
`Collecting wxPython~=4.1`
  `Using cached wxPython-4.2.0.tar.gz (71.0 MB)`
  `Preparing metadata (setup.py) ... error`
 ` error: subprocess-exited-with-error`
  
  `× python setup.py egg_info did not run successfully.`
  `│ exit code: 1`
 ` ╰─> [8 lines of output]`
    `  Traceback (most recent call last):`
       ` File "<string>", line 2, in <module>`
        `File "<pip-setuptools-caller>", line 34, in <module>`
        `File "/tmp/pip-install-190biuhi/wxpython_fb8d2a7d22b34692bcacfac2fd12d791/setup.py", line 27, in <module>`
       `   from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName`
       ` File "/tmp/pip-install-190biuhi/wxpython_fb8d2a7d22b34692bcacfac2fd12d791/buildtools/config.py", line 30, in <module>`
        `  from attrdict import AttrDict`
     ` ModuleNotFoundError: No module named 'attrdict'`
     ` [end of output]`
  
 ` note: This error originates from a subprocess, and is likely not a problem with pip.`
`error: metadata-generation-failed`

`× Encountered error while generating package metadata.`
`╰─> See above for output.`

`note: This is an issue with the package mentioned above, not pip.`
`hint: See above for details.`

I wonder where I did wrong and how to install it properly.

**Comment by viperultra** [comment]
Install `attrdict3` with `pip install attrdict3`

**Comment by wilsontulus** [comment]
> Install `attrdict3` with `pip install attrdict3`

Not recommended since it will cause pacman conflict with packages depending on attrdict in the future.
**Use `pacman -S python-attrdict` instead.**

**Comment by gentlegiantJGC** [comment]
You are using an unsupported version of Python. You need to use Python 3.7-3.9.
