### ISSUE TITLE
[Bug Report] No format loaders found.

### ISSUE THREAD

**Issue by Avakining** [Amulet-Team/Amulet-Map-Editor#868]
### Current Behaviour:

After selecting a world, an error is presented and the world is not loaded

### Expected behavior:

World loads

### Steps To Reproduce:

1. Open the Amulet Editor on macOS
2. Click 'Open World'
3. No worlds already appear
4. Click 'Open other world'
5. Select world file
6. Error

### Environment:

- OS: OSX / macOS 13.1
- Minecraft Platform: Java
- Minecraft Version: 1.19.2 
- Amulet Version: 0.10.8 

### Additional context

Error:
```
Traceback (most recent call last):
  File "amulet_map_editor/api/framework/amulet_ui.py", line 183, in open_level
    world = WorldPageUI(self, path)
  File "amulet_map_editor/api/framework/pages/world_page.py", line 71, in __init__
    self.world = load_level(path)
  File "amulet/level/load.py", line 30, in load_level
  File "amulet/level/load.py", line 59, in load_format
  File "amulet/level/loader.py", line 62, in get
  File "amulet/level/loader.py", line 67, in identify
Exception: No format loaders found.
```

### Screenshots

https://user-images.githubusercontent.com/25210618/212521773-6f7da286-984a-457f-861f-91761c559674.mov

**Comment by gentlegiantJGC** [comment]
Please can you upload a small world that does not open in Amulet.

**Comment by Avakining** [comment]
It happens with *every* world, both vanilla and modded, in every version I've tried.
Here's a brand-new 1.19.3 superflat world that it fails to open: 
[New World (6).zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/10473047/New.World.6.zip)

**Comment by gentlegiantJGC** [comment]
The world you have sent looks fine.
Does the directory you are selecting contain the level.dat file or is it in a subfolder?
I know mac sometimes duplicates things in the worlds users have sent me.

I assume you are running from source. Please can run this and respond with the output `python3 -m pip list`

If all of that looks normal then it is probably an issue with the way it is finding the loaders.

**Comment by gentlegiantJGC** [comment]
Is there any more info in the log file?

**Comment by ViRb3** [comment]
Experiencing the same issue when I package the app using PyInstaller, using the official `Amulet.spec` on macOS 13.4, arm64. Running Amulet directly via venv works fine. Btw, you need to set `console=False` to get the packaged app to run on a Mac.

```
INFO - Loading level /Users/user/Library/Application Support/PrismLauncher/instances/Fabric 1.19/.minecraft/saves/New World
ERROR - Error loading world.
Traceback (most recent call last):
  File "amulet_map_editor/api/framework/amulet_ui.py", line 183, in open_level
  File "amulet_map_editor/api/framework/pages/world_page.py", line 71, in __init__
  File "amulet/level/load.py", line 30, in load_level
  File "amulet/level/load.py", line 59, in load_format
  File "amulet/level/loader.py", line 62, in get
  File "amulet/level/loader.py", line 67, in identify
Exception: No format loaders found.
```

**Comment by gentlegiantJGC** [comment]
It must be an issue with our build script on mac then.
The OP did not make it clear if they were running from source or a pyinstaller build.

**Comment by Avakining** [comment]
I was running it as pyinstaller, if I remember correctly

**Comment by gentlegiantJGC** [comment]
I believe this is an issue with `pkgutil.iter_modules` while using PyInstaller on macOS as a result of symbolic links.

I have opened a bug report on the pyinstaller repo pyinstaller/pyinstaller#7884

**Comment by ViRb3** [comment]
Works great with the latest update of PyInstaller, thanks a lot @gentlegiantJGC!

A quick guide for those who want to build an app package on macOS:
```python
pip install poetry
git clone https://github.com/Amulet-Team/Amulet-Map-Editor --branch 0.10.19 amulet
cd amulet
sed -i '' "s/console=True/console=False/g" Amulet.spec
rm pyproject.toml
poetry init --python "<3.13,>=3.9" --dependency amulet-map-editor --dependency numpy=^1.25.2 --dev-dependency pyinstaller -n
poetry install
poetry run pyinstaller Amulet.spec
sudo mv dist/amulet.app /Applications/
```

@gentlegiantJGC two requests to remove the hacks to build on macOS:
- Can you please set `console=False` in https://github.com/Amulet-Team/Amulet-Map-Editor/blob/0.10/Amulet.spec#L108? Not sure if it'll have any impact on other OSes, but macOS shows no GUI unless this is False.
- Can you bump numpy to `^1.25.2`? Lower versions do not contain prebuilt binaries for macos arm64, so building requires external dependencies and a lot more time.

**Comment by gentlegiantJGC** [comment]
Just checked our numpy requirement and we don't specify a maximum bound. It is `numpy~=1.17` which is any `1.x` where `x>=17` so it should just pull whatever is the newest version compatible with your install of python and OS.
