### ISSUE TITLE
[Bug Report] Upgrade on Linux

### ISSUE THREAD

**Issue by Moilleadoir** [Amulet-Team/Amulet-Map-Editor#869]
## Bug Report
The recommended way to install on Linux is through `pip`, but Amulet doesn’t seem to upgrade through pip.
### Current Behaviour:
Running `pip install amulet-map-editor --upgrade` in a virtual env only upgrades dependencies; the amulet version remains the same (0.9.6).

### Expected behavior:
The latest release should be installed (10.8).

### Environment:

- OS: Manjaro Linux
- (Minecraft Platform: Java | Bedrock)
- Minecraft Version: not relevant
- Amulet Version: 0.9.6

Is there some other way to do this?

**Comment by Moilleadoir** [comment]
Actually, can you install any other version through pip?

```
pew in amulet pip install amulet-map-editor --upgrade --force-reinstall
Collecting amulet-map-editor
  Downloading amulet_map_editor-0.9.6-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.4 MB/s eta 0:00:00
Collecting amulet-core==1.8.1
  Downloading amulet_core-1.8.1-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 11.3 MB/s eta 0:00:00
Collecting pyopengl~=3.0
  Downloading PyOpenGL-3.1.6-py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.0 MB/s eta 0:00:00
Collecting numpy~=1.17
  Downloading numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 12.2 MB/s eta 0:00:00
Collecting minecraft-resource-pack==1.2.8
  Downloading minecraft_resource_pack-1.2.8-py3-none-any.whl (449 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.0/449.0 kB 10.9 MB/s eta 0:00:00
Collecting wxPython~=4.1
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 11.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ammhkufj/wxpython_2c41b83d46bf450a90c0ba8a02f8f18b/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-ammhkufj/wxpython_2c41b83d46bf450a90c0ba8a02f8f18b/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by gentlegiantJGC** [comment]
We currently only support Python 3.7 to 3.9.
Use python in this range and you can install the newer versions.

**Comment by chocolateimage** [comment]
> Actually, can you install any other version through pip?
> 
> ```
> pew in amulet pip install amulet-map-editor --upgrade --force-reinstall
> Collecting amulet-map-editor
>   Downloading amulet_map_editor-0.9.6-py3-none-any.whl (1.7 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.4 MB/s eta 0:00:00
> Collecting amulet-core==1.8.1
>   Downloading amulet_core-1.8.1-py3-none-any.whl (1.0 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 11.3 MB/s eta 0:00:00
> Collecting pyopengl~=3.0
>   Downloading PyOpenGL-3.1.6-py3-none-any.whl (2.4 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.0 MB/s eta 0:00:00
> Collecting numpy~=1.17
>   Downloading numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 12.2 MB/s eta 0:00:00
> Collecting minecraft-resource-pack==1.2.8
>   Downloading minecraft_resource_pack-1.2.8-py3-none-any.whl (449 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.0/449.0 kB 10.9 MB/s eta 0:00:00
> Collecting wxPython~=4.1
>   Downloading wxPython-4.2.0.tar.gz (71.0 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 11.0 MB/s eta 0:00:00
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-ammhkufj/wxpython_2c41b83d46bf450a90c0ba8a02f8f18b/setup.py", line 27, in <module>
>           from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
>         File "/tmp/pip-install-ammhkufj/wxpython_2c41b83d46bf450a90c0ba8a02f8f18b/buildtools/config.py", line 30, in <module>
>           from attrdict import AttrDict
>       ModuleNotFoundError: No module named 'attrdict'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```

in this thing you can run `pip install attrdict3`

**Comment by Moilleadoir** [comment]
Found a bit of time to try this again.  I haven’t tried installing `attrdict3` — maybe that works, but who knows what other gotchas will pop up if you’re using a different python?  In case anyone finds this in a search here's what I did to create a new install…

(assuming you’re using `pew`)
```
$ pew install 3.9.16 -t cpython
$ pew new --python=$(pythonz locate 3.9.16 --type cpython) amulet
amulet $ pip install amulet-map-editor
```
`Building wheel for wxPython` takes a long time…

Run from virtual env…

`amulet $ python -m amulet_map_editor`

or

` $ pew in amulet python -m amulet_map_editor`

Amulet ends up in `~/.local/share/virtualenvs/amulet/lib/python3.9/site-packages`

**Updating**
`$ pew in amulet pip install amulet-map-editor --upgrade`
