### ISSUE TITLE
Open a world file at the world's default spawn point?

### ISSUE THREAD

**Issue by nkrs200** [Amulet-Team/Amulet-Map-Editor#87]
Hello,

So, I just started using the Amulet Map Editor, and I was impressed with how easy it is to use, but the one thing that stumps me everytime is the fact that the world file always opens at x:0, y:100, z:0.  Is it possible to have it load the world with the start position at the world's default spawn point?

**Comment by gentlegiantJGC** [comment]
This is something we want to add but we haven't implemented support to read non-chunk data yet

**Comment by EeaseDev** [comment]
That would be great! However, I think it would be more useful if you spawned in at the player location because usually, I want to edit an area where I'm at with my player.

**Comment by Podshot** [comment]
We hope to add that in as well, but that data is also stored in a separate file which we currently don’t have that support implemented yet

**Comment by gentlegiantJGC** [comment]
A temporary workaround while we get that implemented is to use the camera location from the last amulet session

**Comment by gentlegiantJGC** [comment]
This is now implemented as of the latest release.
