### ISSUE TITLE
[Bug Report] Java custom dimensions

### ISSUE THREAD

**Issue by BenjaminNicro** [Amulet-Team/Amulet-Map-Editor#883]
### Current Behaviour:
Is there a way to paste a saved structure to a dimension made with a datapack? when i try it gives me an error

error type:

The dimension exists but there is not selection registered for it. Please report this to a developer "minecraft:space" <amulet.level.formats.anvil_world.format.AnvilFormat object at 0x00000161CCE2E608>
NoneType: None

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by gentlegiantJGC** [comment]
You haven't given me enough information to debug this issue.
I have added the bug template. Please can you fill it out.
