### ISSUE TITLE
Left handed Controls

### ISSUE THREAD

**Issue by BSarmady** [Amulet-Team/Amulet-Map-Editor#884]
1- Keys group is not editable (why?), if I'm the only user of the app, why shouldn't I be able to set the keys to anything I want without having to create a copy?

2- Left handed people (I'm one) use arrow keys or numeric keypad to navigate. neither of them are an option!

3- Downloading default textures, why? If I was playing minecraft on same PC that world data is stored, why would you need to download them again, there is a copy exactly in same folder.

4- Downloading textures failed. OK, not even a pink default texture? just an empty blank world?

**Comment by gentlegiantJGC** [comment]
1) You need to create a copy of the controls to edit them.
2) I will need to look into this. I too am left handled and use JIKL
3) It was just easier to implement
4) Try the following. Restart Amulet, restart your computer, disable antivirus for Amulet.
