### ISSUE TITLE
Minecraft Bedrock Edition Block Aliases Issue Converting from version 1.18.30 to 1.18.12 and prior

### ISSUE THREAD

**Issue by GoaticRelics** [Amulet-Team/Amulet-Map-Editor#886]
Hello, for context. I have a MCBE world, the version of this world is 1.18.30, I'm trying to convert the world to the 1.18.12 version of the game. Unfortunately for me, block aliases were introduced in the 1.18.30 version of the game. This means that when I use the Amulet converter and I then load the world in the 1.18.12 vanilla version of the game, 2 types of blocks in my world become "unknown". In particular the concrete powder (green in my situation) and the invisible bedrock. In 1.18.12 and versions prior to 1.18.30, concretePowder was the appropriate name, now it is called concrete_powder, same for the invisibleBedrock that became invisible_bedrock. Basically, when my world is loaded in 1.18.12, it cannot find the ID "invisible_bedrock" for example (I suppose), because logically it didn't exist, and the converter doesn't "downgrade" the blocks (every other converter I tried can't, Amulet is a really great tool besides that one issue). Someone said the following : "Well it’s because they’re technically treated as aliases but I imagine amulet doesn't downgrade aliases". I also got great feedback from that same person which is : "amulet developers seem to be more community oriented, I would recommend you make a bug report there, it’s not necessarily a difficult problem to overcome so they could probably fix it fairly quickly". Let me know if what I wrote makes sense and if you guys understand the issue and if a possible fix could be implemented. Thanks.

This is the world I want to convert in 1.18.12 but is currently in 1.18.30 :
[Nodebuff FFA World 1.18.30.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11115881/Nodebuff.FFA.World.1.18.30.zip)

This is the world template in 1.18.12 to convert the 1.18.30 world :
[Fresh Flat 1.18.12 World.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11115890/Fresh.Flat.1.18.12.World.zip)

To my knowledge, seaLantern also became a block alias now to => sea_lantern if I'm not mistaken.

Edit:
Reading through the other issues, this user seems to have a similar issue but converting from Java to Bedrock 1.18.12 : https://github.com/Amulet-Team/Amulet-Map-Editor/issues/870#issue-1555608033
Important to note that this is likely caused because of the block aliases.

**Comment by gentlegiantJGC** [comment]
Here is the issue.
Each block stores a version number and we use that version number to find the translator to use.
Some of the green concrete powder blocks look like this
`(17959425, Block(minecraft:concrete_powder[color="green"]))`
Which is 1.18.30 so it behaves correctly.

Some of the blocks in the world however look like this.
`(17825806, Block(minecraft:concrete_powder[color="green"]))`
Which is 1.16.0 however the concrete_powder as far as I am aware did not exist in 1.16.

Amulet is therefore treating it as a modded block.

**Comment by GoaticRelics** [comment]
I see what you mean, the world is old and has been through some updates, so maybe that could explain those blocks but, like you said, they weren't introduced in 1.16.0 apparently so that's strange. I opened the world in Amulet and I saw those older concrete_powder blocks as well. And I could replace those "1.16" blocks by 1.18.30 blocks anyways.
But (In the replace operation), if I select a `17959425` concrete_powder block in 1.18.30, and I select the same block but for the platform 1.18.0, which is the target version, I obviously get 2 different ways or writing the powder concrete (block name) since the block aliases were introduced in 1.18.30. As shown in the image below.
![image](https://user-images.githubusercontent.com/128065482/229390580-b6dbf3dd-84f9-4cd9-91e3-c2f71f10cd6c.png)
You can see there's clearly 2 types of powder concrete. What the converter should technically and ideally do, is turn every new "concrete_powder" blocks to "concretePowder" blocks if I'm trying to convert/downgrade to a version prior 1.18.30, in my case 1.18.12. Same for every other block aliases, like the invisible bedrock blocks too. -> 
![image](https://user-images.githubusercontent.com/128065482/229391041-9a2369a3-8079-423a-a605-8feba54cc331.png)
Because the issue is not really related to the "1.16.0" blocks, I could replace those by 1.18.30 concrete powder blocks, and it still wouldn't convert them into 1.18.12 concretePowder blocks.

**Comment by gentlegiantJGC** [comment]
I think your confusion is a misunderstanding of how the fill and replace tool works. The actual implementation is a bit abstract so I can understand.

It is built upon our conversion system so that it will replace any matching state regardless of the origin version or platform.
The issue is that when loading the invalid state it is treated as a modded block.
To replace it you will need to select 1.16.0 (or any version where concrete_powder is not a valid block) and manually type in the block properties.

I think the `__version__` property remaining in the state is a bug that I am currently fixing.

I may look into backporting the translator to support the alias states to before they were actually implemented because they are coming from somewhere and it shouldn't hurt anything.

**Comment by gentlegiantJGC** [comment]
I think Amulet should automatically fix these blocks if you make a change in those chunks and save it.
It will just save the state out as it loaded it but in the newer version where it is valid.
I don't know if it would strip out the `__version__` tag but Amulet-Team/Amulet-Core#243 should fix that.
