### ISSUE TITLE
Persistent Windows Process Hang Issue on Opening 3d Editor (Possibly Caused by Earlier Crash)

### ISSUE THREAD

**Issue by Pheotis** [Amulet-Team/Amulet-Map-Editor#89]
### Circumstances
- Attempting to export certain large assets from an extremely large 1.13.2 world to the construction format
  - This world was originally generated in 1.8, and was converted to 1.13.2 with PaperSpigot
- Attempting to assemble a collection of the aforementioned constructions into a new, empty, superflat, 1.13.2 world.
### Precedent
***Note that this section is not necessarily associated with this issue, but may be useful as context***
#### Issue
- Originally, the export was attempted as a whole; i.e. selecting and exporting a 2 500 x 2 500 x 250 block area.
- Although it took several hours per attempt, Amulet was always able to export the given area to a construction file without error.
- When attempting to import said construction file, amulet successfully loaded the file into the superflat target world, but indefinitely hanged upon attempting to place it (no errors on console).
#### Workaround
- Dividing the area into smaller constructions and assembling them in the superflat world appeared to work without issue.
- The above process was successful in transferring 80% of the target area before experiencing a fatal error.
  - That fatal issue is the subject of this report.
### Onset
- This version of Amulet had been installed and operated for weeks before this issue.
  - Numerous similar operations had already successfully been attempted.
- While attempting to move about an 1.13.2 map that was already open, amulet's process hung.
  - The area this movement occurred in had already been successfully explored within amulet earlier.
- After waiting for about 15 minutes with no changes, an attempt was made to close the program.
  - This attempt caused amulet to stop responding with no additional errors or information on console
  - Following this, the process was forcibly killed with `taskkill /im amulet_app.exe /f`
### The issue
- Although amulet appeared to be functional after being restarted, it now hangs when attempting to 3D edit *any* world.
  - Amulet is able to open worlds to the about window
    - ![Stage_1](https://user-images.githubusercontent.com/49039536/91648863-e0dffd80-ea3a-11ea-9008-bbc91cfd36e3.png)
  - When attempting to any world in the 3D editor, amulet's process stops responding with no additional errors in console.
    - ![Stage_2b](https://user-images.githubusercontent.com/49039536/91649089-cc513480-ea3d-11ea-84fa-77304d03f1dc.png)
  - After no amount of time (18 hours tested) will the process respond.
## Attempted troubleshooting
- This issue impacts all worlds, and has been tested with the following:
  - Existing vanilla-generated singleplayer worlds from 1.6, 1.8, 1.9, 1.12, 1.13, & 1.15
  - Existing paper worlds generated from 1.8, 1.12, & 1.15
  - Freshly generated vanilla worlds from 1.6, 1.8, 1.9, 1.12, 1.13, & 1.15
  - Freshly generated paper worlds from 1.8, 1.12, & 1.15
- Restarting the computer does not effect this issue
- Resources do not appear to be the issue
  - During no attempt did amulet reach more than 20% cpu and/or memory; at least 50% of system resources remained available at all times. 
- This issue impacts fresh installations of amulet
  - After deleting the original amulet installation's folder, downloading a fresh installation, and opening it, this issue still exists.
- This issue impacts several versions of amulet, and has been tested with the following:
  - v6.10.0, v6.11.0, v7.0.0, v7.0.1
## Environment
![Specs_1](https://user-images.githubusercontent.com/49039536/91648998-aecf9b00-ea3c-11ea-9ef7-38cc537a851c.png)
Executed normally; plenty of space on all disks being interacted with.
## Conclusion
Thank you for your help resolving this; sorry for creating such a lengthy report.

**Comment by gentlegiantJGC** [comment]
I am honestly not sure what could be causing this issue.

**Comment by gentlegiantJGC** [comment]
Is this still an issue?

**Comment by Pheotis** [comment]
Honestly, I am not sure; it has been a while since I last tried.
In any case, my testing environment has changed since then, so the details of this issue would probably be different.

Probably best for me to make a new issue report should it reoccur.
