### ISSUE TITLE
[Feature Request] The Cherry Grove biome

### ISSUE THREAD

**Issue by WindowsSystemAdmin** [Amulet-Team/Amulet-Map-Editor#899]
### The Problem
Bedrock 1.19.80 and up include the new cherry grove biome.
### Feature Description
Add cherry biome in the set biome function.

### Alternatives
If not then will it be out when its released publicly?

**Comment by gentlegiantJGC** [comment]
Thanks. I had missed this.
It is an experimental feature so I will look into supporting it in the future.

**Comment by WindowsSystemAdmin** [comment]
also not sure if some blocks are added yet like bamboo and hanging signs..

**Comment by gentlegiantJGC** [comment]
This should work in the next update
