### ISSUE TITLE
View shift

### ISSUE THREAD

**Issue by Filude** [Amulet-Team/Amulet-Map-Editor#9]
When opening the 3d world renderer, the view constantly goes ot the top left for me, until i click mouse 3 (Middle mouse button) to be able to interact with the UI again. 
It's not severe, but definitly noticable.

**Comment by gentlegiantJGC** [comment]
Do you have a screenshot to explain what you mean?

**Comment by Filude** [comment]
[Shift.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/4288637/Shift.zip)

**Comment by gentlegiantJGC** [comment]
I experienced something like this but I thought I fixed it. I will have a look into it

**Comment by gentlegiantJGC** [comment]
I have just made some changes that might fix the issue. I wasn't experiencing the issues myself so I can't test but the changes will be in the next build so you can test. I will let you know when that is.

**Comment by gentlegiantJGC** [comment]
Apparently I hadn't but hopefully a change made by @Barteks2x has fixed this. #13

**Comment by gentlegiantJGC** [comment]
I think this issue should be fixed now. If it is still an issue please reopen this
