### ISSUE TITLE
[Bug Report] After the conversion, some items will be garbled on the map.

### ISSUE THREAD

**Issue by xiaobaikooo** [Amulet-Team/Amulet-Map-Editor#900]
### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by gentlegiantJGC** [comment]
You have not provided any information so I am going to close this.
It may be the same issue as #155 
If not please open a new issue with enough information for me to debug the issue.
