### ISSUE TITLE
[Bug Report] Unable to import construction

### ISSUE THREAD

**Issue by Griefed** [Amulet-Team/Amulet-Map-Editor#903]
### Current Behaviour:

I am unable to import a construction. Amulet errors out after selecting the file.
After opening the world and selecting the construction-file to import, the following error occurs, preventing the import:

```
Could not open G:\path\to\my\file

NBT Stream too short. Asked for 51515 bytes, 29227 more than the buffer.

Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\plugins\tools\import_tool.py", line 68, in _on_open_file
  File "amulet\level\load.py", line 34, in load_level
  File "amulet\api\level\structure.py", line 17, in __init__
  File "amulet\api\level\base_level\base_level.py", line 63, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 337, in open
  File "amulet\api\wrapper\structure_format_wrapper.py", line 88, in _open
  File "amulet\level\formats\construction\format_wrapper.py", line 265, in open_from
  File "amulet_nbt\\_load_nbt.pyx", line 188, in amulet_nbt._load_nbt.load
  File "amulet_nbt\\_load_nbt.pyx", line 130, in amulet_nbt._load_nbt._load_one
  File "amulet_nbt\\_load_nbt.pyx", line 110, in amulet_nbt._load_nbt.load_named_tag
  File "amulet_nbt\\_load_nbt.pyx", line 104, in amulet_nbt._load_nbt.load_tag
  File "amulet_nbt\\_load_nbt.pyx", line 92, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_compound.pyx", line 55, in amulet_nbt._compound.read_compound_tag
  File "amulet_nbt\\_load_nbt.pyx", line 90, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_list.pyx", line 29, in amulet_nbt._list.read_list_tag
  File "amulet_nbt\\_load_nbt.pyx", line 92, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_compound.pyx", line 55, in amulet_nbt._compound.read_compound_tag
  File "amulet_nbt\\_load_nbt.pyx", line 92, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_compound.pyx", line 55, in amulet_nbt._compound.read_compound_tag
  File "amulet_nbt\\_load_nbt.pyx", line 88, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_string.pyx", line 23, in amulet_nbt._string.read_string_tag
  File "amulet_nbt\\_util.pyx", line 72, in amulet_nbt._util.read_string
  File "amulet_nbt\\_util.pyx", line 78, in amulet_nbt._util.read_bytes
  File "amulet_nbt\\_util.pyx", line 44, in amulet_nbt._util.read_data
amulet_nbt._errors.NBTFormatError: NBT Stream too short. Asked for 51515 bytes, 29227 more than the buffer.
```
 
### Expected behavior:

After selecting the construction-file to import, I should be able to position said construction in the world and import it when I am pleased with the position.

### Steps To Reproduce:

*Unsure as to how reliable this is. I do not know whats causing this issue*

1. Have a modded 1.19.2 world
2. Create chests with modded items in them
3. Export a construction roughly dx 596, dy 237, dz 596
4. Import said construction into another world

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.19.2
- Amulet Version: v0.10.10

### Additional context

If the source of the error is a layer 8 ID10T problem because I did something wrong, please let me know so I can remedy the situation myself and get out of your hair asap. 😊

Should you require anything else, please let me know.

### World

When loading the world up in Amulet, you should immediately be around the coordinates of the build of which I require a working export of, in order to import it into another world.

https://files.seriouszone.de/share/aq1LuOoP

### Construction

The attached ZIP contains two construction-files of the import I want to make. The source for this construction-file is the world I linked to above.

[constructions.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11469660/constructions.zip)

**Comment by Griefed** [comment]
A workaround is to use the Copy-feature to copy the desired selection, switch to the target world and paste it there.
Though that is only a viable workaround if you have both the source and the target worlds at hand.

**Comment by Griefed** [comment]
I have a suspicion that the culprit of this issue is either

- a command block
- a book in a lectern
- an enderchest
- regular chests

I removed these block-types from a chunk I was unable to copy from the provided world to the target world. Everytime I copied the chunk the resulting target chunk would get corrupted after saving and loading the world in Minecraft, resulting in a void chunk.

After removing said block-types I was finally able to paste the selection without the chunk getting corrupter.

**Comment by gentlegiantJGC** [comment]
Sorry for taking so long to get back to you.
I can confirm that the file has been corrupted.
Looks like a bug in our exporting process.
The world link does not work. Don't suppose you still have a copy of that world.

**Comment by gentlegiantJGC** [comment]
I have found a bug writing long string tags. It however errors when writing long strings so that wouldn't explain how it got into the data.

**Comment by gentlegiantJGC** [comment]
Actually I think this is the issue.
Writing a string of length 65536 encodes to a string of length 0.
I have added an error if writing a string longer than 65535.

**Comment by Griefed** [comment]
> Sorry for taking so long to get back to you.
> 
> I can confirm that the file has been corrupted.
> 
> Looks like a bug in our exporting process.
> 
> The world link does not work. Don't suppose you still have a copy of that world.

No worries! I'm patient and hella thankful for all the hard you're putting into this. Thanks for getting back to me.

I have to check whether I still have the affected world. If that'd be still useful to you, let me know.

**Comment by gentlegiantJGC** [comment]
I am 90% certain that the change I made to the NBT library will stop this error happening again.
I would be interested to know what the string was that caused it to happen.
It was the last output field of the command block containing the following command.

```/give @p written_book{pages:['["",{"text":" ","bold":true},{"text":"\\u2605Tome Of Control\\u2605","bold":true,"underlined":true},{"text":"\\n\\n","color":"reset"},{"text":"1. Gamemode","bold":true,"color":"gold","clickEvent":{"action":"change_page","value":2},"hoverEvent":{"action":"show_text","value":"Jump to Gamemodes"}},{"text":"s","bold":true,"color":"gold","hoverEvent":{"action":"show_text","value":"Jump to Gamemodes"}},{"text":"\\n\\n","color":"reset","bold":true},{"text":"2. Gamerules","bold":true,"color":"yellow","clickEvent":{"action":"change_page","value":3},"hoverEvent":{"action":"show_text","value":"Jump to Gamerules"}},{"text":"\\n\\n","color":"reset","bold":true},{"text":"3. Useful Stuff","bold":true,"color":"dark_green","clickEvent":{"action":"change_page","value":6},"hoverEvent":{"action":"show_text","value":"Jump to Usefull Stuff"}},{"text":"\\n\\n","color":"reset","bold":true},{"text":"4. Difficulty","bold":true,"color":"dark_gray","clickEvent":{"action":"change_page","value":7},"hoverEvent":{"action":"show_text","value":"Jump to Difficulty"}},{"text":"\\n\\n","color":"reset","bold":true},{"text":"5. Potion Effects","bold":true,"color":"light_purple","clickEvent":{"action":"change_page","value":8},"hoverEvent":{"action":"show_text","value":"Jump to Potion Effects"}},{"text":"\\n\\n","color":"reset","bold":true},{"text":"6","bold":true,"color":"yellow","clickEvent":{"action":"change_page","value":9},"hoverEvent":{"action":"show_text","value":"Jump to Time & Weather"}},{"text":".","bold":true,"color":"blue","clickEvent":{"action":"change_page","value":9},"hoverEvent":{"action":"show_text","value":"Jump to Time & Weather"}},{"text":" ","color":"reset","bold":true,"clickEvent":{"action":"change_page","value":9},"hoverEvent":{"action":"show_text","value":"Jump to Time & Weather"}},{"text":"Time","bold":true,"color":"yellow","clickEvent":{"action":"change_page","value":9},"hoverEvent":{"action":"show_text","value":"Jump to Time & Weather"}},{"text":" & ","color":"reset","bold":true,"clickEvent":{"action":"change_page","value":9},"hoverEvent":{"action":"show_text","value":"Jump to Time & Weather"}},{"text":"Weather","bold":true,"color":"blue","clickEvent":{"action":"change_page","value":9},"hoverEvent":{"action":"show_text","value":"Jump to Time & Weather"}}]','["",{"text":"Gamemodes","bold":true,"underlined":true,"color":"gold","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Click to go back to the Table of Contents"}},{"text":"\\n\\n","color":"reset"},{"text":"Survival","color":"red","clickEvent":{"action":"run_command","value":"/gamemode survival"},"hoverEvent":{"action":"show_text","value":"Sets your Gamemode to Survival"}},{"text":"\\n","color":"reset"},{"text":"Creative","color":"green","clickEvent":{"action":"run_command","value":"/gamemode creative"},"hoverEvent":{"action":"show_text","value":"Sets your Gamemode to Creative"}},{"text":"\\n","color":"reset"},{"text":"Adventure","color":"blue","clickEvent":{"action":"run_command","value":"/gamemode adventure"},"hoverEvent":{"action":"show_text","value":"Sets your Gamemode to Adventure"}},{"text":"\\n","color":"reset"},{"text":"Spectator","color":"dark_gray","clickEvent":{"action":"run_command","value":"/gamemode spectator"},"hoverEvent":{"action":"show_text","value":"Sets your Gamemode to Spectator"}}]','["",{"text":"Gamerules","bold":true,"underlined":true,"color":"yellow","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Click to go back to the Table of Contents"}},{"text":"\\nKeepInventory ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule keepinventory true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule keepinventory false"}},{"text":"\\nMob Spawning ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule domobspawning true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule domobspawning false"}},{"text":"\\nCommand Block\\nOutput ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule commandblockoutput true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule commandblockoutput false"}},{"text":"\\nMob Griefing ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule mobgriefing true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule mobgriefing false"}},{"text":"\\nDaylightcycle ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule dodaylightcycle true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule dodaylightcycle false"}},{"text":"\\nWeathercycle ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule doweathercycle true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule doweathercycle false"}},{"text":"\\nAnnounce\\nAdvancements ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule announceadvancements true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule announceadvancements false"}},{"text":"\\nDisable Elytra Movement\\nCheck ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule disableElytraMovementCheck true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule disableElytraMovementCheck false"}},{"text":"\\nEntity Drops ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule doEntityDrops true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule doEntityDrops false"}}]','["",{"text":"Firetick "},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule doFireTick true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule doFireTick false"}},{"text":"\\nLimited\\nCrafting ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule doLimitedCrafting true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule doLimitedCrafting false"}},{"text":"\\nMob Loot ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule doMobLoot true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule doMobLoot false"}},{"text":"\\nTile Drops ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule doTileDrops true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule doTileDrops false"}},{"text":"\\nLog Admin\\nCommands ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule logAdminCommands true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule logAdminCommands false"}},{"text":"\\nNatural\\nRegeneration ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule naturalRegeneration true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule naturalRegeneration false"}},{"text":"\\nReduced Debug\\nInfo ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule reducedDebugInfo true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule reducedDebugInfo false"}},{"text":"\\nSend Command\\nFeedback ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule sendCommandFeedback true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule sendCommandFeedback false"}}]','["",{"text":"Show Death\\nMessages "},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule showDeathMessages true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule showDeathMessages false"}},{"text":"\\nSpectators Generate\\nChunks ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule spectatorsGenerateChunks true"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule spectatorsGenerateChunks false"}},{"text":"\\nMax Entity\\nCramming ","color":"reset"},{"text":"On","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule maxEntityCramming 24"}},{"text":" | ","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule maxEntityCramming 0"}},{"text":"\\nRandom Tick Speed\\n","color":"reset"},{"text":"Off","color":"red","clickEvent":{"action":"run_command","value":"/gamerule randomTickSpeed 0"}},{"text":" | ","color":"reset"},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/gamerule randomTickSpeed 1"}},{"text":" | ","color":"reset"},{"text":"3","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule randomTickSpeed 3"}},{"text":" | ","color":"reset"},{"text":"5","color":"gold","clickEvent":{"action":"run_command","value":"/gamerule randomTickSpeed 5"}},{"text":" | ","color":"reset"},{"text":"7","color":"red","clickEvent":{"action":"run_command","value":"/gamerule randomTickSpeed 7"}},{"text":"\\nSpawn Radius\\n","color":"reset"},{"text":"1","color":"dark_blue","clickEvent":{"action":"run_command","value":"/gamerule spawnRadius 1"}},{"text":" | ","color":"reset"},{"text":"3","color":"blue","clickEvent":{"action":"run_command","value":"/gamerule spawnRadius 3"}},{"text":" | ","color":"reset"},{"text":"5","color":"dark_green","clickEvent":{"action":"run_command","value":"/gamerule spawnRadius 5"}},{"text":" | ","color":"reset"},{"text":"7","color":"green","clickEvent":{"action":"run_command","value":"/gamerule spawnRadius 7"}},{"text":" | ","color":"reset"},{"text":"9","color":"light_purple","clickEvent":{"action":"run_command","value":"/gamerule spawnRadius 9"}},{"text":" |","color":"reset"},{"text":" ","color":"light_purple"},{"text":"10","bold":true,"color":"dark_purple","clickEvent":{"action":"run_command","value":"/gamerule spawnRadius 10"}}]','["",{"text":"Useful Stuff","bold":true,"underlined":true,"color":"dark_green","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Click to go back to the Table of Contents"}},{"text":"\\n\\n","color":"reset"},{"text":"XP Orb (~30 Levels)","color":"green","clickEvent":{"action":"run_command","value":"/summon xp_orb ~ ~5 ~ {CustomName:Ding,CustomNameVisible:1,Value:1396,Health:5}"},"hoverEvent":{"action":"show_text","value":"Gives you ~30 Levels of Experience"}},{"text":"\\n","color":"reset"},{"text":"Command Block","color":"gold","clickEvent":{"action":"run_command","value":"/give @p minecraft:command_block"},"hoverEvent":{"action":"show_text","value":"Gives you a Command Block"}},{"text":"\\n","color":"reset"},{"text":"Repeating Command Block","color":"gold","clickEvent":{"action":"run_command","value":"/give @p minecraft:repeating_command_block"},"hoverEvent":{"action":"show_text","value":"Gives you a Repeating Command Block"}},{"text":"\\n","color":"reset"},{"text":"Chain Command Block","color":"gold","clickEvent":{"action":"run_command","value":"/give @p minecraft:chain_command_block"},"hoverEvent":{"action":"show_text","value":"Gives you a Chain Command Block"}},{"text":"\\n","color":"reset"},{"text":"Minecart With Command Block","color":"gold","clickEvent":{"action":"run_command","value":"/give @p Minecraft:command_block_minecart"},"hoverEvent":{"action":"show_text","value":"Gives you a Minecart with a Command Block"}},{"text":"\\n","color":"reset"},{"text":"Barrier","color":"gray","clickEvent":{"action":"run_command","value":"/give @p minecraft:barrier"},"hoverEvent":{"action":"show_text","value":"Gives you a Barrier Block"}},{"text":"\\n","color":"reset"},{"text":"Kill Entities","color":"red","clickEvent":{"action":"run_command","value":"/kill @e[type=!Player,r=10]"},"hoverEvent":{"action":"show_text","value":"Kills entities in a 10 block radius"}},{"text":"\\n","color":"reset"},{"text":"Spawnpoint","clickEvent":{"action":"run_command","value":"/spawnpoint @p ~ ~ ~"},"hoverEvent":{"action":"show_text","value":"Sets your Spawnpoint to where you are currently standing"}},{"text":"\\n"},{"text":"Heal","color":"red","clickEvent":{"action":"run_command","value":"/effect @p minecraft:regeneration 2 255"},"hoverEvent":{"action":"show_text","value":"Heals ~ 20 Health (~10 Hearts)"}}]','["",{"text":"Difficulty","bold":true,"underlined":true,"color":"dark_purple","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Go back to the Table of Contents"}},{"text":"\\n\\n","color":"reset"},{"text":"Peaceful","color":"aqua","clickEvent":{"action":"run_command","value":"/difficulty peaceful"}},{"text":"\\n","color":"reset"},{"text":"Easy","color":"green","clickEvent":{"action":"run_command","value":"/difficulty easy"}},{"text":"\\n","color":"reset"},{"text":"Normal","color":"gold","clickEvent":{"action":"run_command","value":"/difficulty normal"}},{"text":"\\n","color":"reset"},{"text":"Hard","color":"red","clickEvent":{"action":"run_command","value":"/difficulty hard"}}]','["",{"text":"Potion Effects","bold":true,"underlined":true,"color":"light_purple","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Go back to the Table of Contents"}},{"text":"\\n","color":"reset"},{"text":"Clear all Effects","color":"white","clickEvent":{"action":"run_command","value":"/effect clear"},"hoverEvent":{"action":"show_text","value":"Clears all Effects affecting you"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:speed 600 10"},"hoverEvent":{"action":"show_text","value":"Expands FOV and Increases walking speed by 200%"}},{"text":"Speed","color":"yellow","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:speed 600 10"},"hoverEvent":{"action":"show_text","value":"Expands FOV and Increases walking speed by 200%"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:haste 600 10"},"hoverEvent":{"action":"show_text","value":"Arm swings 200% faster"}},{"text":"Haste","color":"gold","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:haste 600 10"},"hoverEvent":{"action":"show_text","value":"Arm swings 200% faster"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:strength 600 3"},"hoverEvent":{"action":"show_text","value":"Hits do 390% More damage"}},{"text":"Strength","color":"red","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:strength 600 3"},"hoverEvent":{"action":"show_text","value":"Hits do 390% More damage"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:night_vision 600"},"hoverEvent":{"action":"show_text","value":"See in the dark!"}},{"text":"Nightvision","color":"blue","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:night_vision 600"},"hoverEvent":{"action":"show_text","value":"See in the dark!"}},{"text":"\\n","color":"reset"},{"text":"\\"Infinite\\" ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:night_vision 1000000"},"hoverEvent":{"action":"show_text","value":"See in the dark, but even longer!"}},{"text":"Nightvision","color":"blue","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:night_vision 1000000"},"hoverEvent":{"action":"show_text","value":"See in the dark, but even longer!"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:glowing 600"},"hoverEvent":{"action":"show_text","value":"Outlines entities (can be seen through blocks)"}},{"text":"Glowing","color":"yellow","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:glowing 600"},"hoverEvent":{"action":"show_text","value":"Outlines entities (can be seen through blocks)"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:health_boost 600"},"hoverEvent":{"action":"show_text","value":"Increases Maximum Health"}},{"text":"Health Boost","color":"dark_red","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:health_boost 600"},"hoverEvent":{"action":"show_text","value":"Increases Maximum Health"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:invisibility 600"},"hoverEvent":{"action":"show_text","value":"Be the peeping Tom you always wanted to be"}},{"text":"Invisibility","color":"gray","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:invisibility 600"},"hoverEvent":{"action":"show_text","value":"Be the peeping Tom you always wanted to be"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:jump_boost 600"},"hoverEvent":{"action":"show_text","value":"Yer a bunny, Steve"}},{"text":"Jump Boost","color":"black","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:jump_boost 600"},"hoverEvent":{"action":"show_text","value":"Yer a bunny, Steve"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:water_breathing 600"},"hoverEvent":{"action":"show_text","value":"Swim with the fishes"}},{"text":"Water Breathing","color":"dark_blue","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:water_breathing 600"},"hoverEvent":{"action":"show_text","value":"Swim with the fishes"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:saturation 600"},"hoverEvent":{"action":"show_text","value":"Don\'t Starve!"}},{"text":"Saturation","color":"dark_green","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:saturation 600"},"hoverEvent":{"action":"show_text","value":"Don\'t Starve!"}},{"text":"\\n","color":"reset"},{"text":"10 min ","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:absorption 600"},"hoverEvent":{"action":"show_text","value":"Damage Absorption!"}},{"text":"Absorption","color":"dark_gray","clickEvent":{"action":"run_command","value":"/effect give @p minecraft:absorption 600"},"hoverEvent":{"action":"show_text","value":"Damage Absorption!"}}]','["",{"text":"Time","bold":true,"underlined":true,"color":"yellow","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Go back to the Table of Contents"}},{"text":" & ","color":"reset","bold":true,"underlined":true,"clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Go back to the Table of Contents"}},{"text":"Weather","bold":true,"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":1},"hoverEvent":{"action":"show_text","value":"Go back to the Table of Contents"}},{"text":"\\n\\n","color":"reset"},{"text":"Time Manipulation:","bold":true},{"text":"\\n","color":"reset"},{"text":"Dawn","color":"yellow","clickEvent":{"action":"run_command","value":"/time set day"}},{"text":"\\n","color":"reset"},{"text":"Midday","color":"gold","clickEvent":{"action":"run_command","value":"/time set 6000"}},{"text":"\\n","color":"reset"},{"text":"Dusk","color":"blue","clickEvent":{"action":"run_command","value":"/time set night"}},{"text":"\\n","color":"reset"},{"text":"Midnight","color":"dark_blue","clickEvent":{"action":"run_command","value":"/time set 18000"}},{"text":"\\n\\n","color":"reset"},{"text":"Weather Manipulation:","bold":true},{"text":"\\n","color":"reset"},{"text":"Toggle Weather","clickEvent":{"action":"run_command","value":"/toggledownfall"}},{"text":"\\n"},{"text":"Sunshine","color":"yellow","clickEvent":{"action":"run_command","value":"/weather clear"}},{"text":"\\n","color":"reset"},{"text":"Rain","color":"blue","clickEvent":{"action":"run_command","value":"/weather rain"}},{"text":"\\n","color":"reset"},{"text":"Thunderstorm","color":"dark_blue","clickEvent":{"action":"run_command","value":"/weather thunder"}}]'],title:"Tome Of Control",author:Griefed,display:{Lore:["One book to rule them (almost) all.","One book to control (most of) the world.","Look, it's a Command Book, alright?"]}}```
