### ISSUE TITLE
Logs aren't being Replaced

### ISSUE THREAD

**Issue by Diaa333** [Amulet-Team/Amulet-Map-Editor#907]
When trying to replace Logs in a new world with Air, it isn't working. I selected the Asterisk for Type and Direction - see the first screenshot - and hit Run Operation, but it's just not doing anything. Doing this for Leaves works just fine... just not the Logs, for some unknown reason. 

I did notice, though, when trying to use the "select" tool from the Replace Operation Menu, and click on one of the logs, it shows as "oak_log" but that isn't an option; it defaults to "stripped_dark_oak_log", with the only other option being "stripped_oak_log", but as the Logs aren't stripped this doesn't work, either - see second screenshot. And yes, I've tried it. I've also tried to select every available option for Logs, but nothing is working.

I don't know if it's worth noting or not that the Logs in-game are not positioned sideways like they are on the app, too.

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/112234803/bcff921f-9a72-4e88-960d-dae39206f7e0)

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/112234803/b58dc222-cb49-45c5-bff3-bcb25668d225)

**Comment by gentlegiantJGC** [comment]
Please can you provide an example world

**Comment by gentlegiantJGC** [comment]
Looks like the block state changed in 1.19.80.2
I will fix it.

**Comment by Diaa333** [comment]
Sorry, I was running errands all day yesterday and by the time I got home for dinner I had forgotten to reply. But thank you very much for looking into this and working on a fix; I appreciate it! 😊

**Comment by gentlegiantJGC** [comment]
This should be fixed in the next release
