### ISSUE TITLE
Could not find a matching format...

### ISSUE THREAD

**Issue by rsmalec** [Amulet-Team/Amulet-Map-Editor#91]
I just set up a brand new Windows 10 PC, Java 1.16.2 and Amulet 0.70.1
I created a 1.16.2 new world.
When I open Amulet and click 'open world', my java worlds are not showing up.
If I click 'open other world' and navigate to my world I get an error message that starts, "could not find a matching format..."

**Comment by gentlegiantJGC** [comment]
I am not able to reproduce this issue with a newly generated Java 1.16.2 world. Can you send over a world that causes the issue for me to test.

**Comment by rsmalec** [comment]
I was able to fix it by re-downloading the .zip and re-extracting to a new folder.
Not sure why, but the original folder did not have the 'amulet' subfolder, even though I do see it in the .zip.

So this must have been some kind of user error or glitch with my computer during the unzip.
