### ISSUE TITLE
KeyError: DimensionName

### ISSUE THREAD

**Issue by Link9868** [Amulet-Team/Amulet-Map-Editor#910]
### Current Behaviour:

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/132351290/f0febc62-ea90-418f-95bf-bd0258fa22f8)

### Environment:

- OS: Windows
- Minecraft PlatfBedrock
- Minecraft Version: 1.20
- Amulet Version:

**Comment by gentlegiantJGC** [comment]
Please click `copy error` and paste it here

**Comment by Link9868** [comment]
> 
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/132351290/a9436f8c-8b33-4752-8a37-9a252ed10902)

**Comment by gentlegiantJGC** [comment]
Please can you share the world

**Comment by Link9868** [comment]
> 请你分享世界

**Comment by Link9868** [comment]
> 请你分享世界

**Comment by Link9868** [comment]
> 请你分享世界

The file is too large，I don't know much about that

**Comment by gentlegiantJGC** [comment]
Upload it to something like google drive and share the link

**Comment by Link9868** [comment]
> 将其上传到谷歌云端硬盘之类的东西并分享链接

链接：https://pan.baidu.com/s/19hRE1VB_F1ZtKBfpiSKbxg?pwd=1111 
提取码：1111

**Comment by Link9868** [comment]
> 将其上传到谷歌云端硬盘之类的东西并分享链接

Trouble you

**Comment by gentlegiantJGC** [comment]
It is stuck on `提取中...`

**Comment by Link9868** [comment]
> 它卡在`提取中...`

https://www.123pan.com/s/bALUVv-m7zJ.html

**Comment by Link9868** [comment]
Hello, are you still there?

> 它卡在`提取中...`

**Comment by Link9868** [comment]
> 它卡在`提取中...`

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/132351290/72792626-4770-4c86-82be-4fefb4aa9f7f)
How to use this？
