### ISSUE TITLE
[Bug Report] Chunks Won't Load Back In

### ISSUE THREAD

**Issue by BioDannz** [Amulet-Team/Amulet-Map-Editor#911]
### Environment:

- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.0
- Amulet Version: 0.10.11

**Comment by gentlegiantJGC** [comment]
Minecraft Bedrock only saves chunks if the data in it has changed.
You need to modify the data somehow (eg placing blocks) to force the game to save the chunk.
