### ISSUE TITLE
[Bug Report] 0.10.11 version error

### ISSUE THREAD

**Issue by 2138550057** [Amulet-Team/Amulet-Map-Editor#912]
Bedlock 1.19.81.1.0 Conversion to Java 1.19.4 Clicking on the conversion directly prompts the world conversion to be completed, but the conversion has not been completed. This error can be converted normally in version 0.10.10.
This is what the console displays, but there is no error reported
INFO - Saving changes to level I:  game  MCJAVA  java . Minecraft  versions  1.19.4  saves  wza
INFO - Finished saving changes to level I:  game  MCJAVA  java . Minecraft  versions  1.19.4  saves  wza
INFO - Finished converting world I:  game  wza  wzaserver  1.19.81  Server  worlds  wza to I:  game  MCJAVA  java . Minecraft  versions  1.19.4  saves  wza

**Comment by 2138550057** [comment]
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/52618123/d30ee79b-88a0-4278-bbff-3dd2d8eb3fd1)

**Comment by AnnoyingVillager** [comment]
This happens when converting worlds from Bedrock 1.20.0.1.0 to Java 1.20 as well. Click the convert button and it will immediately finish without converting anything.

**Comment by AnnoyingVillager** [comment]
It seems that converting any Bedrock worlds to Java worlds will trigger this bug.

**Comment by jsousou77** [comment]
I'm also seeing this converting a 1.19.4 java world to 1.19.83.1 bedrock world. Works on 0.10.10 but immediately finishes without doing anything on 0.10.11

**Comment by gentlegiantJGC** [comment]
I have reproduced this. I did change some dimension code which may have broken this. I will investigate.
