### ISSUE TITLE
[Bug Report] Cherry Grove & Set biome feature

### ISSUE THREAD

**Issue by WindowsSystemAdmin** [Amulet-Team/Amulet-Map-Editor#913]
### Current Behaviour:
So when I select the set biome feature, I noticed the Cherry grove is under 1.19.80. 

### Expected behavior:
I expected the cherry grove to be under a separate tag under 1.20.

### Environment:

- OS: Windows 11
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.20.0.1
- Amulet Version: 0.10.11

**Comment by gentlegiantJGC** [comment]
The biome was added as an experimental feature in 1.19.80 which is why it is implemented there.
1.20 isn't fully supported yet.
