### ISSUE TITLE
[Bug Report] Latest version not available when installed via pip using Python 3.10 or newer

### ISSUE THREAD

**Issue by juozaspo** [Amulet-Team/Amulet-Map-Editor#914]
### Current Behaviour:

~Pip installs version 0.9.6 instead of latest version (0.10.x)~ _As default Python on Ubuntu 22.04 LTS is 3.10.x, latest version is not available when using it so older release is installed instead, also_ a notification about newer release version is shown upon program start

### Expected behavior:

Latest version being available and installed when using latest Python such as 3.10 or newer, no update notification shown
### Steps To Reproduce:
1. Create env on Linux and activate it
   - `python3 -m venv ENV`
   -  `. ENV/bin/activate`
2. Install amulet editor
   - `python3 -m pip install amulet-map-editor --upgrade`
3. Notice wrong version is installed, running it reports that update is available

### Environment:

- OS: Ubuntu Linux 22.04 LTS
- Minecraft Platform: Java
- Minecraft Version: None (not related to issue)
- Amulet Version: 0.9.6 (0.10.x cannot be installed using Python 3.10)

### Additional context

Output during installation
```
Collecting amulet-map-editor
  Downloading amulet_map_editor-0.9.6-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 6.0 MB/s eta 0:00:00
Collecting wxPython~=4.1
  Downloading wxPython-4.2.1.tar.gz (73.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.7/73.7 MB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting amulet-nbt==1.2.1
  Downloading amulet-nbt-1.2.1.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyMCTranslate==1.2.2
  Downloading PyMCTranslate-1.2.2-py3-none-any.whl (699 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 699.3/699.3 KB 2.9 MB/s eta 0:00:00
Collecting numpy~=1.17
  Using cached numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting amulet-core==1.8.1
  Downloading amulet_core-1.8.1-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 3.8 MB/s eta 0:00:00
Collecting pyopengl~=3.0
  Downloading PyOpenGL-3.1.7-py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 4.5 MB/s eta 0:00:00
Collecting minecraft-resource-pack==1.2.8
  Downloading minecraft_resource_pack-1.2.8-py3-none-any.whl (449 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.0/449.0 KB 2.2 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 KB 427.3 kB/s eta 0:00:00
Collecting portalocker~=2.4
  Downloading portalocker-2.7.0-py2.py3-none-any.whl (15 kB)
Collecting Pillow>=7.1
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 4.7 MB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for wxPython, since package 'wheel' is not installed.
Building wheels for collected packages: amulet-nbt
  Building wheel for amulet-nbt (pyproject.toml) ... done
  Created wheel for amulet-nbt: filename=amulet_nbt-1.2.1-cp310-cp310-linux_x86_64.whl size=1115937 sha256=c49f4afb84262edfa562b98bed39c5b1004835f45a68e115f575d82c0571ad26
  Stored in directory: /home/juozas/.cache/pip/wheels/2a/32/c0/6d5ba1392b662cffd92a3adee7ee0004efc3db8a8fe1b7282c
Successfully built amulet-nbt
Installing collected packages: pyopengl, six, portalocker, Pillow, packaging, numpy, wxPython, amulet-nbt, PyMCTranslate, minecraft-resource-pack, amulet-core, amulet-map-editor
  Running setup.py install for wxPython ...
```
Downgrading to Python 3.9 allows latest version to be installed.
### Screenshots

None yet (wxPython was still compiling at the time of posting)
### Worlds

None (not related to issue)

**Comment by gentlegiantJGC** [comment]
We only support Python 3.7-3.9

**Comment by juozaspo** [comment]
I'm using Python 3.10.6 as Python 3.9 and older is no longer in Ubuntu repositories.

**Comment by Podshot** [comment]
You can install Python 3.9 on Ubuntu Linux 22.04 LTS, you just have to make sure to install it separately and not override your system's built-in python installation

Here's a handy guide I found: https://linux.how2shout.com/install-python-3-9-or-3-8-on-ubuntu-22-04-lts-jammy-jellyfish/#Steps_to_install_Python_39_or_38_on_Ubuntu_2204_LTS (this will add a new PPA with older Python versions)

**Comment by juozaspo** [comment]
I was about to get source and compile python 3.9. Installed ppa python version, now latest version installs correctly. The issue that it is not available (e.g. incompatible) when using python 3.10

**Comment by Artoria2e5** [comment]
> We only support Python 3.7-3.9

Yes, that's what pip says, but is there a reason for the `<3.10` stuff? Git blame for the relevant line gives a14e680494870f170e5f903cc43ef5aa7216ca3e

```
wxPython does not have compiled builds for python versions newer than 3.9.
Many users report issues with compiling wxPython on 3.10 and newer so it is just easier to not support 3.10 for now.
```

which is not a particularly good reason when you are dealing with users that know to use pip in the first place! These guys hate to be treated as children.

And there are plenty of environments where getting Python 3.9 is a way bigger hassle than looking at wxPython build.
* Linux installations tend to have a healthy enough environment to build wxPython, but providing multiple versions of Python is rare, and downgrading can break other things. Yes, you can use your own prefix, but that's pointless when the problem you are trying to avoid does not exist for me.
* macOS homebrew does give python down to 3.7, but again wxPython can build just fine.

6632b85d935211d367dd1aa25ee764fea96185b9 is a bit weird too, because no issue reference have been given to specify what was broken -- how would people know what fix to look for in the future?

**Comment by gentlegiantJGC** [comment]
WxPython got another release a couple of weeks ago which supports newer versions so I should look back into this.

**Comment by juozaspo** [comment]
Upgrading to Python 3.10 introduces errors as described in https://github.com/Amulet-Team/Amulet-Map-Editor/pull/923#issuecomment-1599228122, the mentioned pr should be reverted untill an alternate solution could be found or underlying issue in code would be fixed.

**Comment by gentlegiantJGC** [comment]
I meant to remove the pinned version of wxpython
