### ISSUE TITLE
Program hang when importing large structures

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#92]
This is due to two problems.
The first is the whole structure is stored in RAM so if RAM is limited it may stop here. The solution is caching to disk like we do the world database. Some rewriting will be needed here perhaps to make the two share some logic.

The second is once the structure has been loaded into memory the geometry for the structure is created. This is all done at once which for small structures is quick but large structures cause the program to hang while it does this. If the computer runs out of VRAM it may hang indefinitely. The solution to this is to only generate geometry as required like is done with the actual world.

**Comment by Podshot** [comment]
I think a solution would be to hash the `.construction` file contents, then open the file for importing a collection of the subsections, then closing the file, then once those subsections have been imported into the world we re-open the file (while keeping the necessary metadata still stored in memory from earlier), checking the hash to confirm the contents haven't been changed, then importing another collection of subsections and repeating the process until we've imported every subsection

**Comment by FluffyDiscord** [comment]
> I think a solution would be to hash the `.construction` file contents, then open the file for importing a collection of the subsections, then closing the file, then once those subsections have been imported into the world we re-open the file (while keeping the necessary metadata still stored in memory from earlier), checking the hash to confirm the contents haven't been changed, then importing another collection of subsections and repeating the process until we've imported every subsection

I think the real solution is to just read it sequentially. If the .construction file does not support seeking/cursor offset and the file size is over, let's say, 1MB, then Amulet should convert it to some different file format which is seekable and able to use multiple cpu cores asynchronously for batch processing. I also think the rendering could be just put at hold, until it imports whole .construction
