### ISSUE TITLE
[Bug Report] Chunks not regenerating differently after deletion

### ISSUE THREAD

**Issue by PhyxiaGH** [Amulet-Team/Amulet-Map-Editor#920]
## Bug Report

Chunks not regenerating on 1.20

### Current Behaviour:
Chunks do not regenerate differently after being deleted and regenerated. 

### Expected behavior:
Expected chunks to regnerate differently after deletion.

### Steps To Reproduce:

1. Open Amulet
2. Open 1.20 Word
3. Delete surrounding chunks around specified object
4. Save world
5. Open 1.20 world in Minecraft Java
6. Deleted chunks remain the same and untouched

### Environment:

- OS: Windows 10
- Minecraft Platform: Java
- Minecraft Version: 
- Amulet Version: 

### Worlds
(https://drive.google.com/file/d/1FP7CsWVBv62rAf5gerOlgv8e54K1WUW1/view?usp=sharing)

**Comment by gentlegiantJGC** [comment]
That sounds like it is working as intended.
When you delete chunks the game will recreate them using the same algorithm it used the first time producing the same chunk.
Do you have player created structures in the chunk? Do these stay after deleting the chunk?

**Comment by PhyxiaGH** [comment]
I've tested and confirmed that player made structures do not stay after chunk deletion.

**Comment by PhyxiaGH** [comment]
My intention was to re-generate the chunks different to how they were originally generated, mostly to allow newer content to exist in older saves. Is this possible with Amulet?

**Comment by gentlegiantJGC** [comment]
The game will generate the chunks using the generator it comes with.
If the world was generated in an old version before a generator change then it will generate different terrain but otherwise it will generate the same terrain.

**Comment by gentlegiantJGC** [comment]
In the discord server you sent this image. Is this the same issue or a different one?
![](https://cdn.discordapp.com/attachments/1116543160919801986/1116543162052259950/image-27.png)

**Comment by PhyxiaGH** [comment]
This is what appears when deleting surrounding chunks. I assumed this was unintended.

**Comment by gentlegiantJGC** [comment]
That pull request fixes the status issue.
