### ISSUE TITLE
Amulet CAN'T open some Modded Dimensions

### ISSUE THREAD

**Issue by Rageouss** [Amulet-Team/Amulet-Map-Editor#922]
### Current Behaviour:
- Amulet cannot access Dimensions from a MOD that adds 15+ Dimensions and will add more. 
- I am a part of the DEV Team for the MOD in Question called ["RSMC: The Third Age"](https://www.curseforge.com/minecraft/mc-mods/rsmc-the-third-age)

### Expected behavior:
- When using Amulet Editor you should be able to click the "Dimension" Dropdown at the Top Right of the screen and select these Dimensions, but they are not there.

### Steps To Reproduce:

- I will provide a link to my Google Drive that will contain a newly created Minecraft World in which I generated these Dimensions in already. In the event you need to investigate the world by launching it the Google Drive Link will contain everything needed. 
1. Launch Amulet Editor and open the World provided (Amulet Test).

2. Go to the Top Right and Click the Dimension Dropdown and you will see that the only Dimensions available are the Vanilla Minecraft Dimensions (Minecraft:Overworld, Minecraft:The Nether, and Minecraft:The_End).

### Environment:

- OS: Windows 10 Pro // Version: 22H2 // OS Build: 19045.3086
- Minecraft Platform: Java
- Minecraft Version: 1.18.2 // Forge Version: 40.2.0
- Amulet Version: V0.10.11

## Attachments
- Below is a Google Drive Link that includes: 
1. Images.
2. Modded Minecraft World.
4. MOD in question.
5. Forge Version
6. A Pre-Configured MultiMC that only requires a Minecraft Account to be logged in and then Launched. 

[Google Drive Link:](https://drive.google.com/file/d/1Lz4uSp_fwwvKDWGMs_CT71bVXcDWeF04/view?usp=sharing)

### Screenshots
- Attached and Included in the Google Drive Link in ## Attachments

- Amulet not showing Dimensions 
![Amulet Bug 1 of 6](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/f0cdb1ba-3593-448d-96d1-5e6f2a356898)

- NBT Editor Showcase
![Amulet Bug 2 of 6 (NBT Editor Showcase)](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/8069d94f-0588-4df4-9c02-8a48bffcda80)

- Minecraft World Dimension Folder (Part 1)
![Amulet Bug 3 of 6 (Minecraft World Dimension Folder)](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/7ab009ef-157a-4447-bb11-00bf9141e3c6)

- Minecraft World Dimension Folder (Part 2)
![Amulet Bug 4 of 6 (Minecraft World Dimension Folder Part 2)](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/65dcf7b4-ad16-4fc1-bcee-b0a20bae0986)

- RSMC Dev Comments (Part 1)
![Amulet Bug 5 of 6 (RSMC Dev Comments)](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/ea0d7b2d-ac71-48fc-8eb3-24fabf0d47f4)

- RSMC Dev Comments (Part 2)
![Amulet Bug 5 of 6 (RSMC Dev Comments Part 2)](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/2f0bd0b4-496a-49a0-b421-053b97881a02)

### Worlds
- Included in the Google Drive Link in ## Attachments

**Comment by gentlegiantJGC** [comment]
Is there any documentation on the format that mods use? I am not really into the modding scene and have been implementing mod support mostly by reverse engineering save files that I find.
It would be useful if there is an actual specification to use.

**Comment by Rageouss** [comment]
@gentlegiantJGC 

Yes 2 of the Images I provided stated how it's structured

- See the last TWO Images

- The MODs Dimension are setup like this 
1. dimension/runecrafting/[air, water, etc.]

2. dimension/dungeon/[abyss, barrows]

**Comment by gentlegiantJGC** [comment]
Yes I saw that. I was asking more generally if there is any documentation for modded formats

**Comment by Rageouss** [comment]
@gentlegiantJGC 

- Alright let me break it down for you haha. 

1. Most MODS use the Vanilla Minecraft Dimension Structuring when adding Dimensions which is **"Dimensions/The Nether"**.

2. Since our MOD (**RSMC**) has A LOT OF DIMENSIONS (And will be adding more) we have them organized by **Grouping** them by based off the **Types** of Dimensions.

***RSMC Structures Dimensions like so***
- Dimension/Runecrafting/[Air, Water, Earth, Fire, Body, etc.]
- Dimension/Dungeon/[Abyss, Barrows, and etc]

3. For RSMC to work they need to be Flattened so their locations are "Dimensions/RSMC/Dungeon/Barrows"(RSMC Method) instead of "Dimensions/RSMC/Barrows"(Vanilla Method)

4. I couldn't find it in **Amulet's** Code, but I'm guessing **Amulet** just does a shallow Search in the **Dimensions Folder** for any Dimension setup just like Vanilla Minecraft's which is **"Dimensions/The Nether"**, but if a Modded Dimension goes any further it either ignores it or doesn't even read it.

This is not something we can change in our CODE as we have to have it setup like this for Organizing and because we have a Complex System to make them work like they do in RuneScape.

**Comment by Podshot** [comment]
I think @gentlegiantJGC is trying to figure out the documentation for modded dimensions to determine how best approach your situation (feel free to correct me if I'm wrong here @gentlegiantJGC).

Here's why the documentation on the recommended Forge/Fabric/Quilt/etc. way is helpful for us as a few case examples:
- Case 1: You're following the recommended/standard way(s) of doing modded dimensions
  - We can write a system that allows Amulet to load modded dimensions in a "general case" so then most mods that also add their own modded dimensions don't need any additional code changes from us to be loaded
- Case 2: You're mostly following the recommended way(s) but with major changes to how that data is stored
  - We can still write a system like in `Case 1` to support the general cases but then implement a possible custom add-in system (as in, we design our custom "general case" system to be extended easily knowing that each mod can have it's own quirks in regards to how they handle dimensions) to check if your mod seems to be present and then hook into our custom dimension loading system that's tailored to how your mod stores dimensions
- Case 3: You're not following the recommended way(s) at all
  -  This means we'll still have to write a custom system like in `Case 1`\\`Case 2` but we'll be able to know ahead of time that the "general case" solution we come up with __can__ be incompatible with some mods so we can write something that allows a system that just handles your mod to still work with our existing vanilla dimension system and a new modded dimension system as well as other systems for similar mods who don't follow the recommended method(s)
  
We need to know this information because if we go in implementing a system to load your custom dimensions not knowing this we might end up in a situation where we assumed you were the "usual" way of implementing modded dimensions and then other dimensions mods come along all using a standard format it ends up being more work for us re-coding and redesigning everything again. We just want to make sure we know how to approach this so we don't break other modded dimensions mods in the future and/or we don't have to keep doing this for every single dimension mod that wants their dimensions to be loaded in Amulet. I hope you understand where we're coming from on this.

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 


- As I've already stated there IS NOT a standardized way for how MODS structure Dimensions. MOST OF THEM use the Vanilla Minecraft method and that's it. 
- There isn't a single Document for Forge or any other Modding API that says you must handle adding Dimensions a certain way because structuring them just like Mojang did for the Vanilla Version of Minecraft works perfectly for Modded Dimensions. 
- I explained in my previous reply the reason why our MOD goes an ADDITIONAL Layer.

### Amulet Accesses Dimensions like this
- File handle/access/whatever to dimensions, then go one level deeper, and expect all folders in there to represent a dimension (they are expecting a structure like dimensions/<mod>/<dim_name>/[data, entities, poi, region]

### How this can be FIXED in Amulet?
- Amulet needs to do a recursive search until they FIND those expected folders (data, entities, poi, region), and then the parent folder is the actual dimension folder. 

**_Steps_**
1. Filehandle to dimensions, see what directories exist within that folder.
2. Go through those directories, and recursively see what directories are within. If the folder DOESN'T contain the 4 expected folders, go another level (recursively). 
3. Continue doing this until you have the expected folders - return the current directory at that point in the recursion chain.

### Last Resort
- If you need the Lead Programmer our MOD said will write the implementation HIMSELF.
- But anyone should be able to do this as there is no need for branching logic to say "Oh, is this mod installed? do this instead"

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

I hope I didn't come off as rude. I wasn't trying to. I've just been trying to get this fixed since like February.

If I did, I apologize. 

Are we on the same page now?

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

Could I please get a rough ETA for when this will be fixed?

**Comment by Podshot** [comment]
> Could I please get a rough ETA for when this will be fixed?

I'm currently in the process of moving and I'll resume working on it and finishing the implementation up when I'm done with that. I can't give an ETA when it will be implemented and in a release but I should be able to resume work in about 1-1.5 weeks

**Comment by Rageouss** [comment]
@Podshot Perfect. Thank you so much

**Comment by Rageouss** [comment]
Who do I need to bribe to get this added lmao. We're about to roll out our new Official Server for the RuneScape MOD and we need this tool to finish a big portion of it

**Comment by gentlegiantJGC** [comment]
Are all of these directories actually required? `data, entities, poi, region`
I thought it only needed the `region` directory to exist.

**Comment by Rageouss** [comment]
What? 

It needs to look deeper into the Dimension Folder. I explained in previous messages exactly what the fix is.

## Vanilla Minecraft 
- This is Currently how Amulet Editor looks for Dimensions
   -.Minecraft/Saves/World Name/Dimensions/*Dimension Name*
   
## How RSMC stores Dimensions
- Minecraft/Saves/World Name/Dimensions/RSMC/Dungeons/*Dungeon Name*
- Minecraft/Saves/World Name/Dimensions/RSMC/RuneCrafting/Air



All you need to do is have Amulet search deeper in the Dimensions Folder and that's it. 
![Am1](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/0c30b8d3-0265-455d-aca4-d50db9f0b57f)
![Amulet 2](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/595a3834-3114-483b-80c3-c409b7f95542)
![Amulet 3](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/64507792/400ebb41-a678-4379-945a-b655bd1f5c03)

**Comment by gentlegiantJGC** [comment]
@Podshot has implemented the code as you suggested.
It finds dimensions at the following glob `dimensions/*/**/region`
Where `*` is the namespace and `**` is one or more directories that make up the base name of the dimension separated by the `/` symbol.
I was asking do all of the following need to exist for it to be considered a valid level or just the region directory.
`dimensions/rsmc/runecrafting/air/data`
`dimensions/rsmc/runecrafting/air/entities`
`dimensions/rsmc/runecrafting/air/poi`
`dimensions/rsmc/runecrafting/air/region`

all of the above or just region?
`dimensions/rsmc/runecrafting/air/region`

In vanilla I believe the `data`, `entities` and `poi` are optional

**Comment by Rageouss** [comment]
I believe that `dimensions/rsmc/runecrafting/air/region` should do what's needed, but I will test it ASAP whenever it's dropped to verify if it worked or not.

**Comment by Podshot** [comment]
> I believe that `dimensions/rsmc/runecrafting/air/region` should do what's needed, but I will test it ASAP whenever it's dropped to verify if it worked or not.

The implementation is in the PR Amulet-Team/Amulet-Core#251, if you run Amulet from source you can just pull that branch down in-place of regularly installing the `amulet-core` dependency and test locally.

**Comment by Rageouss** [comment]
@Podshot 
Yeah It't not working, but could be me doing something wrong. When will this hit a Release Version?

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

This is going to end up in a release right? Not some plugin or something that requires additional steps to use?

**Comment by Podshot** [comment]
> @Podshot @gentlegiantJGC 
> 
> This is going to end up in a release right? Not some plugin or something that requires additional steps to use? 

Yes, this functionality will be apart of Amulet itself and won't require a plugin to use

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

That's good to hear. I thank you for taking the time to implement this. 

I haven't been able to test it or I was doing something wrong. Could you use the Map I shared to test it?

You should see any other Dimensions not named "Overworld, Nether, or End"

Thank you so much

**Comment by Rageouss** [comment]
@gentlegiantJGC @Podshot 

Two Questions: 

1. Will this be in the next release? 

2. When will the next release be? 

I hate to rush, but I've needed this for months haha

**Comment by gentlegiantJGC** [comment]
I am waiting for @Podshot to fix some issues with the pull request.

**Comment by Podshot** [comment]
> I am waiting for @Podshot to fix some issues with the pull request.

I forgot to push up the commit for that requested change, it's now pushed to the PR

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

I gotcha. I really appreciate y'all for doing this. 

Is there any ETA on that release?

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

I noticed this was closed. Did you get it implemented?

**Comment by Podshot** [comment]
> @Podshot @gentlegiantJGC
> 
> I noticed this was closed. Did you get it implemented?

Yes, the feature PR was merged/implemented

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

Awesome. Is there a way I can start using it?

**Comment by Rageouss** [comment]
@Podshot @gentlegiantJGC 

Awesome. Is there a way I can start using it?

**Comment by Rageouss** [comment]
Hey @Podshot @gentlegiantJGC, is there a way I can start using it because I really need it to finish the Map that will serve as our MODS Official Server Map.

**Comment by gentlegiantJGC** [comment]
It should be in the build from the other day
