### ISSUE TITLE
[Bug Report] sign data erased while changing biome or copy/paste

### ISSUE THREAD

**Issue by TylerSky** [Amulet-Team/Amulet-Map-Editor#924]
when converting biomes and when copying and pasting it removes all sign data.

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by gentlegiantJGC** [comment]
Please can you edit your report and fill out the issue template.

**Comment by gentlegiantJGC** [comment]
I am going to track this in #927
