### ISSUE TITLE
[Bug Report] After deleting chunks, it is not possible to save the world (MCBE)

### ISSUE THREAD

**Issue by Viniloko198** [Amulet-Team/Amulet-Map-Editor#926]
I loaded the world normally into the program, deleted some chunks to enjoy the update, but when I save the changes made, an error message appears. I'm going to paste the print of the error message here, how do I solve this?

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/118551658/1dc2020e-7de5-496c-b3fa-8f038bbeb3c8)

**Comment by gentlegiantJGC** [comment]
Did you open the world in game while it was open in Amulet?

**Comment by Viniloko198** [comment]
> Did you open the world in game while it was open in Amulet?

No, i export the world archives to my notebook and tried to erase some chuncks, but when it was done, it was not possible to save.

**Comment by Viniloko198** [comment]
EVEN WITH THE SAME WORLD IN JAVA EDITION IM HAVING THE SAME FUCKING PROBLEM

**Comment by Viniloko198** [comment]
[
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/118551658/df59bb29-e6d8-41b0-9559-131eade1c3f2)
](url)

**Comment by gentlegiantJGC** [comment]
In both of those cases it looks like another application is opening the level and Amulet is reacting so that the data doesn't get corrupted.

**Comment by gentlegiantJGC** [comment]
Looking back over the first error is from the leveldb library. `end of file reached` which looks like a corrupted world.
The latter looks like you have opened the level somewhere else and Amulet has stopped you editing the world.

Please can you share a world that the first issue happens on and I can look into it.
