### ISSUE TITLE
[Bug Report] Sign Data erased when you changing biome in the chunk zone with any sign

### ISSUE THREAD

**Issue by Sodvic** [Amulet-Team/Amulet-Map-Editor#927]
## Bug Report
If you change the biome of a selected area of ​​a Minecraft Bedrock edition world, all the signs included in the chunks in which the selected area is located are deleted all the writings. I think it's a version compatibility problem, in fact in 1.19 you could only write on one side of the cartel and now you can also write on both sides.
The same problem is also found with the new signs with the chains of 1.20.

### Current Behaviour:
The writing in the sign is erased upon saving the world.

### Expected behavior:
The sign should keep the writing instead of being deleted on both sides of the sign.

### Steps To Reproduce:

1. Select an area with a write sign
2. Go to operation
3. Click on change biome
4. Click on Minecraft Bedrock
5. Scroll down to any biome
6. See error on Minecraft Bedrock Edition 1.20 (The sign is empty)

### Environment:
- OS: Windows 10
- Minecraft Platform: Bedrock | Education Edition
- Minecraft Version: 1.20.0.0.0 & 1.20.0.1.0
- Amulet Version: Amulet V0.10-12

**Comment by gentlegiantJGC** [comment]
This should be fixed in the next build
