### ISSUE TITLE
[Bug Report] Error when installing wxPython

### ISSUE THREAD

**Issue by hexahigh** [Amulet-Team/Amulet-Map-Editor#931]
Hello, im trying to install Amulet in a python venv. But when i run the install command "python -m pip install amulet-map-editor==0.10.13 --upgrade" i get an error during the installation that says that wxPython failed to install and it ends the setup.
Here are some more detailed system info:
OS: ubuntu 22.04
Python version: 3.10
Arch: AMD64
Ram: 16gb

Here is the full log of the installation:
<pre>
(amulet) ajax@Ajax-POWER:~/Documents/python venv$ python -m pip install amulet-map-editor==0.10.13 --upgrade
Collecting amulet-map-editor==0.10.13
  Using cached amulet_map_editor-0.10.13-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: numpy~=1.17 in ./amulet/lib/python3.10/site-packages (from amulet-map-editor==0.10.13) (1.25.0)
Collecting amulet-nbt~=2.0
  Using cached amulet_nbt-2.1.1-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: pyopengl~=3.0 in ./amulet/lib/python3.10/site-packages (from amulet-map-editor==0.10.13) (3.1.7)
Collecting amulet-core~=1.9
  Using cached amulet_core-1.9.15-py3-none-any.whl (275 kB)
Requirement already satisfied: packaging in ./amulet/lib/python3.10/site-packages (from amulet-map-editor==0.10.13) (23.1)
Collecting wxPython
  Using cached wxPython-4.2.1.tar.gz (73.7 MB)
  Preparing metadata (setup.py) ... done
Collecting minecraft-resource-pack~=1.3
  Using cached minecraft_resource_pack-1.3.3-py3-none-any.whl (452 kB)
Collecting pymctranslate~=1.2
  Using cached PyMCTranslate-1.2.12-py3-none-any.whl (867 kB)
Requirement already satisfied: pyopengl-accelerate~=3.0 in ./amulet/lib/python3.10/site-packages (from amulet-map-editor==0.10.13) (3.1.7)
Requirement already satisfied: amulet-leveldb~=1.0b0 in ./amulet/lib/python3.10/site-packages (from amulet-core~=1.9->amulet-map-editor==0.10.13) (1.0.0b5)
Requirement already satisfied: portalocker~=2.4 in ./amulet/lib/python3.10/site-packages (from amulet-core~=1.9->amulet-map-editor==0.10.13) (2.7.0)
Requirement already satisfied: mutf8~=1.0 in ./amulet/lib/python3.10/site-packages (from amulet-nbt~=2.0->amulet-map-editor==0.10.13) (1.0.6)
Requirement already satisfied: Pillow>=7.1 in ./amulet/lib/python3.10/site-packages (from minecraft-resource-pack~=1.3->amulet-map-editor==0.10.13) (9.5.0)
Requirement already satisfied: six in ./amulet/lib/python3.10/site-packages (from wxPython->amulet-map-editor==0.10.13) (1.16.0)
Using legacy 'setup.py install' for wxPython, since package 'wheel' is not installed.
Installing collected packages: wxPython, amulet-nbt, pymctranslate, minecraft-resource-pack, amulet-core, amulet-map-editor
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [145 lines of output]
      running install
      /home/ajax/Documents/python venv/amulet/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
      
      "/home/ajax/Documents/python venv/amulet/bin/python" -u build.py build
      /tmp/pip-install-8xpfbyla/wxpython_43ad88a37ba94935ac2f9560cdbcfce5/build.py:43: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.dep_util import newer, newer_group
      Will build using: "/home/ajax/Documents/python venv/amulet/bin/python"
      3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.1
      
      Running command: build
      Running command: build_wx
      wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
      Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
      /tmp/pip-install-8xpfbyla/wxpython_43ad88a37ba94935ac2f9560cdbcfce5/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
      checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking for toolkit... gtk
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether we are using the Intel C compiler... no
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking whether gcc needs -traditional... no
      checking for g++... g++
      checking whether we are using the GNU C++ compiler... yes
      checking whether g++ accepts -g... yes
      checking whether we are using the Intel C++ compiler... no
      checking whether we are using the Sun C++ compiler... no
      checking for ar... ar
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for langinfo.h... yes
      checking for wchar.h... yes
      checking for sys/select.h... yes
      checking for cxxabi.h... yes
      checking for an ANSI C-conforming const... yes
      checking for inline... inline
      checking size of short... 2
      checking size of void *... 8
      checking size of int... 4
      checking size of long... 8
      checking size of size_t... 8
      checking size of long long... 8
      checking size of wchar_t... 4
      checking for va_copy... yes
      checking for _FILE_OFFSET_BITS value needed for large files... 64
      checking if large file support is available... yes
      checking for _LARGEFILE_SOURCE value needed for large files... no
      checking whether byte ordering is bigendian... no
      checking for std::wstring in <string>... yes
      checking for std::istream... yes
      checking for std::ostream... yes
      checking for type_traits... yes
      checking for __sync_xxx_and_fetch builtins... yes
      checking for libraries directories... /usr/lib/x86_64-linux-gnu /usr/lib
      checking for cos... no
      checking for floor... no
      checking if floating point functions link without -lm... no
      checking for sin... yes
      checking for ceil... yes
      checking if floating point functions link with -lm... yes
      checking for strtoull... yes
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for LIBPCRE... checking whether pcre submodule exists... yes
      checking for zlib.h >= 1.1.4... yes
      checking for zlib.h... (cached) yes
      checking for deflate in -lz... yes
      checking for png.h > 0.90... no
      checking for png.h... (cached) no
      configure: WARNING: system png library not found or too old, will use built-in instead
      checking whether png.c file exists... yes
      checking for jpeglib.h... no
      configure: WARNING: system jpeg library not found, will use built-in instead
      checking whether jpeglib.h file exists... yes
      checking for jbg_dec_init in -ljbig... no
      checking for LIBTIFF... not found via pkg-config
      checking for tiffio.h... no
      configure: WARNING: system tiff library not found, will use built-in instead
      checking whether tiff.h file exists... yes
      checking for expat.h... yes
      checking if expat.h is valid C++ header... yes
      checking for XML_ParserCreate in -lexpat... yes
      checking for LIBCURL... not found
      checking for GTK+ version...
      checking for pkg-config... (cached) /usr/bin/pkg-config
      checking pkg-config is at least version 0.16... yes
      checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gtk+-3.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gtk+-3.0' found
      Package gthread-2.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gthread-2.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gthread-2.0' found
      no
      *** Could not run GTK+ test program, checking why...
      *** The test program failed to compile or link. See the file config.log for the
      *** exact error that occurred. This usually means GTK+ is incorrectly installed.
      configure: error:
      The development files for GTK+ were not found. For GTK+ 2, please
      ensure that pkg-config is in the path and that gtk+-2.0.pc is
      installed. For GTK+ 1.2 please check that gtk-config is in the path,
      and that the version is 1.2.3 or above. Also check that the
      libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
      --libs' are in the LD_LIBRARY_PATH or equivalent.
      
      Error running configure
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "/tmp/pip-install-8xpfbyla/wxpython_43ad88a37ba94935ac2f9560cdbcfce5/build.py", line 1563, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "/tmp/pip-install-8xpfbyla/wxpython_43ad88a37ba94935ac2f9560cdbcfce5/buildtools/build_wxwidgets.py", line 379, in main
          exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
        File "/tmp/pip-install-8xpfbyla/wxpython_43ad88a37ba94935ac2f9560cdbcfce5/buildtools/build_wxwidgets.py", line 72, in exitIfError
          raise builder.BuildError(msg)
      buildtools.builder.BuildError: Error running configure
      Finished command: build_wx (0m2.273s)
      Finished command: build (0m2.273s)
      Command '"/home/ajax/Documents/python venv/amulet/bin/python" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
<pre>

**Comment by gentlegiantJGC** [comment]
Did you read the error log?
```
      The development files for GTK+ were not found. For GTK+ 2, please
      ensure that pkg-config is in the path and that gtk+-2.0.pc is
      installed. For GTK+ 1.2 please check that gtk-config is in the path,
      and that the version is 1.2.3 or above. Also check that the
      libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
      --libs' are in the LD_LIBRARY_PATH or equivalent.
```

I am not a linux user so I can't really help beyond reading back the error log to you.

**Comment by hexahigh** [comment]
I did, libgtk is installed.

**Comment by gentlegiantJGC** [comment]
The issue is in WxPython which is a third party library that we don't maintain.
Have you tried googling to see if anyone else has had similar issue?
You can also check out their bug tracker.

**Comment by hexahigh** [comment]
I managed to fix it, but now im getting the same issue as in #127.

For anyone else having the same problem, you need to manually download prebuilt wheels for wxPython from the official website.

**Comment by ericjs** [comment]
I probelms with this also (in Linux, specifically openSUSE Tumbleweed). Besides having to install several packages (dev versions of gtk and wx things, I was stuck on an compile error of

fatal error: wx/setup.h: No such file or directory

during the attempt to wheel wxPython

What worked for me was running:

`CFLAGS=$(wx-config --cflags) CPPFLAGS=$(wx-config --cxxflags) python -m pip wheel wxPython`

the flags generated by cxconfig basically configured the build to know where to find the wx includes. After that I could run

`python -m pip install amulet-map-editor`
