### ISSUE TITLE
[Feature Request] Support for vanilla structure files (nbt)

### ISSUE THREAD

**Issue by vico93** [Amulet-Team/Amulet-Map-Editor#935]
Why not add support for the vanilla [structure file format](https://minecraft.fandom.com/wiki/Structure_Block_file_format)? Having import/export support for that natively would make setup of custom datapack structures faster (instead of need to export to schematic/construction and the use another thing like worldedit to "convert" to .nbt).

**Comment by gentlegiantJGC** [comment]
Duplicate of #385
