### ISSUE TITLE
[Bug Report] Water Blocks don't render on Bedrock Worlds versions 1.20.0+

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#937]
## Bug Report
Amulet seemingly no longer renders water in bedrock 1.20+ worlds.

### Current Behaviour:
When loading a Minecraft Bedrock World Amulet no longer renders the world's water blocks.

### Expected behavior:
The Amulet should render water blocks in 1.20+ Minecraft Bedrock worlds without any issues.

### Steps To Reproduce:
1. Load a 1.20+ bedrock world and import it into the Amulet.
2. Then go to an ocean biome of saved chunks of water blocks.
3.  See the errored water with the missing textures?

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.0.1
- Amulet Version: v0.10.16b0

### Additional context
I think some new data of a block state, new block metadata, etc may be causing this, possibly due to this error when loading the world, could be because of the new level.dat version not being supported, the below error was in the console.

```bat
ERROR - Error loading format wrapper for C:\Users\kidsr\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\9XSbZB7VdgA= Traceback (most recent call last):
  File "amulet_map_editor\api\wx\ui\select_world.py", line 140, in __init__
  File "amulet\level\load.py", line 59, in load_format
  File "amulet\level\formats\leveldb_world\format.py", line 174, in __init__
  File "amulet\level\formats\leveldb_world\format.py", line 88, in from_file
  File "amulet\level\formats\leveldb_world\format.py", line 111, in _read_from
amulet.api.errors.ObjectReadError: Unsupported level.dat version 134217738
```

### Screenshots
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/3df53891-0833-42f5-a18e-3cd623a30818)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/18ff648d-0544-43a6-aec3-42687add657b)

### Worlds
N/A
- I'll try uploading a world later next week when I'm back at my computer, though it may not be possible due to my busy schedule.
- Though it does seem to happen with other worlds after testing a few newly created worlds from the bedrock edition.

**Comment by AHDAMAD** [comment]
This is happening on my Java world also.
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/128824293/b2485e89-5a9b-46d4-b081-734fd8baf476)
This is Amulet V0.10.16.
Java Edition 1.20
I do not get an error in the console though.
