### ISSUE TITLE
[Bug Report] Sign text not converted

### ISSUE THREAD

**Issue by EliteEric** [Amulet-Team/Amulet-Map-Editor#939]
### Current Behaviour:
Signs do not contain text when converted from Bedrock to Java. This was tested on a 6.5 GB Bedrock World (1.20.10, No 1.20 Chunks) converted to a Java 1.19.4 World.

### Expected behavior:
Signs should contain the text on Java that was present on the bedrock equivalent of the world. Earlier tools such as MCC Toolchest that have now become obsolete have this feature and it is strange for Amulet, still being actively worked on, to not have it.

### Steps To Reproduce:
1. Go to Amulet
2. Select Bedrock World in Latest Release
3. Convert to Java 1.19.4
4. Check signs and see they will have no text

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock to Java
- Minecraft Version: Bedrock 1.20.10 to Java 1.19.4
- Amulet Version: V0.10.15

### Additional context
Admin said on the Amulet Discord that there was a bug with signs that should be fixed in the latest release but it has not been fixed. This is a large server world as well (~7 GB)

### Screenshots

![AmuletEdit](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/139595811/e81ee136-78fd-4210-89e0-6052a90b60a1)

### Worlds
I am not ok with sharing this server's world but I am sure if you follow the steps you can recreate the issue. If you can not replicate it yourselves I am open to screen sharing on Discord to show the problem directly.

**Comment by gentlegiantJGC** [comment]
It looks like I broke the translations for 1.19.3 and 1.19.4
