### ISSUE TITLE
[Bug Report] Observer direction is not copied correctly

### ISSUE THREAD

**Issue by jfterpstra** [Amulet-Team/Amulet-Map-Editor#942]
### Current Behaviour:
Whenever an observer is copied and pasted, the direction resets to a default and is not the same as the original direction anymore. This also happens to existing observers in the same chunk as the chunk where the copied material is placed.

### Expected behavior:
The pasted observer should have the same direction as the original. Existing observers in the chunk should also remain the same.

### Steps To Reproduce:
1. Create a new world in Minecraft
2. Create some kind of redstone observer machine, e.g. a trident killer.
3. Close and save the world 
4. Open the world in Amulet
5. Copy the machine and paste it somewhere else in the world
6. Close and save the world in Amulet
7. Open the world in Minecraft and look at the direction of the observers in the pasted machine.

### Environment:
- OS: Windows 
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.20.10
- Amulet Version: 0.10.17

### Screenshots
![Screenshot 2023-07-18 141255](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/4849935/b5d898a3-9dbe-43a6-8e35-b8ceab652cbf)
Left: the original
Right: the copied trident killer, with the observers facing the wrong direction

### Worlds
[Test 2.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12080266/Test.2.zip)

**Comment by gentlegiantJGC** [comment]
Looks like 1.20.10 changed some more blockstates. I will need to update the translator again.
