### ISSUE TITLE
[Bug Report] UI Breakdown and World Loading Failure on Bad Plugin Installation

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#943]
### Current Behaviour:
After installing a problematic plugin for the Amulet Minecraft world editor, the application's User Interface (UI) becomes unusable. The world fails to load properly, displaying as blank. The UI options also seem to be offset randomly, making the application difficult to navigate and interact with.

### Expected behavior:
Even with a malfunctioning plugin, the UI of Amulet should remain consistent and usable. Worlds should load correctly and UI elements should remain in their appropriate positions.

### Steps To Reproduce:
1. Open Amulet World editor.
2. Install the problematic plugin.
3. Try to load a Minecraft world - the world fails to load, and the screen is blank.
4. Notice the UI options are randomly offset and the application is unusable.

### Environment:
- OS: Windows 10
- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.0
- Amulet Version: v0.10.16b0

### Additional context
The issue is resolved by removing the problematic plugin, suggesting the error is due to the plugin. However, a plugin should not be able to cause such a significant issue with the UI. This means a lack of proper error handling or isolation of plugin issues within Amulet.

This issue may not be limited to the specific performance of Amulet (v0.10.16b0)e it might occur in other versions as well. Therefore, this bug should be investigated thoroughly to prevent its recurrence in newer versions.

## Attachments
- Bad Plugin that was missing some imports, nothing crazy.
1. [set_leaves_to_persisent_plugin.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12137426/set_leaves_to_persisent_plugin.zip)

### Screenshots
1.
- Screenshot of the UI being Broken.
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/d2498173-61af-404f-81eb-0bf9072f6b8e)

2.
- Screenshot of the console.
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/22cc1f54-9497-4701-b112-5a4f24d35ac5)

### Worlds
N/A - Happens with other worlds it seems like 1.20.0, 1.19.81 is on bedrock when testing.

**Comment by gentlegiantJGC** [comment]
I was not able to reproduce the UI breaking but this should catch all exceptions raised while loading and running the plugin.
