### ISSUE TITLE
[Bug Report] Errors Loading level.dat Files in Newer World Updates

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#944]
### Current Behaviour:
When attempting to load certain worlds from recent updates in the Amulet Minecraft world editor, the level.dat files fail to load properly. This failure is accompanied by error messages appearing in the Amulet console log.

### Expected behavior:
The level.dat files of any world, regardless of the update version, should load correctly in Amulet without producing error messages in the console log.

### Steps To Reproduce:
1. - Open Amulet World editor.
2. - Attempt to load a Minecraft world from a recent update or using the level.dat file, I provided below.
3. - Observe that the level.dat file fails to load properly.
4. - Notice the error messages that appear in the Amulet console log.

### Environment:
- OS: Windows 10
- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.0
- Amulet Version: v0.10.16b0

### Additional context
This issue seems to be related to newer updates of Minecraft worlds, implying that the latest features or changes in the world structure could be causing compatibility issues with Amulet's level.dat loading mechanism.

## Attachments
[level_dat.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12137433/level_dat.zip)

### Screenshots
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/3c0ec4f3-3124-44cc-8007-03b1fdc80e5d)

### Worlds
N/A

**Comment by Apothicon02** [comment]
I also get this error.

**Comment by gentlegiantJGC** [comment]
The level.dat file you have linked is a perfectly valid level.dat file. The code can load it just fine.
Do you have any other examples?

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/11940194/77b2a631-58eb-498c-a261-2e46c5119224)

**Comment by StealthyExpertX** [comment]
I'll do some testing later today and see if I can get a few more samples for you.

**Comment by StealthyExpertX** [comment]
Just tried loading another level.dat.
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/6825b77b-0240-4348-a6c6-f41f7ac0c9a9)

Here's another level.dat file, just tested 2 minutes ago.

 it, and does the same thing!
[level_dat2.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12139737/level_dat2.zip)

**Comment by StealthyExpertX** [comment]
If you want me to create some more level.dat files that have the same issue let me know.

**Comment by gentlegiantJGC** [comment]
I really don't know what is going on here.
Both level.dat files are normal.
The code can open them.
I have tested the first file by loading it directly with that class and it loads fine.
The second I tested by putting it into an existing world and loading with the built version of Amulet and it loads fine.
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/11940194/76435dae-783d-4925-afdb-6d81bfed2ae8)

Can I suggest deleting your install of Amulet and reinstalling.

**Comment by StealthyExpertX** [comment]
I will try that and see if it fixes it.

**Comment by StealthyExpertX** [comment]
No, I still have the issue even with a newer Amulet version and a Fresh install!

**Comment by StealthyExpertX** [comment]
I'll try getting multiple amulet examples and try finding the exact cause of this issue.

**Comment by joschemd** [comment]
I am getting the same with my world (downloaded from Realms today)
Downloaded .18 today

[Update] Tried .11 (Which is the version I had previously)  No error on the load.


[level_dat.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12330399/level_dat.zip)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/27264271/5cd2bac8-4c8c-4b7b-a4ed-d8446ce68d1e)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/27264271/b130b13b-78fb-4d09-9147-654bb5d699e6)

**Comment by gentlegiantJGC** [comment]
That is a different issue.

**Comment by gentlegiantJGC** [comment]
I don't know what is going on here because none of the level.dat files you have sent have the problem.
If you can get a level.dat file that you can put into a world and load in Amulet and it produces the issue then send it to me.
I assume that something funky is happening with the world outside of Amulet.

**Comment by gentlegiantJGC** [comment]
If anyone can help me reproduce this issue then let me know.

**Comment by StealthyExpertX** [comment]
Wasn't able to reproduce it, my older level data files that used to do it, aren't that I had locally maybe it was somehow fixed?
