### ISSUE TITLE
[Bug Report] Missing Block Entity for Suspicious Gravel & Suspicious Sand Blocks

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#945]
## Bug Report
When attempting to create the new Suspicious Gravel and Sand blocks using the Fill or Replace tools in Amulet, the NBT data for both Bedrock and Java platforms is not properly generated. This seems to suggest that the translations for these block entities might be missing or not included in the PYMCTranslate translations for both Bedrock and Java 1.20.0 versions.

### Current Behaviour:
The NBT data for the new Suspicious Gravel and Sand blocks are not created or generated.

### Expected behavior:
When creating the new Suspicious Gravel and Sand blocks, the corresponding NBT data should be correctly generated.

### Steps To Reproduce:
1. - Open Amulet Editor.
2. - Load a world in either (Bedrock or Java) 1.20.0 or above.
3. - Use the Fill or Replace tool/operation to create Suspicious Gravel and Sand blocks.
4. - Check the NBT data for the newly created blocks. 
- By holding the Alt key and hovering over a block.

### Environment:
- OS: Windows 10
- Minecraft Platform: Bedrock and Java
- Minecraft Version: 1.20.0
- Amulet Version: V0.10.18

### Additional context
- This issue is related to missing or incorrect translations in the PYMCTranslate module.

The new Block Entity ids for Java and Bedrock editions are the following:

**- Bedrock:** "BrushableBlock"
**- Java:** "minecraft:brushable_block"

The NBT Formats
- BEDROCK
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/12506973-1838-4506-ac44-76d025b29958)

- JAVA
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/7ea30ad1-80b4-47c8-8b7c-5818b21248b6)

## Attachments
N/A

### Screenshots
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/2158d2cb-75dd-469d-b03b-04e256c79c78)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/a2fd48ed-564b-45ba-bfd5-435c5d8e5abc)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/af2f7278-c861-4b57-8c69-413a40cad99f)

### Worlds
N/A

**Comment by StealthyExpertX** [comment]
I tried writing a script to force the block entities to be set but seems they have to be supported by the translator or it wont be able to do that.

[create_brushable_blocks_plugin.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12157655/create_brushable_blocks_plugin.zip)
That was my attempt at forcing it to save the Block Entity Data.

**Comment by gentlegiantJGC** [comment]
Fixed in gentlegiantJGC/PyMCTranslate#39
