### ISSUE TITLE
Unable to open world 1.20.1 version

### ISSUE THREAD

**Issue by Tardamana** [Amulet-Team/Amulet-Map-Editor#946]
### Current Behaviour:
f"Could not find a matching {self._object_type} for {identifier}"
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 3465)

### Expected behavior:
World opens correctly

### Environment:
- OS: Ventura 13.3.1 (22E261) (Mac)
- Minecraft Platform: Java 
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.18

### Screenshots
<img width="1728" alt="Screenshot 2023-07-25 at 11 46 24" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/140500243/8f61e1b8-d0fb-407a-ac08-6dc1579735d4">

**Comment by gentlegiantJGC** [comment]
Please can you run the following command and send the output.
If you have installed a python virtual environment you will need to run it from inside the virtual environment.
`python3 -m pip list`
