### ISSUE TITLE
je to be concrete will turn into an unknown block

### ISSUE THREAD

**Issue by Townrain** [Amulet-Team/Amulet-Map-Editor#947]
je to be concrete will turn into an unknown block

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by Podshot** [comment]
Can you please provide more detail on what's happening? Like what version of Amulet you are using and the Minecraft platform and version that this happens with?

**Comment by gentlegiantJGC** [comment]
@Townrain please fill out the bug report template.

**Comment by Townrain** [comment]
I can't understand what you are saying.


________________________________
发件人: Ben Gothard ***@***.***>
发送时间: 2023年8月6日 22:55
收件人: Amulet-Team/Amulet-Map-Editor ***@***.***>
抄送: Townrain ***@***.***>; Author ***@***.***>
主题: Re: [Amulet-Team/Amulet-Map-Editor] je转be混凝土会变成未知方块 (Issue #947)


Can you please provide more detail on what's happening? Like what version of Amulet you are using and the Minecraft platform and version that this happens with?

―

**Comment by gentlegiantJGC** [comment]
You haven't given us enough information to be able to debug the issue.

**Comment by gentlegiantJGC** [comment]
Please can check if this is still an issue in 0.10.25
