### ISSUE TITLE
Update Website for python Version

### ISSUE THREAD

**Issue by Scroogeee** [Amulet-Team/Amulet-Map-Editor#948]
### Current Behaviour:

Website (https://www.amuletmc.com/installing-from-source) says to install python 3.7, but github (this repo) says 3.9.

### Expected behavior:

Website and github installation instructions should be talking about the same required python version.

### Steps To Reproduce:

Go to github / Website and see for yourself

### Additional context

This is not a bug, but an error on the website (but I didn't find a template for that)

**Comment by gentlegiantJGC** [comment]
Fixed
