### ISSUE TITLE
Latest version flagged as malicious by virustotal

### ISSUE THREAD

**Issue by BeldinDragon** [Amulet-Team/Amulet-Map-Editor#951]
i was about to downgrade one of my minecraft maps when I downloaded the latest version. I'm always checking through virustotal, and it flagged it as malicious : [](https://www.virustotal.com/gui/file/b9da4f2a5ad3c2620bf29a63d268162aae76fca82e057f3df13ff40da02ae398)

is it safe? I feel insecure about downloading it.

**Comment by gentlegiantJGC** [comment]
This is a false positive. Antivirus programs don't know how to handle the python bundle and report it as a virus.

**Comment by create-juicey-app** [comment]
if you're still unsure, the project is open-source so you can see the code by yourself, you can make your own version of amulet.
