### ISSUE TITLE
Sign bugs in Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by Sodvic** [Amulet-Team/Amulet-Map-Editor#952]
Bug Report:
§l disappears after copying a sign

Steps To Reproduce:
Follow steps in the video: https://youtu.be/5eUTR4M60a8

### Environment:

- OS: Windows 10
- Minecraft Platform: Bedrock Edition
- Minecraft Version: 1.20.12.1.0
- Amulet Version: 0.10.18

## Attachments
https://youtu.be/5eUTR4M60a8

**Comment by gentlegiantJGC** [comment]
This only seems to effect the case when the text is on a different line to the formatting code.
