### ISSUE TITLE
[Bug Report] Selection box not movable by buttons

### ISSUE THREAD

**Issue by Scroogeee** [Amulet-Team/Amulet-Map-Editor#958]
### Current Behaviour:

Clicking the "move point 1" or "move point 2" or the "move box" buttons whilst applying keyboard input (WASD or space or shift) for the desired direction doesn't result in any movement.

### Expected behavior:

When I click an hold one of the "move point 1" or "move point 2" or the "move box" button, the respective selection points (or the whole bounding box) should be moved in the desired direction indicated by the WASD keypress or up (space) or down (Shift) direction.

### Steps To Reproduce:

1. Open a world in Amulet
2. Select some area by left clicking
3. Click one of the 3 Buttons (see attached screenshot) whilst applying keyboard input in any of the WASD or up (space) or down (Shift) direction
4. See that selection bounding box is not moved.

### Environment:

- OS: OSX Ventura 13.4.1 on Apple Silicon (M1 Pro Chip)
- Minecraft Platform: Java
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.18

### Additional context
Amulet is being run from source on python version 3.11.4.

### Screenshots

<img width="400" alt="Bildschirmfoto 2023-08-26 um 19 40 50" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/30441849/14d65565-8918-4523-9a93-b117db9e1421">

Clicking any of the 3 buttons in the lower left corner and simultaniously pressing WASD / Space / Shift keys has no behaviour.

### Worlds

Any Minecraft World has this problem, for example this one:
[New World.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12446354/New.World.zip)

**Comment by gentlegiantJGC** [comment]
I don't know why this would happen.
It may have something to do with the layer fighting.

**Comment by Scroogeee** [comment]
Might be related: When I drag the bounding box with the cursor, I get loads of those error messages:
```Traceback (most recent call last):
  File "/Users/myUserName/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 273, in _box_renderer_change
    self._update_selection_inputs(*evt.points)
  File "/Users/myUserName/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 287, in _update_selection_inputs
    self._x1.SetValue(x1)
TypeError: SpinCtrl.SetValue(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'```

**Comment by Scroogeee** [comment]
I also noticed that the x1, y1, z1 text fields as well as the x2, y2, z2 text fields seem to be empty (i.e. have 0's in them) all the time, even when a box is selected.

**Comment by gentlegiantJGC** [comment]
I must be passing the wrong type in. It seems to handle it on some operating systems but not others.

Try changing line 286 in `/Users/myUserName/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py` to this

`x1, y1, z1, x2, y2, z2 = map(int, (*point1, *point2))`

**Comment by Scroogeee** [comment]
Thanks, this fixes the second issue:
<img width="149" alt="Bildschirmfoto 2023-08-27 um 12 22 58" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/30441849/080fe8b8-9960-4797-a0b6-a507bc5776ea">

However the buttons still don't have any behaviour.

**Comment by Scroogeee** [comment]
I just played around with some debug printlns in `/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py` in the `_on_held` function.
It seems like `evt.action_ids` only ever has the value `{'ACT_BOX_CLICK'}` or is an empty set. This means that x, y, and z will always be 0 and no nudging will occur.

**Comment by Scroogeee** [comment]
I just checked the value of the keybinds variable:
```
keybinds: {'ACT_MOVE_UP': ((), 'SPACE'), 'ACT_MOVE_DOWN': ((), 'SHIFT'), 'ACT_MOVE_FORWARDS': ((), 'W'), 'ACT_MOVE_BACKWARDS': ((), 'S'), 'ACT_MOVE_LEFT': ((), 'A'), 'ACT_MOVE_RIGHT': ((), 'D'), 'ACT_BOX_CLICK': ((), 'MOUSE_LEFT'), 'ACT_BOX_CLICK_ADD': (('CTRL',), 'MOUSE_LEFT'), 'ACT_CHANGE_MOUSE_MODE': ((), 'MOUSE_RIGHT'), 'ACT_INCR_SPEED': ((), 'MOUSE_WHEEL_SCROLL_UP'), 'ACT_DECR_SPEED': ((), 'MOUSE_WHEEL_SCROLL_DOWN'), 'ACT_INCR_SELECT_DISTANCE': ((), 'R'), 'ACT_DECR_SELECT_DISTANCE': ((), 'F'), 'ACT_DESELECT_ALL_BOXES': (('CTRL', 'SHIFT'), 'D'), 'ACT_DELESECT_BOX': (('CTRL',), 'D'), 'ACT_INSPECT_BLOCK': ((), 'ALT'), 'ACT_CHANGE_PROJECTION': ((), 'TAB')}
```

This doesn't seem to be the problem...

**Comment by Scroogeee** [comment]
There also seems to be a problem with keybindings. When I try to rebind any control, any keyboard input isn't recognized. Only the mouse input is recognized once I close the window.

This might be related.

<img width="750" alt="Bildschirmfoto 2023-08-27 um 13 09 40" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/30441849/9816af8c-219a-4425-a741-4769757c8215">

**Comment by gentlegiantJGC** [comment]
It sounds like the button isn't active. Those controls are for the canvas.
The button just uses normal clicking.

**Comment by Scroogeee** [comment]
> Those controls are for the canvas.

Perhaps I didn't explain properly. I know the "controls" are for navigating in the world (which works).

However, in the "Press the key you want assigned" Pop-Up-Window when changing keybindings (last post upper left), no keyboard input is recognized. Example: If I close said pop-up-window by left-clicking on the red x button, then MOUSE_LEFT is saved as the action to move forward.

So now we have two cases in which keyboard input isn't recognized (the button clicks themselves seem to be registered though (see my debug println experiments above), which I checked with some print statements) which is why I mentioned this behaviour as well.

**Comment by Scroogeee** [comment]
@gentlegiantJGC as of amulet version 0.10.19 I got the following traceback when selecting something:
```Traceback (most recent call last):
  File "/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 273, in _box_renderer_change
    self._update_selection_inputs(*evt.points)
  File "/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 287, in _update_selection_inputs
    self._x1.SetValue(x1)
TypeError: SpinCtrl.SetValue(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'
```

**Comment by Scroogeee** [comment]
A fix for this is casting the respective values in lines 287 to 292 to an int.

**Comment by Scroogeee** [comment]
> Thanks, this fixes the second issue

I created #961 to avoid confusion.
