### ISSUE TITLE
[Bug Report] can't download program my anti-virus finds a virus in it

### ISSUE THREAD

**Issue by KideoTMG** [Amulet-Team/Amulet-Map-Editor#965]
ever since the last 2 updates
my anti virus program always now finds a virus in your program
and does not allow the download 
i did try to turn off the virus i was able to download it
but if i turn it back on
then try to run the program it quarantine's the program
i am using the free version of Avast because it the easy one to turn off

**Comment by gentlegiantJGC** [comment]
This is a false positive caused by the way that we have to package the python code.
I have tried submitting a false positive report but the website is erroring.
