### ISSUE TITLE
[Bug Report] Amulet Issues Due to Unresponsive UI and Corrupt Configs

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#967]
### Current Behaviour:
- When attempting to launch Amulet without administrative privileges, only the console window appears, and the main window fails to open. If the program is run as an administrator, the main window does appear but is completely unresponsive, with UI/GUI buttons being unclickable. Pressing these buttons triggers only the Windows notification sound.

### Expected behavior:
- Amulet should launch smoothly without requiring administrative rights. The main window should appear as intended, and all UI/GUI elements should be interactive and responsive. If the config files are corrupt, outdated, or won't load, the program should regenerate them and function as expected.

### Steps To Reproduce:
N/A

### Environment:
- OS: Windows 10 64-bit
- Minecraft Platform: All Platforms
- Minecraft Version: ALL VERSIONS
- Amulet Version:  v0.10.19

### Additional context
- Upon removing the two config files (amulet_edit.config and amulet_meta.config) as suggested by Gentlegiant from the Amulet Discord, not only did Amulet start properly without requiring administrative rights, but an initial startup UI popup also appeared. Clicking "I Understand" on this popup allowed the program to work as intended. It appears that the type of invalid state or corruption in these config files isn't recognized by Amulet, leading to the issues described. Ideally, even if these files are corrupt or outdated, Amulet should be able to regenerate them and operate normally.

## Attachments
[Amulet_Configs.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12589699/Amulet_Configs.zip)

### Screenshots
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/5763efaf-bee6-450e-bf10-13d23fd34630)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/b19ceb58-51db-4b6b-9ecb-2982f6acc412)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/17806994/37b230cd-ab8c-4eb6-b364-090c1eec33e4)

### Worlds
N/A

**Comment by gentlegiantJGC** [comment]
It takes a while to open on my computer but it does open.
I am going to modify the code so that the main window gets shown and then the dialog gets shown.
It may be something about my janky code that was displaying the dialog parented to the main window before the main window constructor had finished.

**Comment by gentlegiantJGC** [comment]
There is a build cooking here.
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/0.10.20a0

When you get a chance please can you delete your new config files and restore the old ones and run the new build.

**Comment by gentlegiantJGC** [comment]
looks like something in the build broke

**Comment by gentlegiantJGC** [comment]
https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/0.10.20a2

**Comment by StealthyExpertX** [comment]
Alright, I'll test it later today, thanks!

**Comment by gentlegiantJGC** [comment]
@StealthyExpertX did you get a chance to test this?

**Comment by StealthyExpertX** [comment]
I have not, sorry, I have had a lot of stuff coming up this week and wasn't quite expecting things to be this busy. I promise I'll do my best to check as soon as I possibly can.

**Comment by StealthyExpertX** [comment]
Alright, just got around to testing this and yes the issue seems to have been resolved in the latest builds, however, running into another issue as of recent while testing that's unrelated.

I submitted a bug report just now.
