### ISSUE TITLE
Mushroom Blocks and Mushroom Stem Blocks do not convert properly

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#97]
Conversion process using Amulet V0.7.0.1
Java 1.16.1 to Bedrock v1.16.20

From testing, it appears the mushroom blocks that have the top texture exposed convert in bedrock to having the outer texture exposed. In java terms, with blockstate [up=true], it seems the bedrock conversions lead to the wrong damage value.
Mushroom stems convert to having exposed top texture.

**To Reproduce**
1. Plant a giant mushroom in java
2. Convert using Amulet
3. See wrong textures displayed in Bedrock

**Screenshots**
![musrhooms_java](https://user-images.githubusercontent.com/13902631/92288423-ddd18b00-eeda-11ea-8169-706c64b46ed1.png)
![musrhooms_bedrock](https://user-images.githubusercontent.com/13902631/92288427-e033e500-eeda-11ea-8cf3-fb57af5d8c4b.png)

**World file Java 1.16.1**
https://drive.google.com/file/d/1bRBjSiuPlq3PbFQNIxVcKgA-vRac6s6g/view?usp=sharing

**Comment by gentlegiantJGC** [comment]
Yes this is a bug with the translator. I remember being very overwhelmed when I tried implementing this. Java stores the state of each side as a true or false value. False if it is the base texture or true if it is the outer texture. That gives 2^6 states per block (64) and there are three blocks, one for the red, one for the brown and one for the stem. This gives a total of 192 states that need to get squashed into Bedrock's 16 states per colour. I wrote a program to find the best matches but it obviously wasn't good enough

**Comment by qmagnet** [comment]
I could create a worlds with each possible state and label them after conversion if that helps.
Otherwise, could convert them all to fill outside textured mushroom blocks and then let the game alter the sides on its own as each block updates based on it touching?

Full Brown = brown_mushroom_block 14
Full Red = red_mushroom_block 14
Full Stem = red_mushroom_block 15

**Comment by gentlegiantJGC** [comment]
Most of the examples you have shown have better conversions. I am looking into the code that generates the translations now.
The translations are never going to be perfect here because there are a large number of states in Java that have no alternative in Bedrock. I have made a change that I think should make it more biased to having the outer texture rather than the inner texture

**Comment by gentlegiantJGC** [comment]
I believe this should solve the issues mostly. https://github.com/gentlegiantJGC/PyMCTranslate/commit/a8ec96962543090b8b89d6734c8423b08877b482
