### ISSUE TITLE
[Bug Report] Amulet Dimension Build Height Issue

### ISSUE THREAD

**Issue by pyromaniac310** [Amulet-Team/Amulet-Map-Editor#974]
### Current Behaviour: 

 I created a dimension file and its working. However when i open it in amulet it shows that the "buildable space" the gray and blue checkered planes indicating top and bottom max build height is different than what the world file says. In amulet the buildable planes exist on -1 and 255. I can build inside the dimension above to 319 and below to -64 but sometimes on server reboot it will glitch everything into a black void due to the fact my transferred chunks are too tall to fit into the 256 build height amulet has placed on the map. The world file/dimension states it can be built anywhere from -64 to 319. Its also rendering the world correctly at the new default minecraft overworld heights but the build planes are off.  The selections show where bedrock and sky would end on the appropriate build levels of the minecraft generated dimension and you can see where amulet says the buildable space is. Both are very different. According to the checkered build planes in amulet my buildable space is -1 to 255 instead of the actual -64 to 319. I can still build up to 319 and down to -64 but when i start moving or placing water below/above a certain point glass and random blocks will also disappear. 

### Expected behavior:
When i create a world with a dimension and open it in amulet the blue and grey planes indicating buildable space should reflect the default build height for whichever dimension is created. For me i created an overworld dimension which should make the build height -64 to 319 not -1 to 255.  I would like to create an overworld dimension and have amulet build planes show the correct build height from -64 to 319. 

### Steps To Reproduce:
1. Create a single player world with a dimension that is just like the overworld
2. Enter the dimension in single player save and exit world
3. Open up amulet and load the single player world with the dimension and go into the dimension using the drop down in amulet
4. Once open in amulet you should see the dimension build planes are at -1 and 255 instead of -64 and 319 where the world generated. 
5. Fly below to bed rock to see that bedrock generated at -64 but the build plane did not.

### Environment:

- OS: Windows 
- Minecraft Platform: Java 
- Minecraft Version: 1.19.2
- Amulet Version: 0.10.19

### Screenshots

![Untitled](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/145232701/18726254-8155-470e-945f-1bc1d9984a0c)
![bottom world -64 to -1](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/145232701/5d13cd24-4cef-4af1-a33f-8c1a3cd8ddc3)
![top selection -1 to 319](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/145232701/ac220dcd-c0e9-4e6f-b79e-4bf27e44afa4)

### Worlds
https://drive.google.com/file/d/14h0im_cwjf8YLm-SRFuaAc5nSgQuQj3j/view?usp=drive_link

**Comment by gentlegiantJGC** [comment]
Please can you attach a level that I can use to debug the issue.

**Comment by pyromaniac310** [comment]
World has been uploaded via the google drive link in the original post. Let me know if you need anything else!

**Comment by gentlegiantJGC** [comment]
Our code is assuming that there is a data pack in the world.
How are you adding the dimension?

**Comment by gentlegiantJGC** [comment]
I have fixed some issues with the custom height handling but it does not fix the issue with your world.
We load the world height from either the level.dat file if the data is stored inline or in the resource pack if it is just referenced.
Your level.dat file references `dimension_type` `maxheightpyrodome:dragon_dome_dimension_final_construction_site` but the world has no data pack in the `datapacks` directory so I don't know what more Amulet could do.
If you have a datapack stored somewhere else I suggest putting it in the datapacks directory and Amulet should work.
