### ISSUE TITLE
Powered Pistons create ghost blocks

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#98]
**Description:**
Converting from Java 1.16.1 to Bedrock 1.16.2 using Amulet creates ghost blocks where piston head is supposed to be that disable piston functionality until broken.

**To Reproduce**
1. Extend a piston or sticky piston with a block attached
2. Convert with Amulet from Java to Bedrock
3. Pistons convert to appear unpowered, but have new ghost blocks where piston head was in Java version

**Expected behavior**
Pistons should be converted in the powered state and retain their use without having to break the ghost block

**Screenshots**
![pistons_java](https://user-images.githubusercontent.com/13902631/92288736-f42c1680-eedb-11ea-8fa8-1daf91af7529.png)
![pistons_bedrock](https://user-images.githubusercontent.com/13902631/92288739-f68e7080-eedb-11ea-80d1-a55bf39072c5.png)

**Test World from screenshot**
https://drive.google.com/file/d/1bRBjSiuPlq3PbFQNIxVcKgA-vRac6s6g/view?usp=sharing

**Comment by gentlegiantJGC** [comment]
This one is due to some complex nbt that needs setting

**Comment by gentlegiantJGC** [comment]
This specific issue should now be fixed but I am sure there are a number of other issues with pistons. Especially when they are in their moving form
