### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by theohdg2** [Amulet-Team/Amulet-Map-Editor#985]
Hello, I noticed that while using your software, which is very good by the way, it only used 10% of my processor, which is a shame, because the java/bedrock conversion and vice versa takes a lot of time, even more so if you have a small processor, that's why I'm asking if it would be possible to put an option or something that would allow maximum use of the processor

**Comment by gentlegiantJGC** [comment]
This is a limitation of Python
