### ISSUE TITLE
Save UI resized window settings when user reopens Amulet windows

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#99]
The UI window opens fairly smally and cuts off the text for files. If a user drags the window to resize, next time the program opens, it would preferred if it remembered the window size.

**Window example of cut-off images and text**
![UI auto size](https://user-images.githubusercontent.com/13902631/92289073-386be680-eedd-11ea-9229-214160a1c2e8.png)

**Comment by gentlegiantJGC** [comment]
This should be fixed now
