### ISSUE TITLE
[Bug Report] Floating glow lichens when pasting a build from one world to another

### ISSUE THREAD

**Issue by TheBMGPlayzYT** [Amulet-Team/Amulet-Map-Editor#991]
## Bug Report
Floating glow lichens when pasting a build from one world to another
### Current Behaviour:
Glow lichens float when copying and pasting a build from one world to another.

### Expected behaviour:
Glow lichens should NOT float when pasting a build from one world to another world.

### Steps To Reproduce:
1. Open Amulet
2. Click on the world that you want to edit, for this report we will name this "World 1"
3. Then open an another world, "World 2"
4. Copy a build from "World 1" that contains glow lichens
5. Then paste that build to "World 2"
6. Open Minecraft (Bedrock)
7. Click on "World 2"
8. Once it loaded, then you should see that the glow lichens are floating instead of resting on the block that they were originally placed

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock 
- Minecraft Version: 1.20.32
- Amulet Version: 0.10.23

### Screenshots
![Screenshot 2023-10-10 225437](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75167042/59bf3da3-8514-425d-a3ab-e8e2b3c28404)
![Screenshot 2023-10-10 225713](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/75167042/9d3719f7-f787-4270-be5d-c8a29d15c8e4)

**Comment by TheBMGPlayzYT** [comment]
Edited it because this is my first time making a bug report

**Comment by gentlegiantJGC** [comment]
Are both of these worlds Bedrock worlds?
Are you rotating the selection when pasting it?

**Comment by gentlegiantJGC** [comment]
I have tried copying from a Bedrock 1.20.40 world to another Bedrock 1.20.40 world and it works as intended.
Is there any more information that you have omitted?

**Comment by TheBMGPlayzYT** [comment]
Yes both of the worlds are from Bedrock. No I didn't rotated them when pasting it. "World 1" was from 1.20.40 while "World 2" is from 1.17.40.

**Comment by TheBMGPlayzYT** [comment]
> I have tried copying from a Bedrock 1.20.40 world to another Bedrock 1.20.40 world and it works as intended. Is there any more information that you have omitted?

Yes both of the worlds are from Bedrock. No I didn't rotated them when pasting it. "World 1" was from 1.20.40 while "World 2" is from 1.17.40.

**Comment by gentlegiantJGC** [comment]
I can reproduce this issue

**Comment by TheBMGPlayzYT** [comment]
> I can reproduce this issue

So will it get fixed?
