### ISSUE TITLE
[Bug Report] "Update!" blocks replace other blocks upon world conversion

### ISSUE THREAD

**Issue by Anonymous-Kingg** [Amulet-Team/Amulet-Map-Editor#992]
### Current Behaviour:
Upon world conversion, various blocks have been replaced by a block with a dirt texture that says 'update!' on it.
Affected blocks include:
- Stained Glass Panes
- Concrete Powder
- Terracotta

### Expected behavior:
For the blocks to be converted correctly

### Steps To Reproduce:

1. Create world in Minecraft Java 1.20.1 with the affected blocks included
2. Create world in Minecraft Bedrock 1.20.12
3. Convert Java world into Bedrock world
4. Open Bedrock world and find 'update!' blocks where affected blocks used to be

### Environment:

- OS: Windows 10
- Minecraft Platform: Java; Bedrock
- Minecraft Version:  Java 1.20.1; Bedrock 1.20.12
- Amulet Version: 

### Additional context
I am specifically using Minecraft Education Edition, but this version is identical to Bedrock as if education mode was toggled on in a world. It is also some versions behind regular Bedrock (hence the version 1.20.12 and not the current version, 1.20.40)

### Screenshots
![Screenshot 2023-10-18 161335](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/94268574/7ac5c628-60d6-4f35-98a5-fe5ee5f199e1)

### Worlds
[Java (source) world.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12999533/Java.source.world.zip)

[Bedrock (dest) world.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12999520/Bedrock.dest.world.zip)

**Comment by Ctre22** [comment]
![IMG_1721](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/149507077/485ee0af-5417-4e97-9203-8e9571211800)
Same here except the blocks being replaced are polished andesite. Also my Minecraft version is 1.20.40 Bedrock. Most of my main editing is through mojang’s editor through MCpreview 1.20.50 (bedrock) and i use amulet mainly to convert to current version/ import structures. This has worked for me in the past. (2weeks ago) 

a few days ago i used amulet to do another conversion. it prompted me to update and i declined. After conversion i noticed the questionable blocks so i tried updating and exporting again and got the same result.

**Comment by gentlegiantJGC** [comment]
That should fix this problem.

I think this may also fix #947 and #949

**Comment by Andrevinder** [comment]
@gentlegiantJGC really helpful answer 😂 (it's not that helpful honestly). Which version exactly do I have to use?

**Comment by gentlegiantJGC** [comment]
Have you tried the newest version?
