### ISSUE TITLE
[Bug Report] Operations deletes text on signs

### ISSUE THREAD

**Issue by Notacod3r** [Amulet-Team/Amulet-Map-Editor#995]
### Current Behaviour:

Selecting an area, then running an operation like replacing block x with block y will execute the operation, however, if there are signs with text in the selected area, the text will disappear once you check it in game. 

### Expected behavior:

The operation should not affect the text on signs.

### Steps To Reproduce:

See above. Replace a block in a selected area with signs. See text on signs disappear. 

### Environment:

- OS: Windows ARM
- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.40 
- Amulet Version: 0.10.23

**Comment by gentlegiantJGC** [comment]
Looks like a bug in the replace operation
